### ISSUE TITLE
Next and previous Month doesn't work without react-tap-event-plugin installed 

### ISSUE THREAD

**Issue by rach** [gpbl/react-day-picker#1]
No click event exist for this actions.
https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L96-L103

It's maybe not necessary to fix it but maybe amending the doc to say that react-tap-event-plugin is required.

Otherwise I really like the work that you have done with with calendar component, it leave loads of room for flexible behavior.. Exactly what I needed. Thanks

**Comment by gpbl** [comment]
thanks @rach ! You are right. What do you think could be the best approach? 

1. remove the click events at all and impose the use of react-tap-event-plugin
2. use click events (not touch) for the navigation buttons

I'd go with the first.

**Comment by rach** [comment]
Thanks for the fix.
I was going to say that 2) was a better choice so if people doesn't care about mobile tap event.
Great lib, thanks again for sharing it.
