### ISSUE TITLE
Call stopPropagation on nativeEvent on next and previous month click

### ISSUE THREAD

**Issue by iancmyers** [gpbl/react-day-picker#10]
In `handleNextMonthClick` and `handlePrevMonthClick` event propagation is not being stopped because `stopPropagation` is being called on the synthetic event, not on the native event. 

https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L58 and https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L70 should be:

```js
e.nativeEvent.stopPropagation();
```

Alternatively, you could pass the event to the `onNextMonthClick` callback (as you do with `onDayClick`) and let the component user decide whether to stop propagation or not. I'd be happy to PR either fix. Let me know which you prefer.

**Comment by gpbl** [comment]
Yeah definitely we should pass the event to the callback - could you send a PR?
Thanks
