### ISSUE TITLE
Day picker on mobile

### ISSUE THREAD

**Issue by OBellon** [gpbl/react-day-picker#100]
Is there anyway to make the day picker "readonly" so that the keyboard on mobiles doesn't appear when focusing on the input. Now, the calendar shows behind the keyboard, and it's impossible to select a date.

Thank you.

**Comment by gpbl** [comment]
Hi! There's no `input` element in this day picker. Maybe you are referring to a specific implementation? Could you provide an example?

**Comment by OBellon** [comment]
![image](https://cloud.githubusercontent.com/assets/10086802/11347369/5b7e6d64-9221-11e5-86d9-52d70acf975c.png)

I want to avoid that, so I thought that adding "readonly" could fix it, but no.

**Comment by gpbl** [comment]
I believe this keyboard appears because there's the focus on the text field... Couldn't you avoid it? 
I think on mobile an overlay when focusing an input field will hardly work well. you could just show the day picker, or use the input's type `date` instead.

**Comment by webbushka** [comment]
@OBellon that screenshot doesn't look like this datepicker... it looks like https://github.com/Hacker0x01/react-datepicker. Unless you re-skinned the picker to look like that one and added the input popout?

**Comment by gpbl** [comment]
@webbushka lol I knew that `react-day-picker` was a too generic name 😒
