### ISSUE TITLE
Types destroyed v7.4.1

### ISSUE THREAD

**Issue by tonoslav** [gpbl/react-day-picker#1009]
**Describe the bug**
Getting a lot of wrong errors from types

1. Using **DayPickerInput** with **dayPickerProps** prop, keep getting error that **renderDay**, **renderWeek** are required , but should they be?

2. ```js
    import { DateUtils } from 'react-day-picker'
    DateUtils.isDate(...) 
    ```
    **'DateUtils' only refers to a type, but is being used as a value here.**
    **Fix:** (removed **export** before **type**) +
    ![image](https://user-images.githubusercontent.com/3399021/79157131-545ad880-7dd4-11ea-849c-b2ede1314483.png)

3. **DayPickerInputProps** props **onDayPickerShow**, **onDayPickerHide** are required but should they?

**Comment by mr-wildcard** [comment]
Also experiencing 1️⃣. I had to hide `dayPickerProps` prop of `DayPickerInput` component behind a `@ts-ignore`

**Comment by sbusch** [comment]
I think the 1st one should be fixed by my PR https://github.com/gpbl/react-day-picker/pull/1012 (merged quickly by @gpbl, thank you!), not yet published to npm.

Regarding 2nd bug, I fixed the same error for another export (https://github.com/gpbl/react-day-picker/pull/1011), so the fix here could be similar?!

3rd: the JS implementation checks if the props are set before calling those event handlers, so I think they are not mandatory and should be fixed similar to 1.

**Comment by redaxmedia** [comment]
I experienced the same with `MomentLocaleUtils` ... that broken release should be unpublished

**Comment by andrew-r-king** [comment]
FYI: A workaround is to stay at the previous version by removing "^" in front of the version in your package.json:

```
 "react-day-picker": "7.4.0",
```

**Comment by gpbl** [comment]
I'm sorry for that! The hard life of a maintainer :) I should never trust PRs without proper testing and the release was rushed up.

Setting up a typescript app to test it, let see if I come out. 

Please send PRs to help as I'm a bit busy these days 🙏🏽

**Comment by bengry** [comment]
Part of this is already fixed by https://github.com/gpbl/react-day-picker/pull/1012
I'll send a PR to fix the `DateUtils` and `ModifierUtils` export in a bit and update here.

**Comment by redaxmedia** [comment]
You could just `npm unpublish react-day-picker@7.4.1 --force` like I suggested above... anyway, I think this is only allowed during first 24h or something.

**Comment by gpbl** [comment]
Well I've been neglecting the types for too much time :( 

There were many parts requiring a rewrite – now types should work correctly. Please report back if something break again.

Everybody – thanks for your patience. So glad the next version will be in Typescript :)
