### ISSUE TITLE
Ability to set timezone

### ISSUE THREAD

**Issue by Eric24** [gpbl/react-day-picker#1010]
**Is your feature request related to a problem? Please describe.**
There does not appear to be a way to specify the timezone reference used by the component (i.e. it uses only the browser's timezone). This is not always correct, as there are times when an application or even a specific date field needs to be displayed in a specific timezone.

**Describe the solution you'd like**
A way to override the default timezone with a specific timezone.

**Describe alternatives you've considered**
Our current solution is to manipulate the input value, adding an offset value to make the component's default timezone match that of the desired timezone, and then do the same on the way out. It's definitely a hack.

**Comment by gpbl** [comment]
@Eric24 thanks for your suggestion! This should go in the next major release. Do you think a `timezone` prop would work?

**Comment by Eric24** [comment]
Yes, `timezone` would certainly make sense as a prop; the other option is `tz`, which is pretty common.

By default, the component would work as it does now (using the browser's timezone), but if defined, it just uses the prop value to explicitly set the timezone of the passed-in date value.

**Comment by m-nathani** [comment]
hey guys i badly need this.. is there any update for this ? . if you do you have parttime solution how to fix it ?

**Comment by m-nathani** [comment]
or do you guys know whats the timeline for this ? if thats far i can replace it with a datepicker with supports timezone for now.
