### ISSUE TITLE
KeyDown not working

### ISSUE THREAD

**Issue by oforto** [gpbl/react-day-picker#1015]
I dont get any feed back when I keydown on calender. On Dayclick is working fine. 

const onKeyDown = (e: React.KeyboardEvent) => {
  if (e.key === 'Enter') {
    e.preventDefault
    console.log('works')
  }
}

**Comment by gpbl** [comment]
I think you want to use [`onDayKeyDown`](http://react-day-picker.js.org/api/DayPicker#onDayKeyDown).
