### ISSUE TITLE
this does not exist in es modules

### ISSUE THREAD

**Issue by TrySound** [gpbl/react-day-picker#1027]
**Describe the bug**
This is what I talked about. `this` should not be used in module scope as it does not exist there by spec. And rollup fairly complains about it. A few guys said tsc can't generate esm properly and babel should be used instead.
https://unpkg.com/browse/react-day-picker@8.0.0-alpha.0/lib/hooks/useInput.js

**Comment by gpbl** [comment]
Thanks @TrySound! I'd love you working on this if you have some spare time :)

I'm busy doing other things – I'm tracking build issues in https://github.com/gpbl/react-day-picker/issues/1028 (see https://github.com/gpbl/react-day-picker/projects/7). 

Could we move the discussion there?
