### ISSUE TITLE
Cannot set property 'to' of undefined

### ISSUE THREAD

**Issue by Gustavoohrq** [gpbl/react-day-picker#1029]
**Describe the bug**
Pass the examples to hooks and broke

**To Reproduce**
https://codesandbox.io/live/76XGKG
**Expected behavior**
hoped it works
**Screenshots**
![image](https://user-images.githubusercontent.com/47986830/80232547-743b9900-862b-11ea-8821-01bb75c81cee.png)

**Comment by gpbl** [comment]
Looks like a dup of: https://github.com/gpbl/react-day-picker/issues/957
