### ISSUE TITLE
(v8) Investigate compatibility with UI libraries

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1035]
DayPicker should work easily when used with components from other UI libraries, like react-boostrap, react-material-ui, etc.

### To do

- [ ] Setup a project with these libraries and see how it works
- [ ] Apply adjustements to source if needed

**Comment by harrisonturton** [comment]
DayPickerInput is currently pretty difficult to use with TailwindUI, especially when trying to style the input field.

This is from very brief experience trying to integrate it –– I could be wrong, in which case it's just a documentation issue.
