### ISSUE TITLE
Wrong export (v 7.4.1 or higher )

### ISSUE THREAD

**Issue by pavel-sindelka** [gpbl/react-day-picker#1039]
WARNING in ./node_modules/react-day-picker/src/moment.js 1:0-73
"export 'MomentLocalUtils' (reexported as 'default') was not found in './addons/MomentLocaleUtils'
 @ ./node_modules/react-day-picker/build/addons/MomentLocaleUtils.js
 @ ./node_modules/react-day-picker/moment/index.js

**Comment by andrei10k** [comment]
@pavel-sindelka why did you close this? i can still reproduce it wit 7.4.10
