### ISSUE TITLE
Starting from v7.4.2 "locale" property is ignored

### ISSUE THREAD

**Issue by Magomogo** [gpbl/react-day-picker#1050]
We used to define one of locale codes: 'de, en, it, fr' with 'locale' property of day picker (without moment.js). Starting from version v7.4.2 this property seems to ignored, we've got calendar in en-US locale (with Sundays as a first day of week).

Rollback to v7.4.1 fixes the issue.

**Comment by gpbl** [comment]
Hey thanks, please provide a way to reproduce this issue and we will reopen it. Thanks again!
