### ISSUE TITLE
DayPickerInput crashes when user types in some character

### ISSUE THREAD

**Issue by DavidSvetlik** [gpbl/react-day-picker#1053]
Hello!

**Describe the bug**
DayPickerInput crashes when user types in some character directly (letter and even number).

**To Reproduce**
Clone [this CodeSandbox](https://codesandbox.io/s/XDAE3x0W8) to reproduce the bug.

**Expected behavior**
Well, not to crash. In case of letters just skip the symbol completely.

**Screenshots**
It crashes JavaScript, so no screenshot necessary I think. :-)

**Additional context**
Thank you very much for all your work!

**Comment by alekslario** [comment]
I checked the example you've linked and it doesn't crash for me. Also, aren't you supposed to sanitise user input anyhow?

**Comment by eldh** [comment]
@DavidSvetlik Were you using Safari when it crashed by any chance?

**Comment by gpbl** [comment]
I cannot reproduce, please include a reproducible case and reopen the issue. Thanks!
