### ISSUE TITLE
DayPickerInput month prop is not working as expected in IE11

### ISSUE THREAD

**Issue by Prasad-YS** [gpbl/react-day-picker#1067]
I have 2 datepickers - From_Date and To_Date , I want to start to month of To_Date from where we left the From_Date.
So in month prop I have updated the month:From_date . But the month always starts from the To_Date's month 
If try to update using "getDayPicker() " this object giving null in IE11 (in chrome it's working fine).

Note:This will work if we don't have any value in To_Date field, but if we have some value then it starts from the value's month.

Steps To reproduce: 

1. Go to the link: https://react-day-picker.js.org/examples/input-from-to/  in IE 11
2. Select the To Date first (select some future date like April 30, 2021)
3. Now select the From Date (select a past Date like  June 30, 2020)

expected output: To Date DatePickerInput should show window June and July of 2020 calendar.
Actual output : To Date field showing Date window for July Apri of 2021  calendar

(In Chrome it works perfectly, only issue is in IE11)

**Comment by GG-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by gpbl** [comment]
Thanks for the bug report, no plans to fix this issue. Microsoft stopped supporting Internet Explorer 11 on November 30, 2020.
