### ISSUE TITLE
No way to move "min date" forward

### ISSUE THREAD

**Issue by tuhussaindeloitte** [gpbl/react-day-picker#1069]
**Describe the bug**
When selecting a date range, there is no way to move the min date forward. It can be moved back by clicking a previous date, but when clicking any date ahead of it the max date moves to that position.

**Expected behavior**
Ideally both the min and max date anchor could be drag and dropped to a new date using your mouse.

**Comment by gpbl** [comment]
Hey thanks, 

we have no plan to change that behavior, since that feature will change radically from the upcoming major version.
