### ISSUE TITLE
Code Examples in Docs returns 404

### ISSUE THREAD

**Issue by heflinao** [gpbl/react-day-picker#1070]
**Describe the bug**
On the website (ie: http://react-day-picker.js.org/examples/input) the `Code Sandbox` button returns a 404 in the console. Seems like the code examples don't exist at that URL anymore.

**To Reproduce**
Visit http://react-day-picker.js.org/examples/input and inspect the `Code Sandbox` Button, or try to visit https://raw.githubusercontent.com/gpbl/react-day-picker/master/docs/src/code-samples/examples/basic.js

**Screenshots**
<img width="1068" alt="Screen Shot 2020-10-23 at 10 01 14 AM" src="https://user-images.githubusercontent.com/4355979/97013309-e6c3fd80-1516-11eb-95c5-b0d645b5f62c.png">

**Comment by oudoulj** [comment]
You can find examples through the **Search** page
https://codesandbox.io/search?query=react-day-picker&page=1&configure%5BhitsPerPage%5D=12
but it's hard to know which examples are the official ones :confused:

**Comment by gpbl** [comment]
Dup of #985
