### ISSUE TITLE
react-day-picker: missing support for horizontal navigation of year in the calendar picker

### ISSUE THREAD

**Issue by rucsin** [gpbl/react-day-picker#1072]
In the current version we can navigate through year vertically using select dropdowns. Is it possible to add support for horizontal of years as well just like it's for months.

**Comment by rucsin** [comment]
Found the solution by customising the caption element

**Comment by danvoyce** [comment]
@rucsin could your solution please

**Comment by imtheaman** [comment]
@danvoyce i hope ya got a working solution, could ya please share?
