### ISSUE TITLE
Week numbers are wrong for the (UTC +12) Fidji timezone

### ISSUE THREAD

**Issue by hyacintheknobloch** [gpbl/react-day-picker#1079]
**Describe the bug**
The week numbers displayed in the calendar are wrong when the user location is in the (UTC +12) Fidji timezone. The problem may be present for others timezones.

**To Reproduce**
First, change the timezone of your computer and set it to (UTC +12) Fidji
Go to [react-day-picker example page](https://react-day-picker.js.org/examples/customization-week-numbers/)

**Expected behavior**
We need to display the week number 3 instead of number 4

**Screenshots**
Screenshot from the react-day-picker example page.
![image](https://user-images.githubusercontent.com/49550468/104323168-b9ea1a00-554a-11eb-857e-7c72535f94a1.png)

**Comment by applibs** [comment]
I have similar problem. I reported issue to date-dns component. https://github.com/date-fns/date-fns/issues/2148#event-4406116865
It looks that it has problem to generate calendar this picker.

**Comment by gpbl** [comment]
Yes this picker for being "lib agnostic" has few bugs for how it handles the timezones... it looks like the Fiji is the problematic one. Not directly related to that issue in date-fns tho  (as we don't use date-fns in v7).

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
