### ISSUE TITLE
Support rendering multiple months at the same time

### ISSUE THREAD

**Issue by iancmyers** [gpbl/react-day-picker#11]
Would you be open to a PR that added support for rendering multiple months side-by-side?

**Comment by gpbl** [comment]
:+1:  How could the API work? I'd deprecate `initialMonth` and add `startMonth` and `endMonth` props. I'm also thinking that splitting the component in multiple components could help: I mean `<Calendar />`, `<Week/>`, `<WeekHeader/>`, `<Day />`, `<NavButton />` and `<Header />`.
I needed that also to add some unit tests. What do you think?

**Comment by gpbl** [comment]
Or maybe we could leave `initialMonth` and add a `numberOfMonths` prop (defaults to 1)

**Comment by iancmyers** [comment]
I think `initialMonth` and `numberOfMonths` will make the logic for paging through months easier–we'll just have to increment/decrement `month` in the state.

**Comment by gpbl** [comment]
Published in v0.8.0
