### ISSUE TITLE
firstDayOfWeek doesn't change calendar display order.

### ISSUE THREAD

**Issue by Misaka42** [gpbl/react-day-picker#116]
I have getFirstDayOfWeek defined correctly in my localeUtils, which returns 1 if my locale is "ru" (Since Russia regards Monday as a first day of the week), however, my calendar still displays Sunday first, while the dates themselves are re-ordered correctly.
Is this the expected behavior? Do I have do take some additional steps to get Monday displayed as first day of week?
```js
getFirstDayOfWeek: (locale) => {
    if (locale === `ru`) {
      return 1;
    }
    return 0;
  },
```
![image](https://cloud.githubusercontent.com/assets/1235775/11806111/d8bc7e18-a321-11e5-8556-59c4ddf9b59e.png)

**Comment by gpbl** [comment]
Ehy @Misaka42 let me understand, the problem is in the header with the weekdays – which starts from Sunday right? How do you pass the weekdays to the calendar?

**Comment by gpbl** [comment]
@Misaka42 please add also `formatWeekdayShort` and `formatWeekdayLong` to your `localeUtils`, making sure they return the right first day of the week. For example:

```jsx
const weekdaysLong = {
   ru: ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"],
   en: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
};
const weekdaysShort = {
   ru: ["По", "Вт", "Ср", "Че", "Пя", "Су", "Во"],
   en: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"]
};
const firstDayOfWeek = {
   ru: 1,
   en: 0
};

const localeUtils = {
   formatWeekdayShort: (day, locale="en") => weekdaysShort[locale],
   formatWeekdayLong: (day, locale="en") => weekdaysLong[locale],
   getFirstDayOfWeek: (locale) => firstDayOfWeek[locale]
}

<DayPicker localeUtils={ localeUtils } locale="ru" />
```

I think I could add this to the documentation as well :P

**Comment by gpbl** [comment]
Actually I forgot it is [already documented](http://www.gpbl.org/react-day-picker/docs/LocalizationCustom.html).

**Comment by gpbl** [comment]
Ah! I see where you are coming from. The examples were wrong :grin:. Fixed it!
