### ISSUE TITLE
useRange() TypeError with MatchFromTo

### ISSUE THREAD

**Issue by ryanburr** [gpbl/react-day-picker#1168]
**Describe the bug**
The `useRange()` hook returns a `DaysRange` interface which cannot be used with the `selected` prop of `<DayPicker />` due to the following TypeScript error.
```
Type 'DaysRange' is not assignable to type 'Date | MatchDate | MatchFromTo | MatchBefore | MatchAfter | MatchDaysOfWeek | Matcher[] | undefined'.
  Type 'DaysRange' is not assignable to type 'MatchFromTo'.
    Types of property 'from' are incompatible.
      Type 'Date | undefined' is not assignable to type 'Date'.
        Type 'undefined' is not assignable to type 'Date'.
```

**To Reproduce**
Reproduced in this [Codesandbox](https://codesandbox.io/s/react-day-picker-base-forked-66l4r?file=/index.tsx). This is also the example used for the `useRange` hook documented [here](https://github.com/gpbl/react-day-picker/blob/7a46f8dfc9be8a90bdfca8666817607beba654d9/packages/react-day-picker/src/hooks/useRange/useRange.ts#L13).

**Expected behavior**
The `from` and `to` props in [MatchFromTo](https://github.com/gpbl/react-day-picker/blob/7a46f8dfc9be8a90bdfca8666817607beba654d9/packages/react-day-picker/src/types/MatchFromTo.ts#L4) should be optional so they are compatible with `DaysRange`.

**Additional context**
Package version: **`8.0.0-beta.1`**

**Comment by ryanburr** [comment]
Also, I noticed the `DaysRange` interface is not exported from the module.

**Comment by gpbl** [comment]
Thanks! Upcoming beta will have this fixed.
