### ISSUE TITLE
v.8.0.0 - I can choose a date that is marked as disabled

### ISSUE THREAD

**Issue by ajotka** [gpbl/react-day-picker#1169]
**Describe the bug**
I can choose a date that is marked as disabled. 
This is what the disabled attribute is for - to prevent from being clickable or keyboard accessible.

**To Reproduce**
[this CodeSandbox](https://codesandbox.io/s/naughty-flower-1okvx?file=/src/FormInputDate.js).

**Expected behavior**
cursor: not allowed 
no possibility to select this date (by clicking, from the keyboard and using useInput())

**Screenshots**
![image](https://user-images.githubusercontent.com/15144546/108356842-ef8abe80-71ec-11eb-9a80-16826c123d78.png)

**Additional**
In my example on CodeSanbox you can find a temporary workaround.

Ps. Accessibility works great!

**Comment by gpbl** [comment]
Thanks! This is going to be resolved in the next beta.

**Comment by gpbl** [comment]
This should be fixed https://codesandbox.io/s/objective-hooks-3td1t (style being fixed soon)

Please note props may have been changed from the version you were testing!

If you are working with range of days, try the new built-in feature: https://react-day-picker-next.netlify.app/basics/selecting-days#selecting-a-range-of-days I'd love a feedback!
