### ISSUE TITLE
how to apply modifiers not only to DayPicker-Day

### ISSUE THREAD

**Issue by mqklin** [gpbl/react-day-picker#117]
How can i apply some classes with `modifiers` not only to `DayPicker-Day`, but to `DayPicker`, `DayPicker-Weekdays`, ... too?

**Comment by gpbl** [comment]
@mqklin this is not possíble yet, however I'm open to new ideas ... What is your use case? Could you explain better your need? Thanks!

**Comment by mqklin** [comment]
I wanted to open calendar on input click and close it after date pick:
![datepick-example](https://cloud.githubusercontent.com/assets/9456433/12002577/325f8204-ab23-11e5-9060-6f0c5812469b.gif)

These are my workarounds, the first one with `react-day-picker` and the second one with `react-datetime`.
Here is the code, if you interested:
`my-daypicker.scss`

    .my-datepicker {
      input {
        color: transparent;
        text-shadow: 0 0 0 black;
        text-align: center;
      }
      .DayPicker {
        position: absolute;
        z-index: 1;
        padding: 0;
        margin-left: -7px;
        &.is-opened {
          display: flex;
        }
        &.is-closed {
          display: none;
        }
        .DayPicker-Month {
          margin-top: 1em;
          background: white;
          .DayPicker-Caption {
            background: white;
            line-height: 2.3em;
          }
        }
        .DayPicker-NavButton {
          margin-top: 1em;
          &.DayPicker-NavButton--prev {
            left: 1.4rem;
          }
          &.DayPicker-NavButton--next {
            right: 0.6rem;
          }
        }
        .DayPicker-Day:hover {
          background: #F5F5FA;;
        }
      }
    }

`MyDayPicker.js`
import React from "react";
    import DayPicker from "react-day-picker";
    import MomentLocaleUtils from "react-day-picker/moment";
    import "moment/locale/ru";

    export class MyDayPicker extends React.Component {
      constructor(options) {
        super(options);
        this.state = {
          opened: false,
          value: null,
          month: null
        };
      }

      handleDayClick = (e, day) => {
        this.setState({
          value: moment(day).format("L"),
          month: day,
          opened: false
        });
      }

      onKeyPress(e) {
        e.preventDefault();
      }

      onClick = () => {
        let x = !this.state.opened;
        this.setState({opened: x});
      }

      render() {
        return (
          <div className={this.props.className}>
            <input
              type="text"
              onClick={this.onClick}
              onKeyPress={this.onKeyPress}
              value={this.state.value}/>
            <DayPicker
              className={this.state.opened ? "is-opened" : "is-closed"}
              locale="ru"
              localeUtils={MomentLocaleUtils}
              onDayClick={this.handleDayClick}/>
          </div>
        );
      }
    }

`Main.js`

    import {MyDayPicker} from "../../common-components/MyDayPicker";
    ....
    render() {
      return <MyDayPicker className="my-daypicker"/>;
    }

**Comment by gpbl** [comment]
@mqklin I don't see what's wrong with your solution - what would you expect from the day picker?

**Comment by mqklin** [comment]
@gpbl,
1) ability to open/close calendar under input with absolute position on input click  (i think that this input should be in one box with `DayPicker` component)
2) ability to take some `preventKeyPresses` prop, that will hide blinking cursor in this input and prevent keypresses (in this case you can select data only with mouse)
3) ability to take some `closeOnDaySelect` prop, that will hide calendar after data select (i think it should be behaviour by default: i can't imagine benefits to keep calendar opened after data select). After select, elected date must appear in the input.

So, i believe that my solution is so tricky and day picker should make this out of the box.

**Comment by gpbl** [comment]
This is a part [I'd like](https://github.com/gpbl/react-day-picker/issues/98) to document better. I understand it is a difficult task, but it is not strictly related to the component itself.

**Comment by mqklin** [comment]
Ok, issue can be closed.

**Comment by gpbl** [comment]
Thanks for the feedback !
