### ISSUE TITLE
Property 'labelsFormatters' required in type 'DayPickerComponentProps' (v8)

### ISSUE THREAD

**Issue by pmartiner** [gpbl/react-day-picker#1170]
**Describe the bug**
When creating a wrapper for the `DayPicker` component, I get a TypeScript error stating that the property 'labelsFormatters' is required in type `DayPickerComponentProps`.

**To Reproduce**
The bug is reproduced on [this CodeSandbox](https://codesandbox.io/s/jovial-lewin-fid5n?file=/src/App.tsx) to reproduce the bug.

**Expected behavior**
The `labelFormatters` prop should not appear in `DayPickerComponentProps`. The `DayPickerComponentProps` should be almost the same as the [DayPickerProps.ts](https://github.com/gpbl/react-day-picker/blob/master/packages/react-day-picker/src/components/DayPicker/DayPickerProps.ts) src file.

**Screenshots**
![image](https://user-images.githubusercontent.com/25936810/108406639-4cd04100-71e8-11eb-8aff-2acda455c2d8.png)

**Comment by pmartiner** [comment]
FIXED in beta 5

**Comment by gpbl** [comment]
@pmartiner thanks for trying the beta! Your report has been useful to discover some bugs. I've released a `beta.7`.

I wanted to provide some selection feature out of the box, so now DayPicker handle the selected state: https://react-day-picker-next.netlify.app/basics/selecting-days

Also, I've seen you were trying to create a range picker – I have been working to this feature integrated in DayPicker, and a range picker too: https://react-day-picker-next.netlify.app/basics/selecting-days#selecting-a-range-of-days

Which features are you implementing? I am thinking to add a `minDayCount` and `maxDayCount` (so user cannot choose less than / more than that).

**Comment by pmartiner** [comment]
Thank you for reaching out @gpbl!
The `minDayCount` and `maxDayCount` would actually be really useful!
