### ISSUE TITLE
v.8.0.0 - Navigate by arrow keys works only with React v.17.*

### ISSUE THREAD

**Issue by ajotka** [gpbl/react-day-picker#1171]
**Describe the bug**
I don't know if it's the bug, maybe it's on purpose, but navigate by arrow keys works only for React v.17.0.0 and above.
Tested with `React 17.0.*`, `16.9.*`, `16.10.*` and `Day Picker beta v3` and `v5`.

**To Reproduce**
[CodeSandbox](https://codesandbox.io/s/vibrant-gauss-z65im?file=/package.json)

**Expected behavior**
Fix or if it's on purpose - add a disclaimer to the documentation.

**Screenshots**

Version 16.9.0 (**doesn't work**)
![16 CodeSandbox](https://user-images.githubusercontent.com/15144546/108521304-e1f83600-72cb-11eb-9981-50dc6b6dde09.gif)

Version 17.0.1 (**works**)
![17 CodeSandbox](https://user-images.githubusercontent.com/15144546/108521368-f2a8ac00-72cb-11eb-8654-940ee4f26f3d.gif)

**Comment by gpbl** [comment]
This is very interesting – thanks for spotting it! Hopefully removing `e.stopPropagation();` would work! Let me see.
