### ISSUE TITLE
file pointed to by "module" field of published package.json is not an ES module.

### ISSUE THREAD

**Issue by dgoldstein0** [gpbl/react-day-picker#1172]
**Describe the bug**
The "module" field of a package.json is supposed to point to a file which is an Ecmascript module - i.e. has one or more import or export statements.  The provided file, build/index.js, however, is commonjs.  This trips up build tools which may expect otherwise.

Discovered on version 7.4.8 of react-day-picker

**Comment by gpbl** [comment]
Thanks this should be fixed in v7.4.10.

**Comment by dgoldstein0** [comment]
thanks!
