### ISSUE TITLE
Day, WeekNumber and Navigation buttons should have a type="button" attribute to avoid submission in form

### ISSUE THREAD

**Issue by sermicromegas** [gpbl/react-day-picker#1185]
**Describe the bug**
If the day-picker is inside a form and I click on a day or on the month navigation buttons, it triggers a form submission.

**Expected behavior**
If the day-picker is inside a form and I click on a day or on the month navigation buttons, it should not trigger a form submission.
Simply add the type="button" attribute to each <button> component

**Comment by gpbl** [comment]
Hey thanks so much for reporting this bug 💯

**Comment by sermicromegas** [comment]
It's my pleasure 😉
