### ISSUE TITLE
Option to customize the Nav Bar section

### ISSUE THREAD

**Issue by phkavitha** [gpbl/react-day-picker#119]
Need option to customize the nav bar section so that user can use their own icons for next month, next year, previous month, previous year. Or can add extra functionalities for next month, next year action

**Comment by gpbl** [comment]
Hi @phkavitha! 
You can set your own icons [via CSS](https://github.com/gpbl/react-day-picker/blob/master/src/style.css#L37-L45). 

Currently there's no built-in option to display previous/next year icons. You can however use the [`captionElement`](http://www.gpbl.org/react-day-picker/docs/APIProps.html#captionelement-element) prop to set whatever you want in the caption, e.g. you could add your own toolbar and skip the `.DayPicker-NavBar` elements in your CSS. [Here](http://www.gpbl.org/react-day-picker/examples/#yearNavigation) there's a more complex example using a form to change month and year.
