### ISSUE TITLE
Release v7.x with React 17 support?

### ISSUE THREAD

**Issue by scand1sk** [gpbl/react-day-picker#1192]
Current release (v7.4.0) depends on React 16. I can't wait v8 release to support React 17 in my project. 
Can you release a v7.x depending on React 17?

**Comment by gpbl** [comment]
@scand1sk just released v7.4.10 with React 17 support:

https://codesandbox.io/s/xdae3x0w8

**Comment by scand1sk** [comment]
I did not notice the v7.4.9 release, sorry! Thanks for implementing a feature the day before I ask for it :)
