### ISSUE TITLE
esm version

### ISSUE THREAD

**Issue by KannarFr** [gpbl/react-day-picker#1194]
**Describe the bug**

Due to https://github.com/vitejs/vite/issues/2692, https://github.com/vitejs/vite/issues/2139 and finally https://github.com/rollup/plugins/issues/481, can you release an esm version of this library like lodash does with lodash & lodash-es?

**Comment by KannarFr** [comment]
@gpbl fyi

**Comment by sinnbeck** [comment]
If anyone stumble upon this issue, you can do this to make it work in both vite and rollup

```
import DPI from 'react-day-picker/DayPickerInput';
const DayPickerInput = DPI.default || DPI

**Comment by KannarFr** [comment]
@sinnbeck thanks!

**Comment by dylang** [comment]
https://github.com/gpbl/react-day-picker/blob/master/packages/react-day-picker/rollup.config.js#L14

Is this supposed to be `format: 'es'` - not `format: 'esm'`? 

From Rollup's docs:
```
-f, --format <format>       Type of output (amd, cjs, es, iife, umd, system)
```

Just a guess, I'm not a Rollup user.

**Comment by gpbl** [comment]
> Yes, I think it should be es not esm

@tjfred35 we need to organize these build issues. I am not sure if the current build works as expected.

**Comment by jodaka** [comment]
Last week we had to downgrade Node from 17 back to 16, cause this package wasn't compiling. Something to check once this issue is resolved

**Comment by tjfred35** [comment]
`format: 'esm',` and `format: 'es',` produce the exact same result...so that's not the issue. Is this a v7 issue, I imagine?

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
