### ISSUE TITLE
Bug when changing the colour of selected days

### ISSUE THREAD

**Issue by cr3spo9** [gpbl/react-day-picker#1197]
**Describe the bug**
When I change the style of the selected days it happens that with the first and the last days of the week they appear like bugged with the style applied to fields that it shouldnt

**To Reproduce**
const modifiersStyles = {
  selected: {
      color: 'white',
      backgroundColor: '#334355',
  }
}

**Expected behavior**
It should be applied the style like with the default style

**Screenshots**
![image](https://user-images.githubusercontent.com/43613261/112808852-b4946a00-9079-11eb-9873-21434f105d81.png)
![image](https://user-images.githubusercontent.com/43613261/112808884-be1dd200-9079-11eb-99c6-2e75325f898b.png)

**Comment by traksl** [comment]
Please, could someone had a look at this issue? Thanks (:

**Comment by IreneChang423** [comment]
Set "DayPicker-Day--outside" transparent solve this problem!

<style>{`
        .DayPicker-Day--outside {
            background-color: transparent;
            &:hover {
              background-color: transparent;
            }
          }
          `}</style>

**Comment by tjfred35** [comment]
Marking this as v7 because it looks like v8 solves this (no styles are rendered on hidden outside days)

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
