### ISSUE TITLE
initialMonth before fromMonth

### ISSUE THREAD

**Issue by davidspiess** [gpbl/react-day-picker#120]
If i set `initialMonth` to a date before `fromMonth` it displays the `initialMonth` month and bypasses the `fromMonth` constraint.

**Comment by gpbl** [comment]
Hi @davidspiess !
Should it start from the `fromMonth` instead?

**Comment by davidspiess** [comment]
Hi @gpbl ! :)
Yes that's what i expected. I needed a way to get the date of the current month outside of `this.ref.daypicker.state.currentDate`, so i used my own date variable and rerender the datepicker everytime that variable changes, At some point i noticed, it bypasses mit `fromMonth`, `toMonth` constraints that way.

**Comment by gpbl** [comment]
I see... yeah i think you are right. If the `initialDate` is out of range, it should consider `fromMonth` or `toMonth` instead. For now, I believe you can just pass the correct `initialDate` if it falls out of the range. 

Anyway if you need to know the current month, you can use `onMonthChange`.

**Comment by davidspiess** [comment]
I don't think many people will run into this anyway :) Thanks for the suggestion, i try it that way for now!

**Comment by gpbl** [comment]
I've taken a look to this issue and I think it is OK the behavior at it is. I prefer to leave to the implementer the responsibility to check whether `initialDate` is inside the from-to range: there are too many parts of the source that need to be updated just to prevent this case :)
