### ISSUE TITLE
DayPickerInput reopens on tab change

### ISSUE THREAD

**Issue by Jamesgt** [gpbl/react-day-picker#1204]
**Describe the bug**
On tab change a focused input with closed DayPickerInput opens again when tab is refocused.

**To Reproduce**
- Use the first example here: https://react-day-picker.js.org/docs/input.
- select a day, so overlay hides, don't unfocus input
- change to other tab
- change back to the docs tab
- overlay is open again

**Expected behavior**
Overlay should remain hidden.

**Screenshots**
-

**Additional context**
Chrome v89.0.4389.114, Windows
Chrome v89.0.4389.105, Android

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
