### ISSUE TITLE
Wrong export (v7.4.10)

### ISSUE THREAD

**Issue by pustovalov** [gpbl/react-day-picker#1205]
`7.4.9`

```
built modules 624 KiB [built]
  modules by path ./node_modules/react-day-picker/build/*.js 66.8 KiB 14 modules
```

```
import DayPicker from 'react-day-picker'

// all works fine
```

`7.4.10`

```
built modules 598 KiB [built]
    ./node_modules/react-day-picker/lib/react-day-picker.min.js 41.1 KiB [built] [code generated]
```

```
import DayPicker from 'react-day-picker'

// an error
```

**Comment by pustovalov** [comment]
Looks like after the `browser` field was added, the webpack started to use `react-day-picker.min.js` source

Used such workaround:

```
module.exports = {
  resolve: {
    mainFields: ['module', 'main', 'browser'],
  },
}
```

maybe this solution will help someone

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
