### ISSUE TITLE
DayPicker Layout distorted

### ISSUE THREAD

**Issue by MauriceArikoglu** [gpbl/react-day-picker#1209]
**Describe the bug**
Out of the box code for DayPickerInput has incorrect layout.

**Expected behavior**
Layout to be correct and not distorted

**Screenshots**
<img width="436" alt="Bildschirmfoto 2021-04-09 um 20 17 13" src="https://user-images.githubusercontent.com/5528623/114223857-9af3fc00-9970-11eb-9775-f64adad465a5.png">

**Additional context**
Using TailwindCSS 2.0 and React

**Comment by MauriceArikoglu** [comment]
So, this happens because TailwindCSS sets a default line height and react-day-picker inherits this style, as seen here: https://github.com/gpbl/react-day-picker/blob/e60d5fa97223d300293c15d5ab6364582dacab08/packages/react-day-picker/style.css#L186

This can be fixed by setting a custom line height to the DayPicker node directly (or the parent node) `style` to inherit from.
Example with TailwindCSS: 
```
...
<div className="leading-tight">
                    <DayPickerInput ...
```

**Comment by MauriceArikoglu** [comment]
@gpbl is this intended behavior or would you consider this a bug?
Imo the height and width for the table-cells should not be affected by the global line-height - if they are though, the selection indicator should at least be sized independently...

**Comment by kai23** [comment]
Hey, same error here, I don't get why but the width on the left is smaller than the right : 
<img width="339" alt="Capture d’écran 2021-05-05 à 09 58 43" src="https://user-images.githubusercontent.com/796803/117112205-00c57f00-ad89-11eb-9a08-4037e763bfe7.png">
<img width="341" alt="Capture d’écran 2021-05-05 à 09 58 34" src="https://user-images.githubusercontent.com/796803/117112207-01f6ac00-ad89-11eb-96b7-bdeb9817b487.png">

I've tried to change the line-height, without any chances :/

**Comment by MauriceArikoglu** [comment]
@kai23 there are multiple properties set dynamically. 

Have a look into the library's code to figure out which. I would try setting all these on a parent node to see if they fix it.

**Comment by kai23** [comment]
Yeah, I finally found some codesandbox which don't have this problem, and I've adapted it to my project. Thanks for taking the time to reply !

**Comment by MauriceArikoglu** [comment]
@kai23 can you share your solution here? So others will have more references for bug hunting?

**Comment by marllonfrizzo** [comment]
Hi! I resolved it as follows:

defines a fixed width for days
```scss
.DayPicker-Day {
    width: 42px;
}
```
and set the width of the overlay to max-content
```scss
.DayPickerInput-Overlay {
    width: max-content;
}
```

This solved for me, I don't know if it is the best way, but I am curious about the possible solution of @kai23.

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
