### ISSUE TITLE
Can't add a single className, when using classNames prop

### ISSUE THREAD

**Issue by dfvalero** [gpbl/react-day-picker#1219]
**Describe the bug**

I'm trying to overwrite a className using the classNames prop and typescript complains.

**To Reproduce**

![Screen Shot 2021-05-11 at 15 33 05](https://user-images.githubusercontent.com/337955/117823889-40e79e80-b26e-11eb-92ed-46262962b225.png)

**Expected behavior**

Be able to add a single className, or multiple ones. Actually, you need to pass all the classNames because the interface have  all the object keys as required.

**Screenshots**

**Additional context**

**Comment by CarlosHdez** [comment]
I also encountered this problem, and I tried to provide all classes but the link for the defaults on the docs is broken

**Comment by CyrilQuandalle** [comment]
Here you go @CarlosHdez ;-):

`export const defaultDatePickerClasses = {
  container: 'DayPicker',
  wrapper: 'DayPicker-wrapper',
  interactionDisabled: 'DayPicker--interactionDisabled',
  months: 'DayPicker-Months',
  month: 'DayPicker-Month',
  navBar: 'DayPicker-NavBar',
  navButtonPrev: 'DayPicker-NavButton DayPicker-NavButton--prev',
  navButtonNext: 'DayPicker-NavButton DayPicker-NavButton--next',
  navButtonInteractionDisabled: 'DayPicker-NavButton--interactionDisabled',
  caption: 'DayPicker-Caption',
  weekdays: 'DayPicker-Weekdays',
  weekdaysRow: 'DayPicker-WeekdaysRow',
  weekday: 'DayPicker-Weekday',
  body: 'DayPicker-Body',
  week: 'DayPicker-Week',
  weekNumber: 'DayPicker-WeekNumber',
  day: 'DayPicker-Day',
  footer: 'DayPicker-Footer',
  todayButton: 'DayPicker-TodayButton',
  today: 'today',
  selected: 'selected',
  disabled: 'disabled',
  outside: 'outside',
};
`

**Comment by CarlosHdez** [comment]
In case someone sees this, the last 4 are incorrect, they should be
```{
 today: 'DayPicker-Day--today',
 selected: 'DayPicker-Day--selected',
 disabled: 'DayPicker-Day--disabled',
 outside: 'DayPicker-Day--outside'
}

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
