### ISSUE TITLE
v8. Days ordering for locales where week starts on Monday (January 2021-23)

### ISSUE THREAD

**Issue by alesvojta** [gpbl/react-day-picker#1222]
**Describe the bug**
When using locale option where week starts at Monday (eg cs or fr), dates for beginning of the month are aligned at the end of the table for January 2021-2023.

**To Reproduce**
https://codesandbox.io/s/daypicker-locale-week-starts-monday-85bb8

**Expected behavior**
Days are aligned in correct order 1, 2, 3, 4, 5, ..., 28, 29, 30, 31.

**Screenshots**
![image](https://user-images.githubusercontent.com/1668328/118465814-8ee32300-b702-11eb-9e87-c4ed0625508f.png)

**Additional context**
Used beta 29 but experiencing it since alpha 45.

**Comment by brentvb** [comment]
As a workaround you can set the firstWeekContainsDate property of your locale to 1. As far as I am aware the only downside of the workaround would be that you can't show the correct weekNumber according to your locale.

**Comment by tjfred35** [comment]
I think this might be the same root cause as https://github.com/gpbl/react-day-picker/issues/1207

**Comment by tjfred35** [comment]
Yeah same issue
<img width="361" alt="Screen Shot 2021-11-02 at 7 54 09 AM" src="https://user-images.githubusercontent.com/2838338/139841503-5f15d616-47c1-4d80-af6f-523ada1cca81.png">

**Comment by tjfred35** [comment]
I've got a fix here: https://github.com/gpbl/react-day-picker/pull/1270. Would appreciate some review.
