### ISSUE TITLE
v8. Example for in "Selecting a range of days" in documentation raises error

### ISSUE THREAD

**Issue by finnan444** [gpbl/react-day-picker#1223]
**Describe the bug**
If you copy [code](https://react-day-picker-next.netlify.app/basics/selecting-days#selecting-a-range-of-days) from **Selecting a range of days** example, typescript will show error for `onSelect` property
`Type 'Dispatch<SetStateAction<DateRange>>' is not assignable to type '((SelectSingleEventHandler | SelectMultipleEventHandler | SelectRangeEventHandler)`

Plus if you run code in [codesandbox](https://codesandbox.io/s/rtv8d?file=/example.tsx) provided "react-day-picker": "8.0.0-beta.30" - raises npm error:  `No matching version found for react-day-picker@^8.0.0-beta.30.`

**Expected behavior**
Separate handler func should be passed to onSelect, like
``` JS
const handleRangeSelect = (range?: DateRange) => {
        if (range) {
            setRange(range)
        }
    }
...
return <DayPicker mode="range" defaultSelected={defaultSelected} footer={footer} onSelect={handleRangeSelect} />

```

**Comment by tjfred35** [comment]
Oh yeah...interesting. `8.0.0-beta.29` works, although yeah there's an issue with handling no range / deselected range. That nulls out.

**Comment by tjfred35** [comment]
I'm not seeing that typescript error, but I am working on fixing these same stories here: https://github.com/gpbl/react-day-picker/pull/1274

**Comment by tjfred35** [comment]
@finnan444 As far as I can tell this is fixed. Going to close it.

**Comment by aksong-nom2** [comment]
This issue doesn't seem to be fixed.  I'm getting a different TS error for the onSelect handler with `8.0.0-beta.32`:  

`Type 'Dispatch<SetStateAction<DateRange>>' is not assignable to type 'never'.ts(232`

Please see this [forked codesandbox](https://codesandbox.io/s/daypicker-basics-selecting-days-range-example-forked-evc5l?file=/example.tsx).

**Comment by finnan444** [comment]
On version `8.0.0-beta.31` example works if you rewrite state and select handler a little bit:
```TS
const [range, setRange] = React.useState<DateRange | undefined>(defaultSelected)
...
onSelect={(range: DateRange | undefined) => setRange(range)}

**Comment by gpbl** [comment]
There's for sure something not working there! Thanks all for looking at it. I think this Is related to #1298: website is using latest from master (that should have fixed it), but .32 does not.

**Comment by gpbl** [comment]
BTW @aksong-nom2 is running into two different errors. Let see if publishing a new beta fixes them – now we have the tests for the examples.

**Comment by gpbl** [comment]
A beta.33 is published and should have fixed the issue.

https://codesandbox.io/s/sandpack-project-forked-8bwdz?file=/src/App.tsx

The codesandbox is behaving weird (can't find the latest del?) I don't have the time to look at it, any hint appreciated :)

**Comment by finnan444** [comment]
@gpbl the link prints for me
Something went wrong
Sandbox not found

**Comment by aksong-nom2** [comment]
I forked again w/ beta.35 and still see the Typescript issue:

https://codesandbox.io/s/daypicker-basics-selecting-days-range-example-forked-y0cg5?file=/example.tsx

**Comment by gpbl** [comment]
> I forked again w/ beta.35 and still see same the Typescript issue:
> 
> https://codesandbox.io/s/daypicker-basics-selecting-days-range-example-forked-y0cg5?file=/example.tsx

Not sure what's going on in that Sandbox. I don't see the updated version installed. For example, there's no more `defaultSelected`.

There's however an updated example:

https://react-day-picker-next.netlify.app/basics/selecting-days#selecting-a-range-of-days

and the relative sandbox:

https://codesandbox.io/s/wlybt?file=/src/App.tsx&from-sandpack=true

I'd say this issue is outdated – if there's a new bug please file a new issue. Thanks !
