### ISSUE TITLE
Import statement can not find MomentLocaleUtils

### ISSUE THREAD

**Issue by Chusynuk** [gpbl/react-day-picker#1226]
**Describe the bug**
`import` statement is not able to properly find `MomentLocaleUtils` in _node_modules_ cause the folder It's named `moment`  instead of `MomentLocaleUtils` 

**Expected behavior**
To have a `MomentLocaleUtils` folder, same as `DatePicker` and `DatePickerInput`. So then we just need to do:

`import MomentLocaleUtils from 'react-day-picker'`

**Screenshots**

in NODE_MODULES folder

![image](https://user-images.githubusercontent.com/4323435/119268052-6de26c80-bbf1-11eb-9521-a24967210407.png)

![image](https://user-images.githubusercontent.com/4323435/119268008-3ecbfb00-bbf1-11eb-8973-dac98c02dd83.png)

**Additional context**

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
