### ISSUE TITLE
DateUtils.addDayToRange isn't typed correctly

### ISSUE THREAD

**Issue by CyrilQuandalle** [gpbl/react-day-picker#1227]
Hello,
When I try to pass an undefined value as a second argument to DateUtils.addDayToRange I have my typecker yelling at me that this function only accept a RangeModifier, whereas in the implementation I see that undefined is handled.

I'm using the version 7, here is the implementation from the library :

```ts
function addDayToRange(day) {
  var range = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : { from: null, to: null };
  var from = range.from,
      to = range.to;

  if (!from) {
    from = day;
  } else if (from && to && isSameDay(from, to) && isSameDay(day, from)) {
    from = null;
    to = null;
  } else if (to && isDayBefore(day, from)) {
    from = day;
  } else if (to && isSameDay(day, to)) {
    from = day;
    to = day;
  } else {
    to = day;
    if (isDayBefore(to, from)) {
      to = from;
      from = day;
    }
  }

  return { from: from, to: to };
}
```

**Comment by CyrilQuandalle** [comment]
I've created a pull request to fix it :
https://github.com/gpbl/react-day-picker/pull/1230

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
