### ISSUE TITLE
Tab navigation always focuses on the first day of the month

### ISSUE THREAD

**Issue by alexlopezit** [gpbl/react-day-picker#1236]
**Accessibility: Keyboard navigation**
When navigating with the keyboard and entering the dates, the focus seems to always go to the first day of the month, this is fine when no dates are disabled, but is dates are disabled including the fist day, the focus should go to the first enabled day

**To Reproduce**
[CodeSandbox](https://codesandbox.io/s/react-day-picker-base-forked-3j7er?file=/index.js) to reproduce the bug.

**Expected behavior**
When navigating with the keyboard and entering the days, the focus should go to the first day enabled.

**Comment by McSam27** [comment]
We did a work around for our custom date input, we added a listener for a keydown event for when the user is focused on the input, and presses the down arrow key:

`document.querySelector('.DayPicker-Day:not(.DayPicker-Day--disabled):not(.DayPicker-Day--outside)').focus();`

This goes to the first available date. Not the same exact situation as yours but this might be helpful until v8 is out of beta.

**Comment by tjfred35** [comment]
Additionally, the example in https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html for tab navigation suggests that focus should move to the current date (today) or the selected date when opening a date picker dialog 

And what's more! The date that was previously selected with the keyboard is _preserved_ when tabbing backwards and forwards to other focusable elements.

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
