### ISSUE TITLE
Disable all Keyboard Events

### ISSUE THREAD

**Issue by fgildner** [gpbl/react-day-picker#1237]
**Describe the bug**
Cannot disable keyboard event on onDayKeyDown
**To Reproduce**
https://codesandbox.io/s/ilfjj?module=/example.js
and add onDayKeyDown={(day,modifiers, e)=>e.preventDefault()}

**Expected behavior**
Disable all keyboard events and cannot select/deselect Day with Enter and Space

**Comment by GitArika** [comment]
bump
