### ISSUE TITLE
v8. The custom Head component is not used

### ISSUE THREAD

**Issue by fabienmoritz** [gpbl/react-day-picker#1244]
**Describe the bug**
The custom Head component is not used in v8 beta 29.

**To Reproduce**
https://codesandbox.io/s/react-day-picker-base-forked-msgxq?file=/index.js

**Expected behavior**
"Custom header" should be displayed instead of "SU MO..." in the sandbox up there.

**Comment by tjfred35** [comment]
Can you share a little more about why you want to customize the Head component?

**Comment by fabienmoritz** [comment]
I would like to display "N°" in the week number header, because my component is selecting a week instead of a day, so I want to emphasize this column.
