### ISSUE TITLE
Is there a way to unselect a day without user interaction

### ISSUE THREAD

**Issue by ablajievschii** [gpbl/react-day-picker#1245]
### Discussed in https://github.com/gpbl/react-day-picker/discussions/1234

<div type='discussions-op-text'>

<sup>Originally posted by **ablajievschii** June 11, 2021</sup>

Hi all, tried to get an answer in discussion but no help there. Hope I can get an answer here.

I'm using DayPickerInput in my React application and I need to unselect a day without user interaction. I've already tried setting selectedDay to undefined, but it does not work. Setting input element value to empty string does not work either.
I know about clickUnselectsDay, but how to unselect without user interaction ? Is there a way to simulate a click or maybe use some public function on DayPickerInput instance ?</div>

**Comment by tjfred35** [comment]
I was going to suggest that you should use the "controlled" mode where you pass in `selected`...

```
export default function Example() {
  const [days, setDays] = React.useState([]);

  const footer =
    days.length > 0
      ? `You picked ${days.length} day(s).`
      : `Please pick one or more days.`;

      const removeLastSelected = () => {
        setDays(days.slice(0, days.length - 1))
      }

  return (
    <div>
      <DayPicker mode="multiple" selected={days} onSelect={setDays} footer={footer} />
      <button disabled={days.length === 0} onClick={removeLastSelected}>Remove most recent selection</button>
    </div>
  );
}
```

...but it doesn't work! Maybe there is no true "controlled" mode, because it's blending the selected prop here with the internal selected state...

We should make it so that if `selected` is not undefined then we are in a "controlled" mode and the internal state is not used.

**Comment by tjfred35** [comment]
Ok, I have a solution for this:

https://github.com/gpbl/react-day-picker/pull/1276

**Comment by tjfred35** [comment]
@ablajievschii This is now possible in the v8 beta. I think your comments are about v7, so going to change the labels to match that assumption.

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
