### ISSUE TITLE
classNames do not get applied

### ISSUE THREAD

**Issue by alexsmartens** [gpbl/react-day-picker#1249]
**Describe the bug**
`className` is not getting applied.

**To Reproduce**
One of the things that I'm trying to do is to make the `DayPickerInput` to inherit my font size. I can adjust `DayPickerInput`'s font in styling as below.
```
<style>{`
  .DayPicker-Month { font-size: 0.75rem; }
`}</style>
```
However, I'm using named classes and the above option doesn't fit the bill. So, I tried to **do the same thing with classNames instead** but my classes are ignored:
```
<DayPickerInput
  format="MM/dd/yy"
  classNames={{month: "DayPicker-Month _test_class_ text-sm"}}
  placeholder={"MM/DD/YY"}
/>
```

**Expected behavior**
1) `_test_class_` and `text-sm` should be applied.
2) I'm using Tailwind where `text-sm` changes the font size, so I'd expect the font to be small (`font-size: 0.75rem`).

**Screenshots**
As you can see from the inspector neither `_test_class_` nor ` text-sm` are applied to the `month` component.

![Screen Shot 2021-08-11 at 11 41 10 AM](https://user-images.githubusercontent.com/26261714/129060522-637c9cf8-e110-4b4c-b4be-0a586ddd8e6b.png)

Also, for comparison `Date Range` label is `text-sm` but `DayPickerInput month` is not.

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
