### ISSUE TITLE
(v.8) Broken day layout for January for locales where the first day of week is Monday

### ISSUE THREAD

**Issue by dmitriifrlv** [gpbl/react-day-picker#1250]
**Describe the bug**
Day layout breaks for January(not for every year though but it was noticed for January 2021, 2022, 2023 ) for locales where the first day of the week is Monday(for several months)
<img width="388" alt="Screenshot 2021-08-14 at 20 39 16" src="https://user-images.githubusercontent.com/65853205/129451560-0426fbbf-fabc-4db9-b6b7-ef5782475d49.png">

**To Reproduce**
Clone [this CodeSandbox](https://codesandbox.io/s/broken-day-layout-9f9l2?file=/src/App.js) to reproduce the bug.

**Expected behavior**
The layout where the first days of the month are on the first row.

<img width="413" alt="Screenshot 2021-08-14 at 20 44 42" src="https://user-images.githubusercontent.com/65853205/129451716-e056804a-7081-4bec-9850-d80bded88fd9.png">

**Comment by Gertjan1996** [comment]
@dmitriifrlv did you find a workaround for this problem?

**Comment by tjfred35** [comment]
Oh, interesting...the week number is 52
<img width="380" alt="Screen Shot 2021-11-02 at 7 49 28 AM" src="https://user-images.githubusercontent.com/2838338/139840895-d857580d-d380-4251-9535-bf059dd3ec92.png">

**Comment by tjfred35** [comment]
I've got a fix here: https://github.com/gpbl/react-day-picker/pull/1270. Would appreciate some review.
