### ISSUE TITLE
Expose `day_selected` in `classNames`

### ISSUE THREAD

**Issue by reintroducing** [gpbl/react-day-picker#1253]
**Describe the bug**
Looking at https://github.com/gpbl/react-day-picker/blob/1765e4828829eceed818409cc0ea5e7e71cd6176/packages/react-day-picker/src/contexts/DayPicker/defaultClassNames.ts, `day_selected` is not exposed and cannot be used properly with CSS modules. Passing it through anyway also doesn't work.

**To Reproduce**
Pass `classNames.day_selected` and notice it has no output.

**Expected behavior**
Passing the prop in classNames would reflect on the HTML output.

**Comment by reintroducing** [comment]
To follow up, setting `classNames.day_today` also does not seem to be going through to the output, unfortunately.

**Comment by Gertjan1996** [comment]
Also have problems with selecting/ styling day_today, because it is showing up as rdp-day_today in the HTML.

**Comment by gpbl** [comment]
There could be some technical limitations for that. To investigate...

**Comment by tjfred35** [comment]
I think what you want is this:

// Do this
```
  <DayPicker 
    modifierClassNames={{
      today: 'foo',
      selected: 'bar'
    }}
  />
```

// Don't do this
```
  <DayPicker 
    classNames={{
      day_today: 'foo',
      day_selected: 'bar'
    }} 
  />
```

**Comment by tjfred35** [comment]
Modifiers are definitely a somewhat weakly typed API, so I'm not sure where we want to go with the v8 API, but right now the modifiers that you get out of the box are:

- today
- disabled
- selected
- range_start
- range_middle
- range_end

There are two exceptions:

// Do this
```
  <DayPicker 
    classNames={{
      day: 'foo',
      day_outside: 'bar'
    }}
  />
```

// Don't do this

  <DayPicker 
    modifierClassNames={{
      outside: 'bar'
    }} 
  />

**Comment by tjfred35** [comment]
I suppose we could change the implementation to look like this:
```
      const customClassName = context.modifierClassNames[modifier];
      if (customClassName) {
        modifierClassNames.push(customClassName);
      } else {
        // Some people find this API more natural, particularly because that's how we override all the other class names:
        const customClassName2 = context.classNames[`day_${modifier}`];
        if (customClassName2) {
          modifierClassNames.push(customClassName);
        } else {
          modifierClassNames.push(`${context.modifierPrefix}${modifier}`);
        }
      }
```

**Comment by gpbl** [comment]
Not sure about the status of this issue - any repro?

**Comment by reintroducing** [comment]
@gpbl I moved to using a custom Day component which allows me to tweak everything so not quite sure if that is still an issue when using just classNames.

**Comment by gpbl** [comment]
@reintroducing thanks a lot for your feedback. There was indeed some confusion on how to style daypicker and modifiers. I've updated the styling documentation and fixed some bugs in https://github.com/gpbl/react-day-picker/commit/b5140dee1ae1989c3a777df61f16ad438abd7a74.
