### ISSUE TITLE
Disabled DateInterval not working

### ISSUE THREAD

**Issue by jeremiasjutz** [gpbl/react-day-picker#1254]
**Describe the bug**
I have a disabled attribute on my <DayPicker /> component, that should disable any dates before and after the defined  dates:
```js
disabled={{
    after: new Date(),
    before: new Date("2021-08-15"),
 }}
```
If I only have `after` or `before` it works as expected, but not together (as documented here https://react-day-picker-next.netlify.app/api/types/dateinterval)

**To Reproduce**
https://codesandbox.io/s/react-day-picker-base-forked-532es?file=/index.js

**Expected behavior**
I would expect to only have the days between `after` and `before` selectable.

**Comment by tjfred35** [comment]
There is this workaround:
```
        <DayPicker
            mode="single"
            disabled={[
              { after: new Date() },
              { before: new Date("2021-08-15") }
            ]}
          />
```

**Comment by tjfred35** [comment]
Your example specifies an incorrect DateInterval. DateInterval is like DateRange but where the range is exclusive of the bounds: `(after, before)` vs `[from, to]`. You cannot have a date that is both before a date in the past _and_ after the current date.
