### ISSUE TITLE
Custom input overlay not closing when cliking outside

### ISSUE THREAD

**Issue by ovidiuwin** [gpbl/react-day-picker#1259]
**Describe the bug**
I'm building a custom overlay for the date picker and it's not closing when clicking outside the container. This happens only if you click or interact in any way with the custom overlay. (for example changing the month or clicking some custom button)

**To Reproduce**
This bug can be seen even in the example:
https://react-day-picker.js.org/examples/input-custom-overlay/

Open the date picker -> Click the custom button inside the overlay -> Click outside

**Expected behavior**
Clicking outside should close the overlay in all scenarios.

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
