### ISSUE TITLE
Improve codebase

### ISSUE THREAD

**Issue by srph** [gpbl/react-day-picker#126]
I think we should improve the codebase and tests :confused: . I hope this isn't taken from a negative POV :smile:

To help, I can start sending very small PRs so unwanted changes can be closed off easily.

**Comment by gpbl** [comment]
You are so right! Those tests are exploding 😓. What do you propose? I was even thinking to split the main component in smaller ones, but I'm not sure there are benefits from this.

**Comment by srph** [comment]
The only benefits I could think of is readability. I was sort of intimidated at first and as I wrote #123.

- We can split components (but I'm not sure if it would improve readability. What are your thoughts?).
- Also, I think we should refactor some bits of the code (e.g., remove destructed variables that are only used once; might lessen LOC, I guess (insignificant, though)?).
- For the tests, I have no idea at the moment.

**Comment by gpbl** [comment]
I'm open to any improvement :relaxed: 

What did you find intimidating at first? `src/DayPicker.js` or the tests?

Splitting it into more components would mean to move the `render*` methods into other files, yet we should pass many props to them and add boring tests. I don't think we would go anywhere.

Sometimes I destructured variables just to keep the line length < 80, e.g:

```js
      const { currentMonth } = this.state;
      const { numberOfMonths } = this.props;
      const prevMonth = DateUtils.addMonths(currentMonth, -numberOfMonths);
```

 Other times I created a new line to make it easier to read:

```
      this.setState({
        currentMonth: prevMonth
      }, () => {
          // etc.
      });
```

**Comment by srph** [comment]
I see!

For some reason, I'm starting to pick up the tests and codebase (since I reread the codebase before and after I submitted this issue).

This issue didn't (and probably can't) point out any main problem. We can leave this open for later, or close it now since I find it irrelevant myself.

**Comment by gpbl** [comment]
No problem @srph thanks a lot for the feedback 🍻
