### ISSUE TITLE
missing HTML tag ID on the react-day-picker documentation website.

### ISSUE THREAD

**Issue by OladapoAjala** [gpbl/react-day-picker#1263]
**Describe the bug**
A missing HTML tag ID prevents the documentation page to scroll to the selected link on the page.

**To Reproduce**
1. Visit the documentation [website](https://react-day-picker.js.org/docs/localization/).
2. Click on advanced-localization
3. Observe that the webpage remains at its current position after the link has been clicked.

**Expected behavior**
The webpage is supposed to the section of the page labelled **Advanced Localization** whenever the link is clicked.

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
