### ISSUE TITLE
DayPicker doesn't close until you click on a day if keepfocus is set to false

### ISSUE THREAD

**Issue by kambleaa007** [gpbl/react-day-picker#1266]
**Describe the bug**

**To Reproduce**
Clone [this CodeSandbox](https://codesandbox.io/s/XDAE3x0W8) to reproduce the bug.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Go1dExperience** [comment]
keepFocus is used if you have a custom component inside DayPickerInput, which contains an input inside itself. Check this page of the documentation: [Custom Overlay](http://react-day-picker.js.org/examples/input-custom-overlay). In your example, you don't have another input field, so you probably don't need to add the keepFocus prop

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
