### ISSUE TITLE
mode: "range" requires controlling the state?

### ISSUE THREAD

**Issue by tjfred35** [gpbl/react-day-picker#1271]
The playground app and the documentation site don't do the best job of demonstrating range selection right now, either because we need to support the uncontrolled behavior or we need to update the documentation to use controlled behavior.

```

const RangeSelection = () => {
  // mode="range" requires being controlled, apparently...
  // TODO: Should we support an uncontrolled operation?
  const [dateRange, setDateRange] = React.useState<DateRange>()
  return (
    <>
      <h1>Range selection</h1>
      <DayPicker
        mode="range"
        fromYear={2010}
        toYear={2020}
        selected={dateRange}
        onSelect={(dateRange: DateRange | undefined) => {
          setDateRange(dateRange)
        }}
        showOutsideDays
        showWeekNumber
        numberOfMonths={1}
      />
    </>
  )
}
```

**Comment by tjfred35** [comment]
This is fixed here: https://github.com/gpbl/react-day-picker/pull/1274

**Comment by tjfred35** [comment]
Actually, there isn't a true controlled state. See this issue, for example, where it is seen to be not possible to reduce the selected dates.

https://github.com/gpbl/react-day-picker/issues/1245

**Comment by gpbl** [comment]
@tjfred35 will look at that soon, thanks!
