### ISSUE TITLE
expose ClassNames type on v7

### ISSUE THREAD

**Issue by artola** [gpbl/react-day-picker#1272]
**Describe the bug**
ClassNames types are not exposed in the barrel file, as it was in former versions (e.g., up to 7.4.1)

https://github.com/gpbl/react-day-picker/blob/v7.4.1/types/common.d.ts

**To Reproduce**

```ts
import type {ClassNames} from 'react-day-picker';  // <= Module '"react-day-picker"' has no exported member 
'ClassNames'. 
```

**Expected behavior**
This code should work without workarounds (e.g., `type ClassNames = CaptionElementProps['classNames']`).

```ts
import type {ClassNames} from 'react-day-picker';
```
**Additional context**
"react-day-picker": "^7.4.10"

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
