### ISSUE TITLE
Default stylesheet doesn't handle ranges for dir="rtl"

### ISSUE THREAD

**Issue by tjfred35** [gpbl/react-day-picker#1277]
This is probably an issue for lots of implementations...definitely is for my custom css.

<img width="360" alt="Screen Shot 2021-11-04 at 9 51 04 PM" src="https://user-images.githubusercontent.com/2838338/140444947-015ebf3b-9ca7-4771-b64c-b0fbe6d2021f.png">

**Comment by gpbl** [comment]
It should be easy to fix with the appropriate selector.
