### ISSUE TITLE
Add keyboard navigation for navigating between months

### ISSUE THREAD

**Issue by tjfred35** [gpbl/react-day-picker#1279]
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html

- Page up (subtract one month)
- Page down (add one month)
- Shift + Page up (subtract one year)
- Shift + Page down (add one year)
- Home (go to first day of week)
- End (go to last day of week)

**Comment by rolandsfr** [comment]
Hey @gpbl, I'm ready to give this issue a shot.

**TODO**  
- [ ] Create navigation for all the 6 types of actions
- [ ] Add a  ``keybaordNavigation`` prop that will take a boolean and enable/disable the keyboard navigation (let me know if you do not want to have a different name for this prop or do not want to have it at all)

**Comment by gpbl** [comment]
@rolandsfr awesome, would you start from a PR where you add the relative todo tests? The file to change for now is this:

https://github.com/gpbl/react-day-picker/blob/master/website/examples/keyboard.test.tsx

For example:

```ts
 describe('when the PageUp is pressed', () => {
        beforeEach(pressPageUp);
        test.todo('should display the previous month');
});
```

**Comment by Ayan-web** [comment]
is someone working on this issue?
