### ISSUE TITLE
v7: Webpack v5 incorrect ESM exports

### ISSUE THREAD

**Issue by mayteio** [gpbl/react-day-picker#1287]
**Describe the bug**
This bug -> discussion describes the issue perfectly: https://github.com/gpbl/react-day-picker/issues/1084. 

In ESM modules, the files need to be fully specified (i.e. `/components/index.js` vs `/components`). This is how native ESM works in node.

**To Reproduce**
```
git clone https://github.com/mayteio/react-day-picker-issue
cd react-day-picker-issue && yarn && yarn storybook
```
```
ModuleNotFoundError: Module not found: Error: Can't resolve './DayPicker' in /react-day-picker-issue/node_modules/react-day-picker/esm'
Did you mean 'DayPicker.js'?
BREAKING CHANGE: The request './DayPicker' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
```

[In node ESM, the path must be fully specified](https://github.com/webpack/webpack/issues/11467#issuecomment-691702706). Making this change would be backward compatible as a fully specified path will always work.

**Expected behavior**
You should be able to import it without issue (and ESM imports/exports should be fully specified)

A workaround for now is to remove the `module` field from `package.json` in `node_modules` so the bundler is forced to use the cjs version.

**Comment by mayteio** [comment]
Hey, I don't think this is v7? This error was from sing v8 beta 29

**Comment by gpbl** [comment]
Sorry from the linked issue I read it was v7: we have released `beta.30` – which moves to rollup for bundling. Would you mind to upgrade and see if your issue is solved? Thanks.

```
npm install react-day-picker@next
```

**Comment by gpbl** [comment]
Closing as we don't use web pack anymore. Please open a new issue if it is not resolved, thanks.

**Comment by mayteio** [comment]
Now there's no `main` field at all in the package.json (therefore `dist` is inaccessible to CJS builders), only `module` and `types`:

https://github.com/gpbl/react-day-picker/blob/10ee39d58c4bec52c3b8bb5085801856c5af3a6f/packages/react-day-picker/package.json#L15-L16

The issue I described isn't actually with which bundler react-day-picker uses, it's that webpack v5 uses node ESM, which doesn't automatically resolve "DayPicker" to "DayPicker.js" and is expecting the full file extension in the bundle (which AFAIK is compatible across all bundlers, it's just more specific).

**Comment by mayteio** [comment]
Updating resolve this, thank you!
