### ISSUE TITLE
Navigation buttons with wrong aria labels on rtl direction

### ISSUE THREAD

**Issue by tjfred35** [gpbl/react-day-picker#1288]
In this example:
```
      <DayPicker
        mode="single"
        dir="rtl"
        onSelect={handleSelect}
        fromDate={new Date(2021, 8, 15)}
        defaultMonth={new Date(2021, 8, 1)}
        toDate={new Date(2021, 10, 15)}
      />
```
https://codesandbox.io/s/react-day-picker-8-forked-ouys4

<img width="1165" alt="Screen Shot 2021-11-24 at 11 16 44 AM" src="https://user-images.githubusercontent.com/2838338/143275298-628be598-583e-410e-b4b9-b01481d5992a.png">

In the current implementation, the "next" button has been partially swapped out to _behave_ as the previous button, and vice versa.

Two things are wrong with the existing implementation:

1. the aria-label is not properly swapped
2. the disabled prop is not properly swapped

You can see in the code sandbox that the "next" button is improperly disabled, because the user is not allowed to navigate to a previous month -- the previous button is _not_ properly disabled, but clicking on the previous button does nothing because the click handler must also be guarded by the fromDate config. 

The user is stuck on the month of September 2021

**Expected behavior**
- The user can navigate between September 2021 and November 2021
- The buttons are properly disabled
- The aria labels are appropriate for each button

To fix this, we must also decide what the "expected" behavior is for className, style, and icon of each button. I would propose:

**Additional Expected behavior in dir="rtl"**

- The next button shall use `classNames.nav_button_previous` 
- The next button shall use `IconNext`
- The next button shall use `styles.nav_button_previous`

(this is already how it works)

**Comment by gpbl** [comment]
This is fixed with beta.32. Thanks for the help!

**Comment by tjfred35** [comment]
Awesome. I just verified it was fixed by using the code sandbox. Love that code sandbox!
