### ISSUE TITLE
Arrows not moving in the right direction?

### ISSUE THREAD

**Issue by tjfred35** [gpbl/react-day-picker#1289]
When the user has focus on a cell in the day table, the up, down, left, right arrows move the user around.

With dir="rtl", the left / right arrows should move the user's focus left / right in the grid, respectively, but they move in the opposite direction.

https://codesandbox.io/s/react-day-picker-8-forked-mu7fu

**Expected behavior**
When focus is on a cell in the day table and dir="rtl":

left arrow: move left in the grid (next day)
right arrow: move right in the grid (previous day)

<img width="305" alt="Screen Shot 2021-11-24 at 11 08 37 AM" src="https://user-images.githubusercontent.com/2838338/143274015-69393dc0-1a4a-4df1-b3a1-5c8d9876c188.png">

**Comment by gpbl** [comment]
@tjfred35 let keep our issue following the [bug template](https://github.com/gpbl/react-day-picker/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and be precise in our bug reports 👍

**Comment by gpbl** [comment]
Thanks, I am adding a test for this here: ae51c145.

**Comment by gpbl** [comment]
Definitely not an easy task test this. I've fixed the rtl issues in my test PR, see the test suite:

https://github.com/gpbl/react-day-picker/blob/0aa751f9e0da8380627197d1e15a4752579a08ee/website/examples/navigation-keyboard.test.tsx
