### ISSUE TITLE
Uncaught Invariant Violation: EventPluginRegistry: Cannot inject two different event plugins using the same name, `TapEventPlugin`.

### ISSUE THREAD

**Issue by limscoder** [gpbl/react-day-picker#129]
Failing build and also fails when trying to run the demo.

This might be caused by a 3rd party dependency bump, as the last sha with a passing build still fails.

**Comment by gpbl** [comment]
Yes I'm currently investigating this 😓 

Maybe a sub dependency issue, you are right, since I can't replicate on my machine. Will follow updates thanks!

**Comment by gpbl** [comment]
There are same reports about the same issue [here](https://github.com/zilverline/react-tap-event-plugin/issues/47) and [here](https://github.com/callemall/material-ui/issues/3068). I've solved the examples removing the double call to the TapEventPlugin.

For the test, i've added it at the top of the files: https://github.com/gpbl/react-day-picker/commit/a5882e077938f04c2c0849d8631f9bd93cda729a

Thanks again for the report!
