### ISSUE TITLE
Add new weekStartsOn prop

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1304]
Users may want to change the first day of the week.

- [ ] Add a new prop `weekStartsOn: 0 | 1 | 2 | 3 | 4 | 5 | 6` (default: `0`) to be passed to the `startOfWeek` implementations 
- [ ] Check if other parts should change according to this prop
- [ ] Add test 
- [ ] Add documentation

**Comment by harsohailB** [comment]
Can I contribute to this issue? I would just require a little more info on the end-user use case and where to get started!

**Comment by gpbl** [comment]
@harsohailB thanks a lot for offering your help! Before implementing new feature we need to complete the tests: https://github.com/gpbl/react-day-picker/issues/1311

> Also, how is this different from the currently implemented firstDayOfWeek prop?

There's no `firstDayOfWeek` prop yet, `weekStartsOn` is the prop!

**Comment by harsohailB** [comment]
@gpbl Thank you for your response! I was looking the following in the [docs](http://react-day-picker.js.org/api/DayPicker/#firstDayOfWeek) for `firstDayOfWeek` and it worked in the sandbox.

**Comment by VladSez** [comment]
@harsohailB seem's that tests #1311 are done. Are you still considering working on this feature🙂?

**Comment by VladSez** [comment]
@gpbl @harsohailB  I can start working on this

**Comment by gpbl** [comment]
@VladSez that would be great thanks!
