### ISSUE TITLE
DatePickerInput validation/supression and access optimization

### ISSUE THREAD

**Issue by n1xn** [gpbl/react-day-picker#1305]
### Bug description

I want to display the usual calendar icon within `<DatePickerInput />` and supress any not "date-related" values from
being entered.

As a result I am adding `type="date"` as property to the `inputProps` from `DatePickerInput` which breaks the access and logic of the component because now I am reaching the goal to only enter date related inputs but am able to open the default HTML DatePicker AND the DatePicker from `react-day-picker`. 

### To reproduce 

```
		<DayPickerInput
			{...filteredProps}
			formatDate={(date) => {
				return dayjs(date).format('DD.MM.YYYY');
			}}
			dayPickerProps={{
				month: new Date(availableDates[0]),
				months: MONTHS,
				weekdaysLong: WEEKDAYS_LONG,
				weekdaysShort: WEEKDAYS_SHORT,
				firstDayOfWeek: 1,
				disabledDays: getDisabledDays(),
			}}
			placeholder={`${disabled ? '' : 'Datum auswählen'}`}
			inputProps={{
				type: 'date', // here
				disabled: disabled,
				className: `w-full rounded-md py-3 px-6 border-2 font-sub ${
					disabled ? 'border-gray-200 bg-gray-100' : 'border-black cursor-pointer'
				} border-solid text-center`,
			}}
		/>
```

#### Steps

![image](https://user-images.githubusercontent.com/30150915/144570382-908cc6a2-2204-46ff-bb85-51b448c0b234.png)

### Expected behavior

1. By clicking on the CalendarIcon I would expect to open the DatePicker from `react-day-picker`.
2. I would generally expect input validation / supression of string, numbers that are not within the date format
3. I would expect that by default `type="date"` is set to `<DatePickerInput />`
4. I would also kind of expect to only be able to select dates via `DatePicker` as I have custom disabled dates and would need to verify manually from user text inputs.
5. DateFormat breaks and does not set value to input if using `type=date` and `formatDate=`

### Screenshots

As attatched above.

### Additional context

With that many issues I think I have to change the library to something more mature.

**Comment by n1xn** [comment]
By adding `onChange: (e) => (e.target.value = '')` to `inputProps` I can hack my way around point 2, 3, 4 & 5. Now I am just missing the CalendarIcon.

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
