### ISSUE TITLE
onDayFocus prop missing from v7 types

### ISSUE THREAD

**Issue by jpveooys** [gpbl/react-day-picker#1317]
### Bug description

`onDayFocus` is missing from from `DayPickerProps` in the v7 types.

The prop is documented here: https://react-day-picker.js.org/api/DayPicker#onDayFocus and works despite being missing from the types.

It's missing from this file: https://github.com/gpbl/react-day-picker/blob/v7/types/Props.d.ts

#### Steps

1. Try to use the documented `onDayFocus` prop with TypeScript

### Expected behavior

No type error.

### Screenshots

n/a

### Additional context

n/a

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
