### ISSUE TITLE
Focus navigation breaks with disabled days 

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1320]
### Bug description

When navigating the calendar with the keyboard the focus breaks when the day to focus is disabled

### To reproduce 

[Code sandbox: https://codesandbox.io/s/react-day-picker-8-vl4ry](https://codesandbox.io/s/react-day-picker-8-forked-yk2ez?file=/src/App.tsx)

#### Steps

Focus the calendar and move with the arrows until a disabled day is met. The focus get lost.

### Expected behavior

The focus should get to the next (or previous?) focusable (not disabled) day. If there are no days to navigate to, the focus should stay in the last navigable day.

### Additional notes

Test should check all the keyboard combinations. Consider the specific use cases (e.g. navigate end of week when end of week is disabled).

**Comment by gpbl** [comment]
@tjfred35 do you think the recent updates to focus may help fixing this?

**Comment by tjfred35** [comment]
No -- those updates only changed the _initial_ focus. This is still an issue.

**Comment by milorava** [comment]
Is this in the plans to be fixed?
It has a further issue, see this sandbox: https://codesandbox.io/s/sandpack-project-forked-i07lee?file=/App.tsx
If one selects the 3rd of January 2015 and then left arrow 3 times it will jump into the disabled month. From there the arrow keyboard navigation is no longer working.

**Comment by caydgreen** [comment]
I'm also seeing this issue and the one that @milorava mentioned above.  Is there any move to fix this?

**Comment by gpbl** [comment]
If #1449 get fixed probably we can move forward and fix this one too!

> Is this in the plans to be fixed?
> Is there any move to fix this?

Yes @caydgreen @milorava please consider sponsoring my work: https://github.com/sponsors/gpbl 🙏
