### ISSUE TITLE
First & Last selected days marked for styling...

### ISSUE THREAD

**Issue by emminnn** [gpbl/react-day-picker#134]
Hello again!

It'd be really nice to somehow give class to first and last dates that are selected in a range so the selected range styling can be done a bit more elegant. I'm sure this is a no brainer once one alters the source, but wonder if it's possible with existing API? Or is there workaround you can suggest?

An example is as below. Cheers!

![screen_shot_2016-02-23_at_12_52_45__2_](https://cloud.githubusercontent.com/assets/3763957/13432239/0ac00d70-dfcd-11e5-8605-250921627dcb.png)

**Comment by gpbl** [comment]
Sure you can! Remember that `modifiers` becomes CSS selectors, so if you are looking to [this example](http://www.gpbl.org/react-day-picker/examples/#range), the modifiers could be

```js
const modifiers = {
  // modifier for the days in range
  selected: day => DateUtils.isDayInRange(day, this.state),
  // modifiers for first and last days in range
  firstSelected: day => DateUtils.isSameDay(day, this.state.from),
  lastSelected: day => DateUtils.isSameDay(day, this.state.to)
};
```

then in your css style the selectors:

```css
.DayPicker-Day--firstSelected {
   // add border left radius
} 
.DayPicker-Day--lastSelected {
   // add border right radius
} 
```

**Comment by emminnn** [comment]
You are awesome sir!! :dancers:  :smiley: :smile: 
Thanks a lot!!

**Comment by watery** [comment]
@gpbl Cool, can this be added to the documentation / examples?
