### ISSUE TITLE
Codeblock Sandpack doesn't allow adding dependencies

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1349]
When adding `react-popper` dependency in website for #1347 we will break the SandPacks code blocks with an error:

```
Could not find dependency: 'react-popper' relative to '/src/App.tsx'
```

This is because the dependencies in https://github.com/gpbl/react-day-picker/blob/master/website/src/theme/CodeBlock/index.tsx#L50 don't list it.

There are many ways to fix this, but i think the quickest one is to parse the `src` (required with the raw-loader), if contains popper add it to the dependency list.

**Comment by tjfred35** [comment]
Going to try using [jscodeshift](https://github.com/facebook/jscodeshift) for this

**Comment by tjfred35** [comment]
Ok...jscodeshift didn't work

**Comment by tjfred35** [comment]
I just used a basic regex to find imports -- not perfect, but you can see the solution here: https://github.com/gpbl/react-day-picker/pull/1347
