### ISSUE TITLE
Modifier for today missing in useDay output

### ISSUE THREAD

**Issue by reintroducing** [gpbl/react-day-picker#1353]
### Bug description

In beta 29 I was using the following code to get `today` on a custom Day component I had built:
```js
const {
    buttonProps,
    modifiers: {today, selected},
} = useDay(date, displayMonth, ref);
```

I just upgraded to beta 35 which seems to be the latest and `today` is no longer in the modifiers for today's date. Even in looking at the code sandbox below in the `To reproduce` section (and any other demos in the docs), it does not seem that any class names or anything is signifying the `today` day in any way.

### To reproduce 

Code sandbox: https://codesandbox.io/s/react-day-picker-8-vl4ry

#### Steps

N/A

### Expected behavior

The `today` modifier should be present in the modifiers list of useDay output.

### Additional context

Setting the actual `today` prop to today's date on `DayPicker` also has no impact on this.

**Comment by tjfred35** [comment]
I believe I fixed this and the fix will go out with beta 36

**Comment by tjfred35** [comment]
See https://github.com/gpbl/react-day-picker/pull/1319

**Comment by reintroducing** [comment]
Awesome! Any idea when 36 will be released?

**Comment by tjfred35** [comment]
Any chance you are using this component at work and can get your company to sponsor @gpbl ? He is working hard nights and weekends to try to get a stable 8.0.0 out by Christmas, with a lot more planned for 8.1.0. I’m sure he would appreciate the support.

**Comment by reintroducing** [comment]
@tjfred35 Actually yes, I am, I just started at a very small startup and am redoing their UI components, but I brought up the idea of donating to this project to my VP of engineering this morning and he is going to try and get approval so that we can throw some money your way. I certainly do appreciate all the time and effort that goes into this library (and many others), so hopefully we can help out.

**Comment by tjfred35** [comment]
Awesome thanks!!

**Comment by tjfred35** [comment]
This is fixed in `8.0.0-beta.36`

**Comment by reintroducing** [comment]
@tjfred35 @gpbl I'm just curious how changelogs are kept for the beta releases? I see that on npm beta 36 is out but when looking at the site it is reflecting 35 (top header) and there are no changelog notes for 36 either: https://react-day-picker-next.netlify.app/changelog

**Comment by reintroducing** [comment]
by the way i just updated and can confirm this is indeed fixed, thank you.
