### ISSUE TITLE
Move test actions into its own file

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1356]
Move actions and events from the page object file (test/po.ts) to a new test/actions.ts file.

_Originally posted by @gpbl in https://github.com/gpbl/react-day-picker/pull/1355#discussion_r771828774_

**Comment by Aayush987** [comment]
Hi @gpbl i would like to work on this issue can you explain it to me?

**Comment by gpbl** [comment]
Thanks @Aayush987! this is already implemented in https://github.com/gpbl/react-day-picker/blob/master/packages/react-day-picker/test/actions.ts
