### ISSUE TITLE
Element type invalid when importing module via commonjs' require

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#136]
@LeoAref reported in [this message](https://gitter.im/gpbl/react-day-picker?at=56d6a30bb01413547d89654a) that requiring the component via commonjs would throw an invariant violation:

```js
var DayPicker = require('react-day-picker');
```

console output:

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

A temporary workaround is to use the exported `default` object:

```js
var DayPicker = require('react-day-picker').default;
```

The way of exporting in the [main script](https://github.com/gpbl/react-day-picker/blob/b38ecb6e57db14838b9d3735998a8023a01d50d4/DayPicker.js) doesn't indeed consider this case, so instead of writing 

```js
"use strict";

module.exports = require("./lib/DayPicker");
module.exports.DateUtils = require("./lib/DateUtils");
module.exports.LocaleUtils  = require("./lib/LocaleUtils");
```

I'd put

```js
"use strict";

var DayPicker = require("./lib/DayPicker");
var DateUtils =  require("./lib/DateUtils");
var LocaleUtils = require("./lib/LocaleUtils");

module.exports = DayPicker.default || DayPicker;
module.exports.DateUtils = DateUtils.default || DateUtils;
module.exports.LocaleUtils  = LocaleUtils.default || LocaleUtils;
```

...considering we must support webpack, commonjs, babel 5 and babel 6 :sweat_smile: 

I tag this as breaking change since users may already require using the above workaround.

**Comment by JKillian** [comment]
I think upgrading to Babel 6 caused this breaking change in the past. (So I think there's a breaking change between 1.20 and 1.31 somewhere. According [to this SO question](http://stackoverflow.com/q/33505992/3124288), [this plugin](https://www.npmjs.com/package/babel-plugin-add-module-exports) will bring back the old behavior that exports things at the top-level and as `default`.

**Comment by varun-raj** [comment]
Using `default` is good ? I'm using it with browserify rails

**Comment by gpbl** [comment]
FYI this should have been solved in v2.
