### ISSUE TITLE
Couldn't find https://unpkg.com/react-day-picker@8.0.0-beta.36/lib/style.css 

### ISSUE THREAD

**Issue by pgaurav9** [gpbl/react-day-picker#1363]
Hi @gpbl, after the recent release, we are getting this issue **Status code: 404** when trying to get this file https://unpkg.com/react-day-picker@8.0.0-beta.36/lib/style.css. Kindly help with this?

Thanks!

**Comment by tjfred35** [comment]
Can you try: https://unpkg.com/react-day-picker@8.0.0-beta.36/style.css instead? Is there any documentation that we need to update?

**Comment by gpbl** [comment]
Does actually loading the build from unpkg work?

**Comment by pgaurav9** [comment]
@gpbl yes it is helpful. Previously we were using https://unpkg.com/react-day-picker/lib/style.css with the react-day-picker@v7.4.8. I hope this new change won't impact us. Thanks @tjfred35 !
