### ISSUE TITLE
DayPickerInput css not working

### ISSUE THREAD

**Issue by Vishal-Kank** [gpbl/react-day-picker#1364]
### Bug description

we are using react-day-picker v.7.3.1 
but ```<link rel="stylesheet" href="https://unpkg.com/react-day-picker/lib/style.css" />``` is returning   
```GET https://unpkg.com/react-day-picker@8.0.0-beta.36/lib/style.css net::ERR_ABORTED 404```

its returning styles for v.8 is that the problem ?

### To reproduce 

Code sandbox: 
https://codesandbox.io/s/zdlfy?module=/example.js

#### Steps

1. Do this
2. Do that

### Screenshots
![Screenshot (552)](https://user-images.githubusercontent.com/23529259/146891295-de72bc7d-6151-4de1-9cd0-3aeb3a6c7f4d.png)
![Screenshot (554)](https://user-images.githubusercontent.com/23529259/146891300-82da1881-712e-4c45-890d-cacf560a4581.png)
![Screenshot (556)](https://user-images.githubusercontent.com/23529259/146891302-3306cb2a-8c54-4a2a-a1f4-f41e7ad1dda3.png)

**Comment by tjfred35** [comment]
Have you been using a v8 stylesheet for a v7 react component? Has that been working?

Can you try changing to the v7 stylesheet?
```
https://unpkg.com/react-day-picker@7/lib/style.css
```

**Comment by tjfred35** [comment]
Sorry for the trouble, and thanks for notifying us, but I think this workaround should work for you for now

**Comment by tjfred35** [comment]
You might try even more specifically: ```https://unpkg.com/react-day-picker@7.3.1/lib/style.css```
