### ISSUE TITLE
Choose position for the overlay to popup 

### ISSUE THREAD

**Issue by VaZark** [gpbl/react-day-picker#1365]
Occasionally, when the day picker input is near the bottom of the page and the page size is fixed (say 100vh) , the overla extends beyond the window's fixed borders breaking the UI with additional unexpected whitespace beneath components that do are not aware of the day picker.

The simplest solution would be being able to specify the position the overlay must be created in, ie, being able to choose if the overlay must be created above / below the DayPickerInput component.

**_Alternatives_**
1. Allow passing custom styles / props to OverlayComponent locally (replace `top : 0` with `bottom: 0` or custom values)
2. Allow to popup as a Modal

**Comment by gpbl** [comment]
Related: #1347

**Comment by ltbittner** [comment]
+1 this would be a great feature. It would be even better if it would auto position itself when it doesn't have room. 

For now I just added some global CSS to position it:

```css
.DayPickerInput-Overlay {
  bottom: 40px;
}
```

**Comment by VaZark** [comment]
Popper.js has an amazing library that handles the popover effect. Maybe it can used to handle the overlay ?

Pro: Longtime support shouldn’t be a problem as it is used by bootstrap as well.
Con: additional package and the overhead that comes with it

**Comment by tjfred35** [comment]
I like popper.js, and I _think_ the current direction in react-day-picker v8 is to make a reference implementation only of the DayPickerInput component, and I think it would probably use react-popper / popper js

**Comment by gpbl** [comment]
We won't add new feature to v7 of DayPicker – we do have however an example how to implement the popup with v8 (currently in beta):

https://react-day-picker-next.netlify.app/guides/date-picker-dialog
