### ISSUE TITLE
v8: Webpack v5 incorrect ESM exports

### ISSUE THREAD

**Issue by andreifloricel** [gpbl/react-day-picker#1366]
The problem described in #1287 & #1084 still exists in the latest beta version (v8.0.0-beta.36) because the bundler of `react-day-picker` is not relevant (be it webpack or rollup), but the bundler of the app that depends on it.
More specifically, Webpack 5 is stricter and enforces the [ESM specification] (https://github.com/webpack/webpack/issues/11467#issuecomment-691702706):
imported files must be fully specified (i.e. /`components/index.js` vs. `/components`).

This change would be backwards compatible, as a fully specified path will always work.

**Comment by gpbl** [comment]
Makes sense , thanks for pointing it out. Wondering how to force it via eslint.

**Comment by tjfred35** [comment]
Is that true? I’ve been working with webpack 5 for a while and haven’t had any problems with react-day-picker…can you share your webpack config file perhaps?

**Comment by gpbl** [comment]
This is when using ECMAScript modules: 

https://nodejs.org/api/esm.html#mandatory-file-extensions

> A file extension must be provided when using the import keyword to resolve relative or absolute specifiers. Directory indexes (e.g. './startup/index.js') must also be fully specified.

It is indeed something we should investigate (e.g. [tsc-esm-fix](https://www.npmjs.com/package/tsc-esm-fix). It would help   a reproducible example, @andreifloricel.

**Comment by gpbl** [comment]
When we find the proper way to fix this (e.g. by eslint or by tsc-esm-fix), better have some tests confirming it works as expected.

**Comment by andreifloricel** [comment]
> It is indeed something we should investigate (e.g. [tsc-esm-fix](https://www.npmjs.com/package/tsc-esm-fix)). It would help a reproducible example, @andreifloricel.

Hi, will try to add a reproducible example, as soon as Christmas passes :)

**Comment by andreifloricel** [comment]
I wanted to create a repo to reproduce the issue but just realised that @mayteio already did all the work :)
From https://github.com/gpbl/react-day-picker/issues/1287#issue-1059728085:


`git clone https://github.com/mayteio/react-day-picker-issue`

`cd react-day-picker-issue && yarn && yarn storybook`

=> 

```
ModuleNotFoundError: Module not found: Error: Can't resolve './DayPicker' in /react-day-picker-issue/node_modules/react-day-picker/esm'
Did you mean 'DayPicker.js'?
BREAKING CHANGE: The request './DayPicker' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.```

**Comment by gpbl** [comment]
Thanks @andreifloricel . What if we remove the esm version and just go with commonjs 😅

**Comment by andreifloricel** [comment]
Definitely worth a try :)
I can test it if you release it in a test/canary version.

**Comment by mayteio** [comment]
FWIW I upgraded to the latest beta and everything works as expected

**Comment by gpbl** [comment]
Thanks @mayteio! Please reopen if needed.

**Comment by andreifloricel** [comment]
For reference, this now works (as of beta.36) because the published `package.json` does NOT contain a `type` entry.
As specified (https://webpack.js.org/api/module-methods/#root), ESM strict mode is activated only when the `...nearest parent package.json file contains a "type" field with a value of either "module" or "commonjs"...`

**Comment by gpbl** [comment]
@andreifloricel thanks for your help – i think I will never get it right. What would be the best solution here? At this point i don't even know why we need an ESM build.

**Comment by andreifloricel** [comment]
@gpbl well, with the current state of webpack (check for `type: module`) and react-day-picker (missing `type`), everything should be fine :)
In the coming days I will integrate react-day-picker into some more complex projects and report when I find some edge cases.
