### ISSUE TITLE
You can select disabled dates if you write them in the input.

### ISSUE THREAD

**Issue by PaoloTorregroza** [gpbl/react-day-picker#1375]
### Bug description

You can select disabled dates if you write them in the input.

### To reproduce 

```jsx
<DayPickerInput 
  dayPickerProps={{
    modifiers: {
      disabled: [{after: new Date()}]
    }
  }}
/>
```

#### Steps

1. Write a future date, for example tomorrow (2021-12-29)

### Expected behavior

I am not sure how it is suposed to behave the input if you select a disabled date.

### Screenshots

![Screen Shot 2021-12-28 at 11 52 36 AM](https://user-images.githubusercontent.com/29853181/147588864-5835fb19-11c1-45d6-9ebc-cd249bf33334.png)

**Comment by PaoloTorregroza** [comment]
For now I did this workaround:

```js
onDayChange={(day: Date) => {=
    const today = new Date().getDate();
    if (day && day.getDate() > today) {
      day.setDate(today);
    }

    setDate(day);
}}
```

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
