### ISSUE TITLE
dist-tags incorrectly point to the v8 beta as the latest stable version

### ISSUE THREAD

**Issue by NobleMule** [gpbl/react-day-picker#1378]
### Bug description

When updating packages to their latest versions, I expect only stable releases (unless explicitly specified in my `package.json`). The dist-tags of react-date-picker specifies that the latest stable version is 8.0.0-beta.36 and next is 8.0.0-beta.35.

I think that the wrong dist tag was updated when a new beta was released.

### To reproduce 

Install the latest version of react-day-picker

### Expected behavior

v7.4.10 is installed.

### Actual result

v8.0.0-beta.36 is installed.

**Comment by gpbl** [comment]
Thanks @NobleMule, no idea how that version has been tagged as `--latest`. 

It should be fixed now:

```
npm install react-day-picker                                                                                     6s

+ react-day-picker@7.4.10
added 6 packages from 4 contributors and audited 6 packages in 4.225s
found 0 vulnerabilities
```
