### ISSUE TITLE
`useDayRender` is not packaged in final build

### ISSUE THREAD

**Issue by acnebs** [gpbl/react-day-picker#1386]
### Bug description

The `useDayRender` hook is not included in the rollup'd build of the beta.

### To reproduce 

Install and attempt to import `useDayRender` or `DayRender`, etc.

### Expected behavior

Export these.

**Comment by gpbl** [comment]
@acnebs are you using the version from the master branch or from npm?

**Comment by acnebs** [comment]
@gpbl From NPM, the @next tagged version.

**Comment by gpbl** [comment]
The change has not been published yet (sorry I've been busy lately), if you see that in the docs is because the docs doesn't reflect the published version. This will be fixed in: https://github.com/gpbl/react-day-picker/issues/1298

Sorry for the confusion!
