### ISSUE TITLE
v8 setting range={{from: date, to: date}} makes it impossible to select previous date

### ISSUE THREAD

**Issue by persocon** [gpbl/react-day-picker#1387]
### Bug description

As title says, when implementing the follow:
```jsx
    const range = {
        from: new Date(parsedState.date_from), // parsedState comes from localstorage
        to: new Date(parsedState.date_to),
    }
    <DayPicker
        mode="range"
        min={2}
        selected={range}
        onSelect={setRange}
        fromDate={today}
        numberOfMonths={2}
        locale={datePickerLocale}
    />
```

I'm unable to select `today` for example or any day previous from the ones inside `range` state
![image](https://user-images.githubusercontent.com/1276067/151375581-45ea99c3-5967-40a6-9515-afcd54d65c79.png)
In the screenshot example, today is 27 and selected is actually 28 to 31 but 28 is marked as disabled AND selected but also can't click on it or do anything

**Comment by gpbl** [comment]
I think https://github.com/gpbl/react-day-picker/pull/1383 is related or should fix this.

**Comment by persocon** [comment]
@gpbl could be :D I read them but thought it was about the behaviour of the return of the range state :)
