### ISSUE TITLE
Setting the date from within the Overlay and/or the Navbar

### ISSUE THREAD

**Issue by dimitur2204** [gpbl/react-day-picker#1397]
### Is your feature request related to a problem? Please describe.
The problem I am having is with the  custom `navbarElement` and it's limited functionality. 

The props passed to it are only `onPreviousClick` `onNextClick` and I would like to change the date in a different way that only by a  single month every single time.

### Describe the solution you'd like
I would **LOVE** to be able to have something like a `setDate`  prop passed down to the `navbarElement` and/or `overlayComponent` which overrides the currently set date on the Datepicker.

### Describe alternatives you've considered
Another thing I have considered is a `onPreviousYearClick` and `onNextYearClick` so that you can change years one by one too. But by doing a general `setDate` as in the solution I would like would be better. It would be more flexible, because you could also change just the time for example. 

### Additional context
![image](https://user-images.githubusercontent.com/61479393/152952200-d8c3d14f-09ef-4976-9704-2a1676dc09f3.png)

**Comment by bartoszgolebiowski** [comment]
https://github.com/gpbl/react-day-picker/pull/1406
I have added new property for navbarElement, it is "onSelectMonth"

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
