### ISSUE TITLE
DayPicker and DayPickerInput : Italian locale gives lower case month like marzo instead of Marzo for months.

### ISSUE THREAD

**Issue by ur-gh** [gpbl/react-day-picker#1409]
### Bug description

Change locale to Italian for Daypicker and DaypickerINput. Try in code sandbox below. The first character of the month is in lowercase
### To reproduce 

Code sandbox: https://codesandbox.io/s/0vfnq?module=/example.js

#### Steps

1. Do this
2. Do that

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!

**Comment by idoo** [comment]
@gpbl bug still exist in 8.0.4

**Comment by gpbl** [comment]
@idoo this is not a bug, the translation is correct.

**Comment by idoo** [comment]
¯\_(ツ)_/¯ any advice how to capitalize it? or make it by default

**Comment by gpbl** [comment]
I'm italian: lowercase it is orthographically correct, hence a not-fix.

> any advice how to capitalize it? or make it by default

- Use CSS `text-transform` 
- Override the values coming from the date-fns locale
- Propose a change to date-fns library
