### ISSUE TITLE
Website: search isn't working

### ISSUE THREAD

**Issue by Blumed** [gpbl/react-day-picker#1424]
DayPicker version:
React version:

### Bug description

The search functionality on your new website doesn't work. I have typed in few terms and no results are come up at all.

### To reproduce

Code sandbox: https://codesandbox.io/s/react-day-picker-8-vl4ry

#### Steps

1. https://react-day-picker.js.org/
2. Click search icon
3. Type words like "day", "the", "week"
4. No results will be found

### Expected behavior

The search to give me some parsed data to navigate the site.

### Screenshots

![Screen Shot 2022-03-31 at 10 22 55 PM](https://user-images.githubusercontent.com/2773888/161189163-02c3c7e0-1784-487b-9df6-d21f86ab5680.png)

**Comment by gpbl** [comment]
Thanks! There's an issue with the Algolia crawler. I'll disable the search until we get that fixed...

**Comment by gpbl** [comment]
Fixed! Thanks to the people from Algolia :)
