### ISSUE TITLE
Bug: 8.x release doesn't pass through extra props to useDayPicker

### ISSUE THREAD

**Issue by reintroducing** [gpbl/react-day-picker#1432]
### Bug description

Prior to the official 8.x release, I was using beta 38 and this was working fine.

### To reproduce

Fork this CodeSandbox: https://codesandbox.io/s/react-day-picker-8-vl4ry with the code to reproduce the issue.

#### Steps

With the below code:
```js
<DayPicker foo="foo" />
```

I was able to retrieve foo in a custom subcomponent with this:
```js
const {foo} = useDayPicker();
```

This no longer works and foo is undefined.

### Expected behavior

`foo` is defined in a custom child component when accessing extra props through `useDayPicker`. 

### Additional context

This was super helpful functionality to have as I'm using custom components heavily in my usage of RDP and I now don't have a way to grab those props. If there is another way to do this, what is the suggested way?

**Comment by gpbl** [comment]
Hi @reintroducing! Your sandbox is empty and doesn't help to replicate the issue. 

Anyway, we won't support this way of using `DayPicker`. What are you trying to do?

Moving to support discussions.
