### ISSUE TITLE
Bug: date-fns not getting tree-shaken in webpack

### ISSUE THREAD

**Issue by jdelStrother** [gpbl/react-day-picker#1435]
### Bug description

By default (at least in my project), `import ReactDayPicker from "react-day-picker"` loads dist/react-day-picker.min.js, and with it the entire of the date-fns/esm directory (which minimizes to 75kb parsed size, or 17kb gzipped).

### To reproduce

(Not supplied. I can try & come up with a sample project if really necessary though)

### Expected behavior

Webpack successfully tree-shakes the unused bits of date-fns

### Additional context

I can avoid this by importing `react-day-picker/dist/index.esm.js` instead of just `react-day-picker`.
I think the proper fix might be to add this to react-day-picker's package.json:

```json
  "exports": {
    ".": {
      "require": "dist/index.js",
      "import": "dist/index.esm.js",
      "style": "dist/style.css"
    },
    "./dist/style.css": "dist/style.css"
  }
```

which works fine in my local tests, but I don't know enough about it to say it's 100% complete or correct. There's some more info on that here: https://github.com/webpack/webpack/issues/4674 / https://webpack.js.org/guides/package-exports

**Comment by jdelStrother** [comment]
> Having a way to reproduce this issue would be great.

OK, I set up a quick webpack/react app - https://github.com/jdelStrother/react-day-picker-app/commits/main


| App version | minified bytes |
|----------|-------------|
| Basic react app, no daypicker | 129,724 |
| daypicker 7.4.10 | 181,137 |
| daypicker 8.0.2 | 261,922 |
| daypicker 8.0.3 | 194,802 |

**Comment by gpbl** [comment]
@jdelStrother thanks, that's helping a lot. Hopefully we will have a chance to reduce the bundle size soon.
