### ISSUE TITLE
Bug: Typescript error when using useInput & mode="single"

### ISSUE THREAD

**Issue by bogdanpetru** [gpbl/react-day-picker#1458]
### Bug description

Typescript throws the following error when using `useInput` & `mode='single'`.
This happens starting from version [v8.0.0-rc.0](https://github.com/gpbl/react-day-picker/releases/tag/v8.0.0-rc.0), with v8.0.0-beta.41 it works.
I am upgrading from https://github.com/gpbl/react-day-picker/releases/tag/v8.0.0-beta.38.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/6267231/170342051-3b241642-2de6-4fe6-8eaf-21428545d07f.png">

### To reproduce

Codesandbox: https://codesandbox.io/s/sandpack-project-forked-7znh6n

#### Steps

- fork this example https://react-day-picker.js.org/guides/input-fields#using-the-useinput-hook
- add mode="single"

### Expected behavior

Should `useInput` receive a param to know in what mode it is?
 
Thank you!

**Comment by gpbl** [comment]
`useInput` always work with `mode="single"` so it shouldn't be added there. Still I agree it shouldn't give an error there...

**Comment by bogdanpetru** [comment]
If I do not specify 'mode', I think it will use 'default' mode. Some props do not work in this mode, e.g. 'onSelect'.
