### ISSUE TITLE
Bug: Maximum update depth exceeded when select the range date

### ISSUE THREAD

**Issue by caricati** [gpbl/react-day-picker#1464]
### Bug description

When I select the day before the selected day, my browser is crashed and I see the message: "Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render."

Note: Use the `numberOfMonths={2}`, `mode="range"`, `showOutsideDays={true}`, and the last day of the month selected.

### To reproduce

https://codesandbox.io/s/react-day-picker-8-forked-h3ok12?file=/src/App.tsx

#### Steps

1. Open the console 
2. The last day of the month selected
3. Select the day before of the last day (29 June, on the example).
4. Check the console and see the message.

### Expected behavior

Do not execute the infinite loop.

### Screenshots

![image](https://user-images.githubusercontent.com/3439641/171043902-09274d45-316c-4c60-abdb-1a7bde220815.png)

**Comment by gpbl** [comment]
@caricati I cannot reproduce or see the error in the console:

https://user-images.githubusercontent.com/120693/172064466-1b41cec4-6a05-4a0b-8487-611dcada2051.mov

**Comment by DanielJKelly** [comment]
@gpbl @caricati I was able to reproduce the error without making any changes to the sandbox. I am also running into the same error in the application I am working on (using v8.0.5)

https://user-images.githubusercontent.com/22672008/172704013-e86417a2-3929-48b2-9a8c-d7fc82d28693.mov

**Comment by gpbl** [comment]
Thanks! I could reproduce it... let see how i can find a fix :D

**Comment by gpbl** [comment]
This should be fixed in v8.0.7. Please write back if it still appears!
