### ISSUE TITLE
Bug: CSS Module incompatible with 'pure' option for css-loader webpack plugin

### ISSUE THREAD

**Issue by amcurative** [gpbl/react-day-picker#1472]
### Bug description

CssSyntax error: Selector ":root" is not pure (pure selectors must contain at least one local class or id) (1:1)

```
  1 | :root {
    | ^
  2 |   --rdp-cell-size: 40px;
  3 |   --rdp-accent-color: #0000ff;
```

### To reproduce

Run webpack with css-loader where modules option is pure using CSS module from day-picker.

#### Steps

I encountered it when doing a next.js build but it can be reproduced simpler by

1. Create a project
2. Create a day-picker component, use CSS module (style.module.css) to style it
3. Modify webpack rules to include:
     {
        test: /\.css$/i,
        loader: "css-loader",
        options: {
          modules: {
            mode: "pure",
          },
        },
      },

5. Use webpack to package it and you should see the error

### Expected behavior

To not encounter this error and build successfully.

### Additional context

https://github.com/vercel/next.js/discussions/17089

This happens for next.js apps because they are defaulting to pure for this loader.

**Comment by gpbl** [comment]
Not sure what "pure" mean – it is to avoid the global scope of the variables? In this case, replacing `:root` with `.rdp` would fix the issue?

**Comment by andyschulzz** [comment]
@gpbl 
https://github.com/vercel/next.js/discussions/17089
we are running in the same issue, replacing :root with .rdp would fix this issue it seems.

**Comment by andyschulzz** [comment]
I was able to fix this issue by adding the following to our next.config.js:

```
const regexEqual = (x, y) => {
    return (
        x instanceof RegExp &&
        y instanceof RegExp &&
        x.source === y.source &&
        x.global === y.global &&
        x.ignoreCase === y.ignoreCase &&
        x.multiline === y.multiline
    );
};

const loaderUtils = require('loader-utils');

/**
 * Generate context-aware class names when developing locally
 */
const localIdent = (loaderContext, localIdentName, localName, options) => {
    return (
        loaderUtils
            .interpolateName(
                loaderContext,
                `[folder]_[name]__${localName}`,
                options
            )
            // Webpack name interpolation returns `about_about.module__root` for
            // `.root {}` inside a file named `about/about.module.css`. Let's simplify
            // this.
            .replace(/\.module_/, '_')
            // Replace invalid symbols with underscores instead of escaping
            // https://mathiasbynens.be/notes/css-escapes#identifiers-strings
            .replace(/[^a-zA-Z0-9-_]/g, '_')
            // "they cannot start with a digit, two hyphens, or a hyphen followed by a digit [sic]"
            // https://www.w3.org/TR/CSS21/syndata.html#characters
            .replace(/^(\d|--|-\d)/, '__$1')
    );
};

// Overrides for css-loader plugin
function cssLoaderOptions(modules) {
    const { getLocalIdent, ...others } = modules;
    return {
        ...others,
        getLocalIdent: localIdent,
        exportLocalsConvention: 'camelCaseOnly',
        mode: 'local',
    };
}

const oneOf = config.module.rules.find(
            (rule) => typeof rule.oneOf === 'object'
        );

        if (oneOf) {
            const moduleCssRule = oneOf.oneOf.find((rule) =>
                regexEqual(rule.test, /\.module\.css$/)
            );

            if (moduleCssRule) {
                const cssLoader = moduleCssRule.use.find(({ loader }) =>
                    loader.includes('css-loader')
                );

                if (cssLoader) {
                    cssLoader.options.modules.mode = 'local';
                }
            }
        }
```

@gpbl  sorry for bad PR, it worked on my end but was because of a different setup I forgot about.
