### ISSUE TITLE
@reach/auto-id y React18

### ISSUE THREAD

**Issue by enric-joco** [gpbl/react-day-picker#1478]
### Bug description

We have updated to React 18 and react-day-picker dependency @reach/auto-id is giving a lot of warnings. On npm install.

### To reproduce

Update to react 18 the main project and npm i.

### Expected behavior

It would be great to avoid all this noise. Will you update dependency or know any solution?

**Comment by gpbl** [comment]
Ugh seeing this. I think I'd better remove the dependency.
