### ISSUE TITLE
IE9 browser support

### ISSUE THREAD

**Issue by samsch** [gpbl/react-day-picker#148]
I can't seem to find any listed browser support for react-day-picker.

Using es5-shim, es6-shim, Babel 6 (ES2015+react presets), and bundled with webpack, it seems to error during loading in IE9. The error is `Unable to get value of the property 'currentMonth': object is null or undefined`. Unfortunately, it doesn't point to a useful line number in IE9, so I can't tell you exactly where it errors. IE9 also failed to load the examples page.

This is with the latest version, 1.3.1.

Which browsers are "officially" supported and tested?

**Comment by gpbl** [comment]
Hi @samsch interesting error, as the `currentMonth` is just found in the component's state. The component must work with versions supported by React, e.g. for 0.14 even IE9. I'll check this out and report back!

**Comment by gpbl** [comment]
I've updated the code for IE11, but I can't test it with IE9. If someone would like to care about IE9 I'm open to tests and PR :)

**Comment by samsch** [comment]
The Examples page is loading fine with IE9. You can test using the [MS-provided Windows/IE VMs](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

Going down the list of examples, Advanced Modifiers gives errors on mouseover: `https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/`. The Year Navigation styling breaks, but that looks like it's just a CSS issue. The Year Calendar page has an odd glitch. The current year doesn't always update immediately when you click the next/previous year. It seems to fix it (updates to current) if you click on the current year though.

Of course, any of the examples using Flex don't display as nice, but that's to be expected, and those silly IE9 users can deal with it.

**Comment by gpbl** [comment]
Thanks for the report! Just I don't have the time to care about IE9 😞 
The CSS is just for demo purposes, I expect developers to write their own – so I wouldn't care about it.

**Comment by adidahiya** [comment]
IE9/10 have been deprecated by Microsoft as of January 2016... So I would actually prefer if react-day-picker did not make _any_ effort to support those browsers (to avoid code complexity).

**Comment by gpbl** [comment]
Closing this as it seems there's no interest to help me supporting IE9 :)
