### ISSUE TITLE
Support updating the date

### ISSUE THREAD

**Issue by tarjei** [gpbl/react-day-picker#149]
Hi,

One use case I would love to see is to be able to update the date from the outside of the component. My usage for this is to be able to change the current year through a custom dropdown outside the component and then updating the selected date.

**Comment by gpbl** [comment]
@tarjei check better [the examples](https://github.com/react-component/tooltip), you can find something similar there (input field, year navigation) 😀

**Comment by tarjei** [comment]
Thanks!

Hiding the selected date in modifiers is what threw me off :)

**Comment by gpbl** [comment]
Yeah it is not so easy to explain the concept, I'm planning to add some default modifiers as prop (#34)
