### ISSUE TITLE
Bug: Google translate in chrome distort the calendar

### ISSUE THREAD

**Issue by atinder** [gpbl/react-day-picker#1490]
### Bug description
When google translater is run on a webpage with a foreign language, all the content is translated correctly and the layout of the page is maintained.
But the `react day picker` calendar is distorted during the translation.

### To reproduce

Fork: https://codesandbox.io/embed/react-day-picker-8-forked-ilzqpt
Preview: https://ilzqpt.csb.app/

#### Steps

1. Go to https://ilzqpt.csb.app/ in the Google Chrome browser.
2. click on the google translate icon right side of the address  bar
3. Hit translate

### Expected behavior

The calendar should not distort

### Screenshots
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/2451681/181149447-bfc59264-71d3-4d52-aa08-3492d0b578f0.png">

**Comment by rodgobbi** [comment]
Hi @atinder 
Could you provide again the steps to reproduce?
The links in the original PR description don't work anymore
