### ISSUE TITLE
DatePicker without browserify

### ISSUE THREAD

**Issue by pjebs** [gpbl/react-day-picker#15]
I have gotten your component to work without grunt, npm etc:  https://github.com/gpbl/react-day-picker/issues/8

It works well except the css does not seem to apply properly.

1) In your dist/Daypicker.js

Change require(React) to global.React;
Change require(moment) to global.moment;

That way you can use react and moment from the global scope.

2) Export Datepicker to global scope

global.DayPicker = DayPicker; (after var DayPicker = React.createClass ...)

3) Modify asset/left.svg -> Remove sketch:type="MSShapeGroup" (Causes XML Parse errors)

**Comment by pjebs** [comment]
It works now, but it still doesn't look as polished as your demo.
![screen shot 2015-04-20 at 1 37 08 am](https://cloud.githubusercontent.com/assets/5377970/7220083/fcc5fad0-e6fe-11e4-83b1-97b3782d5b1a.png)
![screen shot 2015-04-20 at 1 37 14 am](https://cloud.githubusercontent.com/assets/5377970/7220084/fcc678ac-e6fe-11e4-81f1-7336389d1dc0.png)

**Comment by pjebs** [comment]
I'm not sure if it is a css issue.

**Comment by pjebs** [comment]
Here are my files. It is very small(just a small demo to show your component working).

https://github.com/pjebs/datepicker

If you can have a quick look, it would be greatly appreciated. You are likely to figure out the issue straight away.

**Comment by pjebs** [comment]
You may have to run chrome  in a different mode to run react files outside a local web server

In Terminal:
open -a 'Google Chrome' --args -allow-file-access-from-files

**Comment by pjebs** [comment]
I had also converted your SCSS file to CSS using http://sasstocss.appspot.com/

**Comment by gpbl** [comment]
Hi @pjebs, the css is just to be used as example, is not meant for production. In your case, it looks like you have not the font used from the CSS.
