### ISSUE TITLE
issue when importing style.css with commonjs

### ISSUE THREAD

**Issue by Jbarget** [gpbl/react-day-picker#150]
Im getting a syntax error when i try and load the css file into the component with no specific info on the problem.

![screen shot 2016-04-05 at 16 27 25](https://cloud.githubusercontent.com/assets/11725595/14287627/51e99de4-fb4b-11e5-893f-565c568f5321.png)

Here is my code,
https://repl.it/CC1o

For now im just going to extract your css file and load it in via our internal style set up, but would love to know if im doing something wrong or if theres a way to fix it and use 
`
import "react-day-picker/lib/style.css"
`

**Comment by gpbl** [comment]
Hi @Jbarget 
if you are importing .css files via javascript, you need something else in between to import them, as commonJS can't import css natively. In my examples I'm using webpack with the css-loader. 

Anyway, copying the CSS file into your own styles is the way to go – the style.css is just an example. I should clarify better this part in the docs :)

**Comment by Jbarget** [comment]
gotcha @gpbl, thanks for the fast reply! will keep the copied version of your css for now :)
