### ISSUE TITLE
Bug: v8.1 does not have :root css variable set, causing the UI to not render well

### ISSUE THREAD

**Issue by Jonakemon** [gpbl/react-day-picker#1503]
### Bug description

 v8.1 does not have :root css variable set, causing the UI to not render well. The rdp-cell elements expect various css variables to be available on :root, which are not. Probably caused by https://github.com/gpbl/react-day-picker/pull/1482.

### To reproduce

`npm i react-day-picker` to install the latest version; then include it in whatever you use to compile your assets.

#### Steps

1. Compile the relevant assets.
2. Visit a page that uses the component.

### Expected behavior

I expected the component to look as in the docs, instead it looks like described in #1482.

### Screenshots

This is how it looks for me, very similar to #1482.

![image](https://user-images.githubusercontent.com/17858692/184709610-d113dd6f-59c8-40fa-9f1d-326f872b04d9.png)

**Comment by gpbl** [comment]
@Jonakemon I cannot reproduce your problem: https://codesandbox.io/s/react-daypicker-vl4ry 

- what are you using to compile your assets?
- did you apply some customizations to the CSS?

The CSS variables are set in the `.rdp` class. If it doesn't work for you you can always place them in `:root` or where you prefer:

```css
--rdp-cell-size: 40px;
--rdp-accent-color: #0000ff;
--rdp-background-color: #e7edff;
--rdp-accent-color-dark: #3003e1;
--rdp-background-color-dark: #180270;
--rdp-outline: 2px solid var(--rdp-accent-color);
--rdp-outline-selected: 2px solid rgba(0, 0, 0, 0.75);
```

<img width="1805" alt="Screenshot 2022-08-16 at 08 51 46" src="https://user-images.githubusercontent.com/120693/184899017-bc46559e-02f7-40d1-9fee-12ab3ef47aba.png">

Let us know, thanks!

**Comment by Jonakemon** [comment]
Hi @gpbl, thanks for the response! After debugging a bit further, it seems that the `.rdp` is not set correctly on the DayPicker element when I add a className prop. Example: https://codesandbox.io/s/react-daypicker-forked-ovvpsj?file=/src/App.tsx. Manually re-adding the `rdp` class in the className prop fixes the problem.

Maybe it's worthwhile to add to the documentation that the `rdp` class will be overridden when you add your own className prop? Right now it states that the class is `added` to the container element, not that it overrides the base class. The documentation can be [found here](https://react-day-picker.js.org/api/interfaces/DayPickerDefaultProps#classname).

**Comment by gpbl** [comment]
@Jonakemon thanks for spotting this bug. Definitely the `.rdp` class should stay. Will push an update soon.
