### ISSUE TITLE
onDayClick getting invoked twice when mode="range"?

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1506]
### Discussed in https://github.com/gpbl/react-day-picker/discussions/1475

<div type='discussions-op-text'>

<sup>Originally posted by **tchestnut85** June 23, 2022</sup>
It looks like when the mode is set to `range` that onDayClick is getting invoked twice. 
Does anyone know if this is intentional (maybe since a range has a start and end)?

I modified one of the sandbox examples to reproduce this:

https://codesandbox.io/s/sandpack-project-forked-z0szxe?file=/App.tsx

Here's a recording too:

https://user-images.githubusercontent.com/67440557/175339913-6e3fab16-6ddd-457b-816c-045cf336d20f.mov

</div>

**Comment by mbsAndrew** [comment]
I'm also seeing this in the mode is set to `single` as well. Is that expected behavior?

[https://codesandbox.io/s/sandpack-project-forked-ecrym2?file=/App.tsx](https://codesandbox.io/s/sandpack-project-forked-ecrym2?file=/App.tsx)
