### ISSUE TITLE
docs: example with time picker

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1507]
It is a frequent request to see how DayPicker should work with time. We should add an example to the docs...

### Discussed in https://github.com/gpbl/react-day-picker/discussions/1474

<div type='discussions-op-text'>

<sup>Originally posted by **marcostaborda** June 23, 2022</sup>
How to use `react-day-picker` with a time picker?

Does anyone have used `react-day-picker` with time selector?</div>

**Comment by Erik-McKelvey** [comment]
I can work on this

**Comment by Erik-McKelvey** [comment]
I could show an example of integrating it with this time picker https://github.com/wojtekmaj/react-time-picker?
