### ISSUE TITLE
:focus vs :focus-visible

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1529]
### Discussed in https://github.com/gpbl/react-day-picker/discussions/1528

<div type='discussions-op-text'>

<sup>Originally posted by **VilleKylmamaa** August 27, 2022</sup>
When you click the arrow to change the month, the button will remain in focus and the focus style will remain. It's good when you are using the keyboard to navigate but I find it odd when using the mouse.

Could the focus or just the style be dropped on click? If not feasible within the component, how should I go about doing this from outside the component?</div>

**Comment by Arijit0** [comment]
.rdp-button:focus:not([disabled]) {
    color: inherit;
    border: var(--rdp-outline);
    background-color: var(--rdp-background-color);
}

For using these code the button will remain on focus. Not applying this style or remove these style will solve the issue i think. Or if it is not. So can you please describe more with screenshots?? I will love to help. Thank you.

**Comment by gpbl** [comment]
@Arijit0 try to upgrade to v8.1.4 – it should fix this issue too.
