### ISSUE TITLE
Current Release w/ CJS and React 15 Dependency Support?

### ISSUE THREAD

**Issue by JKillian** [gpbl/react-day-picker#154]
Is there a release that has [this change included](https://github.com/gpbl/react-day-picker/commit/b39c60a2c1d48a2c70f83c27ddabdf77ab7fae20), supports React 15 as a peer dependency, and is on NPM and tagged for Bower? I was having a little trouble figuring out what the 2.0.0-beta and 1.3.2 releases contained.

Thanks, great component!

**Comment by gpbl** [comment]
1.3.2 does _not_ include the changes for commonJS, as they may break existing code. Let me publish a beta-2 release. I'm still writing some docs :)

(sorry for the mess)

**Comment by JKillian** [comment]
Sounds good, thank you!

**Comment by gpbl** [comment]
@JKillian i've published a `next` tag:

```
npm install react-day-picker@next
```

[changelog](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md)

**Comment by JKillian** [comment]
Thank you! Mind updating the `dist/` directory and tagging this?

**Comment by adidahiya** [comment]
updating dist here https://github.com/gpbl/react-day-picker/pull/158
