### ISSUE TITLE
onMouseDown, onMouseUp, onTouchStart, onTouchMove, etc. for days

### ISSUE THREAD

**Issue by johannesd** [gpbl/react-day-picker#155]
Currently, the only available event callbacks for a day are onDayClick, onDayMouseEnter and onDayMouseLeave. However, I need support for the events mouseDown, mouseUp, touchStart, touchMove, and touchEnd.

Are there any plans for supporting this? If there are no objections, I'd like to add this feature.

**Comment by gpbl** [comment]
It would be great, thanks! As [we are removing `onDayTouchTap`](https://github.com/gpbl/react-day-picker/issues/153) in the next version, this change will be useful. 

Also, check [the changelog](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md) for the upcoming release I've just published.

I'd call those props keeping the `onDay*` prefix.

**Comment by johannesd** [comment]
OK great, I'll make the changes and send you a pull request.

**Comment by gpbl** [comment]
Thanks! Going to fix the current build failure in the next minutes...

**Comment by johannesd** [comment]
Just sent you a pull request! :)

**Comment by gpbl** [comment]
Closing this old issue since some of those event handlers [has been added](http://www.gpbl.org/react-day-picker/APIProps.html#event-handlers). Thanks!
