### ISSUE TITLE
Bug: `min` property in "range" mode disables unnecessary days

### ISSUE THREAD

**Issue by sophiaknowles** [gpbl/react-day-picker#1554]
### Bug description

When using the `min` with `mode="range"`, the days before the selected days are disabled

### To reproduce

Created an example here - https://codesandbox.io/s/react-daypicker-forked-m1mr4c

```
<DayPicker
        mode="range"
        selected={range}
        onSelect={(range: any) => {setRange(range)}}
        disabled={{ after: new Date() }}
        numberOfMonths={2}
        weekStartsOn={1}
        min={7}
/>
```
### Expected behavior

The days before the range should be selectable

### Screenshots

![Screen Shot 2022-09-20 at 5 06 32 PM](https://user-images.githubusercontent.com/10272829/191364603-d63d4fdc-c62b-445f-a672-9de118c36c35.png)

**Comment by gpbl** [comment]
Thanks! Indeed, we are missing the test in https://github.com/gpbl/react-day-picker/blob/1b0101794de768397d6a38263239209c3f2d9555/packages/react-day-picker/src/contexts/SelectRange/useSelectRange.test.ts#L192...
