### ISSUE TITLE
Bug: version 8 uses non ISO week as it was in v.7

### ISSUE THREAD

**Issue by iuriipaniukov** [gpbl/react-day-picker#1557]
### Bug description

Week numbers from v8 are based on `date-fns/getWeek` that returns in some cases other values than it was in versions earlier (v7 for example)

It creates a huge problem in case of migration because it is not back-compatible

### To reproduce

Compare behaviour (week numbers) with `showWeekNumber` prop on versions 7 and 8

### Expected behaviour

Should support the same behaviour as earlier to cover back-compatibility

### Screenshots

v7:
![Screenshot 2022-09-21 at 16 03 02](https://user-images.githubusercontent.com/102951489/191532539-438d41a5-20e2-4c46-83f5-8fc646eacd69.png)

v8:
![Screenshot 2022-09-21 at 16 02 53](https://user-images.githubusercontent.com/102951489/191532529-a3d754c9-babf-4c0b-980f-4b515348eea5.png)

**Comment by gpbl** [comment]
Interesting thanks for the heads up. Is there a way to make the dat-fns function to work like the previous? We could add a prop to help with this.

**Comment by gpbl** [comment]
I believe we can fix this by adding a prop `firstWeekContainsDate` to pass to `getMonthWeeks` in:  https://github.com/gpbl/react-day-picker/blob/94e32d18d30505d101290c77dc96d8fd25a861b4/packages/react-day-picker/src/components/Table/Table.tsx#L30-L34

This function pass the arguments to date-fns/getWeek: https://date-fns.org/v2.29.3/docs/getWeek#arguments

**Comment by iuriipaniukov** [comment]
> Interesting thanks for the heads up. Is there a way to make the dat-fns function to work like the previous? We could add a prop to help with this.

I assume `getISOMonth` works exactly as recentry.

![Screenshot 2022-09-22 at 09 44 01](https://user-images.githubusercontent.com/102951489/191687921-40a96d61-1197-4b29-8fd6-d9d8f002e175.png)
