### ISSUE TITLE
Bug: Not handling both "before" and "after" properties in "disabled" field

### ISSUE THREAD

**Issue by sophiaknowles** [gpbl/react-day-picker#1568]
### Bug description

When using both the `before` and `after` properties on the `disabled` object, no days are disabled.

### To reproduce

Example here - https://codesandbox.io/s/react-daypicker-forked-m1mr4c?file=/src/App.tsx
This should disable anything before 5 days before today, and disable anything after today. Instead, nothing is disabled. If you comment out the `before` line, it disables using the `after` property properly. And visa versa. 

```
      <DayPicker
        mode="day"
        selected={range}
        onSelect={setRange}
        disabled={{
          before: new Date(new Date().getTime() - 10 * 24 * 60 * 60 * 1000),
          after: new Date()
        }}
        numberOfMonths={2}
        weekStartsOn={1}
        min={7}
      />
```
### Expected behavior

The correct days should be disabled

### Screenshots

![Screen Shot 2022-09-27 at 3 24 03 PM](https://user-images.githubusercontent.com/10272829/192617348-cc6f013b-ae09-4b8b-bec3-12af717f47a7.png)

**Comment by bsledz** [comment]
Workaround:

```
<DayPicker
        mode="day"
        selected={range}
        onSelect={setRange}
        disabled={[
              (day: Date) => {
                return day > new Date() || day < new Date(new Date().getTime() - 10 * 24 * 60 * 60 * 1000)
              }
        ]}
        numberOfMonths={2}
        weekStartsOn={1}
        min={7}
/>
```

**Comment by sophiaknowles** [comment]
@bsledz Great, thank you!

**Comment by gpbl** [comment]
It seems that [DateInterval](https://react-day-picker.js.org/api/types/DateInterval) is not handled correctly in [isMatch](https://github.com/gpbl/react-day-picker/blob/5b9f24b7abbcab507c73f619d2446a671505d680/packages/react-day-picker/src/contexts/Modifiers/utils/isMatch.ts#L60-L64):

https://github.com/gpbl/react-day-picker/blob/5b9f24b7abbcab507c73f619d2446a671505d680/packages/react-day-picker/src/contexts/Modifiers/utils/isMatch.ts#L60-L64

I agree it is confusing. As alternative:

```tsx
disabled={[
  { after: new Date() },
  { before: new Date(new Date().getTime() - 10 * 24 * 60 * 60 * 1000) }
]}
}
```

[codesandbox](https://codesandbox.io/s/react-daypicker-forked-9mr6rr)
