### ISSUE TITLE
Bug: If you select a range from one date, all days will be marked as "middle".

### ISSUE THREAD

**Issue by dartess** [gpbl/react-day-picker#1579]
### Bug description

If you select a range from one date, all days will be marked as "middle".

### To reproduce

https://codesandbox.io/s/react-daypicker-forked-pjmm6c

#### Steps

1. Open sandbox
2. Click any day
3. Click the same day again
4. See that all days are marked as "middle" (colored in pink)

### Expected behavior

Days around the range are not marked as middle.

**Comment by gpbl** [comment]
Hey thanks for reporting this bug. It has been fixed in 8.3.5: 

https://codesandbox.io/s/react-daypicker-forked-thie8y?file=/src/App.tsx
