### ISSUE TITLE
Bug: tabIndex toggling from 0 to -1 on today or selected day for the first time

### ISSUE THREAD

**Issue by anil1687** [gpbl/react-day-picker#1586]
### Bug description

Tabindex is changing from 0 to -1 for focused today/selected day element when we navigate using tab key.

### To reproduce

1. Open https://react-day-picker.js.org/start -Example
2. Inspect today element(Button) observe the tabIndex is "0"
3.  Navigate using Tab key focus moves from next(>) to today
4. Observe the tabIndex of today button it is "-1"

### Expected behavior

TabIndex of today button should be "0" 

### Screenshots

![image](https://user-images.githubusercontent.com/8499692/196206042-6af5e6ea-af12-4041-9fc7-cd3ba1940742.png)

### Additional context

After focusing on today and the tabIndex is "-1", if we tab again it is moving header control(prev button)

@gpbl, this issue is causing my focus loop logic. Due to the tabindex "-1", this element is not considered as focusable element and breaking out of the focus loop.

**Comment by ApplyBoardDak** [comment]
Here's a video reproducing the behaviour (on the homepage). It only ends up looping once but it still seems like an issue.

https://user-images.githubusercontent.com/89859711/196482815-8422b75d-3e53-42b2-8b79-d79909d99b0f.mov

**Comment by krishna63** [comment]
@gpbl : Let us know your opinion so that we can spend some time and get a solution for it, before diving it will help to understand if there is any reason for making it as  `-1` after the first blur on the seleced date ?

cc: @anil1687

**Comment by gpbl** [comment]
I suspect this is related to https://github.com/gpbl/react-day-picker/pull/1576... investigating...

**Comment by gpbl** [comment]
I've seen this behavior in https://github.com/gpbl/react-day-picker/pull/1576. The tab indexes seem to work right. It would be nice a unit test to reproduce this case.

**Comment by gpbl** [comment]
This should be fixed in v8.3.6. @anil1687 please let us know :) thanks for the bug report.
