### ISSUE TITLE
Bug: Calendar truncated when browser set to different timezone.

### ISSUE THREAD

**Issue by wavded** [gpbl/react-day-picker#1587]
### Bug description

Calendar truncated when browser set to different timezone.

Expected:

<img width="874" alt="Screenshot 2022-10-18 at 11 42 27 AM" src="https://user-images.githubusercontent.com/26638/196517076-801707b2-36d5-4c62-b37f-6acb4aa2715a.png">

Got:

<img width="953" alt="Screenshot 2022-10-18 at 11 42 06 AM" src="https://user-images.githubusercontent.com/26638/196517099-fe10a2b6-07bd-4fa0-8818-21935b22219a.png">

#### Steps

1. Set timezone of browser to `Europe/Athens`
2. Visit https://react-day-picker.js.org/basics/navigation

**Comment by gpbl** [comment]
@wavded I've set the browser's timezone to Europe/Athens but I cannot reproduce the issue. Could you help to replicate? Thanks.

**Comment by wavded** [comment]
@gpbl Sure. This was reported by a user in Europe/Athens TZ and I was able to reproduce in Firefox using the following workflow:

1. Install https://mybrowseraddon.com/change-timezone.html extension
2. Set extension to use Europe/Athens as TZ.
3. Visit https://react-day-picker.js.org/basics/navigation

Here is a little video demonstration:

https://user-images.githubusercontent.com/26638/200346524-89fd16b3-af1f-4531-bc1c-53ffa2d6196b.mov

**Comment by gpbl** [comment]
@wavded that plugin seem to change the DateTime prototype thus breaking the calendar. I won't spend time to investigate why...

**Comment by wavded** [comment]
Ahh I didn't think of that. Thx for checking!
