### ISSUE TITLE
Disabling days disables wrong date

### ISSUE THREAD

**Issue by quocDat040702** [gpbl/react-day-picker#1589]
**Bug description**

Calendar disables wrong date ( in month ) while using `disabled` modifier

 Expected: 
![image](https://user-images.githubusercontent.com/85924986/198080889-53ae7c65-18d0-471f-93e0-df077b39bed1.png)
Got:
![image](https://user-images.githubusercontent.com/85924986/198080982-774cd5dd-a4dc-4950-a1e9-3e51d194d007.png)

The code produces bug above:
![image](https://user-images.githubusercontent.com/85924986/198081091-dec9aa57-cf4d-4376-a87d-1c9220fb0ffd.png)

**Comment by ronaldvimal** [comment]
Month is 0-indexed. This is not a defect 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
