### ISSUE TITLE
Use onMouseDown instead of onClick to allow usage of blur for input

### ISSUE THREAD

**Issue by eisisig** [gpbl/react-day-picker#16]
Now it is using onClick when clicking a day. onClick fires AFTER blur so if you want to use an input and have a blur event on that (to close the cal) the blur event fires before the onClick can fire.

By changing this to use onMouseDown you can have both

**Comment by gpbl** [comment]
Hi @eisisig I also have been fighting with this kind of issue. IMHO the best approach is to use a timeout before actually hiding the calendar.

**Comment by eisisig** [comment]
I really don't like timeout if they are not needed :) For me it is enough to change onClick to onMouseDown same effect but different event order.

I also had to add e.preventDefault() to the nav handlers.

I also don't like changing 3rd party scripts and I won't. So if this is not a change you agree on I'll find another solution. :)

**Comment by gpbl** [comment]
I'm open to change my mind :-) but using the mousedown event is imho a wrong fix: we change a correct  behavior of the calendar to support a specific need. Also on touch devices it wouldn't work right. This is for me a case where the timeout is the best compromise.

**Comment by jpprodriguez** [comment]
Thank you very much! I was spending a lot of time trying to fix that issue. I also don't like setTimeout when its not needed
