### ISSUE TITLE
Bug: new items added to useMemo array

### ISSUE THREAD

**Issue by mmxdr** [gpbl/react-day-picker#1604]
### Bug description

The library adds new items to the array of dates stored in useMemo when i pass this array to **disabled** prop, If i use **fromDate**, **toDate** and **disabled** props together.

### To reproduce

Fork this CodeSandbox: https://codesandbox.io/s/react-daypicker-forked-smpcs9?file=/src/App.tsx:821-896 with the code to reproduce the issue.

#### Steps

1. Look at the console, there are two objects added at the end of the array.
2. If you comment **fromDate** and **toDate** props everything works as expected.

### Expected behavior

useMemo value should stay the same.

### Screenshots

<img width="670" alt="image" src="https://user-images.githubusercontent.com/3596230/201405816-496ad428-e921-42ef-99e7-bcdce6cdee38.png">

**Comment by gpbl** [comment]
There's no useMemo in the DayPicker source.

**Comment by mmxdr** [comment]
@gpbl hello, looks like you didn't understand me.

please, look at the provided CodeSandbox https://codesandbox.io/s/react-daypicker-forked-smpcs9?file=/src/App.tsx:821-896

i'm sure that it's this library bug.

after passing **const disabledDates** to **disabled** prop in **DayPicker** component it adds 2 objects to an array.
so i can't use this const in other places, to get the length of array for example.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/3596230/201476950-d250026f-56db-4b84-ad35-fb400208b5e0.png">
<img width="677" alt="image" src="https://user-images.githubusercontent.com/3596230/201476968-bc7f8d50-7a34-42cf-8ce8-a68fd8bb7e61.png">

if i remove **fromDate** and **toDate** props from **DayPicker** component everything is fine
<img width="660" alt="image" src="https://user-images.githubusercontent.com/3596230/201477033-5827944f-9ff1-4ac0-b37d-38880df12308.png">

**Comment by dddrey** [comment]
same here

**Comment by mmxdr** [comment]
@gpbl i found this part of code in the library https://github.com/gpbl/react-day-picker/blob/a8c3e3c1565ff2fc729825b2f337a6323bbaae2b/packages/react-day-picker/src/contexts/Modifiers/utils/getInternalModifiers.ts
```
if (dayPicker.fromDate) {
    internalModifiers[Disabled].push({ before: dayPicker.fromDate });
}
if (dayPicker.toDate) {
    internalModifiers[Disabled].push({ after: dayPicker.toDate });
}
```
you push values to the data outside of library provided through props, thats why i got modified array in useMemo.
is this expected behavior?

**Comment by gpbl** [comment]
@mmxdr sorry I misread your bug report. I believe the bug is because of this line:

https://github.com/gpbl/react-day-picker/blob/8ca51f7f440960e363bc2ca6d76d8b708895fdfb/packages/react-day-picker/src/contexts/Modifiers/utils/matcherToArray.ts#L8

it returns the same array you passed in, then it push these objects into it. I fix this in https://github.com/gpbl/react-day-picker/pull/1609.

Thanks for reporting this!

**Comment by mmxdr** [comment]
@gpbl everything perfect now, thank you!
