### ISSUE TITLE
toMonth can be toDay

### ISSUE THREAD

**Issue by LiranBri** [gpbl/react-day-picker#161]
Hi,

I would like to restrict user of picking any days after current date.
the closest thing i found for this is to do:
> toMonth={new Date()}
> 

but this would disable only following months, and not future days within the current month.

I suggest to make it restrict up to the specific date passed to this prop, or add additional **toDay** prop

**Comment by gpbl** [comment]
Hi @LiranBri, you can still use `toMonth` to prevent the user _navigating_ to the months next to the current one. For disabling single days, e.g. those in the future, you should set up a modifier: check [this example](http://www.gpbl.org/react-day-picker/examples/#disabled). `DateUtils.isPastDay` should work for you, just negate its result, e.g.

```js
function isToday(day) {
 const today = new Date();
 return DateUtils.isSameDay(day, today)
}
const modifiers = {
    disabled: day => !DateUtils.isPastDay(day) || !isToday(day)
}
```

**Comment by LiranBri** [comment]
thank you @gpbl. why not make it as built-in feature? its very useful and common. for my opinion no new prop is needed, just to extend **toMonth** to use the days of the date passed

**Comment by gpbl** [comment]
@LiranBri thanks, I've corrected my comment. 

The `toMonth` means _allow navigation up to this month_. Anyway, a good compromise would be implementing the `disabled` prop as tracked in https://github.com/gpbl/react-day-picker/issues/34. The API would look like:

```js
<DayPicker disabled={ day => isFutureDay(day) } />
```

So I'm closing this, you can subscribe the mentioned issue to know be notified when it's closed.
