### ISSUE TITLE
Bug: aria-label text is not localized

### ISSUE THREAD

**Issue by rdebeasi** [gpbl/react-day-picker#1615]
### Bug description

The `aria-label` text announced by screen readers is in English, even when the `locale` is set to another language.

Thank you so much in advance for your time!

### To reproduce

Open https://react-day-picker.js.org/basics/localization

#### Steps

1. Open browser dev tools and inspect the "next" button in the first example.
2. Note that the `aria-label` is "go to next month", even though the locale is `es`.

### Expected behavior

I expected `aria-label` text to be in Spanish.

### Screenshots

<img width="814" alt="Screenshot of web browser dev tools inspecting the 'next' button in a calendar" src="https://user-images.githubusercontent.com/1299370/207953099-ab67d6e5-b1fd-434a-9333-86867e54169b.png">

**Comment by gpbl** [comment]
Thanks for the report. ARIA-labels must be translated using the `labels` prop: https://react-day-picker.js.org/basics/localization#aria-labels-translations

**Comment by rdebeasi** [comment]
Cool - thanks for clearing that up!
