### ISSUE TITLE
Keyboard navigation allows to navigate before `fromMonth`

### ISSUE THREAD

**Issue by pioul** [gpbl/react-day-picker#162]
It doesn't feel critical at all, but I wanted to bring it up nonetheless 😄 

Steps to reproduce:

1. Open a day picker with restricted months, e.g. http://www.gpbl.org/react-day-picker/examples/#restricted
2. Select one of the allowed days
3. Using the left arrow key, keep navigating to previous days: you'll be able to navigate to days before `fromMonth`

Screencast: http://cl.ly/1E3n441u462h

Note: this issue doesn't exist when navigating through months, rather than days, using the keyboard (i.e. when pressing left arrow while focus is on a month label rather than a day box)

**Comment by gpbl** [comment]
Woah true! Thanks for the precise report. Fix coming soon!

**Comment by gpbl** [comment]
This has been fixed in the next major version, I guess after https://github.com/gpbl/react-day-picker/pull/132. Version 2 [doesn't have](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md) such big breaking changes, so I'd suggest to upgrade to it once it is released :)

**Comment by pioul** [comment]
Awesome, thanks for the quick fix!
