### ISSUE TITLE
A Boolean property to set previous dates disabled.

### ISSUE THREAD

**Issue by MohibWasay** [gpbl/react-day-picker#163]
Boolean property that could set the Date picking of all the past days disabled on picker.

**Comment by gpbl** [comment]
Hi @MohibWasay, something similar is coming in v2 once https://github.com/gpbl/react-day-picker/issues/34 is close  :)

**Comment by MohibWasay** [comment]
Cool Thanks! @gpbl I saw this  [Disable Days Example](http://www.gpbl.org/react-day-picker/examples/#disabled) Hence closed this issue :)
