### ISSUE TITLE
Incorrect VERSION field (possible build issue?)

### ISSUE THREAD

**Issue by JKillian** [gpbl/react-day-picker#167]
Noticed that `VERSION` in [`dist/DayPicker.js`](https://github.com/gpbl/react-day-picker/blob/1d56af9a59343b7f57944c8cc9f5337f6d77c281/dist/DayPicker.js) still includes a `-beta` suffix - maybe something isn't getting built correctly?

**Comment by gpbl** [comment]
Hi @JKillian the build is correct, I just forgot to update that value. Thanks for reporting this !

**Comment by gpbl** [comment]
Nope, you were right. Something didn't work between tagging and pushing the dist files. Now [it is correct](https://github.com/gpbl/react-day-picker/blob/v2.0.2/dist/DayPicker.js). I will pay double attention to it the next time, thanks for reporting it!
