### ISSUE TITLE
initialMonth should not update after first mounted

### ISSUE THREAD

**Issue by willmcclellan** [gpbl/react-day-picker#169]
I'm not sure if this is the intended behaviour, but I expected the `initialMonth` property to only be relevant on the first mount of the component. So you set an initialMonth but subsequent renders ignore it.

The current behaviour here:

https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L80-L84

... updates the current month to the initialMonth when receiving props which, if you aren't storing/updating the current month in state when clicking next/prev, means the months don't switch if initialMonth is always the same value.

If that is the intended behaviour, then maybe the naming of `initialMonth` should be changed as it doesn't fit with how it actually works?

**Comment by gpbl** [comment]
Yes I believe you are right, implementers should use the `showMonth` instance method instead. I think this is a leftover from some early release, but it may lead to some unintended effects.

**Comment by davidspiess** [comment]
I'm not happy about that change. How would i now be able to (re)render the calendar, when my date variable in my store changes?

**Comment by gpbl** [comment]
@davidspiess you can use the `ref` prop and the `this.daypicker.showMonth(newMonthFromProps)` in `componentDidUpdate`. Would that work for you?

**Comment by davidspiess** [comment]
@gpbl  yes it works that way, but i think it should be a prop like it was. When my state changes, i want my UI to reflect that. With this behavior have to call a method when this is the case, which goes against the whole purpose of react.

**Comment by gpbl** [comment]
@davidspiess the problem lies in the prop's name: people expect `initialMonth` to work just for the first render (as reported by @willmcclellan here), similarly to the `defaultValue` in uncontrolled components. 

I think i should add a new `month` prop behaving like the previous `initialMonth` - what do you think?

**Comment by davidspiess** [comment]
That would be awesome! 👍
