### ISSUE TITLE
Improve custom components examples

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1719]
In my use case, I insert markings in specific days that contain additional data. Think of it as bookings or events in a calendar. It could be as simple as colored shapes, or icons, or marking the whole day container with a border. Something along these lines perhaps?

_Originally posted by @amivag in https://github.com/gpbl/react-day-picker/discussions/1672#discussioncomment-4882384_

**Comment by Anj1nST** [comment]
Have the same problem - with documentation I can't get how to change the root component (className '.rdp). It's so unclear. I just want to change background and place it in the end of the container. I've tried to apply my classNames, to use modifiers, but I don't understand what modifier shoud I use

**Comment by GregorGabric** [comment]
`
<DayPicker
// this affects the parent class
          className={clsx('date-picker-wrapper')}
// these are the modifiers
            modifiersClassNames={
           selected: 'date-picker-wrapper__selected',
           today: 'date-picker-wrapper__today',
           disabled: 'date-picker-wrapper__disabled',
}
            showOutsideDays
          />


`
