### ISSUE TITLE
IE11 symbol is undefined error

### ISSUE THREAD

**Issue by davidspiess** [gpbl/react-day-picker#174]
I updated to 2.1.0 today and stumbled upon a `"Symbol" is undefined` error in IE 11.
I think the problem lies in the new `for of`loop in [Helpers.js](https://github.com/gpbl/react-day-picker/blob/6adf3dc6a937c98a600626d4ca58a92b27e5a446/src/Helpers.js#L26).
Babel transpiles that into a Symbol iterator which doesn't exist in IE.

**Comment by gpbl** [comment]
@davidspiess uhh i wonder if this is the only problem with babel and IE. I'd like to avoid the babel-polyfill as requirement. Maybe also related with #148

**Comment by davidspiess** [comment]
I agree with leaving away `babel-polyfill`. The easiest option imo would be rewriting the mighty `for of` loop  with a plain old `forEach` as `Object.keys` returns an array anyway and it isn't required to break out early.

```js
Object.keys(modifierFunctions).forEach(function(modifier) {
  const func = modifierFunctions[modifier];
  if (func(d)) {
    modifiers.push(modifier);
  }
});
```

**Comment by gpbl** [comment]
👍 for `reduce`! would you mind sending a PR? otherwise I could work on it in the next days!

**Comment by davidspiess** [comment]
I'm on vacation over the weekend but eventually i could make one on monday 👍🏻
