### ISSUE TITLE
Min Width of DayPicker

### ISSUE THREAD

**Issue by monapasan** [gpbl/react-day-picker#180]
I come across a problem, that i am not able to set width of DayPicker under 239 px:
![image](https://cloud.githubusercontent.com/assets/10222766/16001587/30d1ef1a-3153-11e6-829a-16539a37d843.png)

Is there any known workaround to prevent this?

**Comment by gpbl** [comment]
The included stylesheet is just an example, you should write your own if you need to customize the component 
http://www.gpbl.org/react-day-picker/docs/Styling.html

I know is far from being perfect 😄
