### ISSUE TITLE
Bug: Page crashes when trying to toggle editor

### ISSUE THREAD

**Issue by diaasaur** [gpbl/react-day-picker#1821]
### Bug description

Clicking on Toggle Editor for code examples in DayPicker Basics/Guides crashes page

<img width="765" alt="Screenshot 2023-07-02 at 11 52 13 AM" src="https://github.com/gpbl/react-day-picker/assets/111369805/dab8f1d0-0051-4e5f-b790-a473a61b26e2">

**Comment by gpbl** [comment]
Thanks! Fixed.
