### ISSUE TITLE
Support for `nonce` attribute for inline style tags

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1834]
### Discussed in https://github.com/gpbl/react-day-picker/discussions/1758

<div type='discussions-op-text'>

<sup>Originally posted by **bcalou** April 17, 2023</sup>
Hi and thanks for this great library :)
Would you welcome a PR adding support for the nonce attribute ?
This would allow to use Content-Security-Policy headers (see https://content-security-policy.com/unsafe-inline/). Currently we have to add the `unsafe-inline` header, which is considered, well, unsafe ;)

Something like that:

```tsx
<DayPicker
    nonce="..."
```

The nonce value would then be added to the inline `style` tag.</div>

**Comment by mmerezhko-hv** [comment]
Any updates on this?
