### ISSUE TITLE
Bug: dropdown with two month updating the first month only

### ISSUE THREAD

**Issue by fotopixel** [gpbl/react-day-picker#1853]
### Bug description

If i use `numberOfMonths={2}` with and display a dropdown for the month if have a bug when i change the toMonth. This will set the fromMonth and not the toMonth. 

### To reproduce

https://codesandbox.io/s/react-daypicker-forked-vs4qvd?file=/src/App.tsx:189-207

#### Steps

1. change to fromMonth to March
2. change the toMonth in the second Month to December
3. have a look to the fromMonth it will change to the selected toMonth

### Expected behavior

If I change the month for a displayed month, all other Months should be alight to see selected Month. 

For example: 

selecting in the second Month December, i would expect that the first Month will become November and not December

**Comment by gpbl** [comment]
@fotopixel I'm not understanding your issue. What is the current behavior - what is the expected behavior?

**Comment by fotopixel** [comment]
@gpbl sorry. 

ok let's try to describe it more clear. 

if you set the number of displayed month to 2 or even more, you will get the described issue. 

Current behavior: 

the picked month (from the **right** side) is selected in the **left** calendar, and the **right** calendar shows the **following** month

https://github.com/gpbl/react-day-picker/assets/7202441/65618063-82ae-48ea-b401-a669f05e2b92

expected behavior:

The month which I select in the calendar should also be displayed in the same. 

If I select in the **right** calendar **December** it should be displayed in the **right** calendar

**Comment by gpbl** [comment]
Thanks @fotopixel, now I got it! Yeah, I understand this is unexpected. You'd see the calendar under the second dropdown change to the selected month – instead is the first being updated.

**Comment by gpbl** [comment]
@IDrumsey I'm currently working on [the next version](https://github.com/gpbl/react-day-picker/discussions/1833) that would for sure make this easy to fix. The underlying issue is the caption is rendered per each month – while it should be just one.

You could try with a [custom component](https://react-day-picker.js.org/guides/custom-components) replacing the `Caption`, but it may get tricky.

https://codesandbox.io/s/rktq65

**Comment by gpbl** [comment]
@xskipy thanks for the update and for sharing your workaround.

I could implement the fix in https://github.com/gpbl/react-day-picker/pull/1884 (I would appreciate a quick review there). Publishing it later in the day...
