### ISSUE TITLE
Disabled parameter not working

### ISSUE THREAD

**Issue by rasmuswoelk** [gpbl/react-day-picker#186]
Hi

I'm having a problem with the disabled parameter when using `onDayClick` prop.

I'm getting `undefined` when using it in the same way as shown in your examples:
```js
      onDayClick={(e, day, { disabled }) => {
          console.log(disabled); // returns undefined
      }}
```

Any idea why this is happening?

Nice component - just what I needed! 👍

**Comment by gpbl** [comment]
Thanks @rasmuswoelk!

If `disabled` is `undefined`, are you sure the day is actually disabled? E.g. the day cell should have the `DayPicker-Day--disabled` CSS class.

Check out this example:
http://www.gpbl.org/react-day-picker/examples/?disabled

**Comment by rasmuswoelk** [comment]
You are totally right! 👍  My bad. Thanks!

Is the "selected" property still a part of the parameter like this?:

`onDayClick(e, day, { disabled, selected}) {....`

It returns undefined - what exactly does "selected" mean? :)

**Comment by gpbl** [comment]
`onDayClick` signature is: 

```js
onDayClick(e, day, modifiers)
```

where `modifiers` is an object with `disabled` key (if you pass `disabledDays` prop) and `selected`  (if you pass `selectedDays` prop, as in the example).

In ES6 we can just write:

```js
onDayClick(e, day, { a, b })
```

to "destructure" an object having (or not having) `a` and `b` keys.

**Comment by rasmuswoelk** [comment]
Ah got it! Thanks! 👍
