### ISSUE TITLE
dist/DayPicker.js out of date

### ISSUE THREAD

**Issue by chondl** [gpbl/react-day-picker#187]
I'm just picking up react-day-picker for the first time so I might be confused, but the DayPicker.js in dist appears to not have been upgraded to 2.2.  It still contains the string VERSION="2.1.1" and does not contain the new fixedWeeks feature.

This issue appears to apply both to the file in GitHub and the file in npm

**Comment by gpbl** [comment]
I'm sorry – i guess something didn't work out when publishing on npm. You should find now the version `2.3.1` with the updated dist!
