### ISSUE TITLE
Warnings on weekdayComponent/navbarComponent deprecation even if unused

### ISSUE THREAD

**Issue by albertogasparin** [gpbl/react-day-picker#188]
v2.3.0 always prints the `weekdayComponent`/`navbarComponent` deprecation notice even if my code is not using it. 😖 
Are you still using them internally, aren't you? 

https://github.com/gpbl/react-day-picker/search?utf8=✓&q=weekdayComponent

**Comment by nkbt** [comment]
Yep, just updated and found it. We definitely do not use those props.

I reckon that might happen because of `defaultProps`, since when default props are there  - `this.props` become always defined

**Comment by gpbl** [comment]
sorry people 😞 fix is coming!
