### ISSUE TITLE
React warnings in 15.2.0

### ISSUE THREAD

**Issue by davidspiess** [gpbl/react-day-picker#190]
After updating to react 15.0.2 i get the following warning:

```
warning: Unknown props `localeUtils`, `modifiers`, `numberOfMonths`, `captionElement`, `initialMonth`, `fromMonth`, `renderDay`, `enableOutsideDays`, `fixedWeeks`, `reverseMonths`, `weekdayElement`, `navbarElement` on <div> tag.
Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```

Removing `attributes` should do the trick
https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L465

But this would kill user defined attributes as well and break some code, so it would be saver to remove all propTypes from `attributes`

**Comment by nkbt** [comment]
Yeah, all custom props need to be excluded from being passed down to the child

**Comment by davidspiess** [comment]
Something like this should do the trick

```js
const customAttributes = {};

Object.keys(attributes).forEach((key) => {
  if (!DayPicker.propTypes.hasOwnProperty(key)) {
    customAttributes[key] = attributes[key];
  }
});

return (
  <div
    {...customAttributes}
    etc
  </div>
);
```

**Comment by gpbl** [comment]
Thanks! Working on it :)

**Comment by mCzolko** [comment]
Thanks @gpbl that you working on it!

**Comment by gpbl** [comment]
Should be fixed in v2.3.3! Please reopen if needed :) Thanks

**Comment by davidspiess** [comment]
Wow that was a fast one! :clap:

**Comment by nkbt** [comment]
👌
