### ISSUE TITLE
Bug: redundant "rowgroup" role on <tbody>

### ISSUE THREAD

**Issue by mihkeleidast** [gpbl/react-day-picker#1903]
### Bug description

The `<tbody>` element rendered has a redundant `rowgroup` role: https://github.com/gpbl/react-day-picker/blob/main/src/components/Table/Table.tsx#L54. as it should be the implicit default role of that element: https://w3c.github.io/html-aria/#el-tbody

### To reproduce

N/A

#### Steps

N/A

### Expected behavior

No redundant ARIA roles on elements.

### Screenshots

N/A

### Additional context

I'm running into an issue with [html-validate](https://www.npmjs.com/package/html-validate), which has a rule for not using redundant roles on elements. I could disable the rule for this component, or turn off the reporting for this role, etc - but wanted to get some additional context about why this is used here.

The attribute was added back in #1658, but there was no context as to why this change improves accessibility. Can this be clarified as to why it's necessary?

**Comment by gpbl** [comment]
@mihkeleidast it looks like a bug. We can for sure remove that redudant `role="rowgroup"` attribute.

**Comment by mihkeleidast** [comment]
@gpbl I can also file a PR, if it makes resolving this any faster?

**Comment by mihkeleidast** [comment]
Cheers, thanks for the quick turnaround!
