### ISSUE TITLE
Ability to change navbar arrows

### ISSUE THREAD

**Issue by olegafx** [gpbl/react-day-picker#195]
I want to replace navbar arrows with svg `use` images. This is impossible with base64 decoded icons in css.

So I need ability to pass something like `renderNavbarPrev` and `renderNavbarNext` functions (that returns my svg icons) to day picker component.

**Comment by gpbl** [comment]
@olegafx thanks for the suggestion, this is a nice feature to have. I will think about it – this addition may unlock an API update I'm thinking since a while. More to follow :)

**Comment by pigoz** [comment]
This is already possibile with the `navbarElement`. I am doing it on my project.

**Comment by gpbl** [comment]
@pigoz is right – `navbarElement` should do the trick!
