### ISSUE TITLE
Bug: changing captionLayout doesn't effect custom component rendering.

### ISSUE THREAD

**Issue by wesleyjanse** [gpbl/react-day-picker#1961]
### Bug description

I created a dayPicker component, since I really need to be able to change year easily (since it will be used for a dob field). I was looking into the documentation if this was possible or not.

So i stumbled upon using `CaptionDropdowns`, when implementing I couldn't get it to work. it simple would not render.

#### Steps
This is the component I have:
```tsx
    <DayPicker
      locale={nl}
      showOutsideDays={showOutsideDays}
      className={cn('p-3', className)}
      captionLayout="dropdown-buttons" // set captionLayout to dropdown-buttons
      classNames={{}}
      components={{
        IconLeft: () => <ChevronLeft className="h-4 w-4" />,
        IconRight: () => <ChevronRight className="h-4 w-4" />,
        Caption: (props) => {
          const { captionLayout } = useDayPicker();
          console.log('captionLayout', captionLayout); // captionLayout = 'buttons' instead of 'dropdown-buttons'

          return <CaptionDropdowns {...props}></CaptionDropdowns>;
        },
      }}
      {...props}
    />
```

I found out that setting captionLayout to something else doesn't effectively change anyhing. when I call `const { captionLayout } = useDayPicker();
` inside of the Caption component function. it will always be set to "buttons"

### Expected behavior

I'd expect it to render the dropdowns, since the jsdoc of the component states: `Render a caption with the dropdowns to navigate between months and years.`

**Comment by wesleyjanse** [comment]
Upon further inspection, and me just reading the docs correctly. I found out that I had to set from/to dates in order for that to work.

It might be a good idea to give a simple example of this behaviour on the main docs. Since I couldn't find anything for year selection on the main documentation.

**Comment by gpbl** [comment]
@wesleyjanse thanks for the feedback! We will definitely make it more clear in the documentation,

**Comment by wesleyjanse** [comment]
If I got time I might be able to open a Pr for it.
