### ISSUE TITLE
onDayClick handler receives Date with time set to 12:00:00

### ISSUE THREAD

**Issue by tg-adz** [gpbl/react-day-picker#199]
Is there any reason that the time is set to 12:00:00 in the Date passed to the onDayClick handler?

Thanks!

**Comment by gpbl** [comment]
Hi @tg-adz,  this is to prevent timezones issues.

**Comment by tg-adz** [comment]
I thought as much! I'll just ignore the time part.

Thanks!

**Comment by gpbl** [comment]
i hope in the future we can find a better way to deal with timezones.

**Comment by nafg** [comment]
This caused a bug for me, these dates won't return true for moment.js `isSame` with dates created without a time.
