### ISSUE TITLE
Bug: Lag when displaying many months and switching selected date

### ISSUE THREAD

**Issue by sjlehtonen** [gpbl/react-day-picker#1998]
### Bug description

Date picker selection is laggy when displaying 12 months and changing the selected day

See the video below in the demo website

https://github.com/gpbl/react-day-picker/assets/10501962/c5c87305-a819-4614-9264-ebdc52af49d2

### To reproduce
https://codesandbox.io/p/sandbox/elastic-ramanujan-smntn8?file=%2FApp.tsx%3A23%2C25 try it out there, with 50 months it start to lag when choosing day, but in the react day picker website, even 12 months is enough to make it laggy

#### Steps

1. Click around the sandbox with numberOfMonths high

### Expected behavior

Not laggy when switching day

### Additional context

I think it is caused because when selecting day in one of the monthly calendars, every other calendar is also re-rendered?

**Comment by gpbl** [comment]
Hi @sjlehtonen we are aware of performance issues with high number of months: https://github.com/gpbl/react-day-picker/issues/1473 

This will be (hopefully) fixed in the next major version, planned for early next year. Thanks for your patience!
