### ISSUE TITLE
Bug: Dependency conflict with date-fns version 3.0.1

### ISSUE THREAD

**Issue by greengem** [gpbl/react-day-picker#1999]
### Bug description

When attempting to update dependencies in a project using react-day-picker and date-fns, I encountered a dependency conflict with the latest version of date-fns (3.0.1).

### To reproduce

1. Have a project with both react-day-picker and date-fns.
2. Run npm outdated to see the available updates.
3. Run npm update.

### Expected behavior

I expected all dependencies to update without any conflicts.

### Actual behaviour

```
npm ERR! Found: date-fns@3.0.1
npm ERR! node_modules/date-fns
npm ERR!   date-fns@"^3.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer date-fns@"^2.28.0" from react-day-picker@8.9.1
npm ERR! node_modules/react-day-picker
npm ERR!   react-day-picker@"^8.9.1" from the root project
```

### Environment

Node.js version: 20.5.0
npm version: 10.1.0
react-day-picker: 8.9.1
date-fns: 3.0.1

**Comment by limonte** [comment]
https://blog.date-fns.org/v3-is-out/

**Comment by gpbl** [comment]
We added support for date-fns@3 in [version 8.10](https://github.com/gpbl/react-day-picker/releases/tag/v8.10.0). Please upgrade `react-day-picker` before upgrading `date-fns`. Thanks!

**Comment by greengem** [comment]
Thank you @gpbl I upgraded react-day-picker first, then date-fns 3 and it worked perfectly.

**Comment by sameersambhare** [comment]
I have the same error message in my project. Can anyone help me with that please?
