### ISSUE TITLE
Switch from moment.js to Intl

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#2]
Moment.js should not be a requirement. The day picker can work with dates using the native `Date` object and return days as Date objects (or I'd prefer `YYYY-MM-DD`).

**Comment by gpbl** [comment]
Removing moment.js requires to pass the translations for the months and the weekdays, or it could use the `Intl` API.

**Comment by iSnifer** [comment]
Do you know libraries who implement date ranges.
Moment.js is not only library for internationalization. Do you agree with me?

**Comment by gpbl** [comment]
To use the [intl polyfill](https://github.com/andyearnshaw/Intl.js/) we need [this issue](https://github.com/andyearnshaw/Intl.js/issues/75) fixed first.

**Comment by gpbl** [comment]
Also, the `Intl` API does not provide a way to detect the first day of the week (http://stackoverflow.com/questions/27550516) ... bummer!

**Comment by gpbl** [comment]
replaced by #27
