### ISSUE TITLE
Override day template

### ISSUE THREAD

**Issue by ericluwj** [gpbl/react-day-picker#203]
I understand that there are class modifiers but there should still be overrides for the day template too.
Currently, I am trying to add multiple labels to the day, but it appears that I am unable to do that.

**Comment by gpbl** [comment]
@ericluwj would the [`renderDay`](http://www.gpbl.org/react-day-picker/APIProps.html#renderday) prop work for you? See [example here](http://www.gpbl.org/react-day-picker/examples/?year).
