### ISSUE TITLE
showOutsideDays is disabled  1st on month start always on Sunday

### ISSUE THREAD

**Issue by tyki6** [gpbl/react-day-picker#2036]
## Description

showOutsideDays is disabled  1st on month start always on Sunday
## Expected Behavior
On february when showOutsideDays   is disabled 1 february start on thursday and not on monday.
## Actual Behavior
```js
<DayPicker initialFocus showOutsideDays  mode="range" numberOfMonths={2} defaultMonth={new Date} />
```
![image](https://github.com/gpbl/react-day-picker/assets/57527739/3235d51e-6bb2-45cb-9d3a-da89fb0845d4)
```js
<DayPicker initialFocus showOutsideDays={false}  mode="range" numberOfMonths={2} defaultMonth={new Date} />
```
![image](https://github.com/gpbl/react-day-picker/assets/57527739/4ed2bc62-bdf8-4ffd-9ddb-64f9f3d28c4a)

## Steps to Reproduce

show two month, in February.
code: 
```js
<DayPicker initialFocus showOutsideDays  mode="range" numberOfMonths={2} defaultMonth={new Date} />
```

## Possible Solution

If you have a suggestion on how to fix the issue, please include it here.

## Your Environment
- React version: `18.2.0`
- Browser [e.g. chrome, safari]: on all browser 
- Operating System [e.g. iOS, Windows]: x86_64 GNU/Linux
- Other relevant information:  `react-day-picker 8.10.0`

**Comment by gpbl** [comment]
Please provide a code sandbox to replicate the issue, thanks!
