### ISSUE TITLE
Range picker components

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#204]
[This example](http://react-day-picker.js.org/examples/selecting-range-mouse-enter.html) (see discussion in #202) has some logic that could be extracted in an external component.

Inspired by the [date picker](http://airbnb.io/react-dates/?selectedKind=DateRangePicker&selectedStory=with%20some%20blocked%20dates&full=0&down=1&left=1&panelRight=0) from Airbnb, a possible API would be:

```jsx
import { DayRangePicker } from 'react-day-picker;

<DayRangePicker
  minimumDays={ 3 }
  onRangeSelect={ (range, days) => handleRangeSelect(range) }
/>
```

Wondering if the component could even allow multiple ranges...

**Comment by adidahiya** [comment]
@JKillian, @giladgray, and I have done some work on this to create a range picker component on top of react-day-picker (we will be open sourcing our UI library some time this fall) -- we'd likely be interested in trying out this new feature.

Also I'd suggest the name `<DayRangePicker/>` because it reads nicer :)

**Comment by gpbl** [comment]
@adidahiya awesome! thanks for your comment.

I'd like to compare your implementation to those in my examples (that one with the mouse it's not working 100% as expected, yet). I'm very curious about your UI library as well.

Maybe `<Day*s*RangePicker />`? 🤔

**Comment by bsr203** [comment]
@gpbl see the component in action http://blueprintjs.com/docs/#components.datetime

**Comment by kvolkovich-sc** [comment]
I didn't think of a better place to express gratitude.
We made our own input components using your DayPicker. Thank you! :smile:

* [DateInput](https://opuscapita.github.io/react-dates/?currentComponentId=%40opuscapita%2Freact-dates%2F0.3.0-beta.6%2FDateInput&showSidebar=true)
* [DateRangeInput](https://opuscapita.github.io/react-dates/?currentComponentId=%40opuscapita%2Freact-dates%2F0.3.0-beta.6%2FDateRangeInput&showSidebar=true) 
* Repository [here](https://github.com/OpusCapita/react-dates)

**Comment by gpbl** [comment]
Awesome work @kvolkovich-sc 👍  Thanks for sharing. We should refer to them in the react-day-picker-docs :)

**Comment by geminiyellow** [comment]
@gpbl still working ? want `date-range-input` component

**Comment by kvolkovich-sc** [comment]
@geminiyellow try https://opuscapita.github.io/react-dates/
(Click "Sidebar" and choose DateRangeInput)

**Comment by gpbl** [comment]
At this point I don't think I'll add a third component to the package. Maintaining multiple components requires a lot of work 😞 

You can however refer to this example: http://react-day-picker.js.org/examples/input-from-to to see how to implement a range component with `DayPickerInput`.

(you are all welcome to improve that example 😄 )

**Comment by nayaabkhan** [comment]
Hi @gpbl, the links no longer work and I'm having trouble finding this in the official docs. Could you guide me to the right page?

**Comment by gpbl** [comment]
> Hi @gpbl, the links no longer work and I'm having trouble finding this in the official docs. Could you guide me to the right page?

Do you mean this page @nayaabkhan ?
https://react-day-picker-v7.netlify.app/examples/input-from-to/

**Comment by nayaabkhan** [comment]
Thanks, it is not this exact page but I found it in another section: https://react-day-picker-v7.netlify.app/examples/selected-range-enter.

By the way, is there a similar example for v8?
