### ISSUE TITLE
Render array of dateRanges?

### ISSUE THREAD

**Issue by fa10** [gpbl/react-day-picker#206]
Hey there!

I need some help using the **modifiers**  to render a array of dateRanges in the calendar.
And what is actually best to renderDay or modifiers?

```js
getEvent(day) {
    const { events } = this.props;

    let value;
    for (const event of events) {
      value = DateUtils.isDayInRange(day, { from: new Date(event.start), to: new Date(event.end) });
    }

    return value;
}
```

Thanks.

**Comment by gpbl** [comment]
Maybe it is more performant to use the array's `some` function, e.g.:

```js
hasEvent(day) {
   const { events } = this.props;
   const eventNames = Object.keys(events);
   return eventNames.some(name => {
        const from = new Date(events[name].start);
        const to = new Date(events[name].end);
        return DateUtils.isDayInRange(day, { from, to });
    });
}
```
```xml
<DayPicker modifiers={ hasEvent } />
```

**Comment by fa10** [comment]
Okay thanks for the answer in general i think maybe it could be good with some examples of rendering array of dateRanges in the DayPicker.

One more question how to call hasEvent without the **this** keyword?

`<DayPicker modifiers={ hasEvent } />`

**Comment by gpbl** [comment]
You can write `hasEvent.bind(this)`

**Comment by fa10** [comment]
I now got a warning and it does seems like it doesn't get hit.

> Warning: Failed propType: Invalid prop `modifiers` of type `function` supplied to `DayPicker`, expected `object`. Check the render method of `YearCalendar`.

**Comment by gpbl** [comment]
Yes, the modifiers prop requires an object of functions:

```js
modifiers={ { hasEvent: hasEvent.bind(this) }}.
```

**Comment by gpbl** [comment]
@fa10 I assume you have been able to solve your issue – if you still need help, please write back, thanks!

**Comment by fa10** [comment]
@gpbl Yes thank you for the answers.
