### ISSUE TITLE
Safari/iOS: hover background when unselecting a day

### ISSUE THREAD

**Issue by jasondainter** [gpbl/react-day-picker#2064]
## Description

When selecting the day of the month, then unselecting in a mobile browser (tested in chrome on IOS) it goes from

**Selected**...

![IMG_4770](https://github.com/gpbl/react-day-picker/assets/1300757/dbe4993a-756a-45d3-9767-503623063cae)

**To Unselected (pressing the date again)**

![IMG_4769](https://github.com/gpbl/react-day-picker/assets/1300757/c3a70d73-da09-4575-ad80-662ddf6a8767)

But as you can see (this was tested via the demo on https://react-day-picker.js.org/start directly) you get this blue highlight remaining

<img width="149" alt="Screenshot 2024-03-01 at 14 33 38" src="https://github.com/gpbl/react-day-picker/assets/1300757/b3773d25-1981-4140-a636-4cb328d84ae6">

This is quite confusing UX as you would expect no selection at all (it looks like it is still selected when it isnt)

Seems fine on Desktop.

Is there any way to turn that off?

## Expected Behavior

Expect the lighter blue circle to dissapear

## Actual Behavior

Lighter blue circle remains after clearing selection.

## Steps to Reproduce

1. Step one - https://react-day-picker.js.org/start
2. Step two - Press a date on mobile (ios/chrome)
3. Step three - Unpress a date (unselect)

## Your Environment
- React version: 18.2.0
- Browser [e.g. chrome, safari]: Chrome
- Version [e.g. 22]: Chrome 122
- Operating System [e.g. iOS, Windows]: iOS 17.3

**Comment by gpbl** [comment]
@jasondainter I see it. It looks like Safari is keeping the `:hover` style. It seems to be an issue for other people too: https://stackoverflow.com/questions/47802530.

<img width="1696" alt="Screenshot 2024-03-02 at 6 40 30 AM" src="https://github.com/gpbl/react-day-picker/assets/120693/29d06b23-0b6f-45f9-8401-d1dc287730ec">

**Comment by gpbl** [comment]
Looks like the fix is to include the over style inside `@media (hover: hover) {`.

**Comment by jasondainter** [comment]
Thanks for quick feedback. in the end I disabled the hover entirely. In my case todays date is highlighted (selected) when the user sees the calendar so I probably get away with this more (eg its more obvious the user has to click a date). would be great to have this fixed in a future version if doable!
