### ISSUE TITLE
Weekday names should respect the first day of week

### ISSUE THREAD

**Issue by emwee** [gpbl/react-day-picker#207]
I want my calendar to let week starts on Monday. The API is pretty much straight-forward, but I can't get it to work.

My code:

```js
const localeUtils = {
	formatDay: (d, locale='en') => formatDate(d, 'LLLL'),
	formatMonthTitle: (d, locale) => moment.months()[d.getMonth()],
	formatWeekdayShort: (i, locale) =>  moment.weekdaysShort()[i],
	formatWeekdayLong: (i, locale) => moment.weekdays()[i],
	getFirstDayOfWeek: (locale) => 0,
}

const Datepicker = props =>
	<DayPicker
		localeUtils={localeUtils}
	/>
```

It doesn't matter if `getFirstDayOfWeek` returns 0 or 1, the first weekday is always Sunday.

I am using version 2.4.1.

**Comment by gpbl** [comment]
Hi @emwee! 
Yeah that's not clear from the examples: if you want to set the first day on monday, also your weekdays names should start on monday as well. So I believe the following should work (I can't check right now):

```diff
const localeUtils = {
    formatDay: (d, locale='en') => formatDate(d, 'LLLL'),
    formatMonthTitle: (d, locale) => moment.months()[d.getMonth()],
-    formatWeekdayShort: (i, locale) =>  moment.weekdaysShort()[i],
-    formatWeekdayLong: (i, locale) => moment.weekdays()[i],
+    formatWeekdayShort: (i, locale) =>  moment.weekdaysShort()[i+1],
+    formatWeekdayLong: (i, locale) => moment.weekdays()[i+1],
    getFirstDayOfWeek: (locale) => 0,
}
```

Please let me know if it works so I can update the docs! Thanks.

**Comment by gpbl** [comment]
(Sorry my previous comment included a code sample that didn't work, the trick is making the weeks name array starting from monday)

**Comment by gpbl** [comment]
I'm filing this as bug as I agree it is an unexpected behavior  :)

**Comment by emwee** [comment]
Alright, fixed it the way you suggested for now. Thanks! :-)

````

const getWeekdayByIndex = (weekdays, i) =>
	weekdays[(i + 1) < weekdays.length ? i + 1 : 0]

export const localeUtils = {
	formatDay: (d, locale='en') => formatDate(d, 'LLLL'),
	formatMonthTitle: (d, locale) => moment.months()[d.getMonth()],
	formatWeekdayShort: (i, locale) => getWeekdayByIndex(moment.weekdaysShort(), i),
	formatWeekdayLong: (i, locale) => getWeekdayByIndex(moment.weekdays(), i),
	getFirstDayOfWeek: () => 1,
}
````

**Comment by gpbl** [comment]
Nice !! Reopening this as i'd like to fix in the next major release

**Comment by emwee** [comment]
👍

**Comment by gpbl** [comment]
This has been fixed in v3 – no need anymore for the workaround above, @emwee !
