### ISSUE TITLE
RootContext is missing pass-through types for each context it provides

### ISSUE THREAD

**Issue by union-zakbutcher** [gpbl/react-day-picker#2072]
## Description
I'm getting the following type error which makes sense b/c of type defs included in this project:

```
Type '{ children: Element; selected: Date; }' is not assignable to type 'IntrinsicAttributes & RootContext'.
  Property 'selected' does not exist on type 'IntrinsicAttributes & RootContext'.
```
The provided type for `RootContext` is:

```ts
export interface RootContext {
  children?: ReactNode;
}
```

Reproduced in [this fork](https://codesandbox.io/p/sandbox/divine-glitter-jw3kps?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltp9uoos00063b6lmcky6d3z%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltp9uoor00023b6l36xnf1kz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltp9uoor00033b6l767lamqv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltp9uoor00053b6l94cwj4s1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltp9uoor00023b6l36xnf1kz%2522%253A%257B%2522id%2522%253A%2522cltp9uoor00023b6l36xnf1kz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltp9v5mv004u3b6lmp9olc4w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltp9v5mv004u3b6lmp9olc4w%2522%257D%252C%2522cltp9uoor00053b6l94cwj4s1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltp9uoor00043b6luu9zap0w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltp9uoor00053b6l94cwj4s1%2522%252C%2522activeTabId%2522%253A%2522cltp9uoor00043b6luu9zap0w%2522%257D%252C%2522cltp9uoor00033b6l767lamqv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltp9uoor00033b6l767lamqv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

If the above link doesn't work, it _should_ be reproducible with this code:

```jsx
export default function App() {
  const [selectedDay, setSelectedDay] = React.useState<Date | undefined>();
  return (
    <RootProvider selected={new Date()}>
      <DayPicker
        mode="single"
        onSelect={setSelectedDay}
        selected={selectedDay}
      />
    </RootProvider>
  );
}
```

## Expected Behavior

I expect the `props` (or `RootContext`) to accept all possible props, flagged as optional, for all included providers because all additional props are automatically spread into each provider via the following where `initialProps` is passed to the `initialProps` prop of each provider

```js
const { children, ...initialProps } = props;
```

Providers:
* `DayPickerProvider`
* `SelectSingleProvider`
* `SelectMultipleProvider`
* `SelectRangeProvider`

## Actual Behavior

I get the following TS error:

```
Type '{ children: Element; selected: Date; }' is not assignable to type 'IntrinsicAttributes & RootContext'.
  Property 'selected' does not exist on type 'IntrinsicAttributes & RootContext'.
```

## Steps to Reproduce
See above setup (copied below) to use `RootProvider` as such:

```jsx
export default function App() {
  const [selectedDay, setSelectedDay] = React.useState<Date | undefined>();
  return (
    <RootProvider selected={new Date()}>
      <DayPicker
        mode="single"
        onSelect={setSelectedDay}
        selected={selectedDay}
      />
    </RootProvider>
  );
}
```

## Possible Solution

Extend each interface accordingly, e.g.:

```ts
type RootContextProps = Partial<DayPickerDefaultProps> | Partial<DayPickerSingleProps> | Partial<DayPickerMultipleProps> | Partial<DayPickerRangeProps>
/** The props of {@link RootProvider}. */
export type RootContext = RootContextProps & {
  children?: ReactNode;
}
```

## Screenshots
_**From Fork**_
![image](https://github.com/gpbl/react-day-picker/assets/138704408/8d517f6f-6a18-44f0-a550-da6533f16bb5)

_**From VS Code**_
<img width="1498" alt="image" src="https://github.com/gpbl/react-day-picker/assets/138704408/c2bcbaeb-cb22-40d3-9c7a-636a4598f3f1">

**Comment by union-zakbutcher** [comment]
I've poked around a bit an know this isn't exactly an easy thing to fix due to TS, but if there is a path forward, it would be VERY good to fix because ultimately all of the props flow down to the correct components / contexts, it's just a matter of playing nice with TS

**Comment by union-zakbutcher** [comment]
If need-be, I can do a sym-link locally to test, but it's nearly 1am my time and I'm not feeling it right now.  Lemme know if I need to do some more due diligence in my project before this is approved / merged

**Comment by gpbl** [comment]
Hey @union-zakbutcher thanks for the detailed report! From a first look, your PR looks good to go. Give me some time to review it more carefully.

Not sure what you are trying to do there with the context providers. I am working on v9 which would actually simplify these parts (and the typings): if you are relying a lot to the DayPicker v8 internals, you may have hard time to refactor to v9. 

Would you like to help us get v9 ready / or do you have time to help us testing it?

**Comment by union-zakbutcher** [comment]
@gpbl I'm certainly open to the idea of helping develop / test v9 - I just can't make any firm commitments involving timeframes.  If you have some general onboarding docs or something I can look at to get an idea of what help you need, I can take a look and get back to you on what I can actually help with!

As far as what I'm doing / needing, I was trying to resolve a type error in a storybook file where I'm documenting my custom implementation of `react-day-picker` to match the design system I'm building out for my company and I needed to use the `RootProvider` in those docs.  The implementation is fairly large and private so sharing it here would be difficult, however I can try and summarize what I'm doing and we can go from there.

I've built two main components: `Calendar` and `DatePicker`.  `Calendar` is my main wrapper around `react-day-picker` and handles low-level customizations like the theme color, some date formatting, our own custom context, and some other behavioral changes we need based on the UX we're targeting.  Ultimately it boils down to a date-range picker and a single-date picker which use `DayPicker` with the necessary props to make it behave as a date range picker or single date picker, respectively.  This component is JUST the UI / UX of the actual calendar

The `DatePicker` component is my higher-level, business-logic-included wrapper around `Calendar` that includes UX smoothing and enhances the calendar with other components from our DS like a `TextInput` for manually typing in a date and then updating `Calendar` accordingly or making sure our `onChange` callback is only called when a valid date has been entered so we don't erroneously call `onChange` with a partial or invalid date.

I'm not actually using `RootProvider` in my app, I'm just using it in my documentation in Storybook to force certain behaviors so I can "lock in" various permutations while using my components that depend on a context existing.  I know all of the above is super vague so I've got a screenshot and the code from my documentation here to help out (note each `const` is associated with a heading in the image, e.g. the `Caption` element is the `CalendarMonthNavigator` heading):

![screencapture-localhost-6006-2024-03-14-12_27_46](https://github.com/gpbl/react-day-picker/assets/138704408/312f7a3b-fb26-4cbf-a174-c4ab97f2c229)

```jsx
export const Caption = () => (
  <StoryWrapper col>
    <RootProvider>
      <CalendarMonthNavigator displayMonth={DATE} />
    </RootProvider>
  </StoryWrapper>
);
export const Day = () => (
  <StoryWrapper>
    <Col className="w-fit items-stretch">
      <Calendar>
        <Row className="justify-between">
          <Text.Body>Unselected Day</Text.Body>
          <RootProvider>
            <DayPickerProvider initialProps={{ mode: "single" }}>
              <div className="w-fit">
                <CalendarDay
                  date={subDays(DATE, 1)}
                  displayMonth={subDays(DATE, 1)}
                />
              </div>
            </DayPickerProvider>
          </RootProvider>
        </Row>
        <Row className="justify-between">
          <Text.Body>Selected Day</Text.Body>
          {/* @ts-expect-error: See above comment regarding use of `any` */}
          <RootProvider selected={DATE}>
            <DayPickerProvider initialProps={{ mode: "single" }}>
              <div className="w-fit">
                <CalendarDay date={DATE} displayMonth={DATE} />
              </div>
            </DayPickerProvider>
          </RootProvider>
        </Row>
        <Row className="justify-between">
          <Text.Body>Today (Unselected)</Text.Body>
          <RootProvider>
            <DayPickerProvider initialProps={{ mode: "single" }}>
              <div className="w-fit">
                <CalendarDay date={DATE} displayMonth={DATE} />
              </div>
            </DayPickerProvider>
          </RootProvider>
        </Row>
        <Row className="justify-between">
          <Text.Body>Date Range Start</Text.Body>
          <RootRangeProvider mode="range" selected={DATE_RANGE}>
            <div className="w-fit">
              <CalendarDay
                date={subDays(DATE, 2)}
                displayMonth={subDays(DATE, 2)}
              />
            </div>
          </RootRangeProvider>
        </Row>
        <Row className="justify-between">
          <Text.Body>Date Range Middle</Text.Body>
          <RootRangeProvider mode="range" selected={DATE_RANGE}>
            <div className="w-fit">
              <CalendarDay
                date={subDays(DATE, 1)}
                displayMonth={subDays(DATE, 1)}
              />
            </div>
          </RootRangeProvider>
        </Row>
        <Row className="justify-between">
          <Text.Body>Date Range End</Text.Body>
          <RootRangeProvider mode="range" selected={DATE_RANGE}>
            <div className="w-fit">
              <CalendarDay date={DATE} displayMonth={DATE} />
            </div>
          </RootRangeProvider>
        </Row>
      </Calendar>
    </Col>
  </StoryWrapper>
);
export const SingleDatePicker = () => {
  const [selected, setSelected] = useState<Date | undefined>(DATE);
  return (
    <StoryWrapper col>
      <Calendar.Single selected={selected} onChange={setSelected} />
    </StoryWrapper>
  );
};
export const DateRangePicker = () => {
  const [selected, setSelected] = useState<DateRange | undefined>(DATE_RANGE);
  return (
    <StoryWrapper col>
      <Calendar.Range selected={selected} onChange={setSelected} />
    </StoryWrapper>
  );
};
export const CalendarTheming = () => {
  const [selected, setSelected] = useState<DateRange | undefined>(DATE_RANGE);
  return (
    <StoryWrapper col>
      <Text.ElementHeader>Blue Theme (Default)</Text.ElementHeader>
      <Calendar>
        <Calendar.Range selected={selected} onChange={setSelected} />
      </Calendar>
      <Text.ElementHeader>Green Theme</Text.ElementHeader>
      <Calendar theme="green">
        <Calendar.Range selected={selected} onChange={setSelected} />
      </Calendar>
    </StoryWrapper>
  );
};
```

**Comment by zakbutcher** [comment]
@gpbl Just wanted to ping you on my personal account because I was recently let go from my job and would rather any supporting efforts come from my own account.  I'm still interested in helping out because this is a great library.  If you have any type of roadmap or plan I can check out to orient myself with your goals for v9, I can check them out and figure out a way to start plugging in!

**Comment by gpbl** [comment]
Hey @zakbutcher, thanks a lot for the follow ups - I'm facing some personal issues myself too, so please forgive my late reply. 

I deeply appreciate your offer for help! I will go through your code and comments here in the upcoming days.
