### ISSUE TITLE
Range should start new if one already selected

### ISSUE THREAD

**Issue by NeilRiver** [gpbl/react-day-picker#2140]
## Description

Hello! the range does not work correctly

## Expected Behavior

1 click - start of range
2 clicks - end of range
3 clicks - new range

## Actual Behavior

the range does not reset to zero, but tries to expand

```
  const [date, setDate] = React.useState<DateRange | undefined>();
  
          <Calendar
            initialFocus
            locale={ru}
            mode='range'
            defaultMonth={date?.from}
            selected={date}
            onSelect={setDate}
            numberOfMonths={2}
          />
```

**Comment by NeilRiver** [comment]
I have cognitive dissonance, as I understand it, this behavior is “expected”. The question is why?

I managed to find a fork in which everything works well, I also looked at the documentation for version 7, adequate behavior was already implemented there. I really have a lot of questions: why did you do this?

https://blueprintjs.com/docs/#datetime2/date-range-picker3
https://react-day-picker-v7.netlify.app/examples/selected-range-enter

to get adequate behavior, do I need to use a fork or an old version?

**Comment by Peeeep** [comment]
This can be archived by utilising the second parameter of the `SelectRangeEventHandler`:

```tsx
const [date, setDate] = useState<DateRange>({ from: undefined });

const handleSelect: SelectRangeEventHandler = (nextRange, selectedDay) => {
  setDate((range) => {
    if (range.from && range.to) return { from: selectedDay };
    return nextRange as DateRange;
  });
};

return <DayPicker mode="range" selected={date} onSelect={handleSelect} />;
```

(IMHO this should be the default behaviour)

**Comment by NeilRiver** [comment]
@Peeeep wow, i also came up with a similar solution. There are some awkward questions for the author... why the whole world works according to the 'new range' principle, but only here it should be different. This is not the level of a library that is downloaded by a million people.

**Comment by gpbl** [comment]
> This is not the level of a library that is downloaded by a million people.

@NeilRiver [please be kind](https://github.com/gpbl/react-day-picker/blob/main/.github/CODE_OF_CONDUCT.md) and do not burn the maintainer out. I am one single dev against "a million people". Be constructive with your comments, thanks.

**Comment by NeilRiver** [comment]
@gpbl I'm sorry, I went too far. Tell me, do you have an official solution to our issue?

**Comment by gpbl** [comment]
@NeilRiver no worries!

A better range behavior will be released in the next major version: an alpha will be released by end-of-month for an early preview.

[This solution](https://github.com/gpbl/react-day-picker/issues/2140#issuecomment-2127651564) is for now a good workaround. There's also a discussion going on: https://github.com/gpbl/react-day-picker/discussions/2050. 

Thanks for your patience!

**Comment by gpbl** [comment]
@NeilRiver this is going to be fixed in v9, see an example here:

https://react-day-picker.js.org/next/using-daypicker/selection-modes#range-mode

does it works according your requirements? We are still iterating over it.

**Comment by NeilRiver** [comment]
@gpbl  Thank you very much! Will wait! At the moment, according to the solution above - everything is ok!

**Comment by lucianocn** [comment]
Hi @gpbl,
Amazing library, congrats!

Has this issue been fixed in v9.0.6? I didn't find any related configuration in https://daypicker.dev/docs/selection-modes#range-mode

Thanks!

**Comment by amanusovich** [comment]
> This can be archived by utilising the second parameter of the `SelectRangeEventHandler`:
> 
> ```tsx
> const [date, setDate] = useState<DateRange>({ from: undefined });
> 
> const handleSelect: SelectRangeEventHandler = (nextRange, selectedDay) => {
>   setDate((range) => {
>     if (range.from && range.to) return { from: selectedDay };
>     return nextRange as DateRange;
>   });
> };
> 
> return <DayPicker mode="range" selected={date} onSelect={handleSelect} />;
> ```
> 
>  Bildschirmaufnahme.2024-05-23.um.19.07.11.mov 
> (IMHO this should be the default behaviour)

**Comment by amanusovich** [comment]
I made it work doing this:

```
const [selectedRange, setSelectedRange] = useState({ from: undefined, to: undefined });

  const handleRangeChange = (nextRange, selectedDay) => {
    setSelectedRange((range) => {
      if (range?.from && range?.to) return { from: selectedDay };
      if (!range?.from && !range?.to) return { from: selectedDay };
      return nextRange;
    });
  };
```

**Comment by jongjunpark** [comment]
@amanusovich Great!

However, in this case, a single date cannot be selected. For example, `from: Jan 1, 2024`, `to: Jan 1, 2024`. It would be nice to add just one line, like below.

```javascript
const [date, setDate] = useState<DateRange>({ from: undefined, to: undefined });

const handleSelect = (nextRange?: DateRange, selectedDay?: Date) => {
  setDate((range) => {
    if (range.from && range.to) return { from: selectedDay };
    if (range.from && !range.to) return { from: range.from, to: selectedDay };
    if (!range.from && !range.to) return { from: selectedDay };
    return nextRange as DateRange;
  });
};
```
