### ISSUE TITLE
docs: not updating selected month during input change event

### ISSUE THREAD

**Issue by lrgurjar** [gpbl/react-day-picker#2148]
## Description

Fork this CodeSandbox: https://codesandbox.io/p/sandbox/react-day-picker-v8-eg8mw and add to it the code to reproduce the issue.
https://codesandbox.io/p/sandbox/frosty-mountain-p44j9f?file=%2Fsrc%2FApp.tsx%3A6%2C12

https://codesandbox.io/p/sandbox/dreamy-chandrasekhar-7d4hcd?file=%2Fsrc%2FApp.tsx%3A8%2C25

![image](https://github.com/gpbl/react-day-picker/assets/18523244/5e1b5ecb-9753-4fe0-a0ae-6c6f765ba0fb)

## Expected Behavior
I want current select month displayed on date picker if user change month form input box
Describe what you expect to happen.

## Actual Behavior

Describe what is actually happening.
I am using 8.10.1 react day picker version when I am changing date from input box date Picker is not displaying current selected month.

## Steps to Reproduce

1. Select the any date form  date picker 
2. try to edit date form input box except default selected 
3. try to change month form input box then it is not showing current selected month
4. in screenshot input box i have selected 04/10/2024 but date picker is showing may 2024 and footer selected message is correct wed April 10 2024
  

## Possible Solution

If you have a suggestion on how to fix the issue, please include it here.

## Screenshots
![image](https://github.com/gpbl/react-day-picker/assets/18523244/5e1b5ecb-9753-4fe0-a0ae-6c6f765ba0fb)
If applicable, add screenshots or GIFs to help explain your problem.

## Your Environment

- React version:18.2
- Your Timezone:9-7 IST
- Browser [e.g. chrome, safari]:Chrome
- Version [e.g. 22]:8.10.1
- Operating System [e.g. iOS, Windows]:windows
- Other relevant information:

**Comment by sbc640964** [comment]
+1

**Comment by lrgurjar** [comment]
> +1

Hi @sbc640964  didn't understood your comment

**Comment by sbc640964** [comment]
+1 = I join too! :)

I also agree with your problem, I encounter the same bug that needs urgent attention...

It always shows the current month without any reference to the selected date.

**Comment by gpbl** [comment]
Thanks for the heads up - I find the examples: https://react-day-picker.js.org/advanced-guides/input-fields#input-with-inline-calendar

**Comment by lrgurjar** [comment]
> Thanks for the heads up - I find the examples: https://react-day-picker.js.org/advanced-guides/input-fields#input-with-inline-calendar

@gpbl thank you so much your response.
would it works same for multiple & range also

**Comment by gpbl** [comment]
> > Thanks for the heads up - I find the examples: [react-day-picker.js.org/advanced-guides/input-fields#input-with-inline-calendar](https://react-day-picker.js.org/advanced-guides/input-fields#input-with-inline-calendar)
> 
> @gpbl thank you so much your response. would it work same for multiple & range also ?

Sure: just change the `<DayPicker>` props as usual.

**Comment by gpbl** [comment]
> > Thanks for the heads up - I find the examples: [react-day-picker.js.org/advanced-guides/input-fields#input-with-inline-calendar](https://react-day-picker.js.org/advanced-guides/input-fields#input-with-inline-calendar)
> 
> @gpbl thank you so much your response. would it work same for multiple & range also ?
 
Sure you can make it working with a range selection by providing two input fields. Maybe multiple input fields as well but then you need _n_ input fields, each for a selectable day.

**Comment by lrgurjar** [comment]
> > > Thanks for the heads up - I find the examples: [react-day-picker.js.org/advanced-guides/input-fields#input-with-inline-calendar](https://react-day-picker.js.org/advanced-guides/input-fields#input-with-inline-calendar)
> > 
> > 
> > @gpbl thank you so much your response. would it work same for multiple & range also ?
> 
> Sure you can make it working with a range selection by providing two input fields. Maybe multiple input fields as well but then you need _n_ input fields, each for a selectable day.

ok thank you so much @gpbl
