### ISSUE TITLE
Style of Range bug - Wrong import in documentation

### ISSUE THREAD

**Issue by Vansh-Baghel** [gpbl/react-day-picker#2150]
## Description
1. While using the Range Calender, I found that the styling is not getting implemented. Make it a little more user-friendly, and include the same in installation section if possible.
2. Main issue, is that even after importing it in React, it says that `Failed to resolve import "react-day-picker/style.css" from "src/App.tsx". Does the file exist?
`
Don't need to panic, just change the import statement to the following for React:
`import "react-day-picker/dist/style.css"`

## Expected Behavior
* The style should be properly applied.

## Actual Behavior
* Style is not getting applied

## Screenshots
Before: 
![image](https://github.com/gpbl/react-day-picker/assets/103327712/fe728f08-013f-49bc-89f7-078d39c6ea3b)

After: 
![image](https://github.com/gpbl/react-day-picker/assets/103327712/d3c2e860-0ae3-4325-8c62-37eb6a7771b9)

## Your Environment

- React version:
- Your Timezone:
- Browser [e.g. chrome, safari]:
- Version [e.g. 22]:
- Operating System [e.g. iOS, Windows]:
- Other relevant information:

**Comment by gpbl** [comment]
Thanks! Fixed it in https://github.com/gpbl/react-day-picker/commit/9ad13dc72fff814dcf720a62f6e3b5ea38e8af6d

**Comment by Vansh-Baghel** [comment]
🔥🚀
