### ISSUE TITLE
Is unselect of date supported?

### ISSUE THREAD

**Issue by alexbeletsky** [gpbl/react-day-picker#217]
I went through the API docs and examples, but can't find how unselection of date is supported. Say, a user has selected value, but he wants to revert (set it back to null). How is this possible with `react-day-picker`?

**Comment by gpbl** [comment]
Hi @alexbeletsky 

please check [this example](http://react-day-picker.js.org/examples/?selectable) as it shows exactly how to select/unselect days :)

**Comment by alexbeletsky** [comment]
@gpbl oh, I see now - thanks a lot :)
