### ISSUE TITLE
Core Web Vitals : Unused Javascript is high when used with Next JS SSR 

### ISSUE THREAD

**Issue by ShivaGuidesly** [gpbl/react-day-picker#2184]
## Description

Core Web Vitals : Unused Javascript is high when used with Next JS SSR . After integrating with Next JS app the unused javascript report is high for this component. 

## Expected Behavior

Reduce the unused JavaScript.

## Actual Behavior

TBT is increased due to the unusual javascript.

## Steps to Reproduce

1. Install the package on a next JS app
2. Add the package
3. Run the light house to observe that there are unused java script showing up for this component causing slowness on page

**Comment by gpbl** [comment]
@ShivaGuidesly interesting thanks for the report. Could you replicate the issue somewhere, e.g. https://codesandbox.io ?
