### ISSUE TITLE
Bug : Date in modifier " booked " is placed one month ahead

### ISSUE THREAD

**Issue by MohamedDanis** [gpbl/react-day-picker#2205]
## Description

Add the attributes modifiers and modifierClassNames to the DatePicker Component. As per the [documentation](https://react-day-picker.js.org/advanced-guides/custom-modifiers#the-selected-modifier) on custom modifiers, I have added a date as value to booked key in in modifier object and defined a classname for modifer with proper styling. But the modifier showing in the next month of same date.

## Expected Behavior

The modifier should show in the defined date

## Actual Behavior

The modifier is placed in next month of same date

## Steps to Reproduce

https://codesandbox.io/p/sandbox/quirky-maxwell-qz423f?file=%2Fsrc%2Fstyles.css%3A11%2C15

## Possible Solution

nop.

## Screenshots

If applicable, add screenshots or GIFs to help explain your problem.

## Your Environment

- React version: 18
- Your Timezone: GMT+5:30
- Browser : chrome
- Version : 125.0.6422.142
- Operating System : Windows

**Comment by gpbl** [comment]
@MohamedDanis does this happen with the next release too?

```
npm install react-day-picker@next
```

**Comment by gpbl** [comment]
The sandbox link is not working...
