### ISSUE TITLE
`formatters.formatCaption` does not provide current day

### ISSUE THREAD

**Issue by AbhiShake1** [gpbl/react-day-picker#2212]
## Description

i am converting date to nepali timeline (bikram sambat), and for correct conversion, i need the day along with month and year. but the value of day is always 1.

## Expected Behavior

when i try to use day in formatCaption callback, i am always getting 1

## Actual Behavior

when i try to use day in formatCaption callback, i should get the selected day. month and year is correct

## Your Environment

- React version: tried 18 and 19
- Your Timezone: asia/kathmandu
- Browser [e.g. chrome, safari]: firefox
- Version [e.g. 22]: 22
- Operating System [e.g. iOS, Windows]: linux
- Other relevant information:

**Comment by gpbl** [comment]
Hi @AbhiShake1 do you have some code to check out? Thanks.

**Comment by AbhiShake1** [comment]
> Hi @AbhiShake1 do you have some code to check out? Thanks.

i realized what i needed (bikram sambat format calendar) is out of scope of this library. sorry for any inconvenience. closing the issue
