### ISSUE TITLE
No way to set styles of selected days in range mode in v9.0

### ISSUE THREAD

**Issue by punit1108** [gpbl/react-day-picker#2218]
## Description

Currently there is no way to add properties for range start selected date and end selected date, which might be useful in a lot of scenarios which customizing the range selection.

![image](https://github.com/gpbl/react-day-picker/assets/7887355/10392c93-7d91-443b-a884-4667d0f5a182)

## Expected Behavior

There should be a way to style the radiuses of the start and end selected days

## Actual Behavior

No styling property currently corresponds to it.

## Steps to Reproduce

1. Set mode as "range"

## Possible Solution

Solution 1 - 
`--rdp-range_start-selected-border-radius`
`--rdp-range_end-selected-border-radius`

Solution 2 -
Add a way to add Tailwind styles apart from the `selected` property, eg,
`range-start-selected`
`range-end-selected`

## Screenshots

If applicable, add screenshots or GIFs to help explain your problem.

## Your Environment

- React version: 18
- Your Timezone: Indian Standard Time
- Browser [e.g. chrome, safari]:
- Version [e.g. 22]:
- Operating System [e.g. iOS, Windows]:macOS
- Other relevant information:

**Comment by lariane-guerra** [comment]
Its possible to change in version v8? 

![image](https://github.com/user-attachments/assets/0842187d-9e00-4156-9edd-dfeb50475a64)


I need almost this (the second photo its from the playground react day pick):
<img width="343" alt="image" src="https://github.com/user-attachments/assets/1823972d-a6cb-497c-84cf-6508ae32276a">

**Comment by gpbl** [comment]
Hi @lariane-guerra! Here to help...

- please upgrade to `react-day-picker@next` if you want to use that style
- please share some code so we can help. Thanks.

**Comment by lariane-guerra** [comment]
![image](https://github.com/user-attachments/assets/eae50e01-bb69-4c93-9543-9a4df4f743ee)
I update to the new version,
how i get off this o padding between the days?

**Comment by lariane-guerra** [comment]
`export const NewDatePickerComponent = styled(DayPicker) 
future styles here
`

```
          <NewDatePickerComponent
            locale={brazilLocale}
            mode="range"
            selected={range}
            onSelect={setRange}
            numberOfMonths={1}
          />

```


locale={brazilLocale}
 
 I found it:
If i remove this, work good, but when i put the brazilocale this what i put in print happen.

**Comment by lariane-guerra** [comment]
To add: in playground when you change to pt-BR, bug happen too.
