### ISSUE TITLE
Keyboard navigation of captionElement select menus

### ISSUE THREAD

**Issue by thomasbarone** [gpbl/react-day-picker#222]
Using the arrow keys to navigate through the select menus for the month / year when using a captionElement causes the months and years to change erratically. This occurs on both Chrome and Firefox

Steps to reproduce:

1. Go to http://react-day-picker.js.org/examples/?yearNavigation
2. Click/focus on the Month select menu
3. Press the down arrow key

In this case the month will change appropriately, however the year will also change. I believe this has to do with the handleKeyDown() event handler in [DayPicker.js](https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L263) being fired alongside the browser handling of arrow keys when a select menu is focused :)

**Comment by gpbl** [comment]
Hi @thomasbarone thanks a lot for the heads up! 

I've fixed the example by stopping the event propagation from the select elements:

```js
onKeyDown={ e => e.stopPropagation() }
```
