### ISSUE TITLE
Start day Monday

### ISSUE THREAD

**Issue by dncdrn** [gpbl/react-day-picker#223]
Hi how can I change the first day of the week is monday? Here's my code

````js
const weekdaysLong = {
   en-gb: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",]
};
const weekdaysShort = {
   en-gb: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"]
};
const firstDayOfWeek = {
   en-gb: 0
};

const localeUtils = {
   formatWeekdayShort: (day, locale="en") => weekdaysShort[locale],
   formatWeekdayLong: (day, locale="en") => weekdaysLong[locale],
   getFirstDayOfWeek: (locale) => firstDayOfWeek[locale]
}
```

Thanks in advance! :)

**Comment by davidspiess** [comment]
I was going to ask the same question! Since 3.0 my calendar starts with Sunday.

**Comment by davidspiess** [comment]
I found the answer in on of the examples:

```jsx
<DayPicker
  locale={ locale }
  localeUtils={ MomentLocaleUtils }
  modifiers={ { sunday: day => day.getDay() === 0 } }
/>
```

**Comment by gpbl** [comment]
@dncdrn did you upgrade to v3 right? From v3 weekdays names must start from Sunday, so you need to specify `1` as first day of week.

See [release notes](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md#v300-2016-10-11).

Hence:

```diff
const weekdaysLong = {
-   en-gb: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",]
+   en-gb: [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
};
const weekdaysShort = {
-   en-gb: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"]
+   en-gb: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"]
};
const firstDayOfWeek = {
-    en-gb: 0,
+   en-gb: 1
};
```

If you wait ~half an hour I'll release a new version including new props that will make easier to localize the UI.

**Comment by gpbl** [comment]
@davidspiess are you using Moment? There's a regression from #220 in the moment locale utils. Fix coming soon!

**Comment by davidspiess** [comment]
Yes momentjs 👍 Awesome :=)

**Comment by gpbl** [comment]
@dncdrn from v3.1.0 you can now use the new localization props:

```jsx
const weekdaysLong = {
   "en-gb": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",]
};
const weekdaysShort = {
   "en-gb": ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"]
};
const firstDayOfWeek = {
   "en-gb": 1
};

<DayPicker 
    firstDayOfWeek={ firstDayOfWeek['en-gb'] }
    weekdaysShort={ weekdaysShort['en-gb'] }
    weekdaysLong={ weekdaysLong['en-gb'] }
/> 
```

Actually, being English the default, for `en-gb` you could just set the first day of week:

```jsx
// same as above
<DayPicker firstDayOfWeek={ 1 } />
```

**Comment by dncdrn** [comment]
Just saw this. Thank you! @gpbl :)

**Comment by driversti** [comment]
Well, I can't to change first day of e week, 'coz <DayPicker /> doesn't has that property. Would you be kind to explain why? Thx in advance))

**Comment by gpbl** [comment]
@driversti did you update to the latest version?

**Comment by driversti** [comment]
@gpbl yeah, of course. I started to use this lib today

**Comment by gpbl** [comment]
@driversti check this example: http://react-day-picker.js.org/examples/?localized
Please add another issue on github if you find a bug, thanks!
