### ISSUE TITLE
Localized weekdays do not match with dates

### ISSUE THREAD

**Issue by davidspiess** [gpbl/react-day-picker#224]
Since the 3.0 update my italian and german weekdays begin the week with tuesday and do not match with the calendar dates anymore.

Same happens in your [online demo](http://react-day-picker.js.org/examples/?localized) if you switch to italian

![image](https://cloud.githubusercontent.com/assets/992674/19378432/db6e66ca-91ec-11e6-95b4-ed2b33844b44.png)

**Comment by gpbl** [comment]
Hi @davidspiess thanks for the bug report! It has been fixed in v3.0.1.

**Comment by davidspiess** [comment]
Thanks @gpbl! Everything works again 👍
