### ISSUE TITLE
Number.isInteger breaks IE and Safari

### ISSUE THREAD

**Issue by davidspiess** [gpbl/react-day-picker#227]
https://github.com/gpbl/react-day-picker/blob/a5db42602223bd813c76d82e721a1a4dc25b6788/src/Helpers.js#L46

**Comment by gpbl** [comment]
😱 I guess is the missing ES6 polyfill. Switching back to old good JavaScript. Thanks for the report !

**Comment by davidspiess** [comment]
Or maybe use typescript ?

Am 17.10.2016 um 17:38 schrieb Giampaolo Bellavite <notifications@github.com<mailto:notifications@github.com>>:


? I guess is the missing ES6 polyfill. Switching back to old good JavaScript. Thanks for the report !

-

**Comment by gpbl** [comment]
@davidspiess don't even try... 😁

**Comment by gpbl** [comment]
This should be fixed in v3.1.1 👍

**Comment by davidspiess** [comment]
👍🏻 haha thanks ;)
