### ISSUE TITLE
Search Not Working on react-day-picker Documentation

### ISSUE THREAD

**Issue by skojphy** [gpbl/react-day-picker#2286]
## Description

- When trying to search for specific topics or properties (such as onSelect), the search feature does not return relevant results or seems to be non-functional.

## Actual Behavior

- When performing a search on the documentation site, such as searching for the term onSelect, the search returns a "Page Not Found" error instead of relevant documentation results.

## Screenshots

<img width="661" alt="image" src="https://github.com/user-attachments/assets/80a1ccd6-590f-45e9-b276-e8aeaf2544a4">

## Your Environment

- Browser [e.g. chrome, safari]: Chrome

**Comment by gpbl** [comment]
Thanks for the report @skojphy. We restarted the index and you should be able to see the updated search result.
