### ISSUE TITLE
Selecting multiple days

### ISSUE THREAD

**Issue by magnusohlin** [gpbl/react-day-picker#229]
Is it possible to somehow configure the component to be used as a multiple date picker? I'm not talking about a range picker, but instead you would click multiple separate dates and they would be selected. For example something like this: 

<img width="326" alt="screenshot 2016-10-21 13 40 09" src="https://cloud.githubusercontent.com/assets/521837/19597278/ef86850a-9793-11e6-9ba7-324429ee2348.png">

**Comment by gpbl** [comment]
Add the clicked day to an array in your component state, then make sure the function passed to `selectedDays` returns `true` when the day is included in the array. 

To know if a day is included, you can loop over that array using the `isSameDay` utility provided in `DateUtils`.

**Comment by magnusohlin** [comment]
Great! Worked perfectly, thanks! Is there any plans on adding a onWeekdayClick method which could be used to for example select all the mondays in a month?

**Comment by gpbl** [comment]
@magnusohlin i haven't planned such feature but if you are interested implementing it .... it should be straightforward to add a prop to the Weekdays.js component ! 👍

**Comment by gpbl** [comment]
I've added [an example](http://react-day-picker.js.org/examples/?multipleselect) about how implement this.
