### ISSUE TITLE
v9 - onDayMouseEnter not working

### ISSUE THREAD

**Issue by martin8877** [gpbl/react-day-picker#2296]
## Description
In v8 I had nice on-hover range selector implemented with onDayMouseEnter. In v9 onDayMouseEnter is not working anymore. 

## Expected Behavior

onDayMouseEnter should call callback on mouse hover 

## Actual Behavior

Callback is not called. 

## Screenshots

This was possible in v8.
![rdp](https://github.com/user-attachments/assets/ec638890-ed74-4c76-a22e-9d98c251628d)

## Your Environment

- React version: 18.2.0
- Your Timezone: CET
- Browser [e.g. chrome, safari]: Chrome, Firefox
- Version [e.g. 22]: latest
- Operating System [e.g. iOS, Windows]: windows, linux
- Other relevant information:

**Comment by ShacharZ1** [comment]
Seems to still be the case
