### ISSUE TITLE
When num of months > 1 - make 'toMonth' as the first month to the right if 'toMonth' is current month

### ISSUE THREAD

**Issue by portons** [gpbl/react-day-picker#230]
I need to make a range date picker with 3 months, that always goes from current month to past days, no future dates.

I'm making 'toMonth' as current month, 'initialMonth' is also current month. And what I get is, the toMonth is to the left side of the calendar, with 2 future months showing as next months, when they should be unavailable.

(Current month is October, initially '**from**' and '**to**' are **null**)

![image](https://cloud.githubusercontent.com/assets/8877864/19625066/f42de6c8-9916-11e6-9167-bae4de15de29.png)

And, while moving back in months, the "next month" arrow is missing until I get to October as the rightmost month:

![image](https://cloud.githubusercontent.com/assets/8877864/19625097/a30ee2fa-9917-11e6-86a6-f8a10253a2c0.png)

![image](https://cloud.githubusercontent.com/assets/8877864/19625098/ad5ac4fe-9917-11e6-9e46-ead3a566b1e2.png)

And only from this point it behaves like I'd expect it to. Is there a way to make current month as first to the right?

**Comment by portons** [comment]
Found a solution. Set 'initialMonth' prop (using moment.js) as: 

`currentMonth.subtract(2, "month")`

**Comment by gpbl** [comment]
Yeah @portons the initialMonth is referred to the month to the left when showing multiple months. Glad you could solve it 👍
