### ISSUE TITLE
v9 Range mode selecting same from and to date

### ISSUE THREAD

**Issue by Nicochung** [gpbl/react-day-picker#2302]
Hi, I have found an issue related to the change of default behaviour for range mode in v9.

In v8, it is possible to select the same date as the from date and to date by clicking the same the date twice.

In v9, clicking the same date twice will instead unselect the from date. 

If this change of default behaviour is intended, what changes need be made in order to select the same date as from and to date in v9?

## Expected Behavior

Range mode selection should be able to select the same date as from date and to date similar to the behaviour in v8.

## Actual Behavior

Clicking the same date twice will unselect the date.

## Screenshots
v8 behaviour https://daypicker.dev/v8/using-daypicker/selection-modes#range-mode

![v8RangeSelect](https://github.com/user-attachments/assets/5a701217-db98-40f0-b525-77498bb78381)

v9 behaviour https://daypicker.dev/docs/selection-modes

![v9RangeSelect](https://github.com/user-attachments/assets/baa84919-1837-4e7b-9d2f-a8578bbbf65d)

**Comment by gpbl** [comment]
@Nicochung thanks for your feedback! We definitely want to put the new behavior here behind a flag to no break your code.

The assumption was that a range of dates must have at least two dates in it. I'm wondering if we should add this behind the `required` prop or add a new prop.

**Comment by Nicochung** [comment]
Thank you for the quick response.

It would be nice to have a flag such as `allowSameDate` to toggle the behaviour.

In my use case, I am treating the range as the start of from date to the end of to date (e.g.  YYYY-MM-DD 00:00:00 -> YYYY-MM-DD 23:59:59), so it is valid for me to have the same date in a range, as I am treating it as a time range.

**Comment by gpbl** [comment]
I am not sure about the prop name. I wish I could use `required` somehow:

```tsx
<DayPicker mode="range" required /> // a required range cannot have the same from/to date
<DayPicker mode="range" required={false} /> // default: a range can have the same from/to date
```

Would it make sense better then `allowSameDate`? 🤔
