### ISSUE TITLE
Consider migrating to date-fns from moment

### ISSUE THREAD

**Issue by andrewmclagan** [gpbl/react-day-picker#231]
Moment is a monolithic library, as a dependancy it adds huge weight to a single component.

Also Moment does not support importing individual components from their library, its all or none.

[date-fns](https://github.com/date-fns/date-fns) is far far more light weight, performant and capable of all the transformations we need.

Would you consider a migration at any point in the future?

**Comment by gpbl** [comment]
👋 @andrewmclagan 
Thanks, I wasn't aware of date-fns! Actually react-day-picker doesn't depend on moment, so there's no migration needed. We do support an [add-on](https://github.com/gpbl/react-day-picker/blob/master/src/addons/MomentLocaleUtils.js) that requires moment.js as dependency, but it is used just for localization. Maybe we can add a similar add-ons for date-fns as well!

**Comment by andrewmclagan** [comment]
oh really, had no idea! 

lets close this!
