### ISSUE TITLE
ES Modules / CommonJS error in next.js 14.2.5

### ISSUE THREAD

**Issue by TheMikeyRoss** [gpbl/react-day-picker#2310]
I have react-day-picker component in my next.js app and it used to work perfectly but after updating to v9 now im getting this critical error.

```
node_modules\.pnpm\react-day-picker@9.0.4_react@18.3.1\node_modules\react-day-picker\dist\cjs\index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename C:\code\MIKEY\node_modules\.pnpm\react-day-picker@9.0.4_react@18.3.1\node_modules\react-day-picker\dist\cjs\index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in C:\code\MIKEY\node_modules\.pnpm\react-day-picker@9.0.4_react@18.3.1\node_modules\react-day-picker\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

if I add type=module in my package.json of my next.js app everything breaks and I have to change things in next.config and i18n.js and dozen other files, and after going through all of that it caused more errors that I could solve. 

I'm I doing something wrong?

**Comment by gpbl** [comment]
@TheMikeyRoss interesting, thanks for the report. How do I reproduce this?

**Comment by TheMikeyRoss** [comment]
Thanks for your reply.

Steps to reproduce:
1. Make a simple react project to act as a ui component library.
2. Build that library using tsup with the following files: [package.json](https://gist.github.com/TheMikeyRoss/dd158eb584b911204c1d9351e6ccd5b7#file-package-json) and [tsconfig.json](https://gist.github.com/TheMikeyRoss/dd158eb584b911204c1d9351e6ccd5b7#file-tsconfig-json) and [tsup.config.js](https://gist.github.com/TheMikeyRoss/dd158eb584b911204c1d9351e6ccd5b7#file-tsup-config-js)
3. Create a new next.js app
4. Import that package into and you should see the same error

**Comment by TheMikeyRoss** [comment]
Yes,

1. Make a new next.js app (pages router)
2. Add [`@sikka/hawa`](https://github.com/sikka-software/Hawa) to it
3. Import the [DayPicker](https://storybook.hawa.style/?path=/story/elements-datepicker--default) to it
4. Make sure to import `import "@sikka/hawa/dist/style.css"` to `_app.tsx`
5. Now try to use the `DatePicker` component anywhere and you should see the same error


I will try to make a stackblitz reproduction

**Comment by TheMikeyRoss** [comment]
# Stackblitz Reproduction

https://stackblitz.com/edit/nextjs-8bsfgq?file=pages%2Findex.js

**Comment by TheMikeyRoss** [comment]
Not sure if it's the way `@sikka/hawa` is bundled by tsup:
https://github.com/sikka-software/Hawa/blob/946889690fbdd0a0cef1f4f1c4eaa92db4869568/packages/components/tsup.config.js#L28-L47

or if it's the pacakge.json of `@sikka/hawa`:
https://github.com/sikka-software/Hawa/blob/main/package.json

**Comment by gpbl** [comment]
> sikka-software/Hawa@`9468896`/packages/components/tsup.config.js#L28-L47

A workaround there _could_ be to use `esm` before `cjs`:

https://github.com/sikka-software/Hawa/blob/946889690fbdd0a0cef1f4f1c4eaa92db4869568/packages/components/tsup.config.js#L37

I am not sure why cjs is not working there, I'll try to fix it.

**Comment by zaaakher** [comment]
> A workaround there could be to use esm before cjs:

I just tried that but unfortunately we're still getting the same error

**Comment by zaaakher** [comment]
I downgraded `react-day-picker` to v8.10.1 in `@sikka/hawa@0.43.0` upward in https://github.com/sikka-software/Hawa/commit/71d696dae95042aafd8905026363a955a6740cd6

**Comment by gpbl** [comment]
Thanks @zaaakher for the follow--back. This with cis vs esm is actually an issue I have since long time when publishing on npm. 

Somebody could give a look to what is wrong in the [package.json](https://github.com/gpbl/react-day-picker/blob/114f087185d320e25f2c83e849955c2ed0175f6d/package.json)? 

- Consider https://github.com/gpbl/react-day-picker/pull/2230 by @ArthurGoupil that may have introduced this problem.
- Should I remove cjs completely? Why it is still needed?

**Comment by strmer15** [comment]
One other idea here: add a `package.json` file to the `dist/cjs` folder that says

```json
{
  "type": "commonjs"
}
```

and Node / bundlers will then use the CommonJS module loader to read the files.

https://webpack.js.org/guides/ecma-script-modules/#flagging-modules-as-esm

**Comment by TheMikeyRoss** [comment]
@gpbl is it published to npm? in 9.0.0-rc.6 ?

**Comment by gpbl** [comment]
Thanks @strmer15! [The fix](https://github.com/gpbl/react-day-picker/pull/2330) - touching a package.json in dist/cjs - should work also for `@sikka/hawa`

@TheMikeyRoss @zaaakher v9.0.6 should be published including the fix. Hopefully it works: I appreciate your feedback, thanks.

**Comment by zaaakher** [comment]
Works like a charm, thanks @gpbl @strmer15 👍
