### ISSUE TITLE
DayClick changes monthView to initial month

### ISSUE THREAD

**Issue by janrop** [gpbl/react-day-picker#232]
Selecting a day returns the Daypicker to the initial month view.

Happens even with the [Basic-Example](http://react-day-picker.js.org/Basic.html).

Is the default behaviour not to stay on the selected month?

**Comment by gpbl** [comment]
It should not, see [this example](http://react-day-picker.js.org/examples/?selectable). Are you using [initialMonth]? Maybe you are seeing this: https://github.com/gpbl/react-day-picker/issues/169

**Comment by janrop** [comment]
Ah yes, I have to update the initalMonth state, too. Thank you
