### ISSUE TITLE
custom style to selected days for Range of Days - click

### ISSUE THREAD

**Issue by mulmulovich** [gpbl/react-day-picker#234]
looking at the Days – mouse enter example, I can see that you are using class `DayPicker-Day--from` and `DayPicker-Day--to` in to give some yellow indication.
how can i give different style when selecting range **on click**? i cant see any class or attribute indicate the "from" and "to" selected date

please assist

and thanks for the great component!

**Comment by gpbl** [comment]
@mulmulovich the part that is setting the `--from` `--to` CSS `modifiers` are [these lines](https://github.com/gpbl/react-day-picker/blob/master/examples/src/examples/RangeAdvanced.js#L86-L89).

**Comment by mulmulovich** [comment]
You are the best!
