### ISSUE TITLE
Code example from docs is broken

### ISSUE THREAD

**Issue by LWJerri** [gpbl/react-day-picker#2342]
## Expected Behavior

All examples in docs must work by copy-paste without any changes.

## Actual Behavior

All (maybe) code examples from the `https://daypicker.dev/docs/styling#custom-class-names` page are broken or outdated.

## Screenshots

![image](https://github.com/user-attachments/assets/7ff0d5f8-f011-4c21-b190-04ed9143c2c2)

![image](https://github.com/user-attachments/assets/5399dedc-4865-4b9b-b502-4540ab869ccf)

**Comment by gpbl** [comment]
Thanks for your report - in the examples we were indeed using `calendar` instead of `root` as class name. I'm fixing this in https://github.com/gpbl/react-day-picker/pull/2347.
