### ISSUE TITLE
Using partial `locale`

### ISSUE THREAD

**Issue by LWJerri** [gpbl/react-day-picker#2345]
## Code 

```tsx
import { DayPicker } from "react-day-picker";

export function Start() {
  return (
    <DayPicker
      mode="range"
      locale={{ code: "ru" }}
      weekStartsOn={1}
      max={7}
      selected={selectedDate}
      onSelect={handleClickOnDate}
    />
  );
}
```

## Expected Behavior

Property `locale` must have all fields as optional.

## Actual Behavior

Can't just change localization in `locale`.

## Screenshots

![image](https://github.com/user-attachments/assets/259852ab-5d4d-42d3-8214-d3ab8ff8de71)

**Comment by gpbl** [comment]
@LWJerri interesting, I see the reason of passing a partial locale there.
