### ISSUE TITLE
Range mode has its own internal state and does not respect the controlled state

### ISSUE THREAD

**Issue by matheusmb** [gpbl/react-day-picker#2362]
## Code 
```tsx
import { useState } from 'react';

import { DateRange, DayPicker } from 'react-day-picker';

export function ControlledCalendar() {
  const [selected, setSelected] = useState<DateRange | undefined>();

  return (
    <DayPicker
      mode="range"
      selected={selected}
      onSelect={(selected) => {
        // setSelected(selected);
      }}
    />
  );
}
```

## Expected Behavior

Since the component is being used in "controlled" mode, it should use the state passed via "selected" prop. In the example above, the selected state is purposely not updated. It was expected that the calendar would not work, since the selected values aren't being updated.

I was trying to implement a behavior where if the range is already selected, and the user click on a new day, the range is reset:

```tsx
import { useState } from 'react';

import { DateRange, DayPicker } from 'react-day-picker';

export function ControlledCalendar() {
  const [selected, setSelected] = useState<DateRange | undefined>();

  function handleOnSelect(range: DateRange, triggerDate: Date) {
    if (selected?.from && selected?.to) {
      setSelected({
        from: triggerDate,
        to: undefined,
      });
      return;
    }
    setSelected(selected);
  }

  return <DayPicker mode="range" required selected={selected} onSelect={handleOnSelect} />;
}
```

Since the internal state is updated via useEffect, it causes a small flicker. The sequence of events is:
User click -> internal range state updated -> onSelect callback -> external state updated (range reset) -> internal state is updated via useEffect due external state change.

## Actual Behavior
 The calendar has its [own internal state](https://github.com/gpbl/react-day-picker/blob/0be591716dfb87de4e52ae422fc568c12a1d65e0/src/selection/useRange.tsx#L26-L28). The external state is updated via [useEffect](https://github.com/gpbl/react-day-picker/blob/0be591716dfb87de4e52ae422fc568c12a1d65e0/src/selection/useRange.tsx#L31-L33).

[CodeSandbox](https://codesandbox.io/p/sandbox/react-daypicker-57s7tx?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzit2e2y00063p86ofn14glm%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzit2e2y00023p86w8dmz24n%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzit2e2y00033p867nwwv2ig%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzit2e2y00053p86r8y4h04g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzit2e2y00023p86w8dmz24n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzit2e2y00013p86agqx7df8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzit2e2y00023p86w8dmz24n%2522%252C%2522activeTabId%2522%253A%2522clzit2e2y00013p86agqx7df8%2522%257D%252C%2522clzit2e2y00053p86r8y4h04g%2522%253A%257B%2522id%2522%253A%2522clzit2e2y00053p86r8y4h04g%2522%252C%2522activeTabId%2522%253A%2522clzmrzvy600153p84gx6r93dx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzit2e2y00043p864iahluk0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzmrzvy600153p84gx6r93dx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzit2e2y00033p867nwwv2ig%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzit2e2y00033p867nwwv2ig%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

## Video

https://github.com/user-attachments/assets/9aebcd67-2281-48da-8894-493ee7e08e82

PS: I throttled the CPU in 6x to make it more noticeable

**Comment by dartess** [comment]
With a single value there is the same problem - if I have a fixed selected value and do not want to change it, version 9 still allows me to pick any day.

**Comment by gpbl** [comment]
thanks @matheusmb for your detailed report ! you are right the controlled vs uncontrolled state isn't the ideal here. 

The code should read something like:

```
const handleSelect = (value: string) => {
    if (onSelect) {
      onSelect(value); // If the component is controlled, trigger the onSelect callback
    } else {
      setInternalSelected(value); // If the component is uncontrolled, update the internal state
    }
  };
```

**Comment by matheusmb** [comment]
Hey @gpbl,sure thing! I like the way Chakra-UI implemented it, it might be useful to take a look at: https://v2.chakra-ui.com/docs/hooks/use-controllable

**Comment by gpbl** [comment]
Hey this is more difficult than I thought. Please have patience...

**Comment by gpbl** [comment]
@matheusmb to help - could you create a (failing) test case, reproducing the issue? 🙏🏽
