### ISSUE TITLE
Pass modifiers to renderDay

### ISSUE THREAD

**Issue by davincho** [gpbl/react-day-picker#237]
I would need access to `modifiers` within the `renderDay` callback. What's about passing not only `day` but also `dayModifers` to the callback (see https://github.com/gpbl/react-day-picker/blob/b5170a47afb5f8fbdeeb387636b9f4c899ce1f4a/src/DayPicker.js#L412)

Before: `{this.props.renderDay(day)}`
After: `{this.props.renderDay(day, dayModifiers)}`

**Comment by jirikolarik** [comment]
I'd like to see this feature as well. If you would like to render specific based on day type.

**Comment by gpbl** [comment]
I'd like first to understand the use case, as I've in mind [a new feature](https://github.com/gpbl/react-day-picker/issues/181#issuecomment-225684329) that may help in this direction :)

The modifiers are intended to add a CSS classname to the day cell. What is your case @davincho, @jirikolarik ?

**Comment by jirikolarik** [comment]
If we have `dayModifiers` passed to renderDay object, we know how that date differentiate between others. For example, if the date is "occupied", we can currently make it grey, green or yellow, but with this information in `renderDay` method we could also render different content as the actual word "occupied" without checking if the date is occupied again inside the method.

**Comment by gpbl** [comment]
Thanks @jirikolarik for the feedback! As this is a simple to implement, it's going to be added in the next minor release!

**Comment by davincho** [comment]
Yes having the same use cases as @jirikolarik described. Looking forward for next minor release!

**Comment by gpbl** [comment]
Released as `v4.0`. It is a major release because of some [minor breaking changes](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md) – it should be easy to upgrade!
