### ISSUE TITLE
Customise month and year selection in day picker

### ISSUE THREAD

**Issue by princeseth** [gpbl/react-day-picker#2375]
### Discussed in https://github.com/gpbl/react-day-picker/discussions/2355

<div type='discussions-op-text'>

<sup>Originally posted by **princeseth** August  5, 2024</sup>
Hello, Is there any way we can customise month and year selection similar to below. Thanks

![image](https://github.com/user-attachments/assets/d3d2da5a-d248-4720-9187-682fb5a502fb)

![image](https://github.com/user-attachments/assets/bef8af52-fd88-4aa7-9b43-b7cdb04ef5ee)
</div>

**Comment by gpbl** [comment]
See duplicated discussion in https://github.com/gpbl/react-day-picker/discussions/2355
