### ISSUE TITLE
Small bug in Input Field with Overlay Example

### ISSUE THREAD

**Issue by Pongetti** [gpbl/react-day-picker#239]
Just noticed a small issue with the "Input Field with Overlay" example and thought I'd point it out.

Open the dropdown, then change the day picker to another month and select a date.  Open the dropdown a second time.  The daypicker will be back on today's month instead of where you left off.

This is because you're mounting/unmounting the overlay to show/hide it, so the daypicker loses its state.  Probably best to use the style attribute to hide/unhide the overlay instead.

**Comment by timcan** [comment]
+1

I'm noticing this when using it with basic usage example:

```
<DayPicker onDayClick={this.handleDayClick} selectedDays={this.isDaySelected} enableOutsideDays={true}/>
```

Would prefer the calendar to show the selected day/month/year which is confirmed by the call to isDaySelected().

**Comment by gpbl** [comment]
Hi thanks for the feedback! Using the `initialMonth` prop should resolve the issue. I can't work on it these weeks - would you send a PR?

@Pongetti I'm for unmounting the component, to reduce the resource usage.

**Comment by timcan** [comment]
Confirmed .. the `initialMonth` prop did the trick:

```
<DayPicker className="pure-u-1-3" onDayClick={this.handleDayClick} initialMonth={this.state.selectedDay} selectedDays={this.isDaySelected} enableOutsideDays={true}/>
```

Thank you. I'll try to see if I can provide a PR.
