### ISSUE TITLE
fromMonth not working as expected

### ISSUE THREAD

**Issue by nealoke** [gpbl/react-day-picker#241]
My code below is not influencing the fromMonth in any way. Is there a bug or am I doing it wrong?

**Render function**
```
	render() {
		const month = new Date();
		month.setMonth(month.getMonth() - 10);

		return (
			<DayPicker
				firstDayOfWeek={ 1 }
				onDayClick={ this.handleDayClick }
				selectedDays={ day => DateUtils.isDayInRange(day, { from: this.state.from, to: this.state.to }) }
				disabledDays={this.disabledDays}
				enableOutsideDays={true}
				fixedWeeks={true}
				numberOfMonths={this.props.numberOfMonths}
				toMonth={this.props.disableFuture ? new Date() : null}
				fromMonth={month}
			/>
		);
	}
```

**Comment by nealoke** [comment]
For further information, when you navigate back and forth it works as expected 

**Wrong / unexpected**
[Initial render](http://imagebucket.net/iewx00t1jzhg/initial_render.png)

**Correct / expected**
[After hitting the previous button](http://imagebucket.net/te7o7a1ho79t/after.png)

**Comment by emwee** [comment]
👍

**Comment by lsanwick** [comment]
@nealoke, you should specify `initialMonth={month}` as well.  It defaults to the current month, but I'd argue that the default should be changed to the `fromMonth`

**Comment by gpbl** [comment]
Thanks for the suggestion @lsanwick! 

I believe the calendar should always show the current month if the `initialMonth` is not specified, so to prevent confusion about its default behavior. E.g.: the current month is after the `toMonth`, should it display the `fromMonth` or the `toMonth`? I'd let the developer choose the behavior.

I'd add a note to the docs 👍

**Comment by nealoke** [comment]
@lsanwick using the `initialMonth` totally fixed my issue here.  

@gpbl best to let the developer choose the behavior 👍

**Comment by nealoke** [comment]
@gpbl @lsanwick oh, I just saw that when using the `initialMonth` is causing the datepicker to stay fixed on the month. The arrows to navigate between months are showing but clicking them has no effect.

**Comment by gpbl** [comment]
@nealoke interesting – how does your code differs from http://react-day-picker.js.org/examples/?restricted ?

**Comment by nealoke** [comment]
@gpbl not much from what I can see :(

```
const month = new Date();
const initialMonth = disablePast ? new Date() : new Date(month.setMonth(month.getMonth() - 1));

<DayPicker
	fromMonth={disablePast ? new Date() : null}
	initialMonth={initialMonth}
	toMonth={disableFuture ? new Date() : null}
/>
```

**Comment by nealoke** [comment]
@gpbl Using this it works `initialMonth={disableFuture ? new Date() : undefined}`. But when using the `new Date(month.setMonth(month.getMonth() - 1)` it breaks.

**Comment by nealoke** [comment]
@gpbl I can't figure out what is going wrong here, as soon as I return anything in the initialMonth it doesn't allow any navigation of months. Code below for reference. 

Also using the example provided by you is not working if I copy the snippets covering the `fromMonth`, `toMonth` and `initialMonth`.

render() {
	const { type, disablePast, disableFuture } = this.props;
	const lastMonth = new moment().subtract(1, 'months').date(1);
	const initialMonth = disablePast ? new Date() : lastMonth.toDate();

```
render() {
	const { type, disablePast, disableFuture } = this.props;
	const lastMonth = new moment().subtract(1, 'months').date(1);
	const initialMonth = disablePast ? new Date() : lastMonth.toDate();

	return (
		<div className='DATEPICKER_wrapper'>
			<div className='DATEPICKER_predefined'>
				{this._renderPrefinedPeriods()}
			</div>

			<DayPicker
				className='DATEPICKER_picker'
				firstDayOfWeek={ 1 }
				onDayClick={ this.handleDayClick }
				onDayMouseEnter={ this.handleDayMouseEnter }
				selectedDays={ day => DateUtils.isDayInRange(day, { from: this.state.from, to: this.state.to }) }
				disabledDays={this.disabledDays}
				enableOutsideDays={true}
				fixedWeeks={true}
				numberOfMonths={type == 'range' ? 2 : 1}
				initialMonth={initialMonth}
				fromMonth={disablePast ? new Date() : null}
				toMonth={disableFuture ? new Date() : null}
				modifiers={{
					firstDay: day => DateUtils.isSameDay(day, this.state.from),
					lastDay: day => DateUtils.isSameDay(day, this.state.to)
				}}
			/>
		</div>
	);
}
```

react-day-picker v 3.1.1

**Comment by gpbl** [comment]
> Also using the example provided by you is not working if I copy the snippets covering the fromMonth, toMonth and initialMonth.

@nealoke actually this code is working for me:

```js
import React from 'react';
import DayPicker, { DateUtils } from 'react-day-picker';
import moment from 'moment';

import 'react-day-picker/lib/style.css';

export default function Restricted() {
  const type = 'range';
  const disablePast = false;
  const disableFuture = true;

  const lastMonth = new moment().subtract(1, 'months').date(1);
  const initialMonth = disablePast ? new Date() : lastMonth.toDate();

  return (
    <DayPicker
      firstDayOfWeek={ 1 }
      enableOutsideDays
      fixedWeeks
      numberOfMonths={ type === 'range' ? 2 : 1 }
      initialMonth={ initialMonth }
      fromMonth={ disablePast ? new Date() : null }
      toMonth={ disableFuture ? new Date() : null }
    />
  );
}
```

does the console show an error when clicking on the navigation arrows?

**Comment by nealoke** [comment]
@gpbl how weird. I also checked the props but they seem correct. The console is not giving any error on render nor when clicking the navigation arrows. Can it be that I have a different version of the package?

**Comment by gpbl** [comment]
@nealoke No I don't see how older versions would affect the issue. 

My guess is that the container component is re-rendering again the calendar when changing the month - hence reinitializing the calendar when to its initial month. Could you investigate better the props passed down to it from the web inspector ? Or try to move it up the hierarchy to isolate the problem?

**Comment by gpbl** [comment]
Maybe these are related? https://github.com/gpbl/react-day-picker/issues/169 https://github.com/gpbl/react-day-picker/issues/232

**Comment by nealoke** [comment]
@gpbl further looking at the issue. Indeed the component re-renders when the date changes, otherwise the from and to don't get visualised on the datepicker right? :( Might be handy to integrate the `initialMonth` only when the component mounts?

**Comment by nealoke** [comment]
@gpbl i'm not sure why it is so difficult to achieve this :( might be that I'm thinking wrong here but don't you always have a wrapping component for the datepicker? 

I've tried with reseting the `initialMonth` with each render (as suggested by [#232](https://github.com/gpbl/react-day-picker/issues/232)) but this also means that when a user clicks on a date from the month on the left, that it moves it automatically to that month which is a no go for me, simply because the datepicker is used for a range of dates.

I'm basically out of ideas on how to solve this issue. Thanks for your kind help though! Let me know if you have any ideas

**Comment by gpbl** [comment]
@nealoke maybe you have been hit by [this behavior](https://github.com/gpbl/react-day-picker/issues/169) which has been fixed in `v4`. 
The latest version has [few minor breaking changes](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md#v400-2017-02-10) so it should be easy to upgrade. 
Could you please upgrade and report back if your issue has been resolved? Thanks!

**Comment by nealoke** [comment]
@gpbl upgrading seems to have resolved the issue! Thank you very much for the effort you've put in this issue (and component)! 👍

**Comment by gpbl** [comment]
Thanks to you for the patience 👌🏽
