### ISSUE TITLE
Using defaultMonth in UTC mode adds an incorrect date line and a wrong style

### ISSUE THREAD

**Issue by DarXnake** [gpbl/react-day-picker#2438]
Hi all, and thank you for this awesome tool !

I found a bug I'd like to share with you.

## Code 

```tsx
import { DayPicker } from "react-day-picker";
import "react-day-picker/style.css";

export default function App() {
  return (
    <DayPicker
      showOutsideDays
      defaultMonth={new Date(2024, 8)}
      mode="range"
      selected={{ from: new Date(2024, 8, 16), to: new Date(2024, 8, 20) }}
    />
  );
}
```

## Expected Behavior

![image](https://github.com/user-attachments/assets/bba6876d-9690-44be-96a7-c9524ded8cbc)

DayPicker should display a correct calendar on september 2024

## Actual Behavior

![image](https://github.com/user-attachments/assets/3f1ecb0e-e348-4c15-910c-6fd817db0ea1)

If you use react-day-picker in UTC mode with `react-day-picker/utc` while having the `defaultMonth` parameter filled, the day picker adds an incorrect first line on every month

Without `showOutsideDays`, this line still exists but the wrong day is hidden, resulting in an empty line

In addition to that, if you use the `selected` parameter with the `range` mode, the selected period's style is incorrect

Removing the `defaultMonth` parameter removes the wrong day line
Using the regular `react-day-picker` (non-UTC) solves both issues at once

## Exemple

[CodeSandbox](https://codesandbox.io/p/sandbox/react-day-picker-forked-nkvw6f?file=%2Fsrc%2FApp.tsx%3A1%2C1-6%2C2)

**Comment by gpbl** [comment]
Hi @DarXnake, thanks for your feedback! I _believe_ this happens when mixing up local date with the UTC date. Using `UTCDate` from `date-fns/utc` should fix it.

```diff
import { DayPicker } from "react-day-picker/utc";
import "react-day-picker/style.css";
+ import { UTCDate } from "@date-fns/utc";

export default function App() {
  return (
    <DayPicker
      showOutsideDays
-     defaultMonth={new Date(2024, 8)}
+     defaultMonth={new UTCDate(2024, 8)}
      mode="range"
      selected={{
-       from: new Date(2024, 8, 16),
+       from: new UTCDate(2024, 8, 16),
-       to: new Date(2024, 8, 20),
+       to: new UTCDate(2024, 8, 20),
      }}
    />
  );
}
```

If this is the case, we should definitely add a note to the documentation. 

Could you please verify if it fixes the issue for you?

**Comment by gpbl** [comment]
I've updated the docs at https://daypicker.dev/docs/localization#utc-dates

**Comment by DarXnake** [comment]
Your fix definitely resolves these issues. Thank you very much!
