### ISSUE TITLE
Use `initialMonth` in <input/> demo

### ISSUE THREAD

**Issue by halt-hammerzeit** [gpbl/react-day-picker#244]
Currently the input field overlay demo always opens on January even if a day from another month is selected
http://react-day-picker.js.org/examples/?overlay

I guess `initialMonth={this.state.selectedDay}` could be employed here.
At least it seems to work for me.
(I'm in the process building a custom component on top of your picker)

(also setting `zIndex: 1` in `overlayStyle` seems to help with positioning)

And also I enhanced input text clearing on it being invalid:

```js

  handleInputBlur() {
    ...

    // Let the `onChange` handler fire after this `onBlur`
    // in case when a user clicked a day in the calendar
    // and the `value` is still the old one.
    setTimeout(() => {
      // If an entered date isn't valid then clear the <input/> field
      const { value } = this.props;
      if (!value) {
        this.setState({ textValue: '' });
      }
    }, 0);
  }
```

**Comment by halt-hammerzeit** [comment]
In case you're interested, here's my final component:
https://github.com/halt-hammerzeit/webapp/blob/master/frontend/code/components/date%20picker.js

A bit of changes to your example and now it's fully working.
You could make it part of the library, I think, because everyone is looking for a collapsible date picker, not a static one.

Usage:
```js
<Date_picker
	value={this.state.selectedDay}
	onChange={selectedDay => this.setState({ selectedDay })}
	format="DD/MM/YYYY"/>
```

**Comment by gpbl** [comment]
Thanks this would fit well for https://github.com/gpbl/react-day-picker/issues/213
