### ISSUE TITLE
'IconLeft' does not exist in type 'Partial<CustomComponents>'

### ISSUE THREAD

**Issue by jpainam** [gpbl/react-day-picker#2451]
Thanks for taking the time for writing this bug report.

## Code 
From `shadcn/ui`

```tsx
"use client";

import * as React from "react";
import { ChevronLeftIcon, ChevronRightIcon } from "@radix-ui/react-icons";
import { DayPicker } from "react-day-picker";

import { cn } from "@repo/ui";

import { buttonVariants } from "./button";

export type CalendarProps = React.ComponentProps<typeof DayPicker>;

function Calendar({
  className,
  classNames,
  showOutsideDays = true,
  ...props
}: CalendarProps) {
  return (
    <DayPicker
      showOutsideDays={showOutsideDays}
      className={cn("p-3", className)}
      classNames={{
        months: "flex flex-col sm:flex-row space-y-4 sm:space-x-4 sm:space-y-0",
        month: "space-y-4",
        caption: "flex justify-center pt-1 relative items-center",
        caption_label: "text-sm font-medium",
        nav: "space-x-1 flex items-center",
        nav_button: cn(
          buttonVariants({ variant: "outline" }),
          "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100",
        ),
        nav_button_previous: "absolute left-1",
        nav_button_next: "absolute right-1",
        table: "w-full border-collapse space-y-1",
        head_row: "flex",
        head_cell:
          "text-muted-foreground rounded-md w-8 font-normal text-[0.8rem]",
        row: "flex w-full mt-2",
        cell: cn(
          "relative p-0 text-center text-sm focus-within:relative focus-within:z-20 [&:has([aria-selected])]:bg-accent [&:has([aria-selected].day-outside)]:bg-accent/50 [&:has([aria-selected].day-range-end)]:rounded-r-md",
          props.mode === "range"
            ? "[&:has(>.day-range-end)]:rounded-r-md [&:has(>.day-range-start)]:rounded-l-md first:[&:has([aria-selected])]:rounded-l-md last:[&:has([aria-selected])]:rounded-r-md"
            : "[&:has([aria-selected])]:rounded-md",
        ),
        day: cn(
          buttonVariants({ variant: "ghost" }),
          "h-8 w-8 p-0 font-normal aria-selected:opacity-100",
        ),
        day_range_start: "day-range-start",
        day_range_end: "day-range-end",
        day_selected:
          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
        day_today: "bg-accent text-accent-foreground",
        day_outside:
          "day-outside text-muted-foreground opacity-50  aria-selected:bg-accent/50 aria-selected:text-muted-foreground aria-selected:opacity-30",
        day_disabled: "text-muted-foreground opacity-50",
        day_range_middle:
          "aria-selected:bg-accent aria-selected:text-accent-foreground",
        day_hidden: "invisible",
        ...classNames,
      }}
      components={{
        IconLeft: ({ ...props }) => <ChevronLeftIcon className="h-4 w-4" />,
        IconRight: ({ ...props }) => <ChevronRightIcon className="h-4 w-4" />,
      }}
      {...props}
    />
  );
}
Calendar.displayName = "Calendar";

export { Calendar };

```

```tsx
import { DayPicker } from "react-day-picker";

export function Start() {
  return (
    <DayPicker  />
  );
}
```

## Expected Behavior

It was working before  i updated to `"react-day-picker": "9.0.9",`, i looked for the changelog, but couldn't see how to update my code.

## Actual Behavior

Describe what is actually happening.

## Screenshots

If applicable, add screenshots or GIFs to help explain your problem.

**Comment by shiedot** [comment]
+1

**Comment by dorukozerr** [comment]
+1

**Comment by linushahs** [comment]
Facing the same issue, there is a prop named "Chevron" but how do I add both ChevronLeft and ChevronRight icon?

**Comment by jpainam** [comment]
I found this. https://date-picker.luca-felix.com/ works great and is based on `v9`

**Comment by jpainam** [comment]
https://daypicker.dev/upgrading#7-update-your-custom-components

```tsx
  <DayPicker
    components={{
-     IconLeft: MyLeftIcon,
+     Chevron: (props) {
+        if (props.orientation === "left") {
+          return <MyLeftIcon {...props} />;
+        }
+       return <Chevron {...props} />;
+     }
  }}
  />
```

**Comment by agamycode** [comment]
## This works for me

``` tsx
'use client';

import * as React from 'react';
import { DayPicker } from 'react-day-picker';
import { ChevronLeftIcon, ChevronRightIcon } from '@radix-ui/react-icons';

import { cn } from '@/lib/utils';
import { buttonVariants } from '@/components/ui/button';

export type CalendarProps = React.ComponentProps<typeof DayPicker>;

function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {

  return (
    <DayPicker
      showOutsideDays={showOutsideDays}
      className={cn('p-3', className)}
      classNames={{
        months: 'flex flex-col relative',
        month_caption: 'flex justify-center h-7 mx-10 relative items-center',
        weekdays: 'flex flex-row',
        weekday: 'text-muted-foreground w-8 font-normal text-[0.8rem]',
        month: 'gap-y-4 overflow-x-hidden w-full',
        caption: 'flex justify-center pt-1 relative items-center',
        caption_label: 'text-sm font-medium truncate',
        button_next: cn(
          buttonVariants({
            variant: 'outline',
            className: 'absolute right-0 h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100',
          })
        ),
        button_previous: cn(
          buttonVariants({
            variant: 'outline',
            className: 'absolute left-0 h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100',
          })
        ),
        nav: 'flex items-start',
        month_grid: 'mt-4',
        week: 'flex w-full mt-2',
        day: 'p-0 size-8 text-sm flex-1 flex items-center justify-center has-[button]:hover:!bg-accent rounded-md has-[button]:hover:aria-selected:!bg-primary has-[button]:hover:text-accent-foreground has-[button]:hover:aria-selected:text-primary-foreground',
        day_button: cn(
          buttonVariants({ variant: 'ghost' }),
          'size-8 p-0 font-normal transition-none hover:bg-transparent hover:text-inherit aria-selected:opacity-100'
        ),
        range_start: 'day-range-start rounded-s-md',
        range_end: 'day-range-end rounded-e-md',
        selected:
          'bg-primary text-primary-foreground hover:!bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground',
        today: 'bg-accent text-accent-foreground',
        outside:
          'day-outside text-muted-foreground opacity-50 aria-selected:bg-accent/50 aria-selected:text-muted-foreground aria-selected:opacity-30',
        disabled: 'text-muted-foreground opacity-50',
        range_middle:
          'aria-selected:bg-accent hover:aria-selected:!bg-accent rounded-none aria-selected:text-accent-foreground hover:aria-selected:text-accent-foreground',
        hidden: 'invisible',
        ...classNames,
      }}
      components={{
        Chevron: ({ orientation }) => {
          const Icon = orientation === 'left' ? ChevronLeftIcon : ChevronRightIcon;
          return <Icon className='h-4 w-4' />;
        },
      }}
      {...props}
    />
  );
}
Calendar.displayName = 'Calendar';

export { Calendar };

```

**Comment by ShaquilleOatmeal4444** [comment]
> I found this. https://date-picker.luca-felix.com/ works great and is based on `v9`

This worked for me thank you @jpainam

**Comment by idugeni** [comment]
## Fixing Type Issues in `react-day-picker`

### Problem

When using `react-day-picker`, TypeScript throws an error related to unknown properties in `components`.

### Solution

Update your import statement and modify the `components` prop type.

### Changes

1. Update Import

**Before:**

```bash
import { DayPicker } from "react-day-picker"
```

**After:**

```
import { DayPicker, DayPickerProps } from "react-day-picker"
```

2. Fix `components` Prop

**Before:**

```
components={{
  IconLeft: ({ className, ...props }) => (
    <ChevronLeft className={cn("size-4", className)} {...props} />
  ),
  IconRight: ({ className, ...props }) => (
    <ChevronRight className={cn("size-4", className)} {...props} />
  ),
}}
```

**After:**

```
components={
  {
    IconLeft: ({
      className,
      ...props
    }: {
      className?: string
      props?: React.SVGProps<SVGSVGElement>
    }) => <ChevronLeft className={cn("size-4", className)} {...props} />,

    IconRight: ({
      className,
      ...props
    }: {
      className?: string
      props?: React.SVGProps<SVGSVGElement>
    }) => <ChevronRight className={cn("size-4", className)} {...props} />,
  } as unknown as Partial<DayPickerProps["components"]>
}
```

### Why This Works

- Added `DayPickerProps` to properly type `components`.
- Explicitly defined `className` and `props` types to match expected properties.
- Used type assertion (`as unknown as Partial<DayPickerProps["components"]>`) to bypass strict TypeScript checks.

Now, your react-day-picker component should work without type errors! 🎉

**Comment by Nattie-Nkosi** [comment]
> ## This works for me
> 'use client';
> 
> import * as React from 'react';
> import { DayPicker } from 'react-day-picker';
> import { ChevronLeftIcon, ChevronRightIcon } from '@radix-ui/react-icons';
> 
> import { cn } from '@/lib/utils';
> import { buttonVariants } from '@/components/ui/button';
> 
> export type CalendarProps = React.ComponentProps<typeof DayPicker>;
> 
> function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
> 
>   return (
>     <DayPicker
>       showOutsideDays={showOutsideDays}
>       className={cn('p-3', className)}
>       classNames={{
>         months: 'flex flex-col relative',
>         month_caption: 'flex justify-center h-7 mx-10 relative items-center',
>         weekdays: 'flex flex-row',
>         weekday: 'text-muted-foreground w-8 font-normal text-[0.8rem]',
>         month: 'gap-y-4 overflow-x-hidden w-full',
>         caption: 'flex justify-center pt-1 relative items-center',
>         caption_label: 'text-sm font-medium truncate',
>         button_next: cn(
>           buttonVariants({
>             variant: 'outline',
>             className: 'absolute right-0 h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100',
>           })
>         ),
>         button_previous: cn(
>           buttonVariants({
>             variant: 'outline',
>             className: 'absolute left-0 h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100',
>           })
>         ),
>         nav: 'flex items-start',
>         month_grid: 'mt-4',
>         week: 'flex w-full mt-2',
>         day: 'p-0 size-8 text-sm flex-1 flex items-center justify-center has-[button]:hover:!bg-accent rounded-md has-[button]:hover:aria-selected:!bg-primary has-[button]:hover:text-accent-foreground has-[button]:hover:aria-selected:text-primary-foreground',
>         day_button: cn(
>           buttonVariants({ variant: 'ghost' }),
>           'size-8 p-0 font-normal transition-none hover:bg-transparent hover:text-inherit aria-selected:opacity-100'
>         ),
>         range_start: 'day-range-start rounded-s-md',
>         range_end: 'day-range-end rounded-e-md',
>         selected:
>           'bg-primary text-primary-foreground hover:!bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground',
>         today: 'bg-accent text-accent-foreground',
>         outside:
>           'day-outside text-muted-foreground opacity-50 aria-selected:bg-accent/50 aria-selected:text-muted-foreground aria-selected:opacity-30',
>         disabled: 'text-muted-foreground opacity-50',
>         range_middle:
>           'aria-selected:bg-accent hover:aria-selected:!bg-accent rounded-none aria-selected:text-accent-foreground hover:aria-selected:text-accent-foreground',
>         hidden: 'invisible',
>         ...classNames,
>       }}
>       components={{
>         Chevron: ({ orientation }) => {
>           const Icon = orientation === 'left' ? ChevronLeftIcon : ChevronRightIcon;
>           return <Icon className='h-4 w-4' />;
>         },
>       }}
>       {...props}
>     />
>   );
> }
> Calendar.displayName = 'Calendar';
> 
> export { Calendar };

Thank you, this worked for me

**Comment by samseen** [comment]
> ## Fixing Type Issues in `react-day-picker`
> ### Problem
> When using `react-day-picker`, TypeScript throws an error related to unknown properties in `components`.
> 
> ### Solution
> Update your import statement and modify the `components` prop type.
> 
> ### Changes
> 1. Update Import
> 
> **Before:**
> 
> import { DayPicker } from "react-day-picker"
> **After:**
> 
> ```
> import { DayPicker, DayPickerProps } from "react-day-picker"
> ```
> 
> 2. Fix `components` Prop
> 
> **Before:**
> 
> ```
> components={{
>   IconLeft: ({ className, ...props }) => (
>     <ChevronLeft className={cn("size-4", className)} {...props} />
>   ),
>   IconRight: ({ className, ...props }) => (
>     <ChevronRight className={cn("size-4", className)} {...props} />
>   ),
> }}
> ```
> 
> **After:**
> 
> ```
> components={
>   {
>     IconLeft: ({
>       className,
>       ...props
>     }: {
>       className?: string
>       props?: React.SVGProps<SVGSVGElement>
>     }) => <ChevronLeft className={cn("size-4", className)} {...props} />,
> 
>     IconRight: ({
>       className,
>       ...props
>     }: {
>       className?: string
>       props?: React.SVGProps<SVGSVGElement>
>     }) => <ChevronRight className={cn("size-4", className)} {...props} />,
>   } as unknown as Partial<DayPickerProps["components"]>
> }
> ```
> 
> ### Why This Works
> * Added `DayPickerProps` to properly type `components`.
> * Explicitly defined `className` and `props` types to match expected properties.
> * Used type assertion (`as unknown as Partial<DayPickerProps["components"]>`) to bypass strict TypeScript checks.
> 
> Now, your react-day-picker component should work without type errors! 🎉

This worked for me.
