### ISSUE TITLE
Support locales like Arabic with different representation of numerals

### ISSUE THREAD

**Issue by rucsin** [gpbl/react-day-picker#246]
parseInt('12').toLocaleString('ar')
=>"١٢"

Can this picker also render numerals in such locales?

**Comment by gpbl** [comment]
Sure! Try with the `renderDay` prop, something like `day => day.getDate().toLocaleString('ar')`.

**Comment by rucsin** [comment]
The picker renders correctly with arabic numerals except the year which still appears e..g, 2017 in the caption when locale is arabic.

**Comment by gpbl** [comment]
@rucsin use the `captionElement` prop to customize the caption element.

**Comment by rucsin** [comment]
Now I can customize the year using captionElement prop.
When I use initialMonth={this.state.selectedDay}, then changing caption month or year does not respond. What should I use to make year/month navigation work correctly and also that correct month/year is shown for a valid date input
