### ISSUE TITLE
React DayPicker 9.0.0+ Not Working with date-fns 4.1.0 and 2.30.0

### ISSUE THREAD

**Issue by s-babaeizadeh** [gpbl/react-day-picker#2465]
I am attempting to use React DayPicker version 9.0.0 or higher, but it seems to be incompatible with date-fns version 4.1.0. Additionally, I have found that the mentioned versions of DayPicker are also not compatible with date-fns version 2.30.0

**Comment by jacksonmccoy11** [comment]
I'm still seeing this issue in v9.1.3 with date-fns v4.1.0.
<img width="584" alt="image" src="https://github.com/user-attachments/assets/32779acf-166c-47cb-80fb-4a261a0b3077">

**Comment by gpbl** [comment]
@jacksonmccoy11, interesting observation—it doesn’t seem to be related to date-fns@4. Could you please open a new issue with steps to reproduce the error? Thanks!
