### ISSUE TITLE
Uncaught ReferenceError: DateUtils is not defined

### ISSUE THREAD

**Issue by PawelGIX** [gpbl/react-day-picker#248]
In bower and unpkg version

**Comment by gpbl** [comment]
Thanks, going to test/fix it soon!

**Comment by gpbl** [comment]
@PawelGIX to use DateUtils via bower or unpkg you have to call `DayPicker.DateUtils` (`DateUtils` is not exposed a global var).

Example: 
https://jsfiddle.net/3nhgppxb/
