### ISSUE TITLE
Not compatible with preact/preact-compat

### ISSUE THREAD

**Issue by computapars** [gpbl/react-day-picker#249]
I'm using the basic usage example and can't get my DayPicker to render. This error keeps coming up in the DayPicker bundle:
```
Uncaught TypeError: f is not a function
```

**Comment by gpbl** [comment]
I never used preact. As the error notifies a compiled function name, it is hard to tell where this problem is happening. Could you fork this repo and run the examples using preact instead of react, or even better change the tests to use preact? This would help to identify the issue.

**Comment by gpbl** [comment]
Not thinking to add preact support soon. If someone is interested, can open a PR to help 😊

**Comment by computapars** [comment]
This only happened when preact/devtools was imported into the app. Otherwise, there were no issues when combining with preact and preact-compat.
https://github.com/developit/preact/tree/master/devtools

**Comment by gpbl** [comment]
Nice! Thanks for the follow-up!
