### ISSUE TITLE
tsconfig-base.json missing in node_modules

### ISSUE THREAD

**Issue by luucvanderzee** [gpbl/react-day-picker#2491]
Really sorry for not providing a reproducible example, but I didn't manage to reproduce it in any way outside of the codebase I use at work. But this might be a common issue with a potentially easy solution, so I still wanted to create this issue.

We use a custom (but not that custom) webpack configuration in combination with `esbuild`. Basically, from version 9, `react-day-picker` does not work with our setup. Version 8 works fine. When I have `react-day-picker` installed and I actually import it, and then try to run the dev server / build the app I get the following error:

```
Error: File './tsconfig-base.json' not found.
```

After a bit of experimentation, I found out that this error is coming from the `node_modules/react-day-picker` folder, where it's referenced by `tsconfig.json`. The file seems to be missing: 

<img width="213" alt="Screenshot 2024-09-26 at 17 53 37" src="https://github.com/user-attachments/assets/e623b782-1bfa-47b1-8825-180e569fffcc">

By manually copying the file (https://github.com/gpbl/react-day-picker/blob/main/tsconfig-base.json) and putting it in my `node_modules/react-day-picker` folder, the problem disappears.

Would it be possible to always include this `tsconfig-base.json` file in the build, so that it ends up in my `node_modules` and I don't get this error?

Thank you and again sorry for the chaotic bug report.

**Comment by gpbl** [comment]
@luucvanderzee Thanks for the report, indeed the tsconfig-base.json should be there. We need to add it to the `files` entry in `package.json`:

https://github.com/gpbl/react-day-picker/blob/2f8fc6311e72c30a651966b1e27b0147c40729b4/package.json#L144

Would you open a PR with it included? 🙏🏽

**Comment by luucvanderzee** [comment]
Done! https://github.com/gpbl/react-day-picker/pull/2492/files
