### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by alexkendall** [gpbl/react-day-picker#251]
The following is displayed when I render the day picker component. Not sure why this is occurring.
![screen shot 2017-02-03 at 3 09 55 pm](https://cloud.githubusercontent.com/assets/8241866/22606758/0777e32a-ea23-11e6-9443-b7d8addebff4.png)
[*/](url)

**Comment by zwallacedev** [comment]
I manually placed the .css file in my project, and had to import it in my .jsx file that was using the react-day-picker.

**Comment by gpbl** [comment]
It looks like the style is not loaded. Make sure the CSS file is actually imported by looking to the outputted source in the browser.
