### ISSUE TITLE
Dont work showOutsideDays={false}

### ISSUE THREAD

**Issue by snakiso** [gpbl/react-day-picker#2510]
import React, { useState } from 'react';
import { DayPicker } from 'react-day-picker';

export const Calendar = () => {
  const today = new Date()
  const [selected, setSelected] = useState<Date[] | undefined>([today]);
  return (
    <DayPicker
      showOutsideDays={false}
      defaultMonth={today}
      numberOfMonths={2}
      mode="multiple"
      min={1} max={5}
      selected={selected}
      onSelect={setSelected}
      classNames={{
        today: 'bg-cGreen rounded-md',
        selected: 'bg-cGreen rounded-md',
        root: 'bg-cBlack text-cWhite w-fit relative  overflow-scroll',
        day: 'w-4 h-4 text-center justify-center',
        weekdays: 'fixed top-7 border-b-2 border-white w-full ',
        weekday: 'w-4 h-4 bg-cBlack',
        month: 'mt-2',
      }}
    />
  );
};
![photo_2024-10-04_12-21-01](https://github.com/user-attachments/assets/c6fe4b13-ecfc-45b5-a221-1013d7e9a780)

**Comment by arnediar** [comment]
Did you find out why this happens?
