### ISSUE TITLE
Using `startMonth` and `endMonth` can make dropdown unusable

### ISSUE THREAD

**Issue by SudoCat** [gpbl/react-day-picker#2549]
When using `captionLayout="dropdown"`, months and years outside of the range are disabled. This prevents the user from using the dropdowns to select a valid month and year, if the currently selected month or year does not exist in the target month or year.

## Code 

```tsx
import { DayPicker } from "react-day-picker";

export function Start() {
  const from = new Date("2024-10-01");
  const to = new Date("2025-02-01");
  return (
    <DayPicker startMonth={from} endMonth={to} captionLayout="dropdown"  />
  );
}
```

## Expected Behavior

I should be able to select a date in the following year using only the dropdowns.

Ideally, if I select "2025" while in "November 2024", it should automatically change the month accordingly.

## Actual Behavior

It is impossible to select a different year if the current month is not available in that year.

## Screenshots

![Screen Recording 2024-10-17 at 17 43 34](https://github.com/user-attachments/assets/8cb836d4-75a9-4f71-bea6-b38614d3b81c)

**Comment by gpbl** [comment]
Hey, thanks for the report.

I was expecting this to happen when implementing the feature. Is there a way to prevent it while keeping the not navigable months out from the options? 🤔 

If it’s too difficult to find a solution, I’d prefer to remove this feature and keep all the options enabled. However, what should happen if the months shouldn’t be navigated to?

**Comment by SudoCat** [comment]
I think with the current UI, the best answer is to never disable the years, and when the user selects a year, if the current month is not available in that year, then change the month to the closest month within the new year.

However I don't think removing the disabled behaviour would be a bad answer either.

**Comment by rodgobbi** [comment]
Hi @gpbl, have you started working on this issue?  
If not, I can work on it, let me know if this would help, I already have some experience with `startMonth` and `endMonth`.

**Comment by gpbl** [comment]
@rodgobbi, thanks for asking. I could investigate the issue a little bit. Still I don't have a clear opinion about the dropdown behavior for not valid months. I would appreciate your help or ideas for sure 🙏

**Comment by gpbl** [comment]
> If the user selects a year that results in a month outside the startMonth and endMonth we could change the displayed month to the closest valid one.

Ah yes, that’s the expected behavior 💯 
If you have some time, feel free to open a pull request to start working on it! Thanks.

**Comment by rodgobbi** [comment]
Happy to help @gpbl 👍 
I'll work on it this week once I have time.
You can assign this issue to me if you want.
