### ISSUE TITLE
Large font-size on selected days in 9.3.0

### ISSUE THREAD

**Issue by staaky** [gpbl/react-day-picker#2580]
In 9.3.0 there's a `font-size: large` on `.rdp-selected`, it makes the selected days too big (see screenshot).

https://github.com/gpbl/react-day-picker/blob/79fc047f805aeefabc6d4cb1f42beca2d223230c/src/style.css#L240-L243

Probably overlooked because the website has overrides that mask the problem.

I can replicate it on [daypicker.dev](https://daypicker.dev/) by disabling these in devtools:

https://github.com/gpbl/react-day-picker/blob/79fc047f805aeefabc6d4cb1f42beca2d223230c/website/src/css/custom.css#L71-L77

https://github.com/gpbl/react-day-picker/blob/79fc047f805aeefabc6d4cb1f42beca2d223230c/website/src/css/docusaurus-reset.css#L142-L146

|  |  |
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/925978bf-a788-4c6e-85ec-48ad9b12ace7) | ![image](https://github.com/user-attachments/assets/531cb552-def7-4439-9391-f097b931c721) |

**Comment by gpbl** [comment]
> Probably overlooked because the website has overrides that mask the problem

Oh, that's an [old story](https://github.com/facebook/docusaurus/issues/6032). Funny thing, that larger font was actually the style I wanted to ship in v9.

Should I revert it ? 🤔

**Comment by staaky** [comment]
I'd revert it just because it's causing layout changes for everyone updating, and new installs will notice it's different from what's shown on the website. I prefer the regular font, but whatever you decide, I'd align the website overrides with it.

**Comment by gpbl** [comment]
> I'd revert it just because it's causing layout changes for everyone updating, and new installs will notice it's different from what's shown on the website. I prefer the regular font, but whatever you decide, I'd align the website overrides with it.

@staaky thanks for the feedback! I've updated website in #2588 to match the actual style, with the larger font. 

If upgrading to v9.3 changes the font of DayPicker, this maybe related to https://github.com/gpbl/react-day-picker/pull/2573 that fixes a style bug introduced in v9.
