### ISSUE TITLE
bug: `fixedWeeks` should display 6 weeks if month has 4 weeks

### ISSUE THREAD

**Issue by oleynikovoleg** [gpbl/react-day-picker#2585]
## Code 

```tsx
<DayPicker
  mode="single"
  selected={selectedDate}
  onSelect={handleDataChange}
  hidden={[
    { before: fromDate },
    { after: toDate }
  ]}
  month={selectedMonth}
  onMonthChange={setSelectedMonth}
  showOutsideDays
  fixedWeeks
/>
```

## Expected Behavior
The calendar should consistently display 6 weeks per month when using the `fixedWeeks` prop, regardless of the month. This should ensure a uniform calendar layout, even for months with fewer than 6 weeks of visible days.

## Actual Behavior
In some months, the `fixedWeeks` prop does not work as expected and displays only 5 weeks instead of 6. This occurs inconsistently, even when `fixedWeeks` is enabled. The issue is reproducible on the example page as well.

## Screenshots
<img width="343" alt="Screenshot 2024-11-14 at 12 30 07 PM" src="https://github.com/user-attachments/assets/ab48f352-3ff5-4287-9f31-5d29302fd672">
<img width="852" alt="Screenshot 2024-11-14 at 12 24 34 PM" src="https://github.com/user-attachments/assets/76242463-1cc9-4530-b675-b096bfd6ba3c">

**Comment by bryce-fitzsimons** [comment]
Came here to report this bug, saw it's already been submitted.
<img width="254" alt="image" src="https://github.com/user-attachments/assets/53ae8984-df2e-483d-afac-7f6c2f8d73f3">
