### ISSUE TITLE
June 2015 is showing 6 weeks instead of 5

### ISSUE THREAD

**Issue by j03w** [gpbl/react-day-picker#26]
Hi all,

Please see attached image:

![screen shot 2015-05-29 at 4 22 00 pm](https://cloud.githubusercontent.com/assets/1011517/7877444/0c689972-061f-11e5-94fb-eb5cb42bfffe.png)

**Comment by gpbl** [comment]
@j03w on which browser? which locale are you using with moment?

**Comment by gpbl** [comment]
Yeah i can reproduce it with weeks starting on monday... working on a fix!

**Comment by gpbl** [comment]
mmh it's weird, @j03w could you help me to reproduce this bug? Are you passing the same localized dates to the component?

**Comment by j03w** [comment]
Hi sorry for the late reply. I'm using Chrome 43. 

The only thing I have for locale setting is this:

```
moment.locale('en', {
  week: {
    dow: 1
  }
});
```

My local timezone is GMT+10

**Comment by j03w** [comment]
OK so the problem for me is this: https://github.com/gpbl/react-day-picker/blob/master/src/CalendarUtils.js#L11

value for my `firstOfMonth` is `Mon Jun 01 2015 00:00:00 GMT+1000` and that's `Sun May 31 2015 14:00:00 GMT+0000`

Remove conversion to UTC solved my issue plus it also resolved date selection issue that I'm having as well. I know this is a fix for #18 but clearly this create more problems than solving it...

**Comment by gpbl** [comment]
Hi @j03w I'm sorry for this issue, I've pushed a version which does not use the utc dates anymore. Version 1 (in progress) will have a full test suit that will help to prevent this kind of problems. Any thought about #27 ?

**Comment by j03w** [comment]
thank you! @gpbl
