### ISSUE TITLE
captionElement is not receiving the correct date.

### ISSUE THREAD

**Issue by alb3rto269** [gpbl/react-day-picker#260]
The `captionElement` component is not receiving the correct date. Check your own example:
http://react-day-picker.js.org/examples/?yearNavigation

If you navigate to the next/prev month using the arrows the calendar is updated. However if you try to change the visible month selecting a new month or year the calendar is not updated.

**Comment by alb3rto269** [comment]
I just figure out the problem. It was the breaking change introduced in v4.0.0.

> Updating initialMonth will not show anymore a different month after the first mount (#169)
> This is a potentially breaking change if you were relying on initialMonth to display another month once the component was mounted. If you need the calendar to display a different month, always use the showMonth method. See this discussion for more info.

I used the `showMonth` as you suggested and the example worked fine.

**Comment by gpbl** [comment]
Hey thanks for catching the bug, sorryi forgot to update the example.

I keep this issue open so I remember it.

**Comment by gpbl** [comment]
Fixed! Thanks again!
