### ISSUE TITLE
 Unknown prop weekdayShort on <div> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by th3fallen** [gpbl/react-day-picker#261]
Getting the titled error when adding `weekdayShort` as a prop on the DayPicker component. Any ideas?

**Comment by gpbl** [comment]
@th3fallen which version are you using? 

Anyway the prop is `weekdaysShort` (with the `s` after `weekday`) – please check you are using the right prop's name.

**Comment by th3fallen** [comment]
(doh) i misnamed my default prop... thanks!
