### ISSUE TITLE
 Incorrect Jalali Month Names in react-day-picker

### ISSUE THREAD

**Issue by alikomijani** [gpbl/react-day-picker#2612]
## To reproduce

```tsx
import { DayPicker } from 'react-day-picker/jalali';
import { faIR } from 'react-day-picker/locale';
import "react-day-picker/style.css";

export default function App() {
  return <DayPicker dir="rtl" locale={faIR} />;
}
```

## Actual Behavior

The month names are displayed as Gregorian months translated into Persian, such as:
 “آپریل”, “می”, and “جون”.

## Expected Behavior
The month names should match the Jalali (Persian) calendar, as follows:
'فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'

## How I fix it

I resolved this issue by overriding the localize property of the locale object and providing the correct Jalali month names. Below is the implementation:

```
'use client';

import * as React from 'react';
import { DayPicker } from 'react-day-picker/jalali';
import 'react-day-picker/style.css';

import { cn } from '@/lib/utils';
import { faIR } from 'react-day-picker/locale';

export type CalendarProps = React.ComponentProps<typeof DayPicker>;
const jalaliMonths = [
  'فروردین',
  'اردیبهشت',
  'خرداد',
  'تیر',
  'مرداد',
  'شهریور',
  'مهر',
  'آبان',
  'آذر',
  'دی',
  'بهمن',
  'اسفند',
] as const;
function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
  return (
    <DayPicker
      className={cn('p-3', className)}
      dir="rtl"
      showOutsideDays={showOutsideDays}
      locale={{
        ...faIR,
        localize: {
          ...faIR.localize,
          month: (month) => jalaliMonths[month],
        },
      }}
      {...props}
    />
  );
}
Calendar.displayName = 'Calendar';

export { Calendar };
```

**Comment by gpbl** [comment]
Thanks @alikomijani, is it appropriate to use the hijri month names? 

I understand these names refer to a different month system. We’re currently discussing this in #2574. Your insights would be greatly appreciated!

**Comment by mahdiElmi** [comment]
Hi @alikomijani, thanks for the workaround!

I've noticed an inconsistency in the year display:

- In day pick mode, the year is correctly shown as 1403 (based on the expected calendar).
- However, when I switch to year pick mode, it displays Western years like 2024, 2025, instead of the expected 1403, 1404, etc.

Here’s an example:

- The year is correct in this view:
![image](https://github.com/user-attachments/assets/964543bb-4870-4053-a685-6ce0cfb2deab) 
- But it’s incorrect here:
![image](https://github.com/user-attachments/assets/0996f455-7e87-4ae6-ad05-6492dfb8af4f)

Have you encountered this issue? If so, have you found a fix or another workaround for it?

Thanks in advance!

**Comment by gpbl** [comment]
@mahdiElmi there's no "year pick mode" in DayPicker - are you sure you are not using another library?

**Comment by gpbl** [comment]
Could there be a misunderstanding here?

Hijri months have a different number of days compared to Gregorian months. Isn't it misleading to display the name of a Hijri month when the dates shown are still in the Gregorian system?

Reopening as considering again to put the Hijri month names into `react-day-picker/jalali`. [here](https://github.com/date-fns/date-fns/issues/1740#issuecomment-1264374497) they are considering using native `Intl`.

**Comment by alikomijani** [comment]
> system

hi,
no hijri month name is deferent from jalali month names, also it's work in another calendar system base on moon not solar.
hijri month names is :
محرم،صفر،ربیع الاول، ربیع الثانی، جمادی الاول، جمادی الثانیه، رجب، شعبان، رمضان، شوال، ذیقعده و ذیحجه
jalali month names is: 
 فروردین , اردیبهشت ,خرداد, تیر, مرداد, شهریور, مهر, 'آبان, آذر, دی, بهمن, اسفند.

**Comment by gpbl** [comment]
@alikomijani thanks for your feedback. The issue should be fixed in version 9.4.4 - please give a try.

**Comment by alikomijani** [comment]
I try but steal get month names wrong, so I check your commit and figure out I should import locale file from another file so i change my import line to this:
// import { faIR } from 'react-day-picker/locale';
import { faIR } from 'date-fns-jalali/locale';
and hopefully it's work.
tanks for your consideration.

**Comment by mahdiElmi** [comment]
> @mahdiElmi there's no "year pick mode" in DayPicker - are you sure you are not using another library?

well, I'm using it with shadcn.
I thought the year picker portion is also from DayPicker. 
sorry for the misunderstanding.
