### ISSUE TITLE
Disabled dayOfWeek with before still allows to pick day before.

### ISSUE THREAD

**Issue by henryornellas** [gpbl/react-day-picker#2616]
When adding BOTH `dayOfWeek` & `before` to `disabled` props, some days before the specified `before` date are still AVAILABLE, but shouldn't be. Only the week days AFTER should be available.

## To reproduce

add disabled prop with `dayOfWeek` & `before`

```tsx
import { DayPicker } from "react-day-picker";
import "react-day-picker/style.css";

export default function App() {
  return <DayPicker
      mode="single"
      disabled={{
        dayOfWeek: [2, 5], // add a week day before your current day here
        before: new Date(),
      }}
    />
}
```

CodeSandbox: https://codesandbox.io/p/sandbox/daypicker-bug-report-forked-xytz92?file=%2Fsrc%2FApp.tsx%3A10%2C74&workspaceId=ws_C81qapoKSu338Nuk1D7Ktn

## Actual Behavior

Day before current date is NOT disabled.

## Expected Behavior

Day before current date SHOULD be disabled.

**Comment by gpbl** [comment]
Hi @henryornellas the correct code to disable days is to pass an array of [Matchers](https://daypicker.dev/api/type-aliases/Matcher). In your case:

```tsx
<DayPicker
  mode="single"
  disabled={[
 	{ dayOfWeek: [1, 3, 5] }, 
    { before: new Date() }]
  ]}
/>
```

https://codesandbox.io/p/sandbox/daypicker-bug-report-forked-yl5fsv?workspaceId=ws_RvAmQfb4KwenQPWDmdZEBC

This should fix your issue!

**Comment by henryornellas** [comment]
Yes it works, thanks!
