### ISSUE TITLE
Add new `month` prop

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#263]
This prop should render the calendar displaying the given month:

```jsx
<DayPicker month={ new Date(2018, 12} />
```

similar to `initialMonth`, but it will re-render the component when its value is set to another month.
[See discussion here](https://github.com/gpbl/react-day-picker/issues/169#issuecomment-282011725)

**Comment by gpbl** [comment]
This has been published as v5.1.1

cc @davidspiess

**Comment by davidspiess** [comment]
❤️ @gpbl

**Comment by dunhuang** [comment]
@gpbl  thanks, it is very useful
