### ISSUE TITLE
Calendar not rendering properly

### ISSUE THREAD

**Issue by danielMensah** [gpbl/react-day-picker#265]
I am including react-day-picker to a project of mine and I wanted to test it using the example provided in the [readme.md](https://github.com/gpbl/react-day-picker). However, I am having some rendering problems and no errors or working in the console and I don't know what is the problem. I am using react 15.0.0.

```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import DayPicker from "react-day-picker";

function sundays(day) {
  return day.getDay() === 0;
}

class Calendar extends Component {

  constructor(prop) {
    super(prop);
    this.state = { selectedDay: new Date() };
    this.handleDayClick = this.handleDayClick.bind(this);
  }

  render() {

    return (
      <DayPicker
        initialMonth={ new Date(2017, 1) }
        disabledDays={ sundays }
        selectedDays={ this.state.selectedDay }
        onDayClick={ this.handleDayClick } />
    )
  }

  handleDayClick(day, { disabled, selected }) {
    if (disabled) return;

    this.setState({
      selectedDay: selected ? null : day
    })
  }
}

export default (Calendar);

```
![scre](https://cloud.githubusercontent.com/assets/20041230/23547147/ff7f0652-fff9-11e6-9c56-f5febffefb5c.png)

**Comment by gpbl** [comment]
Yeah maybe is not clear from the README – sorry! 

You must style the component, please [read this](http://react-day-picker.js.org/Styling.html).
