### ISSUE TITLE
Fix keyboard navigation bug when using custom classNames

### ISSUE THREAD

**Issue by oigewan** [gpbl/react-day-picker#268]
The DayPicker.getDayNodes method is essential to the keyboard navigation functionality working correctly.  However, it has hardcoded assumptions about what the classes for a day and an "outside" day are.  This means that attempting to use the keyboard to select a day becomes impossible if the user passes in something on the classNames prop.

**Comment by gpbl** [comment]
Woah thanks for reporting this and for the PR 👍 going to release an update.

**Comment by gpbl** [comment]
Fixed in v5.1.2 🎉
