### ISSUE TITLE
Bower install does not pull in any JavaScript

### ISSUE THREAD

**Issue by oigewan** [gpbl/react-day-picker#270]
Using bower 1.8.0

`*.js` and `lib` are both listed in the ignore entry of your bower.json.  Also, the lib folder is not in source control, so I don't think that bower could pull down your library even if it wanted to.

Two possible solutions that I can see:

1. Keep the lib directory in source control and delete the two aforementioned entries in the bower.json file.  Would probably need a pre-push hook to run babel or something.
2. Remove `*.js`, `lib`, and `src` from the ignore array and have main point to `src/index.js`.  This would mean that consumers would have to run babel on your code, but that's better than the current scenario where they can't use this through bower at all....

**Comment by gpbl** [comment]
Oh I was completely forgetting about for bower. Sorry. 
This should be fixed with v5.1.2 – please report back if not working, thanks!
