### ISSUE TITLE
initialMonth not changing depending on state

### ISSUE THREAD

**Issue by aroundsix** [gpbl/react-day-picker#272]
Hi, 

I have a React and Redux application. I implemented a reporting periods system where based on the range of days you select you create a reporting period. Then you also have a feature where you can edit said reporting periods depending on which one you click. When you click to edit a reporting period you set the one you clicked on state and I'd also like at that moment for the initialMonth to change to the start date of the reporting period that's being edited. Initially I was working on v3.1.1 and it worked just fine but then I upgraded to 5.1.1 in order to implement disabled days and the initialMonth feature stopped working. It's almost as it's not re-rendering when state changes. 

Any ideas on what's happening ?

**Comment by gpbl** [comment]
@aroundsix please use the new [`month`](http://react-day-picker.js.org/APIProps.html#month) prop instead of `initialMonth` – it has been introduced in v5.1.1. Thanks!

**Comment by aroundsix** [comment]
Thank you, that works perfectly.

**Comment by cmrabet** [comment]
Setting the month prop to a new date is not changing my year calendar. As a matter of fact, if I set the month prop to new Date(year, 0,1) where year is taking from state (it changes), the calendar always starts with the current month (March at the time of writing this post). Only initialMonth is setting the right month for me, however it doesn't change after the component has been rendered for the first time.

**Comment by cmrabet** [comment]
This renders a 12 month calendar starting with January, which is what I want, however when I change the year (taken from state), doesn't update:
`
render(){
        const {year}=this.state;
        const initialMonth=moment([year,0,1]).toDate();

        return(
            <div className="YearCalendar">
                <h1>
                    <a onClick={this.showPrevious.bind(this)}>{year-1}</a>
                        <span className="currentYear">{year}</span>
                    <a onClick={this.showNext.bind(this)}>{year+1}</a>
                </h1>
                <DayPicker
                    canChangeMonth={true}
                    initialMonth={initialMonth}
                    numberOfMonths={12}
                    modifiers={modifiers(this.props.calendar)}                    
                />
            </div>
        );
`

Using prop month, shows the year calendar starting from the current month (March) instead of January, and still doesn't make the calendar to update when year changes:

`
render(){
        const {year}=this.state;
        const newInitialMonth=moment([year,0,1]).toDate();

        return(
            <div className="YearCalendar">
                <h1>
                    <a onClick={this.showPrevious.bind(this)}>{year-1}</a>
                        <span className="currentYear">{year}</span>
                    <a onClick={this.showNext.bind(this)}>{year+1}</a>
                </h1>
                <DayPicker
                    canChangeMonth={true}
                    month={newInitialMonth}
                    numberOfMonths={12}
                    modifiers={modifiers(this.props.calendar)}                    
                />
            </div>
        );
`

**Comment by gpbl** [comment]
@cmrabet please check out this example: http://react-day-picker.js.org/examples/?year
If something doesn't work as expected try to reproduce the problem and open another issue, thanks

**Comment by yairEO** [comment]
@gpbl - all the links in your comments (in this thread) are dead :)
