### ISSUE TITLE
Should Up and Down keys be captured?

### ISSUE THREAD

**Issue by halt-hammerzeit** [gpbl/react-day-picker#273]
http://react-day-picker.js.org/examples/
When I hit "Up" and "Down" keys it increments/decrements the current year but at the same time it scrolls the page.
I guess those events should be `preventDefault()`ed somewhere in the calendar internals?

**Comment by gpbl** [comment]
Good question: events are complicated. To not break anything I'd let the developer add a `onKeyDown` event for that:

```
<DayPicker onKeyDown={ e => e.preventDefault() } />
```
