### ISSUE TITLE
SelectedDays not func

### ISSUE THREAD

**Issue by th3fallen** [gpbl/react-day-picker#282]
in your examples, you pass an instance of new Date to selectedDays but when I do that I get an error that it expects a func?

am i missing something?

**Comment by gpbl** [comment]
👋 @th3fallen, which version are you using? Please upgrade to the latest to use Date objects in `selectedDays`.

**Comment by th3fallen** [comment]
(doh) i was apparently on an older version, updating works as expected. sorry i should have checked before posting this...

**Comment by gpbl** [comment]
no problem 😁

**Comment by sweetaprospa** [comment]
in order to use SelectedDays on DayPickerInput, what version of daypicker supports this?
