### ISSUE TITLE
Disable past dates by default

### ISSUE THREAD

**Issue by tizol** [gpbl/react-day-picker#283]
In most cases we want users to select future dates so it would be nice to have a default feature that disables past dates unless specified otherwise. 

For example the [date picker](http://airbnb.io/projects/react-dates/) from Airbnb has this feature.

> `isOutsideRange` indicates which days are out of selectable range. Past dates out of range by default. If you would like to allow the user to select days in the past, you may set `isOutsideRange` to `() => true`. `isOutsideRange: PropTypes.func`

I was looking through the docs and I did not find an example that shows how to disable past dates. Is there currently a way to disable past dates?

**Comment by adidahiya** [comment]
I think you should just use the [`disabledDays` prop](http://react-day-picker.js.org/Basic.html). react-day-picker probably shouldn't be opinionated about which days users typically select (as a data point, in our usage of react-day-picker, users very rarely select future dates).

**Comment by gpbl** [comment]
@adidahiya is correct! This will disable the past days:
 
```jsx
const today = new Date();
<DayPicker disabledDays={{ before: today }} />,
```

**Comment by tizol** [comment]
@adidahiya @gpbl  Thanks for the help. It works!

**Comment by manjula91** [comment]
Can we also disable the dates using DayPickerInput
<DayPickerInput
					placeholder="DD/MM/YYYY"
					format="DD/MM/YYYY"
					onDayChange={day => console.log(day)}
				/>

How do i do it in this case?

**Comment by gpbl** [comment]
@manjula91 use `dayPickerProps`: http://react-day-picker.js.org/api/DayPickerInput#dayPickerProps

**Comment by manjula91** [comment]
@gpbl Thanks it works :)

**Comment by amanpreet-github** [comment]
Hey, if you are using **DayPickerInput** then the way to disable the past or future dates is very simple.

> For disabling the future dates.

` <DayPickerInput
dayPickerProps={{
                        disabledDays: {after: new Date()}
                      }} >
</DayPickerInput>
`
 

> For disabling the past dates.

` <DayPickerInput
dayPickerProps={{
                        disabledDays: {before: new Date()}
                      }} >
</DayPickerInput>
`

**Comment by nemanjacosovic** [comment]
Here is one more example.

First day is Monday.
Disabled **weekends**.
Disabled days **before today**.
Disabled **today**.

`<DayPicker firstDayOfWeek={ 1 } disabledDays={ [new Date(), { daysOfWeek: [0, 6] }, { before: new Date() }] } />
`

**Comment by alex-resdiary** [comment]
Leaving this here for anyone who might be struggling with the <DayPickerInput> component. You need to pass the props into daypicker as follows :  

```
DayPickerInput
                dayPickerProps={{
                    disabledDays: {
                        before: today,
                    },
                }}/>
```

**Comment by aprzygocki** [comment]
I changed mine around a little and the previous posts in this thread helped me with some of that. Thank you, guys. 
This turns the previous dates into greyscaled numbers but they can still be selected. :( 
Does anyone know how to remedy this?

`import React from 'react';
import DayPicker from 'react-day-picker';

import 'react-day-picker/lib/style.css';

export default class Calendar extends React.Component {
  constructor(props) {
    super(props);
    this.handleDayClick = this.handleDayClick.bind(this);
    this.state = {
      selectedDay: undefined,
    };
  }

  handleDayClick(day) {
    this.setState({ selectedDay: day });
  }

  render() {
    return (
      <div>
        {this.state.selectedDay ? (
          <p>You clicked {this.state.selectedDay.toLocaleDateString()}</p>
        ) : (
          <p>Please select a start day.</p>
        )}
        <DayPicker
          onDayClick={this.handleDayClick}
          selectedDays={this.state.selectedDay}
          firstDayOfWeek={ 0 }
          disabledDays={
            [
              { daysOfWeek: [] },
              { before: new Date()}
            ]
          }
        />
        </div>
    );
  }
}`

**Comment by saqibshahid** [comment]
in DayPickerInput can we disable 2 date like Sunday and before today all date?

**Comment by HayeulTanjib** [comment]
<DayPicker
                            disabled= {{ before: new Date() }}
                        />
This worked for me

**Comment by rihid** [comment]
> ```
>                     <DayPicker
>                         disabled= {{ before: new Date() }}
>                     />
> ```
> 
> This worked for me

thanks, also work for me

**Comment by sravantp7** [comment]
```
disabled={{ before: new Date() }}
```
Thanks, this worked for me.

**Comment by onlyphantom** [comment]
A useful approach as well, is to set up the right number of months using `numberOfMonths` (for example, 3) and then use the `disableNavigation` to disable the pagination of `DayPicker` completely. 

```
<DayPicker
    ...
    numberOfMonths={3}
    disableNavigation
/>
```

It's not a direct answer to the question of course, but in specific situations (like tutoring sites / bookings) where all the available dates are on display, then I find this a cleaner, more direct approach.
