### ISSUE TITLE
Stop propagation of next/previous month clicks

### ISSUE THREAD

**Issue by julen** [gpbl/react-day-picker#286]
Hi there! First of all, thank you very much for this excellent component — it's been a breeze to integrate it and the experience has been superb so far.

Onto the issue:

I am rendering the `<DayPicker />` component within a dropdown/popup which has the ability to dismiss it by clicking _outside_, i.e anywhere in the document.

When clicking the month navigation arrows of `<DayPicker />`, the click event is being propagated, and when this leads to a `fromMonth`/`endMonth` month, any checks I have in place to determine whether the clicked arrow element is contained within the dropdown area will fail, and hence the dropdown will be closed (because the navigation arrows are not there anymore).

I see there was a chance in the past to hook onto `onNextMonthClick` and `onPrevMonthClick`, which allowed to [access the synthetic event object](https://github.com/gpbl/react-day-picker/pull/12), but [these were removed in v1.0.1](http://react-day-picker.js.org/Changelog.html#v101-2015-06-24) and the proposed alternative of using `onMonthChange` doesn't provide access to the event.

(Likewise I realize the [`callback` argument to `showNextMonth`](https://github.com/gpbl/react-day-picker/blob/830e04f4ecf8f2fb9c1dceadc48276440baaeda8/src/DayPicker.js#L231) and `showPreviousMonth` is dead code).

Having said that, in this scenario I would suggest to stop propagation both for synthetic and native events in the `showNextMonth` and `showPreviousMonth` event handlers, just as it was originally suggested in #10.

I verified this does the trick for me and I can send a PR if you are happy with the proposed change.

**Comment by gpbl** [comment]
Thanks for taking the time investigating this and digging into old issues 👍 

I'm not sure about the possible effects by stopping the event propagation (may some users adopt this behavior?), so I'd like to keep it as it is.

About your issue: it's a common problem we have interacting with overlays that should disappear when  clicked outside. We could solve it with a `setTimeout` hack in this example: http://react-day-picker.js.org/examples/?overlay 

Would that solution help you without updating the source?

**Comment by julen** [comment]
Thank you for the quick reply.

I admit I didn't get my hands dirty on it yet but the `setTimeout` hack you mention looks unnecessarily complicated to me, given that the dropdown component I have is rendered as a grandparent of `<DayPicker />` and I believe I would need to drill holes or couple the picker with the dropdown more than needed.

As I see now, in #74 stopping of propagation was requested to be removed. I guess there have been different versions in the wild with different behavior, although it's been mostly with event propagation, and I understand your concern of not willing to change that now.

Still, would you be open to consider bringing back the `onNextMonthClick` and `onPrevMonthClick` hooks? It looks like a reasonable compromise to me: while it would increase the API surface a bit, it would allow to have the desired behavior in a straightforward manner.

**Comment by gpbl** [comment]
>  I believe I would need to drill holes or couple the picker with the dropdown more than needed.

Maybe it's easier creating a wrapper dropdown for the DayPicker? We had a [discussion](https://github.com/gpbl/react-day-picker/issues/98) about implementing the overlay: you may encounter other problems without using timeout and `onMouseDown` :/

**Comment by julen** [comment]
Thank you again for the suggestions. I ended up changing the implementation of my dropdown not to check for the presence of DOM elements, but rather to check the `clickedInside` flag as it's done in the example you linked first. I'm not using any inputs like in the example and there's no need to handle `blur` events, therefore the interaction becomes simpler:

For the dropdown area:
* set the flag in `onMouseDown`
* unset the flag via `setTimeout()` in `onMouseUp`. This ensures the flag is cleared _after_ the document-level `click` listener has been executed
* just in case, don't forget to cleanup the timeout in `componentWillUnmount()`

This will now be more robust because it will work well not only with react-day-picker's navigational elements being removed, but with any other `click` event triggered from any component rendered in the dropdown that would cause removal of an element from the DOM.
