### ISSUE TITLE
bug: enableOutsideDays keeps focus on wrong cell

### ISSUE THREAD

**Issue by joeybaker** [gpbl/react-day-picker#29]
## To repro

1. set `enableOutsideDays` to `true`
2. click on an outside day

## What happens
The cell that you clicked on retains focus

## What should happen
The the selected cell moves when the month changes. Focus should move with it.

**Comment by gpbl** [comment]
Thanks for the bug report, @joeybaker! Indeed I could replicate it, but not for *any* outside day. See for example the [Selectable Day](http://www.gpbl.org/react-day-picker/#examples/Selectable day) and choose August 2015. It focuses the 29th of july but not the 28th. Let me give a look...

**Comment by gpbl** [comment]
Published as v1.0.2!

**Comment by joeybaker** [comment]
Thanks!
