### ISSUE TITLE
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package

### ISSUE THREAD

**Issue by akichim21** [gpbl/react-day-picker#294]
hi
propTypes warning happened

Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types

version:
react@15.5.4
react-day-picker@5.2.2

![2017-04-14 20 30 43](https://cloud.githubusercontent.com/assets/6077520/25042246/67b1fbee-2151-11e7-91e4-9eec7761fd2a.png)

**Comment by gpbl** [comment]
Weird! Which version of prop-types are you using?

```
$ npm ls react prop-types
└─┬ react@15.5.4 
  └── prop-types@15.5.8 
```

Anyway, i released a patch that should make sure you are using the latest version of prop-types. Please report back if you see this error again. I can't replicate it.

**Comment by akichim21** [comment]
sorry.
maybe react version different in server side.

**Comment by akichim21** [comment]
npm ls react prop-types
├── prop-types@15.5.8
└── react@15.5.4
