### ISSUE TITLE
`labels` prop marked as isRequired but doesn't seem necessary in english

### ISSUE THREAD

**Issue by jethrolarson** [gpbl/react-day-picker#297]
This is just throwing warnings unnecessarily.

**Comment by gpbl** [comment]
Which version of react and react-day-picker are you using? The labels prop has already its own default props: https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L116-L119
A code I can replicate this?

**Comment by jethrolarson** [comment]
React 15.5 and the latest day picker as of yesterday. I looked at the
source of day picker and it's marked as required in the props definition

**Comment by jethrolarson** [comment]
Having a default prop definition doesn't stop it from being required. That
just stops it from breaking

**Comment by gpbl** [comment]
> Having a default prop definition doesn't stop it from being required. That
just stops it from breaking

From the [react docs](https://facebook.github.io/react/docs/typechecking-with-proptypes.html):
_The propTypes typechecking happens after defaultProps are resolved, so typechecking will also apply to the defaultProps_.

If you are getting this error likely you are not passing the required prop. If you believe it is a bug, please help us to reproduce it, thanks :)

**Comment by jethrolarson** [comment]
Ohhh I know what happened. I was adding a thin wrapper component and
setting it's propTypes = DayPicker.propTypes without doing the same for
defaultProps. My mistake, you can close

**Comment by gpbl** [comment]
Please be nicer the next time, thanks.

**Comment by jethrolarson** [comment]
I can see that I was wrong, but I don't see how I was being rude. I'm sorry if I came across that way.
