### ISSUE TITLE
Include typescript definitions

### ISSUE THREAD

**Issue by adidahiya** [gpbl/react-day-picker#299]
@gpbl what do you think about including typescript definitions in this repo and the published NPM package? The [blueprint](https://github.com/palantir/blueprint) maintainers could likely help you maintain them. The moment package, among others, does this: https://github.com/moment/moment/blob/develop/moment.d.ts.

I guess the one downside here is that you don't automatically get the testing infrastructure of DefinitelyTyped (you'd have to build some yourself if you wanted it). Upside is that the definitions are more likely to stay up to do date. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16010

cc @giladgray

**Comment by gpbl** [comment]
I was just thinking to ask on that DefinitelyTyped issue for some help 😄

I have no idea how do they work: is it just adding a [react-day-picker.d.ts](https://github.com/giladgray/DefinitelyTyped/blob/266e2977fdd25e3618695121917e65dc6364c96a/types/react-day-picker/index.d.ts) to the package? Need to investigate a bit (or if you have some spare time, I'd be happy to merge a PR). 

As for the tests, we could just copy what moment is doing there!

**Comment by gpbl** [comment]
Type definitions have been released in `v5.3.0`. I hope I made everything right: if not, please report 😄  Thanks!

**Comment by phaza** [comment]
It doesn't appear to work for LocaleUtils:
>import LocaleUtils from "react-day-picker/moment"; implicitly has any type

Not entirely sure how to fix it, my typescript experience is so far fairly limited.

**Comment by adidahiya** [comment]
@phaza try `import { LocaleUtils } from "react-day-picker"`. See https://github.com/gpbl/react-day-picker/blob/7d2625288f022b9df0b94348b68ba08b0f3e584f/types/index.d.ts#L5

**Comment by lpcarignan** [comment]
I tried the following in Typescript 2.0 project:

`import {DayPicker} from "react-day-picker";`

I get the following error message when I run the Typescript compiler

`TS2305: Module '/node_modules/react-day-picker/types/index"' has no exported member 'DayPicker'.`

**Comment by giladgray** [comment]
@lpcarignan the package uses `module.exports` so you have to do the namespace import:
`import * as ReactDayPicker from "react-day-picker";`

see https://github.com/palantir/blueprint/blob/master/packages/datetime/src/datePicker.tsx#L11

**Comment by lpcarignan** [comment]
@giladgray Thx for the quick response and the link to the project on which I can get some ideas. I roughly copy/pasted the ReactDatePicker element in the example you sent.

After playing around for a bit, I get a very ugly ReactDatePicker where all of the days and dates of the month are stacked. In the example you sent me, there's a div with a className refering to DatePicker. Do I have to consider the .css of the ReactDatePicker when I use the component in my code? When I look at the [examples](http://react-day-picker.js.org/examples/), it begins by including

`import 'react-day-picker/lib/style.css';`

I can't do that in TypeScript. To add to the mix, I'm using semantic-ui-react as my React library and I bundle my app into a single .js with Webpack.

![image](https://user-images.githubusercontent.com/1015955/28389860-cd97a72a-6ca5-11e7-9d90-8a3e70d33bb5.png)

**Comment by gpbl** [comment]
@lpcarignan check http://react-day-picker.js.org/docs/styling.html for more info about styling the component.

Please open a new issue or write in the gitter room for questions not related to this issue, thanks 🙏🏽👍🏽

**Comment by giladgray** [comment]
@lpcarignan you'll need to include the css file somehow, either as a `<link>` in your HTML or using a [loader for your JS bundler](https://github.com/webpack-contrib/css-loader) of choice that can handle css.

**Comment by lpcarignan** [comment]
Thanks for all of your help guys with my newbie questions. It is much appreciated.

**Comment by Darren120** [comment]
this package is dependence heavy i uninstalled it.
