### ISSUE TITLE
Show week numbers and handle week number selection

### ISSUE THREAD

**Issue by rodeinator** [gpbl/react-day-picker#304]
I need a quick week selection in this awesome day picker. It is already possible to show week numbers in day picker? Would this feature be something for the core implementation? 

![week-selection](https://cloud.githubusercontent.com/assets/557705/25268467/19179e62-2679-11e7-8ea1-e5b07fe1653d.png)

I would suggest to implements props like this:
`
 <DayPicker
  enableWeekSelection={true}
  onWeekClick={ this.handleWeekClick }
 />
`

**Comment by gpbl** [comment]
yeah we could consider to add a `showWeeks` and `onWeekClick`. 👍🏽

For selecting a week, you could implement an `onDayClick` saving in your component's state the clicked day's week number:

```js
handleDayClick = day =>
    this.setState({
      selectedWeek: getWeekNumber(day)
    })
```

then pass a function to the `selectedDays` prop:

```jsx
<DayPicker
    onDayClick={ this.handleDayClick }
    selectedDays={ day => getWeekNumber(day) === this.state.selectedWeek }
/>
```

- you need to implement `getWeekNumber` by yourself ([example](http://stackoverflow.com/questions/6117814))
- you may add more logic to unselect the week when the user clicks on a day of a already selected week

**Comment by gpbl** [comment]
`showWeekNumbers` and `onWeekClick` have been added to `v5.5.0` 🙆🏽
