### ISSUE TITLE
disabledDays won't handle properly an array of object (range) and date (function)

### ISSUE THREAD

**Issue by Kotpes** [gpbl/react-day-picker#305]
https://jsfiddle.net/69z2wepo/76662/

**Comment by gpbl** [comment]
Thanks! fixed in https://github.com/gpbl/react-day-picker/pull/302 ... release next week 👌🏽

**Comment by gpbl** [comment]
@Kotpes please upgrade to `v.5.3.0` to see this issue fixed, thanks!
