### ISSUE TITLE
Before/after modifiers issue with timezone

### ISSUE THREAD

**Issue by ktusharprdxn** [gpbl/react-day-picker#307]
I want to disable all days from current day, for that I have used 
`const range = {
      before: new Date()
    }
<DayPicker
        initialMonth={ new Date() }
        disabledDays={range}
        selectedDays={ new Date() }
        onDayClick={this.handleDayClick}
    />
`

But it disabled current day as well, i.e. if today is 25th of april then all days before 25th should get disabled and current date i.e. 25th should get selected. 
Can anyone please help me what went wrong here?

**Comment by gpbl** [comment]
Could you please replicate your issue in a jsfiddle? 

https://jsfiddle.net/pkdcqvpk/

thanks!

**Comment by ktusharprdxn** [comment]
@gpbl I have just open your JSfiddle link and I was able to replicate this issue. Please see this screenshot.

![date](https://cloud.githubusercontent.com/assets/10720760/25389599/b0f5626e-29ee-11e7-851d-ff7c31ed8cd7.png)

Today is 25th of april but still it is shown disabled.

**Comment by gpbl** [comment]
interesting ! thanks. what is your timezone?

**Comment by ktusharprdxn** [comment]
@gpbl My timezone is IST

**Comment by gpbl** [comment]
Thanks, I can replicate it! Until I don't publish the fix, as workaround you can use:

```jsx
 <DayPicker 
    disabledDays={ { 
        before: new Date().setHours(0,0,0,0)  
    }} 
/>
```

See [the updated jsfiddle](https://jsfiddle.net/pzzz7sgr/1/).

**Comment by ktusharprdxn** [comment]
@gpbl Thanks for workaround, I will use it for development now, and I will wait for proper fix.

**Comment by gpbl** [comment]
@ktusharprdxn please upgrade to `v5.3.0`

**Comment by ktusharprdxn** [comment]
Hey @gpbl Thanks for the quick fix. :+1:

**Comment by martin-svk** [comment]
This fix broke my code (`v5.2.3 works good)`, and what was before indicated as disabled is no longer working.

**Comment by gpbl** [comment]
@martin-svk could you please replicate your problem https://jsfiddle.net/gpbl/cggxvq6t/ and eventually open a new issue? thanks

**Comment by martin-svk** [comment]
@gpbl Ok, i created https://github.com/gpbl/react-day-picker/issues/324
