### ISSUE TITLE
Any way to change the style from the app once up?

### ISSUE THREAD

**Issue by cmrabet** [gpbl/react-day-picker#310]
The classes in the CSS file are nice, even better with css-modules, however what happens when we want the user to configure the colors for the different modifiers? How do you apply the new colors to the existing style being used by the calendar? 

The calendar doesn't have a styles prop where to pass render-time generated styles, so I don't know how to proceed. My app has a screen where the user can set the color he wants for holidays, Sundays, etc..

**Comment by gpbl** [comment]
Maybe the new [modifiersStyles](http://react-day-picker.js.org/APIProps.html#modifiersstyles) prop introduced by @susielu in `v5.3.0` (released yesterday) is what you are looking for?
