### ISSUE TITLE
calendar month changes

### ISSUE THREAD

**Issue by pjebs** [gpbl/react-day-picker#317]
If I use the arrow to move to a later month and then click on the date, I can change the "current date" to the clicked date.
BUT the calendar ALWAYS changes back to the current month for display, even though the newly selected date is shown as current date.

My code does nothing more than change the selected date when a date is clicked on.

**Comment by pjebs** [comment]
Is this not a bug?

**Comment by gpbl** [comment]
@pjebs could you please help us to reproduce your issue on this jsfiddle? https://jsfiddle.net/28q0jd7x/
