### ISSUE TITLE
Disabled `before` modifier is broken

### ISSUE THREAD

**Issue by martin-svk** [gpbl/react-day-picker#324]
Hello,

It looks like disabled before modifier is broken. 
It works good in `5.2.3` not anymore after `5.3.0` update.
 
Link: [https://jsfiddle.net/cggxvq6t/3/](https://jsfiddle.net/cggxvq6t/3/).

Thanks

**Comment by gpbl** [comment]
Maybe it's not clear [from the docs](http://react-day-picker.js.org/Modifiers.html), but if you need to match days using multiple conditions, you must pass an _array_:

```diff
- disabledDays={{ before: myDate, after: myOtherDate }}
+ disabledDays={[ { before: myDate }, { after: myOtherDate } ]}
```

Check the [fixed jsfiddle](https://jsfiddle.net/gpbl/jbwwL09b/).
Thanks for reporting, I'll see how to improve the docs :)

**Comment by martin-svk** [comment]
Thanks, that works. And yes, it is not super clear, especially in combination with `{ from, to }` where array is not needed.
