### ISSUE TITLE
Too slow for mobile with higher numberOfMonths

### ISSUE THREAD

**Issue by sliker** [gpbl/react-day-picker#374]
Hello,

When using the component on a phone (tested on Android and iOS) and `numberOfMonths` is set to a higher value like 8 or 10 the performance when selecting a range of dates is really slow, it takes a lot to show the selected days, using a lower value like 2 performs better.

This issue only happen on real device, on desktop emulated works ok.

**Comment by gpbl** [comment]
Interesting, thanks for the report! Could you share your code to reproduce it? 

Are you using a code similar to this one?
http://react-day-picker.js.org/examples/?range

**Comment by gpbl** [comment]
I've tested it a bit and found we can do something 👍 See #389.

**Comment by gpbl** [comment]
With #389 I've improved the performance rendering multiple months. Not sure if will solve completely the @sliker's issue, but we should see some benefits. See https://github.com/gpbl/react-day-picker/issues/389#issuecomment-307650746

**Comment by gpbl** [comment]
Improvements has been published  in v6.0.0 ([changelog](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md)), @sliker could you please test if they have improved your use  case? Thanks!

**Comment by sliker** [comment]
@gpbl I will update to this version and check if performs better.
Thank you!

**Comment by yasoza** [comment]
I would not recommend anyone trying to optimise their date picker mobile components with this package v7 version, move to  react-dates. its much better and provides a lot more functionality and smoothness out of the box. Additionally you can lazy load number of months as user scroll to further improve performance (I think it might be possible in this pacakge as well). secondaly keep an availability index/hashmap of available dates. One drawback of  react-dates I found is that it requires you to import moment, but guess what this package's v7 version also internally uses moment.
