### ISSUE TITLE
Incorrect Docs & month prop Question

### ISSUE THREAD

**Issue by reintroducing** [gpbl/react-day-picker#396]
Just a heads up that I was reading through the docs and the `months` prop in the API's description is incorrect: `An array containing the long weekdays names to use in the month's header.` I think this should say `the month names` instead.

In any case, when displaying a calendar with `numberOfMonths` set to more than 1, how will settings `month` affect it? Let's say, for the sake of argument, that I have a calendar with two months displaying. Will this make it show that month as the first month always?

**Comment by gpbl** [comment]
Thanks for the heads up about the docs!

> Let's say that I have a calendar with two months displaying. Will this make it show that month as the first month always?

Yup!

**Comment by reintroducing** [comment]
Got it, thanks. Feel free to close this unless you want to keep it around for your purposes until the new release updates it.
