### ISSUE TITLE
Bug: Fails to load in IE11

### ISSUE THREAD

**Issue by oigewan** [gpbl/react-day-picker#403]
I was testing my app in IE11, and as soon as I attempted to move between days using the keyboard, my console was full of errors.  It seems that your babel settings aren't polyfilling anything, and your output code includes things like `Object.assign` and `Array.from` which don't exist in IE11.

**Comment by gpbl** [comment]
Thanks @oigewan for your help. The fix has been published in v6.0.0 ([changelog](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md)) 🎉
