### ISSUE TITLE
Remove Day by Deleting Input

### ISSUE THREAD

**Issue by maxsalven** [gpbl/react-day-picker#423]
Similar to `clickUnselectsDay`, it would be great to have a `deleteUnselectsDay` on the `DayPickerInput`.

I.e. if the user deletes the content of the input field, and then blurs it, we call `onDayChange(undefined)`. 

Right now it's not super clear from a UI perspective that you have to click on a selected date to unselect it. I've seen my users trying to delete the text in the input box instead.

**Comment by gpbl** [comment]
Definitely a bug! I recall to have implemented this behavior then removed it for some obscure reason :)

Meanwhile, you should be able to workaround this by adding the `onChange` prop, which behaves like the regular input's prop.

Thanks for the feedback 🙏🏽

**Comment by gpbl** [comment]
Fixed in v6.0.3
