### ISSUE TITLE
Bug: DayPickerInput, changing month in captionElement with selected value will be ignored

### ISSUE THREAD

**Issue by Cagyo** [gpbl/react-day-picker#425]
To reproduce the error, in DayPickerInput select any day and after change month or year by selecting it in captionElement - month and year will remain unchanged.

https://jsfiddle.net/pbsbyo72/2/

The problem is in getStateFromProps function:
`const m = moment(props.value, props.format, true);
    if (m.isValid()) {
      month = m.toDate();
    }`

**Comment by gpbl** [comment]
Thanks for the report! Fixed in v6.03
https://jsfiddle.net/gpbl/pbsbyo72/3/
