### ISSUE TITLE
The path to the "unpkg" components is broken

### ISSUE THREAD

**Issue by bbarnell** [gpbl/react-day-picker#429]
👋🏽 Thanks for opening an issue!

🐛 If you are reporting a bug, show us how to reproduce it here:
<script src="https://unpkg.com/react-day-picker/daypicker.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/react-day-picker/lib/style.css">

**Comment by gpbl** [comment]
Thanks, fixed! The correct URL is https://unpkg.com/react-day-picker/lib/daypicker.min.js
