### ISSUE TITLE
Wrapper style cannot be set when using CSS modules

### ISSUE THREAD

**Issue by udovenko** [gpbl/react-day-picker#432]
Wrapper style cannot be set when using a CSS module despite upgrade notes https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md#v600-2017-06-16.

**DayPicker** component is not picking **wrapper** style up from props (https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L507) as it's doing for container props (https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L489). So wrapper allways have class ```DayPicker-wrapper``` and no styles can be set form CSS module.

**Comment by gpbl** [comment]
Thanks for reporting this! Fixed in v6.04.
