### ISSUE TITLE
Add focus modifiers

### ISSUE THREAD

**Issue by basham** [gpbl/react-day-picker#44]
Add `.DayPicker--focus` and `.DayPicker-Month--focus` class modifiers to visually indicate when the widget and respective month has a focused descendant. These aren't necessary, but it could assist users and provide additional style hooks, if desired.

This issue is probably more sensible if the suggestions in #43 are resolved.

## References

- [3.2.5. Managing the Perception of a Dual Focus](http://www.w3.org/WAI/PF/aria-practices/Overview.html#dualfocus)

**Comment by basham** [comment]
As a result of [not managing focus within the widget and rather using `aria-activedescendant`](https://github.com/gpbl/react-day-picker/issues/43#issuecomment-126411207), I retract my aforementioned suggestions regarding `.DayPicker--focus` and `.DayPicker-Month--focus` class modifiers.

Instead, focus on the widget can be styled via `.DayPicker:focus`. Indicate the active day with `.DayPicker-Day--active`. Indicate the active month with `.DayPicker-Month--active`.

**Comment by gpbl** [comment]
I'm OK with the `--active` modifier for `Month`, however what is a valid use case for it? To change the style of the month having a focused day? Isn't a style to :focus enough?
For the `DayPicker` element I'd better avoid to add new default modifiers: `:focus` would suffice for that

**Comment by basham** [comment]
Because `.DayPicker` is the only element that will be focusable, it's the only element that can be styled with `:focus`. There's no way for `.DayPicker-Month` to to know if it contains a selected `.DayPicker-Day` (`.DayPicker-Day--active` or perhaps only `.DayPicker-Day[aria-selected="true"]`). I only see `.DayPicker-Month--active` being used when there's multiple months shown and there needs to be a little more visual emphasis on the month with a selected day. This is more of a nicety to enable a larger range of design possibilities, but it's by no means critical, and I speculate it won't be used extensively.

**Comment by gpbl** [comment]
Since I don't see much people in need of a default `focused` modifier, I feel free to close this issue. Please write back if in need to reopen this issue – thanks!
