### ISSUE TITLE
Dynamically inject styles

### ISSUE THREAD

**Issue by arjun-menon** [gpbl/react-day-picker#440]
**The Proposal:** It would be useful to be able to pass in the styling as a prop to the React component. Or, as multiple props (with names like `style`, `wrapperStyle`, `monthStyle`, etc) that correspond to the classes found in the [style.css](https://github.com/gpbl/react-day-picker/blob/master/lib/style.css) file. The prop(s) can have a `defaultProps` which defaults it the styles specified in the current `style.css` file. (This would eliminate the need to import CSS, and enable users to override styles in React's JavaScript [inline style](https://react-cn.github.io/react/tips/inline-styles.html) syntax.)

How does this idea sound? If this sounds like it would be beneficial, I'd be happy to work on this, and create a pull request for it.

**Context:** I'm working on [a project](https://activeviam.com/products/activeui-decision-making-ui) where the user can pick from various themes, and we pass in all our styles to our React components as props. When the user changes the theme, the components get immediately re-rendered with the new theme (no need to refresh the page). We use [Styletron](https://github.com/rtsao/styletron) for making things a bit more efficient, but all our styles are specified in the React's JavaScript inline style syntax.

**Comment by gpbl** [comment]
Maybe we should reopen https://github.com/gpbl/react-day-picker/issues/170 :) I'd be happy to see a PR 👍

**Comment by arjun-menon** [comment]
@gpbl Do you think it would be okay to add a dependency on [Styletron](https://github.com/rtsao/styletron) to **react-day-picker**? Styletron is fairly light-weight, and makes applying & updating styles more efficient.

(If not, that's fine too!)

I'm going to start working on a PR that'll eliminate the CSS file today. Hopefully it won't take too long.

**Comment by arjun-menon** [comment]
Actually, it looks like it'll be fairly complicated to turn all of the styles into injected styles, since `:not()` is used around, and functions like `getDayNodes` (in `Helpers.js`) uses CSS class names to query for nodes.

**Comment by gpbl** [comment]
@arjun-menon yep it's not that easy at it seems, I know :) 
For the `:not` selector, it should be easy to workaround it by overriding the properties. About`getDayNodes`: we may find another way to find days elements?

Thanks again for the time you are spending on this!

**Comment by gpbl** [comment]
I'm closing this because it seems inactive 🔢

**Comment by arjun-menon** [comment]
Sorry, I got a bit busy with other things. Yes, I don't think I'll be working on this in the short term. My team found another (rather complicated) way to get around this problem, as `react-day-picker` wasn't the only library that required integrating custom style-sheets, and we needed a general solution.

**Comment by gpbl** [comment]
No problem! Thanks for your effort 😊
I believe honestly that there’s no need to support inline style, at least for now.
