### ISSUE TITLE
DatePickerInput-OverlayWrapper z-index

### ISSUE THREAD

**Issue by peatidge** [gpbl/react-day-picker#448]
Thanks for awesome components, really appreciate it :)
Have had trouble with z-index of overlay and react bootstrap inputs, the bootstrap inputs have a higher z-index and are shown on top of the overlay (covering it). 

I have added a z-index prop to .DatePickerInput-OverlayWrapper  to fix it for my projects but obviously I have to add it again everytime I re-install the package.

**Comment by gpbl** [comment]
> I have added a z-index prop to .DatePickerInput-OverlayWrapper to fix it for my projects but obviously I have to add it again everytime I re-install the package.

Indeed! You shouldn't change the css from the node_module dir. Instead, add an extra css file to your app that will override the `.DatePickerInput-OverlayWrapper`'s `z-index`.
