### ISSUE TITLE
Disabling single days with before/after

### ISSUE THREAD

**Issue by agustinramos** [gpbl/react-day-picker#451]
When I want to leave a single day enabled does not work.
Here is the example.
https://jsfiddle.net/obLk164e/

Thank you

**Comment by gpbl** [comment]
Thanks for reporting this. I think the expected behavior should happen when you specify `before` and `after` as the same day (as they are exclusive). This, however, doesn't work either.

Otherwise, you can pass a function, like this:

```jsx
import DayPicker, { DateUtils } from 'react-day-picker';

<DayPicker
  initialMonth={new Date(2017, 3)}
  disabledDays={
     day => !DateUtils.isSameDay(day, new Date(2017, 3, 26))
  }
/>
```

**Comment by tamizharasank** [comment]
How to disable whole dayPicker module any solution ?
