### ISSUE TITLE
Material UI Integration or Material Styling

### ISSUE THREAD

**Issue by brendonlamb** [gpbl/react-day-picker#453]
Less of an issue, more of a feature request.

You guys are awesome, this is hands down the best React date picker i've worked with (I've tried a bunch) ...  

Is there by chance a Material-like style sheet for react-day-picker ? Just figured I'd ask before spending too much time on it :D

Material-UI's DatePicker is kind of suffering, and it looks like they're dropping it all together from V1 - I wish you guys could sync up and build react-day-picker into MUI

**Comment by gpbl** [comment]
> Is there by chance a Material-like style sheet for react-day-picker ? Just figured I'd ask before spending too much time on it :D

Nothing that I'm aware of 😄 Note that react-day-picker has no animations, or ripple effects may be a bit hard to achieve.

**Comment by anoopgq** [comment]
Use this style for animating the react-day-picker

```

.DayPickerInput-OverlayWrapper {
    -webkit-animation-name: slideIn;
    animation-name: slideIn;
    animation-duration: 0.3s;
    -webkit-animation-duration: 0.3s;
    animation-fill-mode: both;
    -webkit-animation-fill-mode: both;
    z-index: 90;
}

@keyframes slideIn {
  0% {
      transform: translateY(1rem);
      opacity: 0;
  }
  100% {
      transform: translateY(0rem);
      opacity: 1;
  }
  0% {
      transform: translateY(1rem);
      opacity: 0;
  }
}

@-webkit-keyframes slideIn {
  0% {
      -webkit-transform: transform;
      -webkit-opacity: 0;
  }
  100% {
      -webkit-transform: translateY(0);
      -webkit-opacity: 1;
  }
  0% {
      -webkit-transform: translateY(1rem);
      -webkit-opacity: 0;
  }
}
```
