### ISSUE TITLE
Prevents change the month when click in outside days

### ISSUE THREAD

**Issue by LucasBassetti** [gpbl/react-day-picker#455]
Hi,

I need use the `enableOutsideDays` but I don't want the month changes when on I click in these days.

Is it possible?

**Comment by gpbl** [comment]
mmm I don't think it is possible... maybe you can find a workaroud with `onDayClick`:

```js
handleDayClick = (day, { outside }) => {
  if (outside) {
     // show another month
     this.daypicker.showMonth(this.state.currentMonth);
  }
}

render() {
  return <DayPicker month={this.state.currentMonth} onDayClick={this.handleDayClick} ref={el => this.daypicker = el } />
}
```

**Comment by j0b0sapi3n** [comment]
I'm having issues with this too, and wish there was a prop to turn off changing months when clicking outside days.

**Comment by ExcitedSpider** [comment]
Is there any hacks or new API to do this trick now?
