### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by brownsmith** [gpbl/react-day-picker#456]
Hello,
Is it possible to set a chosen date in a month to have the tabIndex of 0? For example, when tabbing into the days of a month, that we don't automatically select the first of the month, but instead a chosen day in the month as the first date that is tabbed onto?

**Comment by gpbl** [comment]
> when tabbing ... we don't automatically _select_ the first of the month

(do you mean _focus_? ☝️)

You could use the `onDayFocus` method and with `document.querySelectorAll` find the "selected" day cell element. Then just call the standard DOM `focus()` method on it.
