### ISSUE TITLE
On-the-fly Application of Date Validity

### ISSUE THREAD

**Issue by arjun-menon** [gpbl/react-day-picker#457]
Note: *This is not an issue, but a question regarding a particularly tricky situation and how to handle it.* In my use case scenario, some dates are valid, and some dates are invalid. Unfortunately the existing [date disabling](http://react-day-picker.js.org/examples/disabling.html) mechanism is too simple to handle my scenario. I feel `react-day-picker` might benefit from a more sophisticated date-disabling mechanism. I explain my use case scenario below:

The server has a list of dates that are valid, but it's a very large list that contains the valid dates for several years.

To make things efficient, I am thinking that the client side (web app), should ask the server for a small number of valid dates, dynamically, *as necessary*.

For example, if my `initialDate` for `react-day-picker` is in July 2017, I will ask the server first, which dates are valid in June, July, and August of 2017. Then if the user navigates to February 2016, I would send another request to the server, asking: give me the valid dates of January, February, and March 2016. (The reason I ask for valid dates for the month before/after is so that, the UI is fast/responsive when the user goes to the next/previous month).

In addition, I also want `react-day-picker` to skip months in which there are no valid dates. So that if August 2017 has no valid dates, then, it shows September after July. Similarly if a whole year doesn't have valid dates, it skips that whole year. Basically I'd like it to skip months, until finding a month containing valid dates.

In order to implement checking for valid dates *on-the-fly* (as the user switches between months), it would be helpful to be able to pass in a function (via props) that looks something like `getValidDates(year, month, callback)`. Basically, `react-day-picker` would call this function several times (as necessary) to get valid dates.

As the user navigates through the calendar, `react-day-picker` would call the function, and perhaps display a spinning loading symbol/indicator (that could be passed via prop?), and wait until `callback` is invoked with the list of valid dates before rendering the calendar.

**Comment by gpbl** [comment]
👋 there! 

Not sure I'm following - what is stopping you to implement your requirements? I believe the API gives you all what you need.

There's a `onMonthChange` prop that you can use to fetch data from the server when the calendar displays another month.

You can use the `showMonth` method to change the month and eventually skip the one without valid dates.

Good luck 👍🏽

**Comment by arjun-menon** [comment]
@gpbl The real problem is that I need a way to delay/prevent the month from changing. I would like some kind of hook function, that gets called when the user tries to change to change the month. And instead of changing the month, I want to be able to do somehow overlay a "Loading..." indicator on top of `react-day-picker`. (After that, once I receive a response from my back-end, I could call `showMonth` and show the next month, so that works.)

Would it be okay to add a function to the API that's something like `preMonthChange() => boolean` that gets called when the user tries to change the month? If returned `boolean`is `true`, then the month gets changed, if it is `false`, the user's attempt to change the  change is suppressed. (The "Loading..." overlay is something I could handle/implement outside of `react-day-picker`, so we don't have to pollute `react-day-picker` with it).

**Comment by gpbl** [comment]
@arjun-menon what about a `onBeforeMonthChange` function returning a promise? If the promise is full-filled, the months changes, otherwise it doesn't.
