### ISSUE TITLE
Merge object passed to `localeUtils` with Utils

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#46]

**Comment by gpbl** [comment]
I should extract from `Utils` those function first, otherwise there's the risk a developer would overwrite functions used internally. So `Utils` should be renamed `LocaleUtils`, while `addons/LocaleUtils` should be renamed `MomentUtils` (or something like that). The internal functions could be moved to `Helpers`.

**Comment by gpbl** [comment]
Can't do that since props are immutable: a way for solving this issue is to extends the default LocaleUtils, e.g.:

```js
import LocaleUtils from "react-day-picker/LocaleUtils";
function formatMonthTitle() {
 return "Custom Month Title"
}

<DayPicker localeUtils={{ formatMonthTitle, ...LocaleUtils }} />
```

`LocaleUtils` will be available from v1.1.

**Comment by bvaughn** [comment]
FWYI, (since you pointed to this example in the release notes), I think your example is actually the opposite of what you meant. I think you want...

```javascript
import { localeUtils } from "react-day-picker/utils";
function formatMonthTitle() {
 return "Custom Month Title"
}

<DayPicker localeUtils={{ ...LocaleUtils, formatMonthTitle }} />
```

**Comment by gpbl** [comment]
Thanks! I fixed the comment :+1:
