### ISSUE TITLE
DayPickerInput not working in Typescript 2.0 project

### ISSUE THREAD

**Issue by lpcarignan** [gpbl/react-day-picker#464]
In a Typescript project, when importing DayPickerInput, I get the error message:

`JSX element type 'DayPickerInput' does not have any construct or call signatures.`

In function render()

`render(){
    <DatePickerInput />
}`

I imported the DayPickerInput the following way:

`import DayPickerInput from "react-day-picker/DayPickerInput";`

or directly through its Js file:

`import * as DayPickerInput from "../../node_modules/react-day-picker/DayPickerInput";`

In both cases, I always get the above error message.

**Comment by lpcarignan** [comment]
I've played a bit with the index.d.ts file to include DayPickerInput. With my very limited knowledge of Typed Definition files, I've removed the namespace, added the DayPickerInput props and class declaration of DayPickerInput in the same file. If DayPickerInput supports the same properties as DayPicker, than the additional properties would go in a `DayPickerInputProps` interface.

```
format?: String | Array<String>;
hideOnDayClick?: boolean;
clickUnselectsDay?: boolean;
onDayChange?(day: Date, modifiers: Modifiers): void;
className?: string;
classNames?: ClassNames;
component?: String | React.Component<any, any> | React.PureComponent<any, any>;
```

It didn't fix the problem as I believe the root of the problem is more how DayPickerInput.js is defined as a React component.

When comparing DayPicker.js and DayPickerInput.js, I've noticed these small differences:

DayPickerInput reference `_React$Component` while DayPicker references `_Component`

```
var DayPickerInput = function (_React$Component) {
  _inherits(DayPickerInput, _React$Component);
```

DayPickerInput constructor function (I think) ends with `(_react2.default.Component);` while DayPicker ends with `(_react.Component);`

The event handlers in DayPicker.js seem to be defined outside the constructor function while they are not in DayPickerInput.

I hope this helps. I really would like to use DayPickerInput in my project so let me know if I can be oh help. Let me know if you want a sample project to test it out.

**Comment by gpbl** [comment]
Thanks @lpcarignan for your effort! I'll check better tomorrow :)

Are you sure you are looking to the source code (in the `src` folder) and not to the compiled version? There's also a `yarn dtslint` task to lint the type definition file: it should catch possible errors. 

As not typescript developer myself, I'll need some time to solve this issue.

**Comment by lpcarignan** [comment]
I was referring to `DayPicker.js` and `DayPickerInput.js` under `/lib/src` from the `node_modules/react-day-picker` folder that I got through `npm install react-day-picker --save`.

When I compare those 2 files with those in `/src` folder in GitHub project, under `master` branch, they are not the same. On the other hand, `DayPicker.js` and `DayPickerInput.js` under `/src` seem to both extend React.Component (although not in the same way) and they both have a constructor function (i.e `constructor(props)`).

I can setup a quick Typescript project in my Github account and make it available. It wouldn't take me long to do so if you need to test changes quickly.

**Comment by lpcarignan** [comment]
@gpbl Would you like me to setup a sample Typescript project to help you debug DayPickerInput React component? Let me know if you need my help on this.

**Comment by lpcarignan** [comment]
@gpbl I've created a sample Typescript project where I only call a DayPicker in render() method.

https://github.com/lpcarignan/DayPickerInputTypescript

In `readme.md` file of this project, I describe the steps to install, compile and run the project so you can see the problem I am encountering with DayPicker inside a Typescript application.

**Comment by lpcarignan** [comment]
I've managed to make it work with the DayPicker. I did the following things:

- In `lib/src/DayPicker.js`, I changed the last line to `exports.DayPicker= DayPicker;`
- I moved `index.d.ts` at the root of the react-day-picker folder
- I've cleaned up index.d.ts:
  - Removed the namespace
  - Changed the export on DayPicker to `export class DayPicker extends React.Component<DayPickerProps>`

I'm going to work on DayPickerInput next. Shoud I do a pull request on main branch?

Here's a screenshot of the DayPicker in browser
![image](https://user-images.githubusercontent.com/1015955/29333162-cb19e108-81d0-11e7-8b8e-d00041a9f1a1.png)

**Comment by lpcarignan** [comment]
Got it working with `DayPicker` and `DayPickerInput` together.

As I was saying in previous comment, I moved `index.d.ts` at the root of the `react-day-picker` project. It has Type definition for everything (DayPicker, DayPickerInput, their properties, LocaleUtils, etc).

I've added this new `index.d.ts` at the root of my [sample project](https://github.com/lpcarignan/DayPickerInputTypescript). The sample project has a working example with both controls working in the same page.

`DayPicker.js` at the root of `react-day-picker` has the following content:

```
var DayPicker = require('./lib/src/DayPicker');
var DayPickerInput = require('./lib/src/DayPickerInput');
var DateUtils = require('./lib/src/DateUtils');
var LocaleUtils = require('./lib/src/LocaleUtils');
var ModifiersUtils = require('./lib/src/ModifiersUtils');
var Weekday = require('./lib/src/Weekday').default;
var Navbar = require('./lib/src/Navbar').default;
var PropTypes = require('./lib/src/PropTypes');

module.exports.DayPicker = DayPicker.default || DayPicker;
module.exports.DayPickerInput = DayPickerInput.default || DayPickerInput;
module.exports.DateUtils = DateUtils.default || DateUtils;
module.exports.LocaleUtils = LocaleUtils.default || LocaleUtils;
module.exports.ModifiersUtils = ModifiersUtils.default || ModifiersUtils;
module.exports.WeekdayPropTypes = Weekday.propTypes;
module.exports.NavbarPropTypes = Navbar.propTypes;
module.exports.PropTypes = PropTypes;
```

Notice how I put DayPicker and DayPickerInput in it. 

I don't need `DayPickerInput.js` at the root of `react-day-picker`. I would remove it.

Please inform if I can do a pull request.

Here is a screenshot of both controls:
![workingtypescript](https://user-images.githubusercontent.com/1015955/29385097-84991544-82a4-11e7-8a42-d5b262450b9f.png)

**Comment by gpbl** [comment]
@lpcarignan thanks for the time you are spending on this! however without a PR it is hard to track and comment your changes. would you mind to open a PR and discuss your changes there?
i am back from my vacation i hope i can help you soon on this 🙏🏽

**Comment by lpcarignan** [comment]
Tried to push my branch all morning with ssh and https. Keep getting this error message:

```
ERROR: Permission to gpbl/react-day-picker.git denied to lpcarignan.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Will try again tomorrow. I'm pretty sure it's me as I've looked at your documentation and there doesn't seem to be any constraints on doing a push or a pull request to your repository.

**Comment by gpbl** [comment]
@lpcarignan you need to fork the repo and apply your changes in _your_ repo :) Please read https://help.github.com/articles/working-with-forks/

**Comment by lpcarignan** [comment]
@gpbl Thx for the tip. I'm still new to this Git world.

Pull request created #485

**Comment by gpbl** [comment]
Closed by https://github.com/gpbl/react-day-picker/pull/487
