### ISSUE TITLE
showMonth receives an event proxy object as a callback

### ISSUE THREAD

**Issue by chris-divvito** [gpbl/react-day-picker#467]
When the next/previous month arrows are clicked, they pass the event as first parameter (as expected for event handlers) - this is passed on to the showMonth method as the second parameter (callback) which attempts to call it as a function - obviously this does not work and throws an error.

Working on a PR for this issue

**Comment by gpbl** [comment]
Does it? [This code](https://github.com/gpbl/react-day-picker/blob/master/src/Navbar.js#L45-L49):

```js
handleNextClick = () => {
  if (this.props.onNextClick) {
    this.props.onNextClick();
  }
};
```

should just call the event handlers without arguments. Not sure if I'm overlooking something :) Could  you provide an example? I'd like to avoid to create a new function every time the navbar is rendered.

**Comment by chris-divvito** [comment]
You're totally right, apparently the way it's been implemented in the code I am working on is passing it's own navbar element which uses the props directly, and I just missed it in the stacktrace. Apologies!

**Comment by gpbl** [comment]
no worries 😊
