### ISSUE TITLE
Day not clearable

### ISSUE THREAD

**Issue by bolivier** [gpbl/react-day-picker#469]
A prop called `clearable` or something similar that'd render a small 'x' inside the input that would clear the date on click would be good.

**Comment by gpbl** [comment]
👋 thanks for the suggestion! The input component isn't enhanced by design. Use the [`component` prop](http://react-day-picker.js.org/docs/api-input.html#component) to change the component used to rendered the input fields, e.g. adding one with the clear button.

**Comment by bolivier** [comment]
Cool, thanks!

**Comment by spinybeast** [comment]
@bolivier Hi! Did you manage to do this? I can't understand, how to clear date from other component. Input value is cleared, but there is a date in state of DayPickerInput  and I want to erase it as well. If you managed this, please share the secret)

**Comment by gpbl** [comment]
@spinybeast please share some code, we can update the component to work better for such case.

**Comment by spinybeast** [comment]
@gpbl Finally I solved like this with some css hacks): https://codesandbox.io/s/7m6q1y8xmj
But if it was possible to change date from `component` prop, it could be awesome)
Thanks for amazing job.
