### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by bripkens** [gpbl/react-day-picker#472]
Just wanted to say thank you for this very helpful component, for proper versioning and for a great
 changelog which makes upgrades super easy! 👋🏽  🍹

![thank-you](https://user-images.githubusercontent.com/596443/28716470-bea4fc50-739d-11e7-98d6-12aa5b96907e.png)

**Comment by gpbl** [comment]
ahah thanks for the feedback 😊 ❤️
