### ISSUE TITLE
`onDayClick()` returns 12AM time date

### ISSUE THREAD

**Issue by catamphetamine** [gpbl/react-day-picker#473]
https://codesandbox.io/s/NlwLPp88

See the console log on day click:

```
Tue Jul 04 2017 **12:00:00** GMT+0300 (MSK)
```

**Comment by gpbl** [comment]
Yup this is by design to prevent issues with timezones.
See https://github.com/gpbl/react-day-picker/issues/130 

If you want to change the time, just create a new date with the clicked day:

```js
onDayClick = day => {
    console.log(
        new Date(day.getFullYear(), day.getMonth(), day.getDate())
    );
}
```

**Comment by catamphetamine** [comment]
By the way, in case you're curious, this doesn't prevent issues with timezones.

1. 12:00 in UTC is 00:00 of the next day (not the same day) in UTC+12
2. There are even UTC+13 and [UTC+14](https://en.wikipedia.org/wiki/UTC%2B14:00) along with UTC-12 so there's actually 26 different time zones so the "12:00" workaround is not a complete solution
