### ISSUE TITLE
"Mark or unmark a day as selected when the user clicks a day cell" is not working

### ISSUE THREAD

**Issue by dharanidhanapalan** [gpbl/react-day-picker#476]
Hi,
I am creating a calendar that should contain both http://react-day-picker.js.org/examples/selecting.html and http://react-day-picker.js.org/examples/selecting-click.html funtionalities. 

Since both using "selectedDays" property either  "Display days as selected" or  "mark or unmark a day as selected when the user clicks a day cell" is working.

 But i need both functionalities with separate CSS for "Display days as selected" and  "mark or unmark a day as selected when the user clicks a day cell". 

How do I approach this problem?

Thanks!

**Comment by dharanidhanapalan** [comment]
Hi,
I am creating a calendar that should contain both http://react-day-picker.js.org/examples/selecting.html and http://react-day-picker.js.org/examples/selecting-click.html funtionalities. 

Since both using "selectedDays" property either  "Display days as selected" or  "mark or unmark a day as selected when the user clicks a day cell" is working.

 But i need both functionalities with separate CSS for "Display days as selected" and  "mark or unmark a day as selected when the user clicks a day cell". 

How do I approach this problem?

Thanks!

**Comment by dharanidhanapalan** [comment]
Hi any update in this issue ?

**Comment by gpbl** [comment]
@dharanidhanapalan sorry I'm not sure I understand what you are trying to do.

> But i need both functionalities with separate CSS for "Display days as selected" and "mark or unmark a day as selected when the user clicks a day cell".

What do you mean?

**Comment by drazik** [comment]
What I understand is that you want to display the day picker with some days selected initially, and when the user clicks on a day, you want to display something on it to say "it was initially selected, but you asked to unselect it".

If I'm right, you should use custom modifiers : http://react-day-picker.js.org/examples/modifiers.html

**Comment by dharanidhanapalan** [comment]
@drazik Thanks. I have used modifiers and it worked well.

@gpbl Thanks. I have resolved that using modifiers
