### ISSUE TITLE
DateUtils rangeFromWeekNumber

### ISSUE THREAD

**Issue by AaronBurmeister** [gpbl/react-day-picker#478]
I need  to get the days of a week based on the week number.
I think it would be a good thing if there was something like the reverse of the `DateUtils.getWeekNumber` function which should return a range including the week's days.

**Comment by gpbl** [comment]
I don't think we'll add more function to the DateUtils beyond those already used in the component: you can indeed create your one: https://stackoverflow.com/questions/16590500

What is your use case for this?
