### ISSUE TITLE
Add flow typings

### ISSUE THREAD

**Issue by TrySound** [gpbl/react-day-picker#483]
I'm flow user and would be great to have typings in this repo like for typescript. Do you want me to make a PR?

**Comment by gpbl** [comment]
That would be awesome 👍🏽 go for it! If you find some troubles please write back here.

**Comment by gpbl** [comment]
@TrySound should we give up with flow types? I don't see much interested for this as for TypeScript typings.

**Comment by TrySound** [comment]
@gpbl Nope, I'll take care of it for major release.

**Comment by gpbl** [comment]
Sounds great! Thanks!

**Comment by arjun-menon** [comment]
Would the types be added here, or to the [https://github.com/flowtype/flow-typed](flow-typed) project?

**Comment by gpbl** [comment]
@arjun-menon the idea is to add them here

**Comment by gpbl** [comment]
Makes flow type still sense? 

f we want still to add flow-types then yes, better in https://github.com/gpbl/react-day-picker/issues/flow-typed.
