### ISSUE TITLE
DayPickerInput + Locale with Moment

### ISSUE THREAD

**Issue by ser007** [gpbl/react-day-picker#489]
Great project

I'm finding it difficult to translate the labels with Momentjs and DayPickerInput

Follows [the code](https://codesandbox.io/s/2z1jyr2v4n)

What am I doing wrong?

Thank you

**Comment by gpbl** [comment]
@ser007 the case of the `localeUtils` prop is wrong:

https://codesandbox.io/s/nr90y84ojl

Sorry for the confusion :)
