### ISSUE TITLE
Selecting day on calendar with DayPickerInput and format=Array throws error

### ISSUE THREAD

**Issue by alanasim** [gpbl/react-day-picker#491]
Selecting day in overlay calendar while using DayPickerInput with format=Array<string> throws error "Uncaught TypeError: format.match is not a function" from moment.js.

Traced this to moment.js parsing accepting an array of string formats to check against but moment.format() expects a single string as argument [[doc]](https://momentjs.com/docs/#/displaying/format/)

Example:
https://codesandbox.io/s/5wz092n1pk

Maybe as an easy compromise/fix when format is given as an array default to formatting by the first array element?

**Comment by gpbl** [comment]
This is indeed a bug! Thanks for reporting it 👍

**Comment by gpbl** [comment]
Fixed in `v6.2.0`.
