### ISSUE TITLE
console warning: Received `false` for non-boolean attribute `tabIndex` (React 16)

### ISSUE THREAD

**Issue by vulcanoidlogic** [gpbl/react-day-picker#493]
Please see:  https://codesandbox.io/s/ory016yr9 with developer tools open.

Using react 16.0.0-rc.2, react-day-picker 6.1.0

```jsx
<DayPicker canChangeMonth={false} selectedDays={new Date()} />
```

Displays the following in developer console:

```
**Warning: Received `false` for non-boolean attribute `tabIndex`. If this is expected, cast the value to a string.
    in div (created by DayPicker)
    in div (created by DayPicker)**
```

I don't know how to create a Pull Request, but on my local, the warning disappears if I modify 
DayPicker.js.

```diff
- tabIndex: this.props.canChangeMonth && this.props.tabIndex,
+ tabIndex: (this.props.canChangeMonth && this.props.tabIndex ? this.props.tabIndex : "-1"),
```

Thank you.

**Comment by gpbl** [comment]
Thanks @vulcanoidlogic for the report!

**Comment by gpbl** [comment]
Fixed in #501

**Comment by gpbl** [comment]
Published as 6.2.0.

**Comment by mhdSid** [comment]
I say the people who are responsible for REACT should fix this - cast whatever they need but not force us to cast ourselves.

**Comment by davidspiess** [comment]
@gpbl  can this fix be backported to the 5.x.x branch?

**Comment by gpbl** [comment]
@davidspiess I think yes? I've never published a prev version! Try to send a PR, versions are tagged. Thanks
