### ISSUE TITLE
DayPickerInput Update From New Props

### ISSUE THREAD

**Issue by kradical** [gpbl/react-day-picker#494]
Hello,

First of all thank you for maintaining this project! It has saved me a lot of time :).

I am currently using it in an app that uses redux-form everything works awesome except when the props get updated the logic of `DayPickerInput.componentWillReceiveProps` relies on state rather than props.

I will open up a PR and link it here. I believe I have a good fix.

🐛 If you are reporting a bug, show us how to reproduce it here:
https://codesandbox.io/s/v10o1xnm95
* type in `01/01/2007`
* click the header to change the month to February
* type in `01/01/2009`

No update of the DayPickerInput.

**Comment by gpbl** [comment]
Closing this as #495 has been merged. Thanks @kradical for your contribution 💯

**Comment by gpbl** [comment]
The fix has been published as in v6.2.0.

**Comment by kradical** [comment]
I think it is in 6.1.1, Inspecting the code for tag 6.1.1 it seems to be. And I updated to 6.1.1 and could remove my hacky workaround! Cheers!
