### ISSUE TITLE
Styles are not loaded

### ISSUE THREAD

**Issue by adred** [gpbl/react-day-picker#496]
This seems like a really good alternative to react-datepicker cos it provides custom styling. However, a simple setup following the documentation does not work. The styles do not load. I'm using it with redux-form; the styling is just broken. Anyone else having this issue?

**Comment by gpbl** [comment]
Have you read this first? http://react-day-picker.js.org/docs/styling.html
If there’s something not clear, I’ll be happy to help!

**Comment by adred** [comment]
Yes I read that. The documentation is very clear actually but my implementation does not work.
```js
import React, { Component } from 'react'
import { Field } from 'redux-form/immutable'
import { DayPickerInput } from 'react-day-picker'

import 'react-day-picker/lib/style.css'

class DateTextField extends Component {
  renderField ({ label }) {
    return (
      <div>
        <span>{label}</span>
        <DayPickerInput />
      </div>
    )
  }
  render () {
    const { name, label } = this.props

    return (
      <Field name={name} component={this.renderField} label={label} />
    )
  }
}

export default DateTextField

```
Any ideas?

**Comment by adred** [comment]
So when I added `<link rel="stylesheet" href="https://unpkg.com/react-day-picker/lib/style.css">` in the `<head>` tag, it worked. Not sure what's happening.

**Comment by gpbl** [comment]
@adred I think there's a problem in the way you import CSS from JavaScript:

```
import 'react-day-picker/lib/style.css'
```

Are you sure that the CSS is actually imported? E.g. using [css-loader](https://github.com/webpack-contrib/css-loader) and included it in your final CSS file?

**Comment by shivam16parashar** [comment]
i am also facing the same issue

**Comment by jatintiwari** [comment]
@shivam16parashar any luck, facing same issue

**Comment by TsengTofu** [comment]
I just met the same problem.
And the solution below is work for me.
**<Calendar.js>** or your calendar component name.
`import "./Calendar.sass";`
 
**<Calendar.sass>** or your calendar component style name.
import the style.css form node_modules.
`@import "../../../../../node_modules/react-day-picker/lib/style";`

**Comment by EngAtyaMohammed** [comment]
> So when I added `<link rel="stylesheet" href="https://unpkg.com/react-day-picker/lib/style.css">` in the `<head>` tag, it worked. Not sure what's happening.

thank you so much
