### ISSUE TITLE
DayPickerInput : locale and css not working correctly

### ISSUE THREAD

**Issue by Patafoin** [gpbl/react-day-picker#506]
Hi,

Just created a new create-react-app
added react-day-picker and moment packages

into app.js : 

```jsx
import moment from 'moment'
import DayPickerInput from 'react-day-picker/DayPickerInput';
import 'react-day-picker/lib/style.css';
```

added const like said in this page : http://react-day-picker.js.org/examples/localization.html
then used daypickerinput like this :

```jsx
<DayPickerInput months={MONTHS[locale]}
                  weekdaysLong={WEEKDAYS_LONG[locale]}
                  weekdaysShort={WEEKDAYS_SHORT[locale]}
                  firstDayOfWeek={FIRST_DAY_OF_WEEK[locale]}
                  labels={LABELS[locale]}
                  placeholder="JJ/MM/AAAA"  />
```

My first problem is that locale is not applied.
console saying this : 

```
Warning: Unknown props `months`, `weekdaysLong`, `weekdaysShort`, `firstDayOfWeek`, `labels` on <input> tag. Remove these props from the element.
```

Second problem : I don't know why but using bootstrap seems to interfer with this control's css.
I tried to force className but nothing works.

any idea ?

**Comment by gpbl** [comment]
@Patafoin you can use the `MomentLocaleUtils` provided for translating strings with moment.js: http://react-day-picker.js.org/docs/localization.html#moment

See this CodeSandbox as example with the DayPickerInput: https://codesandbox.io/s/7mnj991x1q

Your code is not working because those props should be passed to the DayPicker using the `dayPickerProps` prop:

```jsx
<DayPickerInput
    placeholder="JJ/MM/AAAA"
    dayPickerProps={{
        months: MONTHS[locale],
        weekdaysLong: WEEKDAYS_LONG[locale],
        firstDayOfWeek: FIRST_DAY_OF_WEEK[locale],
        labels: LABELS[locale]
      }}
    }
</DayPickerInput>
```

Hope this helps! I'll add some docs to better explain it.

**Comment by gpbl** [comment]
> I don't know why but using bootstrap seems to interfer with this control's css.
I tried to force className but nothing works.

Please open a new issue and how to replicate it in this code sandbox: https://codesandbox.io/s/XDAE3x0W8 thanks!

**Comment by joalcava** [comment]
Hi @gpbl 
First of all, thank you for the awesome work with react-day-picker. I've just spend about 3 hours messing arround with locale just to realize that one have to put  the locale realated properties inside dayPickerProps, it would be nice if you can point it out in the docs.
