### ISSUE TITLE
Move input related props to `inputProps`

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#508]
In DayPickerInput, we are spreading input props from the component, e.g.:

```jsx
// Will render 
// <input name="birthday" autocomplete={false} placeholder="Enter a date" />
<DayPickerInput 
    name="birthday"
    autocomplete={false}
    placeholder="Enter a date"
/>
```

We are also using props that are not compatible with `input`, or that may override `input` props:

```jsx
<DayPickerInput 
    format="LL" /* format will not be passed down to <input> */
    name="birthday"
    autocomplete={false}
    placeholder="Enter a date"
/>
```

This may create issues as React 16 now supports custom dom attributes should pass https://reactjs.org/blog/2017/09/26/react-v16.0.html#support-for-custom-dom-attributes

So to fix it, we should add a `inputProps` prop similar to what `dayPickerProps` does:

**Before**

```jsx
<DayPickerInput 
    name="birthday"
    autocomplete={false}
    placeholder="Enter a date"
/>
```

**After**

```jsx
<DayPickerInput 
    inputProps={{
        name: 'birthday',
        autocomplete: false,
        placeholder: 'Enter a date'
    }}
/>
```

**Comment by abiduzz420** [comment]
Can I take up this issue ? @gpbl

**Comment by gpbl** [comment]
@abiduzz420 that would be awesome! 

To keep this in the next minor release, please don’t change the current behaviour - just spread `props.inputProps` to the `input` element. In the next major release, we can remove the current behavior.

**Comment by seeliang** [comment]
hi @gpbl, I could not get the autoComplete set work unless 
```javascript 
Input,
            _extends(
              {
                ref: function ref(el) {
                  return (_this6.input = el);
                },
                placeholder: this.props.placeholder
                autocomplete: this.props.autocomplete // add this
              },
```

could you help when you have time? many thanks

**Comment by vik7607** [comment]
I want DayPickerInput should be like text field not inputwithBox  How can i achieve input with text field and drop down for DayPickerInput
