### ISSUE TITLE
Use Gatsby for the website

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#515]
The [website](http://react-day-picker.js.org) is built using Jekyll. The main issue I have with it is that I can't easily display and run the code examples in the docs (now I'm parsing the example code with  babel client-side 😱). 

Also, with Jekyll it is hard to run code on the local machine while developing (for example, when I'm developing a new feature, I need to test it in a browser). 

Gatsby has been updated and it is used for the react website as well. I feel it's ready for this project too!

**Comment by PeterKottas** [comment]
It seems you are already working on it mate. Just a little side note though. I've been looking into this a little while ago for https://github.com/PeterKottas/guestbell-forms. Now obviously that one is incomparably simpler than what you're after, but the big difference is it's full spa using plain react + react-router for most part. We've been very happy with the dev experience there, it deploys straight to gh pages. There's some more useful things there but as you might have already put work into this solution, I am keeping it simple and up to you to check that out. I'll be happy to answer any questions if you find any of it useful.

**Comment by PeterKottas** [comment]
This is the link for the "docs" app. https://github.com/PeterKottas/guestbell-forms/tree/master/src/demo/ClientApp

**Comment by gpbl** [comment]
@PeterKottas I went with Gatsby because it creates static pages and runs react code i can use for the examples :)
