### ISSUE TITLE
Use rollup instead of webpack

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#516]
[Many](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c) [people](https://stackoverflow.com/questions/43219030) are suggesting to use [rollup](https://rollupjs.org) instead of webpack to build npm modules. This could reduce the final bundle size.

**Comment by TrySound** [comment]
I can handle it.

**Comment by gpbl** [comment]
@TrySound awesome thanks! 👍🏽 
I’ve added you as collaborator to the repo.

**Comment by TrySound** [comment]
Cool!

**Comment by tobi-ajala** [comment]
Crickets.

**Comment by gpbl** [comment]
@tobi-ajala no help ? 🙏🏽

**Comment by gpbl** [comment]
Next version will use rollup 🧻⬆️ 

https://github.com/gpbl/react-day-picker/pull/944
