### ISSUE TITLE
Focus input fied of day picker

### ISSUE THREAD

**Issue by usman-maavan** [gpbl/react-day-picker#522]
Hi, 
This is not an issue exactly. I have looked around quite a lot but I am unable to find the issue I am facing. Is there a way i can give the Ref to input field of day picker and get the instance of the input field to focus on it instead of using autoFocus.

Thanks

**Comment by gpbl** [comment]
Yes, you can use the `input` instance property. 
Check out this example: https://codesandbox.io/s/y7qw286x0x

**Comment by usman-maavan** [comment]
Hi,
Thanks for the quick response and the great example. Its working :)
