### ISSUE TITLE
todayButton is confusingly named

### ISSUE THREAD

**Issue by tomchambers2** [gpbl/react-day-picker#528]
I would expect a button that says 'today' to reset the selection to the current day and remove the existing selection, but it only moves the month.

This is why I was confused, I expect it to select today:
![image](https://user-images.githubusercontent.com/4549380/32049837-7b4c9bee-ba46-11e7-872d-2231a32f20fd.png)
https://giphy.com/gifs/3ohhwpD3O0gUDLfK2Q/html5

**Comment by gpbl** [comment]
Thanks for the feedback! 

Since the Day Picker doesn’t hold the selected days in its state, we cannot do that. However we could add a `onTodayButtonClick` event handler so the developer can choose what to do when the Button is clicked. 

What do you think?

**Comment by tomchambers2** [comment]
That might be helpful. The way I did it was to add my own button underneath since the state is handled by the component as you say, so not essential. Main thing I would suggest is a clearer name could be `currentMonthButton` or something that makes it obvious that it changes the view to the month.

**Comment by gpbl** [comment]
> The way I did it was to add my own button underneath since the state is handled by the component as you say, so not essential.

Yeah this is another way. Added #529. Your feedback give me the idea to implement something similar for the input field (see #530). Thanks!

**Comment by tomchambers2** [comment]
👍
