### ISSUE TITLE
Typescript typings have no default export

### ISSUE THREAD

**Issue by firsttris** [gpbl/react-day-picker#533]
Holla,
before it was possible to import react-day-picker in typescript using the following construct:

```import DayPicker from 'react-day-picker';```

In version 6.2.1 the tsc compiler complains that 'react-day-picker' has no default export.

![image](https://user-images.githubusercontent.com/1709260/32143504-896dfebe-bcaa-11e7-9f23-bd214c58bc4b.png)

but if a change:
```
// **\node_modules\react-day-picker\types\index.d.ts
// TypeScript Version: 2.2

import { DayPicker } from "./DayPicker";
// We need to use 'export =' to be compatible with the 'module.exports = DayPicker.default || DayPicker' syntax
// in DayPicker.js in the final NPM package.
export = DayPicker;
```

to
```
// **\node_modules\react-day-picker\types\index.d.ts
// TypeScript Version: 2.2

import { DayPicker } from "./DayPicker";
// We need to use 'export =' to be compatible with the 'module.exports = DayPicker.default || DayPicker' syntax
// in DayPicker.js in the final NPM package.
export default DayPicker;
```

the import is working again.
Im using 6.2.1 with the integrated typings.

whats the correct way to import in typescript ?

regards
Tristan

**Comment by PeterKottas** [comment]
This is definitely broken/undocumented. I see the same problem.

**Comment by firsttris** [comment]
currently its possible to use: 
`import DayPicker = require('react-day-picker');` 
to get working typings with 6.2.1

**Comment by gpbl** [comment]
#539 has a longer discussion which I'd like to link here.

**Comment by gpbl** [comment]
I'd just plan a major release with the right export. I'd like also to remove the common.js default exports which are the root of all the problems 😄

**Comment by gpbl** [comment]
c221e2dd35b412f4214b5c740062385b78d4d9f0 should fix the issues
