### ISSUE TITLE
Passing date to Redux through a 'onChange' handler

### ISSUE THREAD

**Issue by dreamyguy** [gpbl/react-day-picker#534]
I've been using `onChange` to catch changes on normal input/textarea fields and save the new input value to state through a Redux action:

```jsx
<input value={this.props.value} onChange={this.handleSaveDeadline}/>
```

...but doing this doesn't give me the same results when selecting a date with **DayPickerInput** component (which picks the date up, but doesn't emit a change event):

```jsx
<DayPickerInput placeholder="DD/MM/ÅÅÅÅ" format="DD/MM/YYYY" value={this.getTime(this.props.value)} onChange={this.handleSaveDeadline}/>
```

If I begin typing on the field, though, I get the changes to be picked-up, but at the same time the date gets all weird (deleting `7` from `2017` on `10/10/2017` gives me `10/10/0201`).

All `handleSaveDeadline` does is to listen to events on `event.target.value`:

```jsx
  constructor() {
    super();
    this.handleSaveDeadline = this.saveDeadline.bind(this);
  }
  saveDeadline(event) {
    this.props.dispatch(setDeadline(event.target.value));
  }
```

I totally get it that my description might be hard to understand, but a TLDR; would be that I need changes in the input value to be detected and passed forward.

**Comment by gpbl** [comment]
Hi @dreamyguy, would you like to reproduce the behavior you are getting in a CodeSandbox? https://codesandbox.io/s/XDAE3x0W8

[here](https://github.com/gpbl/react-day-picker/blob/master/src/DayPickerInput.js#L200-L203) is where we are passing the event to your `onChange` prop. I don't see why it doesn't work for you.

Have you tried with the `onDayChange` prop and see how it works?

**Comment by dreamyguy** [comment]
I managed to solve it, but had to think a bit outside the box. 😄 

I thought of posting just the bare minimum, but it wouldn't make sense out of context. So here's the component:

```
import React, {Component} from 'react';
import {connect} from 'react-redux';
// Redux action that writes to 'currentSector' object
import {setDeadline} from '../redux/actions/actionsSectors';
import PropTypes from 'prop-types';
import moment from 'moment';
import DayPickerInput from 'react-day-picker/DayPickerInput';
import '../../../node_modules/react-day-picker/lib/style.css';

class FieldDeadline extends Component {
  constructor() {
    super();
    this.handleSaveDeadline = this.saveDeadline.bind(this);
  }
  // Reset default initial date as it originally comes from the db
  resetInitialDate(time) {
    const initialDate = '0001-01-01T00:00:00';
    let t = time.toString();
    if (initialDate === t) {
      t = '';
      return t;
    }
    return time;
  }
  // Convert time to Moment's format
  getTime(time) {
    const t = moment(time).format('DD/MM/YYYY');
    return t;
  }
  // Dispatch action that writes to Redux's state
  saveDeadline(selectedDay) {
    this.props.dispatch(setDeadline(this.getTime(selectedDay)));
  }
  render() {
    // Necessary check, as 'value' is constantly retrieved and written to Redux's state
    const value = this.resetInitialDate(this.props.value);
    return (
      <DayPickerInput placeholder="DD/MM/ÅÅÅÅ" format="DD/MM/YYYY" value={value} onDayChange={this.handleSaveDeadline}/>
    );
  }
}

FieldDeadline.propTypes = {
  currentSector: PropTypes.object,
  value: PropTypes.string,
  dispatch: PropTypes.func
};

export default connect(store => {
  return {
    currentSector: store.sectors.currentSector
  };
})(FieldDeadline);
```

It works beautifully. Thanks a ton for this component! ✨
