### ISSUE TITLE
toMonth not being respected when numberOfMonths greater than 1

### ISSUE THREAD

**Issue by leojh** [gpbl/react-day-picker#543]
Please take a look at https://codesandbox.io/s/pkxypqr6kx

Basically, if `toMonth` is set to the current month, but `numberOfMonths` is 2 (for example), the date picker will display both this month (ok) and the next month (outside of range).

In this case, the date picker should display last month first, then the current month.

**Comment by gpbl** [comment]
Fixed with #556

**Comment by leojh** [comment]
Verified in v7!
