### ISSUE TITLE
Selected Date cannot be re-selected again

### ISSUE THREAD

**Issue by Swati020494** [gpbl/react-day-picker#545]
The issue is that the day that is already selected , when clicked/selected again, un-selects the selected date, is there a way to remove this un-selecting feature(ie. if the date already selected, is again selected, then it should show the same date/do nothing).

**Comment by hydrognomik** [comment]
You can check modifier of the clicked day. Try [this](https://gist.github.com/hydrognomik/0e952116d74a16eb7d050b5fcc2aa3c9#file-example-jsx-L11).
