### ISSUE TITLE
Selected Date cannot be re-selected again In DayPickerInput

### ISSUE THREAD

**Issue by Swati020494** [gpbl/react-day-picker#553]
I am facing a problem using the DayPickerInput field,
The following happens when date is selected the **first time**:
![image](https://user-images.githubusercontent.com/14866260/32891118-7b27ac6e-caf7-11e7-81d7-af3c99ff4ad5.png)
The following happens when same date is selected the **second time**:
![image](https://user-images.githubusercontent.com/14866260/32891334-256bf7b6-caf8-11e7-8c14-b3ea7cf52848.png)

**Expected output**:
(Same as it happens when in the first time)
But the box unchecks!
`<**DayPickerInput**
selectedDays={validator.convertToDate(this.props.open_date)}
onDayChange={(e)=>this.props.onDateChange(e,'open_date')}
value = {validator.convertToDate(this.props.open_date)}
dayPickerProps = {{disabledDays : { after : new Date()}}}/>`

**Comment by dreamyguy** [comment]
I haven't tried to reproduce your problem, but I'm not experiencing it. I see that `disabledDays` is present in your code, but is not supposed to be supported yet, not until the next release, which is pending. More on that on https://github.com/gpbl/react-day-picker/issues/554.

**Comment by gpbl** [comment]
Yup closing as dup of #554. Thanks!

**Comment by gpbl** [comment]
Published in v7!
