### ISSUE TITLE
[Firefox] scrollIntoView() error on the docs page

### ISSUE THREAD

**Issue by selim13** [gpbl/react-day-picker#555]
```
TypeError: 'block' member of ScrollIntoViewOptions 'center' is not a valid value for enumeration ScrollLogicalPosition. Menu.js:11:6
```
Tested on Firefox 52.5 and 57.0.
Probably due to https://bugzilla.mozilla.org/show_bug.cgi?id=1389274 which will be fixed in Firefox 58

This also breaks all calendar examples, making them non interactive.

**Comment by gpbl** [comment]
BTW this should be solved scrolling the page, e.g. with [react-scroll](https://github.com/fisshy/react-scroll)

**Comment by gpbl** [comment]
Thanks for the report - now it should work!
