### ISSUE TITLE
DayPicker modifiers not working with CSS Modules

### ISSUE THREAD

**Issue by RuslanYurchenko** [gpbl/react-day-picker#558]
Hi there, seems like modifiers not working when a CSS Modules enabled. 
It grabs all the styles properly but modifiers functionality don't work.

An issue only with `classNames={styles}` prop.
Tested with default disabled and selected modifiers from example.
`console.log` inside `handleDayClick = (day, {selected, disabled})` gets `selected` and `disabled` always `undefined` with a CSS modules.

Possible related to #504.

**Comment by gpbl** [comment]
Are you using DayPicker or DayPickerInput?

**Comment by RuslanYurchenko** [comment]
DayPicker

**Comment by gpbl** [comment]
The modifiers are the class names you import from the css module, so `selected` or `disabled` will be always undefined. This should work instead:

```js
import styles from './MyCSSModule.css';
// ...
handleDayClick(day, modifiers) {
    console.log(modifiers[styles.disabled]);
}
```

**Comment by gpbl** [comment]
If it works for you please close this issue, thanks!

**Comment by RuslanYurchenko** [comment]
@gpbl Thanks! It would be nice to add a small paragraph with this case to the docs.
