### ISSUE TITLE
Improve default style

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#565]
I'd like to upgrade the default style included. Style should stay minimal but look a bit more modern :)

**Comment by gpbl** [comment]
Result so far: 

<img width="263" alt="screen shot 2017-11-25 at 00 27 48" src="https://user-images.githubusercontent.com/120693/33225423-82484ce8-d177-11e7-8547-f7544fe0fabd.png">

**Comment by pimmey** [comment]
`old-style.css` doesn't appear to be in the package 😞

**Comment by gpbl** [comment]
@pimmey it is [here](https://github.com/gpbl/react-day-picker/blob/v6.2.1/src/style.css)!
