### ISSUE TITLE
Please tell me how can i use the datepicker using CDN

### ISSUE THREAD

**Issue by er-jyotirmoy-nath** [gpbl/react-day-picker#570]
Please tell me how can i use the datepicker using CDN

**Comment by gpbl** [comment]
Include the component without installing:

```html
<script src="https://unpkg.com/react-day-picker/lib/daypicker.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/react-day-picker/lib/style.css">
```

The components will be available as `window.DayPicker` and `window.DayPicker.Input`.

http://react-day-picker.js.org/docs/getting-started

**Comment by er-jyotirmoy-nath** [comment]
Thank you so much for the response but I tried that but dinot work i am opening a new issue for that
