### ISSUE TITLE
Month always off by 1

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [gpbl/react-day-picker#577]
Looking at the docs (http://react-day-picker.js.org/examples/selected)
you can see that the selected  dates to render are:

```js
 new Date(2017, 3, 12),
        new Date(2017, 3, 2),
```
in this example:

```jsx
export default function Example() {
  return (
    <DayPicker
      initialMonth={new Date(2017, 3)}
      selectedDays={[
        new Date(2017, 3, 12),
        new Date(2017, 3, 2),
        {
          after: new Date(2017, 3, 20),
          before: new Date(2017, 3, 25),
        },
      ]}
    />
  );
}
```

These dates actually render in April. This happens in my own testing too. For example if I add dates into December of 2017 they show up in Jan 18.  

I'm happy to look into fixing something, but just want to ensure I'm not missing something?

thanks for the great component.

**Comment by gpbl** [comment]
Yes this is how dates in javascript work, just keep it in mind: months are 0-11 😌

**Comment by MatthewJamesBoyle** [comment]
Sure- I consider this a flaw with JS though and personally find value in incrementing it to be 1-12 to match other languages. This makes hydrating the date from a server more intuitive. :)

**Comment by gpbl** [comment]
I know :) But we built the component using the native `Date` implementation so we can't do much about it. You can use external libraries like moment.js or date-fns to parse your strings to date objects.

**Comment by MatthewJamesBoyle** [comment]
thanks for the quick response 👍
