### ISSUE TITLE
Values in January are not highlighted like other months

### ISSUE THREAD

**Issue by mshwery** [gpbl/react-day-picker#578]
Hey!

I found a strange bug. Values only in the month of January (both using `Date` and `string` types) are not highlighted like values in other months.

https://codesandbox.io/s/4qqmlv7w19

**Comment by gpbl** [comment]
Thanks for the report! Indeed this is weird. Also, on Safari I get `undefined is not an object (evaluating 'firstWeek.length')` error.

**Comment by gpbl** [comment]
Found the bug! Fixes on v7.0.4.

**Comment by mshwery** [comment]
Nice! Thanks for the super quick bug fix.

**Comment by junmich** [comment]
Hello, I got an error on Safari browser. `TypeError: undefined is not an object (evaluating 'firstWeek.length')`, DayPickerInput works fine in other browsers. I used "react-day-picker": "^7.2.2"

Thanks

**Comment by gpbl** [comment]
@junmich please open another issue, thanks.
