### ISSUE TITLE
Add support for readonly attribute on DayPickerInput

### ISSUE THREAD

**Issue by dreamyguy** [gpbl/react-day-picker#583]
In my current implementation of **DayPickerInput**, the component's markup looks like this:

```
<div class="DayPickerInput">
  <input placeholder="DD/MM/ÅÅÅÅ" value="07/12/2017">
</div>
```

The component is working well, but I'm having issues validating user input.

I suppose it is related to an aggressive input event handler that saves the input to state as one types. I get strange side-effects if I backspace all the way (the previously selected date returns as a value); the user gets to type plain text; etc.

The easiest way to avoid any of these problems would be to set the attribute `readonly="readonly"` to the input field, or just `readonly`, like so:

```
<div class="DayPickerInput">
  <input placeholder="DD/MM/ÅÅÅÅ" value="07/12/2017" readonly>
</div>
```

That way, the user would only be able to pick dates from the calendar, simplifying validation. 🎱

**Comment by gpbl** [comment]
@dreamyguy you can add any prop to the `input` field using the [`inputProps`](http://react-day-picker.js.org/api/DayPickerInput#inputProps) prop.

**Comment by dreamyguy** [comment]
@gpbl would this be correct, then?

```
<DayPickerInput
  key={this.setUniqueIdentifier()}
  placeholder="DD/MM/ÅÅÅÅ"
  format="DD/MM/YYYY"
  value={value}
  onDayChange={this.handleSaveDeadlineAndSetActionStatus}
  dayPickerProps={{
    locale: 'nb',
    months: MONTHS,
    weekdaysLong: WEEKDAYS_LONG,
    weekdaysShort: WEEKDAYS_SHORT
  }}
  inputProps={{
    readonly: 'readonly'
  }}
/>
```

The `inputProps={{readonly: 'readonly'}}` is the only addition to the current code. It didn't work, though.

**Comment by gpbl** [comment]
Yes, seems right. Please try to reproduce your problem in a code sandbox. Here it looks right: https://codesandbox.io/s/9oowj1zmpr

**Comment by dreamyguy** [comment]
Interesting. I managed to pass `title` as an attribute by using:

```
inputProps={{
  title: 'title',
  readonly: 'readonly'
}}
```

...but `readonly`was not passed to the component. Instead I got an error: `Warning: Unknown DOM property readonly. Did you mean readOnly?`.

The sandbox https://codesandbox.io/s/9oowj1zmpr honoured the error by outputting it on console, but the component got the attribute in spite of the error.

**Comment by dreamyguy** [comment]
The error seems to be quite generic, so I filed it as an issue on React's project: https://github.com/facebook/react/issues/11785

**Comment by gpbl** [comment]
@dreamyguy please read the warning from React, it states you should use `readOnly` instead. 

This works as expected: https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes

```jsx
<DayPickerInput
        inputProps={{ readOnly: true }}
        placeholder="DD/MM/YYYY"
        format="DD/MM/YYYY"
      />
```

**Comment by dreamyguy** [comment]
It does work indeed. I did read the warning, but didn't get I should set `readOnly` to true. Learning every day!

Thanks a lot @gpbl ! 🦄 ✨
