### ISSUE TITLE
onBlur is triggered before onDayChange

### ISSUE THREAD

**Issue by mavarazy** [gpbl/react-day-picker#589]
Reproduces constantly after second select
https://codesandbox.io/s/k1rpjk29o

I'm integrating react-day-picker with react-jsonschema-form and I use onBlur as indicator of when input is done, to update a parent form. I expected onBlur to be called after onDayChange, but this is not true.

To work around this I've added 100 ms delay, before updating parent form.

**Comment by gpbl** [comment]
Yes, the delay is the best way to handle this case. Thanks for the heads up!

**Comment by ekaitzht** [comment]
Could you open the example how you fix it? @mavarazy  THanks

**Comment by mavarazy** [comment]
https://github.com/RxNT/react-jsonschema-form-extras/blob/a2af51bb25e31ce178ce3f48d271cf12233a3b67/src/ReactDatePicker.js

Line 41 & 80 for the reference
