### ISSUE TITLE
 Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by dmtrKovalenko** [gpbl/react-day-picker#592]
I have started using your awsome picker and got the following error

`Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.
Check the render method of 'DayPickerInput'.`
Also I am getting error `Uncaught TypeError: Cannot read property 'focus' of null`

Seems that DayPickerInput is a stateless component, but it defines a ref.

Environment

| Tech                | Version |
|---------------------|---------|
| React-day-picker  |   7.0.5      |
| React               |   16.2.0      |
| Browser             |    Chrome 63     |
| Platform            |      MacOS    |

**Comment by gpbl** [comment]
Hi, could you reproduce this in a code sandbox? The component is not stateless, actually.

**Comment by Ronny25** [comment]
Having the same issue.
React-day-picker v7.0.6
React v16.2.0
Browser v63
Platform Ubuntu 16.04

Using custom input component as a bound function in constructor but I don't think that's the point.

**Comment by gpbl** [comment]
Please an example to reproduce this 🙏🏽

**Comment by rodallanmac** [comment]
Hi @gpbl 

My problem is that I need to use custom refs in the DayPickerInput so that onSubmit picks up the changed value. But it seems that they get appended by the component logic? Does that help

  
                  <DayPickerInput
                    onDayClick={this.handleDayClick}
                    placeholder= {doc && doc.dateEnd}
                    ref={dateStart => (this.dateStart = dateStart)}
                    inputProps={{
                      name: 'dateStart',
                  }}
                  />

**Comment by TrySound** [comment]
@rodallanmac Why not listen onChange, write to local state and collect data from state on summit?

**Comment by rodallanmac** [comment]
Hi @TrySound 

You a star! Whilst this does work  it would be so much cleaner if @gpbl allowed us to attach a custom ref to his input component that is generated with DayPickerInput. 

  handleDayChange(selectedDay ) {
    this.setState({
      selectedDay,
    });
    let v = document.getElementById('thisStartDate')
    v.value = selectedDay.toLocaleDateString()
  }

**Comment by gpbl** [comment]
> it would be so much cleaner if @gpbl allowed us to attach a custom ref to his input component that is generated with DayPickerInput.

@rodallanmac please send a PR, thanks!

**Comment by KumarAbhirup** [comment]
Same problem here. I am not using any kinda ref.
```
<DayPickerInput 
                        component={props => (
                          <Form.Input label='Birthdate' onChange={this.handleChange} {...props} disabled />
                        )} 
                        formatDate={formatDate}
                        parseDate={parseDate}
                        placeholder={`${formatDate(new Date())}`}
                        onDayChange={this.handleDayChange}
                        value={this.state.birthday}
                      />
```

This is the error: `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Need help.

**Comment by darrenterhune** [comment]
@KumarAbhirup try this
```js
import React, { Component } from 'react';
import PropTypes from 'prop-types';

export default class BirthDateCalendar extends Component {
  static propTypes = {};

  render = () => (
    <Form.Input label='Birthdate' onChange={this.handleChange} {...this.props} disabled />
  );
}

<DayPickerInput component={BirthDateCalendar} />
```

**Comment by mnsr** [comment]
I know this is an old issue, but this came up when i googled the error. It's solved by using React.forwardRef. Just thought it'd help someone else looking to solve this error.

e.g.

```javascript
const MyDatePicker = () => {

  const renderInput = React.forwardRef(props => {
    <input type="text" className="my-input" {...props} />
  });

  return (
    <DayPickerInput component{renderInput} />
  )

}

**Comment by redaxmedia** [comment]
No luck with `React.forwardRef` but `inputProps={ { ref: null } }` solved it for me...

**Comment by MayaraRMA** [comment]
Thanks @redaxmedia, I had the same problem.

**Comment by adhiljuvane** [comment]
> I know this is an old issue, but this came up when i googled the error. It's solved by using React.forwardRef. Just thought it'd help someone else looking to solve this error.
> 
> e.g.
> 
> ```js
> const MyDatePicker = () => {
> 
>   const renderInput = React.forwardRef(props => {
>     <input type="text" className="my-input" {...props} />
>   });
> 
>   return (
>     <DayPickerInput component{renderInput} />
>   )
> 
> }
> ```

A slight modification in @mnsr's answer helped me

```
const renderInput = React.forwardRef(function someFn(props, ref) {
    return (
      <input type="text" className="my-input" {...props} />
    )
  })
```

Hope this helps someone.

**Comment by zargold** [comment]
These are not working for me... 
- `inputProps={ { ref: null }`
```
const Input = React.forwardRef(function someFn(props, ref) {
    return (
      <input type="text" className="my-input" {...props} />
    )
  })
// and the alternate: fails with: need 2 arguments in the callback
  const Input = React.forwardRef((props) => {
    return (
      <input type="text" className="my-input" {...props} />
    )
  })
  ```
  I would like to Focus the input element and for that I needed a ref... is the only way to do that in a class component to upgrade to v8?
