### ISSUE TITLE
Localization: Could not find a declaration file for module 'react-day-picker/moment'

### ISSUE THREAD

**Issue by frankred** [gpbl/react-day-picker#593]
My Version: 
    "react-day-picker": "^7.0.5",

If I do: 
```
import MomentLocaleUtils from 'react-day-picker/moment';
````

I'll get the error message:
```
Could not find a declaration file for module 'react-day-picker/moment'.
```

**Comment by gpbl** [comment]
This is TypeScript right? please send a PR, type definitions are from contributors. Thanks!

**Comment by feather-aurelie** [comment]
Hi, any update on that type definitions for moment by any chance?
