### ISSUE TITLE
Calendar when using DayPickerInput isn't keyboard accessible

### ISSUE THREAD

**Issue by saramarie** [gpbl/react-day-picker#601]
I'm currently implementing DayPickerInput in a project and noticed that DayPicker is keyboard accessible, but when I used the input version, it's not. What I mean is that when I'm using DayPickerInput and then I tab to the input, I can't then continue tabbing through the now opened calendar. The tab just takes me off the input and closes the calendar.

I thought this might be a problem with my own code, but I'm seeing the same behavior when I try the examples on your doc site. I've visited the page and tried it in Chrome, Firefox and Safari on my Mac.

**Comment by gpbl** [comment]
This is expected. If you need the DayPicker being accessible via keyboard, just avoid using the input and use the DayPicker instead.

**Comment by mattgreenfield** [comment]
@gpbl - would you accept a pull request to improve this?

I believe that focusing the input and hitting the down arrow should focus the date picker. We would need to handle the fact that the input would blur and I'm sure there are many edge cases to work through.
