### ISSUE TITLE
DayPickerInput doesn't call dayPickerProps.onMonthChange

### ISSUE THREAD

**Issue by ah-adarlow** [gpbl/react-day-picker#603]
DayPickerInput overrides the onMonthChange handler passed in through dayPickerProps and doesn't call it when the month changes.

See DayPickerInput.js line 446.

https://codesandbox.io/s/km00lz2vq3

**Comment by gpbl** [comment]
Confirmed! Someone may want to fix it :)

- [ ] [this line](https://github.com/gpbl/react-day-picker/blob/master/src/DayPickerInput.js#L446) should become:

```diff
- onMonthChange={month => this.setState({ month })}
+ onMonthChange={this.handleMonthChange}
```
- [ ] `handleMonthChange` should `setState({month})` and use as callback `props.dayPickerProps.onMonthChange` –if it exists– with the same args
- [ ] must add a test for `handleMonthChange` calling `onMonthChange`
