### ISSUE TITLE
add ability to customize footer

### ISSUE THREAD

**Issue by MhMadHamster** [gpbl/react-day-picker#606]
Hello, this is a feature request
It would be nice to have the ability to customize footer element just as navbar element, since now you can just have a lonely "today" button.
Cheers.

**Comment by MhMadHamster** [comment]
@gpbl will you accept a pr on it, if i will make one?

**Comment by gpbl** [comment]
Why not put the DayPicker in a div and add a footer this way 🤔

**Comment by MhMadHamster** [comment]
well, i do not have "correct" answer for this, in my opinion, it will look more clear and explicit if you have footer as a part of a day-picker, considering that you may have some functionality which changing current date/month/year, on top of that, there are already footer with "today" button, and looking on navbar and caption elements, it's a bit strange that you can not customize footer as you can do with other elements. But i'm not having anything versus not adding this. just in my case it would be more handy.

**Comment by MhMadHamster** [comment]
🏳️
