### ISSUE TITLE
month prop in NavBar component always undefined

### ISSUE THREAD

**Issue by MhMadHamster** [gpbl/react-day-picker#607]
when trying to get month prop in NavBar component you will always get undefined even if you will pass it explicitly. Check the example: https://codesandbox.io/s/4zznpn4ov4

**Comment by MhMadHamster** [comment]
i believe [this ](https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L468) should be `month: this.state.currentMonth,`

**Comment by gpbl** [comment]
Published as [v7.1.0](https://www.npmjs.com/package/react-day-picker).
