### ISSUE TITLE
DayPickerInput as a controlled component with month selection

### ISSUE THREAD

**Issue by kradical** [gpbl/react-day-picker#613]
Hello @gpbl!

Thank you for your time on this project! I believe I have identified a small issue and submitted a proposed fix (https://github.com/gpbl/react-day-picker/pull/612).

Currently the DayPickerInput uses `props.value` for the current month. This means that using `props.dayPickerProps.month` doesn't change the current month. I believe that there is no way to use DayPickerInput as a controlled component (w/ redux-form for me) with month selection.

I believe the DayPickerInput should respect `props.dayPickerProps.month` over calculating it from the current value.

I do know that you can use `this.datePickerRef.getDayPicker().showMonth(day);` to change the selected month on certain events but there is no way to choose the initial month based on props if a `value` prop is passed in (controlled component).

**Comment by gpbl** [comment]
Closed with #612
