### ISSUE TITLE
Add month key to captionElement function parameters when using numberOfMonths

### ISSUE THREAD

**Issue by Noldaru** [gpbl/react-day-picker#623]
Hello,

I think it would be helpful, when using both `numberOfMonths` and `captionElement` props, to pass the key (or some other identifier) of the month component in which the latter is being rendered.

Example:

```js
const MyComponent = () => (
    <DayPicker
        numberOfMonths={2}
        captionElement={({date, localeUtils, monthKey}) => {/* monthKey determines which of the two month components the output will be rendered in. */}}
    />
);
```

Best regards

**Comment by gpbl** [comment]
Hi there thanks for your suggestion! 

Not sure I follow: could you provide a better example of what do you expect `monthKey`?

**Comment by Noldaru** [comment]
In the above example, the output will be two months placed next to each other. The month on the left would have a key of 0, the one on the right a key of 1.

Since the output of captionElement is applied to both of these months, is it possible to pass this key into the captionElement function? (the '`monthKey`' parameter in the example.)

It would help in fine-tuning the way the captionElement is rendered, based on which of the month components it gets rendered in.

**Comment by gpbl** [comment]
@Noldaru isn't the `date` argument enough to know which month is being rendered? Or, I still don't understand the use case here 🙇

**Comment by gpbl** [comment]
Closing this because inactivity.
