### ISSUE TITLE
Typescript 2.6.2 DayPicker render problem

### ISSUE THREAD

**Issue by martinsvb** [gpbl/react-day-picker#624]
Hello,

in our project we are using Typescript 2.6.2 and we want upgrade to react-day-picker 7.0.7.

We are using as:
`import DayPicker from 'react-day-picker';`
in render method:
`<Daypicker />`
and then get error:
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Calendar`.

If I change transpiled file code from:
`React.createElement(react_day_picker_1.default`
to
`React.createElement(react_day_picker_1`
it's working
Looks like problem with default export?

Thank you,
Martin

**Comment by martinsvb** [comment]
Hi, sorry for this issue.
It was caused by different versions of react-day-picker in our library and project.
It can be closed.

**Comment by gpbl** [comment]
thanks for the follow up!
