### ISSUE TITLE
Determine if Week is disabled in onWeekClick.

### ISSUE THREAD

**Issue by harjuto** [gpbl/react-day-picker#625]
Event:
1. User clicks Week label in calendar.
2. onWeekClick is invoked

Problem:
How to determine if clicked week is disabled and thus prevent myEventHandler from firing?

Thoughts:
In onDayClicked we get DayModifiers from which you can easily check if clicked day is disabled.
Having similar functionality for Weeks would be sweet.

**Comment by Noldaru** [comment]
I believe the  second parameter the `onWeekClick` passes is an array (date[]) of days within that week. Perhaps you could cross-reference those with whatever you're passing into `disabledDays`?

**Comment by gpbl** [comment]
@Noldaru is right 👍🏽
