### ISSUE TITLE
CSS modules: default import from styles

### ISSUE THREAD

**Issue by kuldarim** [gpbl/react-day-picker#628]
I'm using react-day-picker with css modules. I would like to apply default styles and modify them a bit. 

As far as I understand it can be achieved with importing default styles and passing them to `classNames` props like

```js
import * as classNames from 'react-day-picker/lib/style.css; // default styles
import * as styles from './styles.css'; // modified styles
....

<DayPicker classNames: {
        ...classNames,
        caption: styles.caption,
        container: styles.container,
      } />

```

I'm importing default styles like that `import * as classNames from 'react-day-picker/lib/style.css';` it imports an object with such values

```js
{
...
  DayPicker:"style__DayPicker___b_Yn_",
  DayPicker--interactionDisabled:"style__DayPicker--interactionDisabled___1H3Hf",
  DayPicker-Body:"style__DayPicker-Body___2jfXi",
  DayPicker-Caption:"style__DayPicker-Caption___2dsPy",
...
}
```

from the [docs](http://react-day-picker.js.org/docs/styling#styling-css-modules) it says to then use it like this: ` <DayPicker classNames={ classNames } />`

And it does not work. I need to write a mapper which maps imported classNames to 

```js
const defaultClassnames = {
  container: 'DayPicker',
  wrapper: 'DayPicker-wrapper',
  interactionDisabled: 'DayPicker--interactionDisabled',
  months: 'DayPicker-Months',
  month: 'DayPicker-Month',

  navBar: 'DayPicker-NavBar',
  navButtonPrev: 'DayPicker-NavButton--prev',
  navButtonNext: 'DayPicker-NavButton--next',
  navButtonInteractionDisabled: 'DayPicker-NavButton--interactionDisabled',

  caption: 'DayPicker-Caption',
  weekdays: 'DayPicker-Weekdays',
  weekdaysRow: 'DayPicker-WeekdaysRow',
  weekday: 'DayPicker-Weekday',
  body: 'DayPicker-Body',
  week: 'DayPicker-Week',
  weekNumber: 'DayPicker-WeekNumber',
  day: 'DayPicker-Day',
  footer: 'DayPicker-Footer',
  todayButton: 'DayPicker-TodayButton',

  // default modifiers
  today: '',
  selected: 'DayPicker-Day--selected',
  disabled: 'DayPicker-Day--disabled',
  outside: 'DayPicker-Day--outside',
};
```

Because as I far as I understand classNames prop expects object with keys like `container, wrapper ...`  not like `DayPicker, DayPicker--interactionDisabled` which is imported from 'react-day-picker/lib/style.css'.

So I need to write a mapper, which maps imported classNames to desired object and only then I can apply the styles. Maybe I'm doing something wrong or its an issue?

**Comment by gpbl** [comment]
> So I need to write a mapper, which maps imported classNames to desired object and only then I can apply the styles. Maybe I'm doing something wrong or its an issue?

Please don't be afraid to copy and paste [style.css](https://github.com/gpbl/react-day-picker/blob/master/src/style.css) into your app and change the selector names (breaking changes will be marked as a major version). The provided `style.css` is not meant to be used with css modules.

The selectors your need are listed here: http://react-day-picker.js.org/api/DayPicker/#classNames
