### ISSUE TITLE
Navigating back to the current date from DayPickerInput

### ISSUE THREAD

**Issue by nbokmans** [gpbl/react-day-picker#629]
Hi, 

I'm looking for a way to allow my users to click a button inside the day picker to go (back to) the current date. Right now, they can navigate back a few years in time to filter the record on that date. Now there is a new requirement where users must be able to click a button to return to the current date.

I see a `todayButton` prop in the `DayPicker` component, but can't find it for `DayPickerInput`.

Is there anything available right now that allows this in the `DayPickerInput`? I've looked through the docs but I haven't found any way to extend the picker input.

I'm using `DayPickerInput` from version 7.0.5.

**Comment by gpbl** [comment]
There's a [`dayPickerProps`](http://react-day-picker.js.org/api/DayPickerInput#dayPickerProps) you can use to pass the DayPicker props to it: 

```jsx
<DayPickerInput dayPickerProps={{ todayButton: 'today' }} />
```

Does it solve your task?

**Comment by nbokmans** [comment]
Can't believe I missed that, thank you so much. Sorry for wasting your time.
