### ISSUE TITLE
Require react-tap-event-plugin in examples

### ISSUE THREAD

**Issue by davidspiess** [gpbl/react-day-picker#64]
In the example code for **Input Fields** and **Range of Days** you missed to require the react-tap-event-plugin as you use `onDayTouchTap`.

**Comment by gpbl** [comment]
Thanks, the plugin is there but it seems not working. Let me see :-)

**Comment by davidspiess** [comment]
The examples work but if you are a lazy person like me and copycat only the code below without further investigation the date selection ditd not work for me. After some stumbling around i found the hint for the react-tap-event-plugin in the api description, but i think it should be part of the example code too.

**Comment by Globegitter** [comment]
:+1: Just ran into the same issue

**Comment by JamesDullaghan** [comment]
I did the same!

**Comment by gpbl** [comment]
Thanks, done!
