### ISSUE TITLE
hideDayPicker default delay

### ISSUE THREAD

**Issue by kuldarim** [gpbl/react-day-picker#642]
Hey,

I am using datepicker input with custom hide dayPicker overlay calls. I cannot use default `hideOnDayClick` prop because it also hides the overlay when user clicks disabled day. And I want to respect that and only hide daypicker when clicking on not disabled days.

This is my config:

```jsx
handleDayClick = (day, modifiers) => {
    if (!modifiers[styles.disabled]) {
      this.hideDatepickerOverlay();
  };

hideDatepickerOverlay = () => {
    this.dayPickerInputRef.hideDayPicker();
  };

<DayPickerInput
        ref={ref => (this.dayPickerInputRef = ref)}
        ...
        hideOnDayClick={false}
      />
```

On desktop it works fine, but not in mobile devices. Default `hideOnDayClick` works fine though. So I dig a bit into your implementation and have noticed, that you have timeout on `this.dayPickerInputRef.hideDayPicker()` for 100 ms ([link](https://github.com/gpbl/react-day-picker/blob/master/src/DayPickerInput.js#L265 )) . 

So maybe it makes sense to add default timeout to [this](https://github.com/gpbl/react-day-picker/blob/master/src/DayPickerInput.js#L257) place instead. For example: 
```
hideDayPicker() {
    this.hideTimeout = setTimeout(() => this.setState({ showOverlay: false });, HIDE_TIMEOUT);
}
```
So end user does not need copy paste the same logic in his code base to simulate same behaviour?

**Comment by gpbl** [comment]
@kuldarim is this issue still valid?

> I cannot use default `hideOnDayClick` prop because it also hides the overlay when user clicks disabled day. 

This example: http://react-day-picker.js.org/examples/input-state does have disabled days but it doesn't hide when user clicks on them. 

> So maybe it makes sense to add default timeout to this place instead. For example:

Uhm no, that delay is used only to provide a feedback to the user that has clicked the day cell.
