### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addDayToRange' of undefined

### ISSUE THREAD

**Issue by devd3js** [gpbl/react-day-picker#649]
Hi,
This issue is coming today, after npm install. Please fix asap. 

In previous version **DateUtils** was working fine. But today after installing a fresh version, it's not working.

![image](https://user-images.githubusercontent.com/20788344/36976686-7ab922dc-20a4-11e8-9a03-2922fe070b47.png)

Thanks

**Comment by gpbl** [comment]
cc @TrySound could this be related to your recent changes?

**Comment by gpbl** [comment]
Thanks @devd3js for the feedback! Fix is published as v7.1.1. Please report back if you have other issues.
