### ISSUE TITLE
Make a date range selectable via drag and drop

### ISSUE THREAD

**Issue by davidspiess** [gpbl/react-day-picker#65]
Any idea how you could accomplish dragging the date range like in this screenshot?
![](https://d13yacurqjgara.cloudfront.net/users/111932/screenshots/2098475/attachments/378850/original.gif)

**Comment by gpbl** [comment]
Interesting case (and styling). Does it work by dragging or just *moving* the mouse over the day? 

If the first latter, I think I'd use `onDayMouseEnter` after setting a state with `onDayClick`. Conceptually:

```js
render() {
return (
  <DayPicker
    onDayClick = { (e, day) => 
      this.setState({ from: day })
    }
    onDayMouseEnter={ (e, day) => 
      this.setState({ to: this.state.from ? day : null })
    }
  />
);
}
```

for dragging it may work as well, but you'd need more logic to check the mouse state.

**Comment by davidspiess** [comment]
It should work by dragging the mouse. Thanks for your code example though :) I got it working by using the `renderDay()` method. Here i'm able to use event listener i need.

```js
renderDay(day) {
    return (
        <div onMouseDown={this.handleDayMouseDown.bind(this, day)}
             onMouseMove={this.handleDayMouseMove.bind(this, day)}
             onMouseUp={this.handleDayMouseUp.bind(this, day)}>
             {day.getDate()}
        </div>
    );
}
```

I tried to get it working with touch events too, but it seems `onTouchMove` fires only for the first element i move my finger across. I asked about that on stackoverflow but i don't think there is a "react" solution for that :/
http://stackoverflow.com/questions/32884397/how-to-handle-ontouchmove-event-in-react

**Comment by gpbl** [comment]
Oh yes i forgot about `renderDay` 👽 Have you looked also at http://gaearon.github.io/react-dnd/? There I read something about touch support.

**Comment by davidspiess** [comment]
It does not quite work with react-dnd eather. All solutions i find are designed only for drag and drop. But i have a workaround now :)
I use the react test utility `Simulate` to trigger a `mouseMove` event on the event currently touched.
Here is the full code, in case if anyone has to implement the same functionality.

```js
getInitialState() {
    return {
        from: null,
        to: null,
        isSelecting: false,
        isSelectionMoving: false
    };
},

renderDay(day) {
    return (
        <div onTouchStart={this.handleDayMouseDown.bind(this, day)}
             onMouseDown={this.handleDayMouseDown.bind(this, day)}
             onMouseMove={this.handleDayMouseMove.bind(this, day)}
             onTouchMove={this.handleDayTouchMove}
             onTouchEnd={this.handleDayMouseUp}
             onMouseUp={this.handleDayMouseUp}>
             {day.getDate()}
        </div>
    );
},

handleDayMouseDown(day) {
    let { from, to } = this.state;

    if (isPastDay(day) || this.state.isSelecting) return;

    if (from && !to) {
        if (day < from) {
            from = day;
        } else if(day > from) {
            to = day;
        }
    } else {
        from = day;
        to = null;
    }

    this.setState({
        from: from,
        to: to,
        isSelecting: true
    });
},

// Quirky on android
handleDayTouchMove(e) {
    e.preventDefault();
    let changedTouch = e.changedTouches[0];
    let elem = document.elementFromPoint(changedTouch.clientX, changedTouch.clientY);
    Simulate.mouseMove(elem);
},

handleDayMouseMove(day) {
    if (!this.state.isSelecting) return;

    let { from, to } = this.state;

    if (day > from) {
        to = day;
    }

    this.setState({ to , isSelectionMoving: true});
},

handleDayMouseUp() {
    this.setState({
        isSelecting: false,
        isSelectionMoving: false
    });
}
```

**Comment by gpbl** [comment]
👍 Are you sure you need the test utility to simulate the mouse move? It feels weird to include it in production. Do you think we could improve the react-day-picker API to help with this?

**Comment by davidspiess** [comment]
I have absolutely no idea how to trigger the SyntheticEvent Wrapper from React manually. I think i ask about that @ https://discuss.reactjs.org/. I keep you updated :)

I don't think it's a problem within the react-day-picker API. Until now it was a pleasure to work with :+1:
