### ISSUE TITLE
Outside-day cells are empty in the first month when displaying multiple months

### ISSUE THREAD

**Issue by geminiyellow** [gpbl/react-day-picker#654]
`react-day-picker` today is `20180308` and i set 

- `toMonth`: `new Date()`;
- `numberOfMonths`: 2
- `fixedWeeks`: true

7.0.7
![image](https://user-images.githubusercontent.com/929878/37135062-ddd071ae-22de-11e8-83f8-cd3c5a4b60e5.png)

7.1.1
![image](https://user-images.githubusercontent.com/929878/37135075-e738c944-22de-11e8-95aa-aa9b649b7b8e.png)

thank you for your work, but when you merge this `Do not show outside days when fromMonth/toMonth #639` , i think you forgot the multiple month case. 

ref: 

- https://github.com/gpbl/react-day-picker/blob/master/src/Month.js#L99-L102
- https://github.com/gpbl/react-day-picker/issues/630

and i think , the new condition for `empty` flag should active for event only but not cell.

ref: https://github.com/gpbl/react-day-picker/blob/master/src/Day.js#L131-L133

**Comment by geminiyellow** [comment]
@gpbl 

thank you for your work, but when you merge this `Do not show outside days when fromMonth/toMonth #639` , i think you forgot the multiple month case.

**Comment by geminiyellow** [comment]
and i think , the new condition for `empty` flag should active for event only but not cell.

ref: https://github.com/gpbl/react-day-picker/blob/master/src/Day.js#L131-L133

**Comment by gpbl** [comment]
Thanks @geminiyellow for the bug report

> and i think , the new condition for empty flag should active for event only but not cell.

What do you mean?

**Comment by geminiyellow** [comment]
thanks @gpbl 

> What do you mean?

means, show the day cell, but disable the mouse events on the day cell.
`7.0.7` 's display , the day after toMonth show light gray, it looks very good. 
no need change it. or you can add a new flag, show or not show.

**Comment by gpbl** [comment]
Yeah I agree I think it is better to revert this change

**Comment by geminiyellow** [comment]
thank you , and i pin the version, wait for your next release. GookLuck.

**Comment by gpbl** [comment]
you can help by sending a PR 😊
