### ISSUE TITLE
Declaration File for moment not found

### ISSUE THREAD

**Issue by feather-aurelie** [gpbl/react-day-picker#659]
Hey, 
Still a newbie in Typescript so not sure how to solve that by myself... 
I am trying to use the formatDate and parseDate functions but I get the following error: `Could not find a declaration file for module 'react-day-picker/moment'.`

This is the line that throws the error:
`import { formatDate, parseDate, }   from 'react-day-picker/moment';`

Moment is installed (v2.21.0). 
Did anybody had that issue and was able to solve it??

**Comment by gpbl** [comment]
I don't have the time to work on this right now, we are looking for a PR:

https://github.com/gpbl/react-day-picker/issues/593
