### ISSUE TITLE
DayPickerInput: month isn't being reset after closing overlay

### ISSUE THREAD

**Issue by Dmitry2703** [gpbl/react-day-picker#667]
After updating react-day-picker from v. 6.2.1 to 7.0.7 I noticed that when I open the overlay (e.g., current value of DayPickerInput is 15th of March), change month (e.g., to August) and close it without selecting a day and then open it again, it shows me the previous month (August), but not month of current value in DayPickerInput (March).

You can see this behavior in the docs (http://react-day-picker.js.org/examples/input-custom-overlay)

In the previous version (6.2.1) after closing the overlay and opening it again it showed the current month (March).

Is there a way to reset the month after closing the overlay without changing the day?

**Comment by gpbl** [comment]
Seems a dup of #669

**Comment by gpbl** [comment]
The fix has been published in v7.1.5. Please report back if you have some feedback, thanks!

**Comment by Dmitry2703** [comment]
Seems to work very good, thank you very much!
