### ISSUE TITLE
Multiple days selection go back to specified month in month prop on every selection

### ISSUE THREAD

**Issue by LouisCuvelier** [gpbl/react-day-picker#669]
Hi,

**Firstly, thanks for this awesome lib** 🥇 

But, I found a weird behavior :
With month prop, when you select multiple days on another month, every time you select a day, the UI goes back to the month specified in the month prop.

[I reproduced the bug here](https://codesandbox.io/s/w23x0wk82l)

You should try to select multiple days on others months with and without the month prop.

**Comment by gpbl** [comment]
It seems a regression from https://github.com/gpbl/react-day-picker/pull/612

**Comment by gpbl** [comment]
Hey, the fix has been published in v7.1.5. Please report back if you have some feedback, thanks!
