### ISSUE TITLE
Value is undefined when invalid input entered in the text field

### ISSUE THREAD

**Issue by activebiz** [gpbl/react-day-picker#671]
Hi,

I am not sure if this should be a right behavior but it is current behavior in the component. 

If user type in random string in the textbox manually the value comes out as undefined. The problem with this is that my validation which happens outside of this control can not say its invalid text (as undefined is valid).

You can replicate it here http://react-day-picker.js.org/examples/input

Check the console log.

![image](https://user-images.githubusercontent.com/2632440/37520070-8802f73e-2913-11e8-83f0-b313f45bf647.png)

**My intuation is that if its returning undefined then it should not allow to enter invalid input. Or it returns whatever input user has entered so that developer write code to validate it.**

Becouse currently from UI (End user) view point you cant say if the incorrect value is passed.

Please advise.

**Comment by gpbl** [comment]
> My intuation is that if its returning undefined then it should not allow to enter invalid input.

It works the other way: when the user enter an invalid input, the day passed to `onDayClick` is `undefined`.

If you want to know the value of the input (thus determine if it contains a valid date or not) you can use the `getInput`:

```jsx
export default class Example extends React.Component {
  handleDayChange(day) {
    const input = this.dayPickerInput.getInput();
    console.log(
      `Selected day: %s, current input value: %s`,
      day.toString(),
      input.value
    );
  }
  render() {
    return (
      <div>
        <p>Please type a day:</p>
        <DayPickerInput
          ref={el => (this.dayPickerInput = el)}
          onDayChange={this.handleDayChange}
        />
      </div>
    );
  }
}
```
