### ISSUE TITLE
Use other roles

### ISSUE THREAD

**Issue by frodehansen2** [gpbl/react-day-picker#674]
We have a forked version of react-day-picker, and have done some accessibility testing on different modified versions of the react-day-picker. The modifications we did which our screen-reader users preferred, we simple role changes from grid roles to link and presentation roles. The stuff they could not interact with got the role presentation, while days which were clickable got role link.

I expect you have also done lot of testing on accessibility, and there are probably different preferences among screen-reader user, but would there be an opening for extending the component to allow developers to set the roles of the different elements, or add an "otherProps" prop on the elements with roles defined, which are spread after all the other props are set?

**Comment by gpbl** [comment]
Well we could map roles instead, and add a new prop `roles` taking a new map, eg:

```jsx
<DayPicker roles={{ dayCell: ‘link’ }} />
```

What do you think?

**Comment by frodehansen2** [comment]
Just started on a branch with those exact changes :) But I met one small issue regarding aria-selected on a day. That is an illegal prop if the role is link. I am not quite sure on how to fix that. Maybe just set aria-selected if the role is gridcell? But that might probably raise other issues?

**Comment by frodehansen2** [comment]
The test are of course broken, so I'll look into that now

**Comment by gpbl** [comment]
> But I met one small issue regarding aria-selected on a day

Bummer! You are right, we can’t switch roles so easily then. Maybe better investigate why the current roles do not work for you? We have reviewed them carefully over the years, they should not change, neither I’d change the source just to fit a special case.

Could you provide more details? (eg I don’t get why the `link` role fits better - as a day cell is not a link in any form)

**Comment by frodehansen2** [comment]
Most of the changes is to reduce "reading noice" and remove/hide elements that the user can't interact with. But I guess it might just be an opiniated preferred user experience. The link role is to make clear that the element is selectable, and the screenreader-user can navigate in a normal manner through the links with the keyboard.

**Comment by gpbl** [comment]
Have you also tried to use [`renderDay`](http://react-day-picker.js.org/api/DayPicker#renderDay) prop to return an element with a role? E.g.

```jsx
const Day = day => <span role="link">{day.toString()}</span>

<DayPicker 
  renderDay={ day => <Day day={day} /> } 
/>
```

Maybe this way you can "hack" the screenreaders. 

I'm closing this as I don't think there's much to do here. We can reconsider this if we have more requests from other developers. Thanks!
