### ISSUE TITLE
Release notes missing for 7.1.1+

### ISSUE THREAD

**Issue by edmorley** [gpbl/react-day-picker#677]
Hi!

The last entry in the release notes is for 7.0.0, whereas the last release is 7.1.4:
https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md

Tools like [Renovate](https://renovateapp.com/) use the changelog to display the release notes in the PRs they open, so all entries being present is quite useful :-)

**Comment by gpbl** [comment]
Yeah... the last 4 patches were just useless things because of some errors on our side, nothing interesting to add to the release notes :) Thanks for the suggestion mate!
