### ISSUE TITLE
replace `formatMonthTitle` with `formatDate` is better

### ISSUE THREAD

**Issue by geminiyellow** [gpbl/react-day-picker#679]
the method [formatMonthTitle](https://github.com/gpbl/react-day-picker/blob/master/src/LocaleUtils.js#L33) here, is works good, in english circle.
but in aisa, people like `YYYY/MM` than `MM/YYYY`.
when i try to change the caption date format, i have to rewrite the caption. 
it looks not good. why dont you export a captionFormat or just apply the `format` to the caption ?
i think that is better than now.

**Comment by gpbl** [comment]
You should use the `localeUtils` prop to change the way titles are formatted. See http://react-day-picker.js.org/api/LocaleUtils
