### ISSUE TITLE
Add support for disabled inputs

### ISSUE THREAD

**Issue by kostiantyn-solianyk** [gpbl/react-day-picker#680]
I want to disable DayPickerInput, when I'll get date from API, or whatever.
I didn't find anything about my issue in docs.

```jsx
inputProps={{disabled: true, readOnly: true }}
```

works, but not so well, whatever I can click on input, end dayPicker will appear, and I'll be able to change date as normal...

**Comment by apalanki** [comment]
DayPickerInput does not take in disabled prop. You could use input box to get past this issue:
`disabled ? <input value={}> : <DayPickerInput/>`

**Comment by gpbl** [comment]
@Meloman4eg adding a `className` shouldn't solve this issue, as the overlay will appear on click even if the field is marked as disabled. I think I should check the `inputProps` and disable the click event there.

**Comment by gpbl** [comment]
The support for disabled inputs is on v7.1.6
