### ISSUE TITLE
A setting to quickly enable switching years

### ISSUE THREAD

**Issue by trevordmiller** [gpbl/react-day-picker#682]
Thanks for the great library :)

**Comment by gpbl** [comment]
I was thinking to make the `YearMonthForm` component available with the library:

https://github.com/gpbl/react-day-picker/blob/master/docs/src/code-samples/examples/elements-year-navigation.js#L9-L40

**Comment by Rohanhacker** [comment]
@gpbl Can I work on this ? I want to start contributing 😃

**Comment by gpbl** [comment]
@Rohanhacker sure thanks a lot! 🙌🏽 do we want to discuss the implementation a bit first? Any questions?

**Comment by Rohanhacker** [comment]
@gpbl I was also thinking about using `YearMonthForm` component but It kinda restricts the range of years that can be selected. I think ant design guys solved this in a great way. Perhaps we can do something similar. 
 
![image](https://user-images.githubusercontent.com/9512969/40249154-b77e07fc-5aef-11e8-8a77-d06aed8acee5.png)

**Comment by Rohanhacker** [comment]
@gpbl waiting for your comment ?

**Comment by gpbl** [comment]
Sorry I’ve been busy :) 

Something like the ANT design is too much complex and IMO the UX is questionable as well: we would get lot of new issues here on Github 😅

The idea is to use the component already found in the example (maybe we need to update it). Sure this won’t allow to display all the possible years from the big bang :) but I don’t think this is a mayor issue.

When some props are passed to `DayPicker`, we would use that component as `captionElement`. This is much simpler and let us focus over a better API.

The first question to answer is how we do imagine the props the final user should use? I have some ideas, when I have some more freetime I’ll share them here.

**Comment by Sawtaytoes** [comment]
The ANT design is the same way Windows 10 does it as well. You click the year + month text, it drops back to a month chooser. If you click the year, now you're on a decade chooser. That's as far as it goes. The UI is very intuitive and would be something nice to see in DayPicker as well!

![image](https://user-images.githubusercontent.com/3948069/43914001-38595198-9bcc-11e8-93e4-05c411a6d60f.png)

![image](https://user-images.githubusercontent.com/3948069/43913937-0a043880-9bcc-11e8-969c-ddcb0a473822.png)

![image](https://user-images.githubusercontent.com/3948069/43913944-0e1fbdc2-9bcc-11e8-8be7-6b9e9bfe072c.png)

**Comment by trevordmiller** [comment]
Going to close this for now as it seems this isn't a heavily requested feature. Bigger fish to fry :)

**Comment by LiquidAssContainer** [comment]
It would be a great! Most of the popular libs are supported this feature.
