### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by catamphetamine** [gpbl/react-day-picker#685]
React 16.3 has been released deprecating `componentWillReceiveProps`.

I can see your code uses `componentWillReceiveProps` in a couple of places.
You can migrate it using https://github.com/reactjs/react-lifecycles-compat

**Comment by gpbl** [comment]
Published as v7.1.5

**Comment by catamphetamine** [comment]
I think you got it all wrong.
React 16.3 deprecates `componentWillReceiveProps` which is being removed in React 17.
The polyfill won't transform old methods into new methods.
It works the opposite way only.

> Lastly, use the polyfill to make the new lifecycles work with older versions of React

https://github.com/reactjs/react-lifecycles-compat

**Comment by gpbl** [comment]
ahah thanks for pointing it out it looked too easy indeed 😅

**Comment by gpbl** [comment]
someone can take this up?
