### ISSUE TITLE
How to define period range as ’week’, ‘month’, ‘year’?

### ISSUE THREAD

**Issue by hplusb** [gpbl/react-day-picker#688]
Hi, thanks for the great lib! I’d like to ask if it is possible to be able to select a predefined period range as ’week’, ‘month’, ‘year’? Some example pics might help what I’m trying to say. I couldn’t find a way to implement such thing with your calendar, would love to hear from you if it is possible?

So for instance, when month range is selected, clicking on the month sets the range from first day of that month to the last day, instead of opening that month basically.

![screen shot 2018-04-06 at 17 16 38](https://user-images.githubusercontent.com/33025255/38428010-6b23031e-39c3-11e8-8659-a69fe3dfa9b9.png)
![screen shot 2018-04-06 at 17 16 48](https://user-images.githubusercontent.com/33025255/38428012-6b87f652-39c3-11e8-8d00-f27616ddd08e.png)
![screen shot 2018-04-06 at 17 16 57](https://user-images.githubusercontent.com/33025255/38428014-6bb2f38e-39c3-11e8-9f29-30c4ffe4faef.png)

**Comment by gpbl** [comment]
Sure it is possible, you just need to add the CSS modifiers for the days you want to be highlighted. http://react-day-picker.js.org/docs/matching-days should help you with this. Is there something you don't understand?

**Comment by gpbl** [comment]
There's a similar issue here: https://github.com/gpbl/react-day-picker/issues/686 maybe docs are not clear enough?
