### ISSUE TITLE
Wrong week number displayed

### ISSUE THREAD

**Issue by HyacintheK** [gpbl/react-day-picker#692]
Hello,

When the prop "showWeekNumbers" is equal to "true", the week numbers displayed are wrong. 

For example, for the 12th april 2018, the week number displayed is "14" while we should see "15" ([see here](https://www.epochconverter.com/weeknumbers)).

I made a sandbox with the behavior : https://codesandbox.io/s/xr4ovz55qo

![image](https://user-images.githubusercontent.com/9976176/38688993-b226b6fa-3e7a-11e8-87b7-f8bf7d0ebfe4.png)
![image](https://user-images.githubusercontent.com/9976176/38689050-d46dd252-3e7a-11e8-86e8-0da43d16993b.png)

Thanks in advance

**Comment by moag1000** [comment]
I was wondering why it didn't do the same thing in my live example. Finally found out why.

The link also says:
"Week number according to the ISO-8601 standard, weeks starting on Monday". If you do that (firstDayOfWeek={1} ), the week number shows up correctly.

**Comment by gpbl** [comment]
I'm not sure if this has something to do with the `firstDayOfTheWeek`. 

For what I see after a quick debug, [this line](https://github.com/gpbl/react-day-picker/blob/master/src/Month.js#L181) where we take `week[0]` (as the first day of the week row) gets the Jan. 1st from the previous year. It should instead get the first day of the week _of the current year_. This should be easily fixable...

**Comment by gpbl** [comment]
mmm the above seems a different bug 🙄

**Comment by gpbl** [comment]
The fix has been published in v7.1.5. Please report back if you have some feedback, thanks!
