### ISSUE TITLE
Add Current form style

### ISSUE THREAD

**Issue by rullymartanto** [gpbl/react-day-picker#702]
How to add style using my current form style ?

<DayPickerInput type="text" onDayChange={this.handleDayChange}  className="form-control" />

DayPickerInput   not follow the style

Thanks

**Comment by gpbl** [comment]
Please help us reproduce your issue and we can give a look, thanks!
https://github.com/gpbl/react-day-picker/blob/master/.github/ISSUE_TEMPLATE.md
