### ISSUE TITLE
Can't navigate months with the navigation buttons

### ISSUE THREAD

**Issue by GhunterStrudel** [gpbl/react-day-picker#703]
As the title describes, it is impossible for me to navigate through the months with the navigation buttons. Using the keyboard does still work though. I can't find anything in the docs and I have no idea how to fix this myself. Any pointers or fixes known about this issue?

Thanks in advance!

**Comment by gpbl** [comment]
Hey please add a way to reproduce your issue, thanks!

https://github.com/gpbl/react-day-picker/blob/master/.github/ISSUE_TEMPLATE.md
