### ISSUE TITLE
Adding onChange logic to DayPicker 

### ISSUE THREAD

**Issue by pcraig3** [gpbl/react-day-picker#705]
Hi there,

Similarly to closed issue #701, I'm trying to integrate `react-day-picker`'s `DayPicker` with [`react-final-form`](https://github.com/final-form/react-final-form). 

React Final Form requires the use of a [`Field`](https://github.com/final-form/react-final-form#field--reactcomponenttypefieldprops) for each form field, which means creating an adapter component whenever you want to a third-party form element to be usable within the form. The adapter component [has to accept an `input` object containing `value` and `onChange`](https://github.com/erikras/redux-form/issues/1221#issuecomment-229002540). The advice is [just to provide a new `onChange`](https://github.com/erikras/redux-form/issues/1797#issuecomment-247798860).

[This approach, which works for many other components, doesn't work for `DayPicker`](https://stackoverflow.com/questions/43640196/how-to-make-react-day-picker-compatible-with-redux-form). It seems like the issue is that [`DayPicker` doesn't actually have an `onChange`](http://react-day-picker.js.org/api/DayPicker) method, so it's up to us to manage what happens when the calendar changes and then store the dates in `value` property that `react-final-form` expects.

I've created a codepen here: [https://codesandbox.io/s/github/pcraig3/date-picker-sandbox](https://codesandbox.io/s/github/pcraig3/date-picker-sandbox) 
(Sorry, I didn't notice your forked codepen earlier).

I have a `handleDayClick` method in `Calendar.js` which runs when days are clicked, so I'm updating `value` and passing it to `onChange` in there. There's an off-by-one error in there somewhere that I'm still investigating.

Does this look like the right approach, or have I gotten something wrong?

**Comment by gpbl** [comment]
> It seems like the issue is that DayPicker doesn't actually have an onChange method, so it's up to us to manage what happens when the calendar changes

This is: it's up to you to manage _user interactions_ with the component. There's no way this component will tell you when "it changes". _You_ decide when it changes. For example, you decide how days should appear according to a date you have in _your_ component state. We provide however an implementation using the component with input field: http://react-day-picker.js.org/docs/input

**Comment by gpbl** [comment]
> But, I want to select a list of days, and an input doesn't accept an array of values. Is there any obvious suggestion if I wanted an HTML element with a default onChange that accepts an array of values? 

Well i think the only solution is not to use an input element :) 

I'm closing this because I don't know which action should I take here.
