### ISSUE TITLE
iPhone 6+ iOS 8.x safari bug

### ISSUE THREAD

**Issue by albertogg** [gpbl/react-day-picker#71]
Hello, I don't know if you are aware of this, but currently there's a bug where people are missing days on the picker on Safari iOS 8.x and the month of October. I'm not sure if this happens with all devices but a friend told me that is happening on an iPhone 6+ and occurs every year in different ways. The problem is that It only happens on the physical device not in the iOS emulator so I can't reproduce it on my own. Here are two screenshots showing the problem. The bug occurs also with the picker on [http://www.gpbl.org/react-day-picker/](http://www.gpbl.org/react-day-picker/) so that's why I'm posting this. 

**missing October 1st on 2017**
![img_20151011_143006450](https://cloud.githubusercontent.com/assets/451539/10419532/4f1cc16a-702f-11e5-86a4-c33eb975bc5a.jpg)

**missing October 2nd 2016**
![img_20151011_144436721](https://cloud.githubusercontent.com/assets/451539/10419533/53429b48-702f-11e5-87c5-2a40c0dbfa49.jpg)

I hope this is useful, I don't know how can I do to help right now.

**Comment by gpbl** [comment]
In which timezone are you? I think it's related to the fact that some timezones (e.g. Brasilia standard time) change to daylight time at midnight. I've seen this bug in #18. Let me check it out!

**Comment by albertogg** [comment]
It's happening in the Sydney timezone and [according to this](http://www.timeanddate.com/time/change/australia/sydney?year=2015) it seems that in fact October is when daylight saving starts...

In fact days missing are exactly that day. for example in 2016 we are missing October 2 and daylight [starts that day](http://www.timeanddate.com/time/change/australia/sydney?year=2016). And for 2017 on [October 1](http://www.timeanddate.com/time/change/australia/sydney?year=2017).

Thank you!

**Comment by gpbl** [comment]
👍 great thanks, releasing a fix asap!

**Comment by albertogg** [comment]
:clap: thanks!

**Comment by gpbl** [comment]
Yet I can't replicate it with the `Australia/Sydney` timezone, and this sounds right since it should affect timezones changing at midnight. I can replicate a similar issue with the Brazilian timezone though 

<img width="515" alt="screen shot 2015-10-12 at 04 30 26" src="https://cloud.githubusercontent.com/assets/120693/10423175/67156b2e-710f-11e5-9d8a-1736251c3058.png">

**Comment by gpbl** [comment]
@albertogg v1.0.9 should fix it, but I can't verify the Australian timezone since I couldn't replicate the problem.
 
Do you have a way to test this version and confirm it's fixed? E.g. checking http://www.gpbl.org/react-day-picker

**Comment by albertogg** [comment]
:clap: @gpbl thanks for fixing it so fast!!! it works great!! :confetti_ball:

Thank you! :heart: :heart:
