### ISSUE TITLE
 when using two Inputs, first Input blurs immediately on change

### ISSUE THREAD

**Issue by zackforbing** [gpbl/react-day-picker#710]
on the ["Range with two inputs" section of the documentation](http://react-day-picker.js.org/examples/input-from-to), you can see this bug in effect. 

Typing in the first input switches focus immediately to the second input. this behavior continues until you select a date for the second input, and once you've done that, then you can type in the first input without interruption.

**Comment by gpbl** [comment]
Thanks for the report!
