### ISSUE TITLE
Can't localize DayPickerInput

### ISSUE THREAD

**Issue by Arseniy-II** [gpbl/react-day-picker#711]
Hi all, sorry I don't provide repo.
Though it is straightforward bug :)
You just don't pass props `months`, `weekdaysLong`, `weekdaysShort`, `firstDayOfWeek`, `locale` from `DayPickerInput` to `DayPicker`

**Comment by Arseniy-II** [comment]
Found `dayPickerProps`

**Comment by ur-gh** [comment]
@Arseniy-II thanks for the hint. But I get lowercase letter for the first character of the Month. The same thing happens to DayPIcker component as well. Is there another prop for that or is it a bug?
