### ISSUE TITLE
Have a props to add icon to DayPickerInput

### ISSUE THREAD

**Issue by threeid** [gpbl/react-day-picker#718]
Hi @gpbl ,

Thank you for react-day-picker!

It would be great if react-day-picker has an icon like
![screen shot 2018-05-09 at 10 08 10 am](https://user-images.githubusercontent.com/37827220/39793809-3bfdb26a-5371-11e8-822e-c497751eb0cd.png)

And usage like:
`<DayPickerInput iconPosition={'left' | 'right'} icon={<SomeIcon type='calendar'/>} />`

Have a great day!
threeid

**Comment by gpbl** [comment]
Hi @threeid ! You can use the `component` prop: http://react-day-picker.js.org/api/DayPickerInput#component

It allows you to set a different component for the input field.
