### ISSUE TITLE
Year and month navigation

### ISSUE THREAD

**Issue by hlavo** [gpbl/react-day-picker#722]
Hi,
i found a bug on your example http://react-day-picker.js.org/examples/elements-year-navigation.  When you choose a month in selectbox and then you go to another month via arrow you can not go on your previous selected month via selectbox.

Thanks for support.

![bug](https://user-images.githubusercontent.com/11485569/40113910-4672be58-590b-11e8-815a-ece0d960f253.gif)

**Comment by igodorogea** [comment]
I was able to fix it by adding an event handler for `onMonthChange`.
Here is an example: https://codesandbox.io/s/6w4vpnmz9z line 58
