### ISSUE TITLE
@types support for DayPickerInput

### ISSUE THREAD

**Issue by samartha230194** [gpbl/react-day-picker#724]
Just tried to use DayPickerInput from react-day-picker/DayPickerInput

[ts]
Could not find a declaration file for module 'react-day-picker/DayPickerInput'. '/home/samatha/projects/web-lumo/node_modules/react-day-picker/DayPickerInput.js' implicitly has an 'any' type.
  Try `npm install @types/react-day-picker` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-day-picker';`

**Comment by gpbl** [comment]
I guess this is a dup of: https://github.com/gpbl/react-day-picker/issues/586
