### ISSUE TITLE
Calendar day hover effect is flickering

### ISSUE THREAD

**Issue by sv3k** [gpbl/react-day-picker#725]
When you move the mouse cursor in gaps between days — hover background effect is flickering:

![Demo](https://image.ibb.co/dQYUvo/demo.gif)

This issue is reproducible on any DayPicker with hover effects, including [demo website](http://react-day-picker.js.org).

Browser: Chrome 66
OS: maxOS 10.13

**Comment by gpbl** [comment]
Hi, check out this: https://github.com/gpbl/react-day-picker/issues/610
