### ISSUE TITLE
Highlight selected week number

### ISSUE THREAD

**Issue by ghost** [gpbl/react-day-picker#727]
Hello,

I think there is no possibility to highlight a week number when user clicks on it.

![image](https://user-images.githubusercontent.com/9976176/40606258-188e8d06-6265-11e8-8f78-bc66f50cfeb2.png)

For example, we could have a kind of modifier for week numbers ?

![image](https://user-images.githubusercontent.com/9976176/40606347-6458ec7c-6265-11e8-82ac-be6ed6220153.png)

Do you think that it would be implemented soon ?

Thanks in advance.

**Comment by gpbl** [comment]
Right, there's no way for now to change that element. We could add a `weekElement` prop so that you can use your own component there.
