### ISSUE TITLE
Customizing the input to use Material UI

### ISSUE THREAD

**Issue by benjam1n** [gpbl/react-day-picker#729]
Hi there!

I'm wondering if there's a way to use Material UI's TextField as a input?

Here's something I tried but can't make it work:

```js
import React from "react";
import { DayPickerInput } from 'react-day-picker';
import TextField from "@material-ui/core/TextField";

class DatePickerCustomInput extends React.Component {
  render() {
    return (
      <TextField
        type="text"
        name="text"
        label="Date"
        placeholder=""
      />
    );
  }
}

class DatePicker extends React.Component {
  render() {
    return (
     <DayPickerInput component={<DatePickerCustomInput />} />
    );
  }
}

export default DatePicker;
```

The error:

`
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`

**Comment by gpbl** [comment]
Please check the `component` prop docs: http://react-day-picker.js.org/api/DayPickerInput#component

```diff
- <DayPickerInput component={<DatePickerCustomInput />} />
+ <DayPickerInput component={DatePickerCustomInput} /> 
```

**Comment by drbeat** [comment]
I think the docs are misleading as I needed to find this to make it work :/

**Comment by drbeat** [comment]
> 
> 
> Please check the `component` prop docs: http://react-day-picker.js.org/api/DayPickerInput#component
> 
> ```diff
> - <DayPickerInput component={<DatePickerCustomInput />} />
> + <DayPickerInput component={DatePickerCustomInput} /> 
> ```

I think the docs are misleading as I needed to find this to make it work :/
