### ISSUE TITLE
DayPickerInput prevent from typing

### ISSUE THREAD

**Issue by matheusml** [gpbl/react-day-picker#731]
Hi, 

I was reading the docs but I didn't find a prop that I could send to the component in order to prevent user from typing in the input.

Is there a way to do it?

Thanks

**Comment by gpbl** [comment]
[`inputProps`](http://react-day-picker.js.org/api/DayPickerInput#inputProps) prop should work:

```jsx
<DayPickerInput inputProps={{ readOnly: true }} />
```
