### ISSUE TITLE
Jalaali & Hijri calendar

### ISSUE THREAD

**Issue by EleRam** [gpbl/react-day-picker#732]
Is there any way to use this calendars?

**Comment by gpbl** [comment]
I don't know. What have you tried so far? Maybe with https://github.com/jalaali/moment-jalaali

**Comment by EleRam** [comment]
I imported 'moment-jalaali' as Moment and then used this:
```
formatDate: function(date, format, locale) {
	return Moment(date).format(format);
}
```

but it just changes the input value not the calendar (overlay)

**Comment by gpbl** [comment]
Please follow this example: http://react-day-picker.js.org/examples/input-moment which implements another language using moment in both input and overlay. Not sure about jalaali however... just give a try 👍

**Comment by gpbl** [comment]
Hey @EleRam some follow ups? I'm closing this for now.
