### ISSUE TITLE
DayPickerInput value for ranges

### ISSUE THREAD

**Issue by matheusml** [gpbl/react-day-picker#733]
Hi,

I'm using a very similar version of this select range: [http://react-day-picker.js.org/examples/selected-range](http://react-day-picker.js.org/examples/selected-range).

The difference is that I'm using it with `DayPickerInput`.

I need to show the selected range in the input, so I change the `value` prop like this:

```jsx
value={
  range.from && range.to
    ? `${formatDateForDayPicker(range.from)} ${translate("TO")} ${formatDateForDayPicker(range.to)}`
    : translate("SELECT_A_DATE_PERIOD")
}
```

This approach is working fine, the only problem with this is that after I select a date period, when I open the DayPicker again it shows the current date, and not the selected range.

I think that your using the `value` prop to do that, but you'll probably should be using the `selectedDays` prop.

Here's the full code:

```jsx
<FilterGroup>
  <RadioButtion
     type="radio"
     value={OPTION2}
     checked={selectedOption === OPTION2}
     onChange={onChangeOption}
  />
  <RadioLabel>{translate("PER_PERIOD")}:</RadioLabel>
    <DayPickerWrapper isRange disabled={selectedOption !== OPTION2}>
      <DayPickerInput
         placeholder={translate("SELECT_A_DATE_PERIOD")}
         formatDate={formatDateForDayPicker}
         onDayChange={onChangeDateRange}
         dayPickerProps={{
           locale: getLanguage(),
           localeUtils,
           numberOfMonths: 2,
           selectedDays: [range.from, range],
           modifiers,
           className: "DatePickerRange"
         }}
         hideOnDayClick={false}
         inputProps={{
            readOnly: true,
            disabled: selectedOption !== OPTION2
         }}
         value={
             range.from && range.to
                ? `${formatDateForDayPicker(range.from)} ${translate(
                   "TO"
                )} ${formatDateForDayPicker(range.to)}`
               : translate("SELECT_A_DATE_PERIOD")
              }
         />
      <Icon type="Arrow" color={darkGreen} />
   </DayPickerWrapper>
</FilterGroup>
```

**Comment by gpbl** [comment]
I'm not sure how difficult is to use `DayPickerInput` for displaying a "<date> to <date>" text into the input. Also, why the need of an input field? Do you expect users to write a range of dates in it? Anyway, it will be easier to test your code from a CodeSandbox (keep in mind, if it is a lot of code I personally won't have the time to look at it).

For what I can see there you are missing a `parseDate` prop. Try playing with `formatDate` and `parseDate` to make the day picker understand how the input value should be formatted and parsed
