### ISSUE TITLE
Add validity to onDayChange

### ISSUE THREAD

**Issue by mwilliamson-healx** [gpbl/react-day-picker#734]
For my use-case, it'd be useful to get the validity of the input when `onDayChange` is called. I've made a branch with these changes on: https://github.com/gpbl/react-day-picker/compare/master...healx:on-day-change-is-valid.

Is this something that'd be useful to merge in?

**Comment by mwilliamson-healx** [comment]
I've also needed to add in a `text` property, so that the input can reflect what the user's actually typed in.

I think what I really want is to have a controlled component version of `DayPickerInput`, but I think the changes I've made on that branch get close enough. Happy to be told of better approaches!

**Comment by gpbl** [comment]
Hey @mwilliamson-healx sorry for the delay...

> For my use-case, it'd be useful to get the validity of the input when onDayChange is called.

If the first argument is `undefined`, the day input is not valid – isn't this enough? 

> I've also needed to add in a text property, so that the input can reflect what the user's actually typed in.

I think you are referring to this issue: https://github.com/gpbl/react-day-picker/issues/736 Patch coming soon!

**Comment by mwilliamson-healx** [comment]
It's been a while since I looked at this, but I think the issue is that the `undefined` value doesn't let you distinguish between an invalid date, and the empty state. Exposing the text in the input would suffice for this, which also necessary for my use-case since I'm using it as a controlled component.
