### ISSUE TITLE
Leftover `focusTo` in docs?

### ISSUE THREAD

**Issue by thomas88** [gpbl/react-day-picker#735]
I'm implementing a date range picker in our app at the moment and looking at the examples online. Thereby I noticed that the `focusTo()` function in this example http://react-day-picker.js.org/examples/input-from-to does not seem to be used any more. Am I missing something? 

If this is actually not used any more, I can provide a pull request removing it from the docs.

**Comment by gpbl** [comment]
@thomas88 thanks for spotting this: yes, that must be a leftover... I'd be super happy to receive a PR :)

**Comment by thomas88** [comment]
Thanks for the fast reply. I've opened a pull request here https://github.com/gpbl/react-day-picker/pull/737 :)

**Comment by gpbl** [comment]
Thanks!
