### ISSUE TITLE
Month and year picker

### ISSUE THREAD

**Issue by LouisCuvelier** [gpbl/react-day-picker#738]
Hi,

Is there a way to transform the picker into a month picker and a year picker ?

Thanks for this lib and for your help ! 😄

**Comment by gpbl** [comment]
No, but you can easily implement one for sure, e.g. displaying it [`onCaptionClick`](http://react-day-picker.js.org/api/DayPicker#onCaptionClick). Here there's an example: http://react-day-picker.js.org/examples/elements-year-navigation. 

We were talking about a similar feature here: https://github.com/gpbl/react-day-picker/issues/722

**Comment by LouisCuvelier** [comment]
Sorry, I misspoke. I was talking about something like this :
https://github.com/nickeljew/react-month-picker
