### ISSUE TITLE
Month picker

### ISSUE THREAD

**Issue by LouisCuvelier** [gpbl/react-day-picker#744]
Hello,

Is it possible to transform the day picker to a month picker (without to have to select a day) ?
Here's an example : https://github.com/nickeljew/react-month-picker

Thanks for support 👍

**Comment by gpbl** [comment]
Hi @LouisCuvelier! 

You could mark all the days as selected using `onDayClick` and [`onCaptionClick`](https://react-day-picker.js.org/api/DayPicker#onCaptionClick). Things like `react-month-picker` are out of the scope of this project...
