### ISSUE TITLE
DayPickerInput range limited to 1000 - 9999

### ISSUE THREAD

**Issue by JuhQ** [gpbl/react-day-picker#757]
It seems odd that I can choose dates outside of this range but I can't set the date through the input to be in between year 1000 and year 9999.

My code:

```
import MomentLocaleUtils, {
  formatDate,
  parseDate
} from 'react-day-picker/moment';


<DayPickerInput
  dayPickerProps={{
    locale: 'fi',
    localeUtils: MomentLocaleUtils
  }}
  formatDate={formatDate}
  parseDate={parseDate}
  placeholder={formatDate(new Date(), 'LL', 'fi')}
/>
```

**Comment by JuhQ** [comment]
I can set the date to be less than year 1000 with 0999, but this is not a valid representation of a year.

**Comment by gpbl** [comment]
@JuhQ could be a limitation of  momentjs? Could you include the code in a codesandbox so we can test it? Thanks!

**Comment by gpbl** [comment]
Reopening when we have a way to reproduce it :)
