### ISSUE TITLE
Expose some useful date utilities

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#76]
The idea is to export some of the internal functions that could  be useful when writing modifiers:

```js
import DayPicker, { DateUtils } from "react-day-picker"
```

e.g. `isSomeDay` (https://github.com/gpbl/react-day-picker/issues/75), `rangeOfDays` (#47), `isDayOutsideMonth`, `isPastDay`, `isDayBetween`, etc.

**Comment by gnrlbzik** [comment]
:+1:

**Comment by bvaughn** [comment]
:+1: The examples make use of `isPastDay` and `isSameDay`. Those would be nice to have access to (even though their implementation is simple enough to fork).

**Comment by gnrlbzik** [comment]
So are there exposed now as well, or I am missing something, i just saw rename utils>helpers

**Comment by gpbl** [comment]
Eheh wait first I had to publish the thing 😀 
I could extract some functions and expose them in `v1.1.0`:

```js
import { dateUtils } from "react-day-picker/utils";
```

the exported functions are not yet documented, but you can see them [here](https://github.com/gpbl/react-day-picker/blob/master/src/DateUtils.js).

**Comment by gnrlbzik** [comment]
@gpbl thank you so much. I will be looking forward to it. Will update our component and add locale support.

**Comment by bvaughn** [comment]
Thanks for the quick update. :) Much appreciated!
