### ISSUE TITLE
Add Input Validation and Date Validation

### ISSUE THREAD

**Issue by parwat08** [gpbl/react-day-picker#766]
Hi, The input field must have the input restricted to the number.
 
Currently, we can type text also. And It would great to see the Date validation like (month range, date range)

Month Validation should also be added like in the `M` placeholder where the range must be up to `1-12`
e.g: February 2018, The last date of February is 28
      And the input format is `YYYY-M-D`
Now, if a user types `2018-2-X`, then the X value must be restricted from 1 to 28.

**Comment by gpbl** [comment]
@parwat08 the `DayPickerInput` component doesn't make any assumption about how do you want to customize the input behavior. If you need to use an input field working differently, you can use the `component` prop: http://react-day-picker.js.org/api/DayPickerInput#component
