### ISSUE TITLE
Disable all the days in the calendar, and enable only an Array of Days

### ISSUE THREAD

**Issue by pedromagalhaes** [gpbl/react-day-picker#768]
Hi, as Im mentioning in the title, Im trying to achieve something that i dont think the plugin has yet the capability. 

- I need to disable the click of all the days, except an array of days (e.g 2 in jan, 5 in aug, 3 sept, etc.)

Please point me out the documentation to achieve this. I already looked for it both in github, stackoverflow and plugin documentation and there is nothing I could found. 

For me this a trivial request and should be included in the plugin to make it even more flexible and awesome! 

Thanks!

**Comment by gpbl** [comment]
The `disabledDays` prop can accept a function that can check if the day is in your array of days:

```jsx
import DayPicker, { DateUtils } from 'react-day-picker';

const disabledDays = [
   new Date(2020, 0, 2), // Jan, 2nd
   new Date(2020, 7, 7), // Aug, 7th
]

function isDayDisabled(day) {
  return disabledDays.some(disabledDay => 
    DateUtils.isSameDay(day, disabledDay)
  )
}

<DayPicker disabledDays={isDayDisabled} />
```

(it should work, I didn't test it)

**Comment by pedromagalhaes** [comment]
Thanks this is exactly what I needed! 👍

**Comment by CristianCucunuba** [comment]
Actually it does the opposite

**Comment by Manne010** [comment]
@CristianCucunuba have u find solution?

**Comment by CristianCucunuba** [comment]
Yes, i found the solution luckylt in another issue

`
// Disable the day on the calendar if it's not available in the affilate schedule
  const isDisabledDay = (day) => daysAvailable.find((availableDate) =>
    moment(day).format("YYYY-MM-DD") === moment(availableDate).format("YYYY-MM-DD")) === undefined;
`

**Comment by MorenoMdz** [comment]
> The `disabledDays` prop can accept a function that can check if the day is in your array of days:
> 
> ```js
> import DayPicker, { DateUtils } from 'react-day-picker';
> 
> const disabledDays = [
>    new Date(2020, 0, 2), // Jan, 2nd
>    new Date(2020, 7, 7), // Aug, 7th
> ]
> 
> function isDayDisabled(day) {
>   return !disabledDays.some(disabledDay => 
>     DateUtils.isSameDay(day, disabledDay)
>   )
> }
> 
> <DayPicker disabledDays={isDayDisabled} />
> ```
> 
> (it should work, I didn't test it)

Actually you just need to bang ! invert it and it should work. @CristianCucunuba and not need to import another lib.

```javascript
!dates.some(disabledDay =>
      DateUtils.isSameDay(day, disabledDay.activeDate.toDate())
    );
```

**Comment by krishanshyperspace** [comment]
This is working properly with DayPicker but not working in DayPickerInput. How can I enable only an array of days and disable all other days in DayPickerInput?
