### ISSUE TITLE
Add `left: auto` to navigation buttons CSS

### ISSUE THREAD

**Issue by DDDDDanica** [gpbl/react-day-picker#771]
Hey guys,

Really appreciate the hard work on the library, it is light and amazing.
There's a small issue i encountered in terms of styles i think it might be a small improvement.
In the style for DayPicker-NavButton(the left and right arrow to navigate months), the original css is 

```diff
    position: absolute;
    cursor: pointer;
    top: 1rem;
    right: 1.5rem;
    margin-top: 2px;
`
```

However, there's no left style appended to icon, which will result in unexpected layout.

So my suggestion is to add one line as 

```diff
    position: absolute;
    cursor: pointer;
    top: 1rem;
+ . left: auto;
    right: 1.5rem;
    margin-top: 2px;
`
```

It will do the trick.

Thanks guys.

**Comment by gpbl** [comment]
Oh, thanks – I did not know!
