### ISSUE TITLE
Disabled days not working in IE9

### ISSUE THREAD

**Issue by Rommadon** [gpbl/react-day-picker#772]
![aug-15-2561 16-15-26](https://user-images.githubusercontent.com/25241006/44141204-9f0a2398-a0a6-11e8-911e-b913836362f2.gif)

**Comment by gpbl** [comment]
Thanks, I'll check it out – someone could help with IE9 here?

**Comment by beckerei** [comment]
Can you provide a small demo where I can have a look at it. Maybe on codesandbox, if that works in IE9.
