### ISSUE TITLE
By pressing tab in DayPickerInput, the body element is focused if it opened in react modal

### ISSUE THREAD

**Issue by naisergic** [gpbl/react-day-picker#773]
I am using react-day-picker v7.1.10 it is inside react modal, so in your code you are closing date picker on pressing TAB and it has tabindex 0 so when you close it focus goes on body, and then again on pressing TAB focus goes on the close button as react modal put the focus on the first element,

but instead of pressing TAB, we put focus on the opened calendar then also it is working fine.

**It is working fine if we use it on normal page**. 

can we do it something like that if we pass a prop "closeOnTab" then only we close datepicker then we don't need to write any extra JS to put focus on the next element

**Comment by gpbl** [comment]
Hi @naisergic! Could you reproduce your issue in a CodeSandbox? https://codesandbox.io/s/XDAE3x0W8

I'm not sure we can do much for fixing this, but maybe using a different `tabIndex` for the Overlay could help (I just need to try). Thanks!
