### ISSUE TITLE
1.1.0 is a breaking change

### ISSUE THREAD

**Issue by iest** [gpbl/react-day-picker#78]
Renaming `Util` to `Helper` (on 0eee2ec868d3b617bbd2668ba1f121a15bf42fdd) and then eventually to `dateUtils` (on f555948a0b376d1c0e797ce4b967f20bc65792a3) is a breaking change according to [semver](http://semver.org).

The latest version should be at least `2.0.0`.

**Comment by gpbl** [comment]
Uhm... did the change break something documented in the API? Because semver applies to the public API, while `Utils` was an internal module.

**Comment by iest** [comment]
Depends what you mean as a "public API" — your [Selectable day](http://www.gpbl.org/react-day-picker/#examples/selectable) example uses the "internal module" for `isSameDay`. I imagine a lot of your users (myself included) use those utilities on their own components.

If your examples use private APIs that aren't included in your definition of semver, I suggest you remove them or label them as such?

Don't get me wrong — this module is awesome and it's saved me a lot of time — I'm just logging an issue that others might well run into.

**Comment by gpbl** [comment]
👍 The examples are right, they have been rewritten for v1.1. Starting from this version, those API are public and [documented](http://www.gpbl.org/react-day-picker/docs/DateUtils.html): from now breaking changes to those utilities will bump a major version.

I'm sorry for the confusion, there've been some delay with the new website...

**Comment by iest** [comment]
Awesome! Glad to hear it :sparkles:

**Comment by gpbl** [comment]
Closing this now that we are on v1.2.0! Thanks for reminding me about the dangers of semver :) I hope I won't break things anymore 🚶
