### ISSUE TITLE
Buggy with date-fns

### ISSUE THREAD

**Issue by yantakus** [gpbl/react-day-picker#785]
I've created a codesanbox to easily reproduce the issue: https://codesandbox.io/s/7yln949mw6

Select a date range and see how date is formatted incorrectly:

![image](https://user-images.githubusercontent.com/2179726/44861814-02f2e980-ac82-11e8-9d89-dc4858e4d45f.png)

**Comment by gpbl** [comment]
You should use `date-fns` compatible [format strings](https://date-fns.org/v2.0.0-alpha.9/docs/format). `DD` is the "day of the year".

**Comment by yantakus** [comment]
@gpbl thanks, my bad!
