### ISSUE TITLE
Bower Support

### ISSUE THREAD

**Issue by JKillian** [gpbl/react-day-picker#79]
Although not ideal, I'm in a situation where installing the package via NPM doesn't meet my use case as we're not using browserify, webpack or anything like that. Is there a current usage story for using this via bower? If not, would you be interested in a contribution to make it more bower friendly?

**Comment by gpbl** [comment]
Yes thanks! I have no idea how does bower work, but sure it would be nice to support it.

**Comment by gpbl** [comment]
Woah I've made some crazy things with `bower register`, `npm publish` etc... 👯 now it should work everything as version 1.1.3. 

@JKillian Could you please test if it *actually* works with bower and eventually close the issue? I don't get why it doesn't appear in [their search](http://bower.io/search/?q=react-day-picker)...

**Comment by JKillian** [comment]
@gpbl I see it in the search now - probably just a caching issue! I'll try it out now

**Comment by JKillian** [comment]
Working like a charm in my project :+1:

**Comment by JKillian** [comment]
Right now we're only exposing the DayPicker React Class as a global variable named `DayPicker`. Do you think instead we should export an object called `DayPicker` and then it could have the following fields:

* DayPicker
* LocalUtils
* MomentLocaleUtils
* Helpers
* DateUtils

or something similar to that?

**Comment by gpbl** [comment]
I was wondering as well... we should however export only the "official" API. 

I don't know what are the common practices for a bower component, but I imagine:

```js
DayPicker
DayPicker.localeUtils
DayPicker.dateUtils
DayPicker.momentLocaleUtils
```

I think we can add some static properties to `DayPicker` when exporting it, so that the component is actually `<DayPicker />` and not `<DayPicker.DayPicker>` or, as I thought at first, `<DayPicker.Component />`. 

(I'm not so happy for this `*Utils`  convention , how would you call them?)

**Comment by gpbl** [comment]
I have no interest in bower so I'd really appreciate a PR 🖖. (pay attention to that `momentLocaleUtils`, because it requires `moment` but I won't put moment as dependency. Maybe you need some "ignore" setting in the webpack config).

Deep thanks for your support, JKillian!

**Comment by JKillian** [comment]
I think PR #93 should take care of things here. Let me know once you release and I'll test it out!

**Comment by gpbl** [comment]
@JKillian I've published as 1.1.4 – it should work! Does it? 👀

**Comment by JKillian** [comment]
Working well for me! :+1:

**Comment by gpbl** [comment]
excellent! thanks for the help!
