### ISSUE TITLE
work without npm, grunt and all that stuff

### ISSUE THREAD

**Issue by pjebs** [gpbl/react-day-picker#8]
HI There,

How Can I make this work without any of those fancy node.js dependencies.
I'm new to react. Im just including the standard react.js file in my html file. I'm although using the JSX transformer (which I will get rid of later).
I just want to drop the js files (DayPicker.js and utils.js) and possibly moment.js (I noticed you wrote in a issue that it's not strictly required).

I took out the export and import statements from the Daypicker and utils file but it still isn't working.

**Comment by pjebs** [comment]
I'm assuming I have to convert the provided scss file to css too and include that in.

**Comment by gpbl** [comment]
Hi @pjebs thank you for the feedback – tbh I don't plan to make a stand-alone version. You are going to use a module loader anyway soon :-)

**Comment by pjebs** [comment]
Can you give some clues on how I can do it?

**Comment by pjebs** [comment]
When I look at your code, it looks like only a few lines of code need to be changed.

**Comment by pjebs** [comment]
please help me.

**Comment by gpbl** [comment]
@pjebs we need to make a webpack config to expose `ReactDayPicker` as global var and to minify the two scripts into one. If you are planning to use other react components, it's likely you will do the same thing by yourself with webpack or browserify. Anyway, I don't have much time to look into this right now: but I suggest you to try browserify or webpack :-)

**Comment by pjebs** [comment]
function weeks(m) {

  const firstOfMonth = m.clone().startOf('month');
  const lastOfMonth = m.clone().endOf('month');
  
  var currentDay = firstOfMonth.clone();
  var currentWeek = [];
  var weeksInMonth = [];

  while (currentDay < lastOfMonth) {
    currentWeek.push(currentDay.clone());
    currentDay.add(1, 'd');
    if (currentDay.weekday() === 0 || currentDay > lastOfMonth) {
      weeksInMonth.push(currentWeek);
      currentWeek = [];
    }
  }
  return weeksInMonth;
}


var DayPicker = React.createClass({

  propTypes: {

    enableOutsideDays: React.PropTypes.bool,

    initialMonth: React.PropTypes.object, // default is current month
    modifiers: React.PropTypes.object,

    onDayClick: React.PropTypes.func,
    onDayTouchTap: React.PropTypes.func, // requires react-tap-event-plugin
    onDayMouseEnter: React.PropTypes.func,
    onDayMouseLeave: React.PropTypes.func,

    onNextMonthClick: React.PropTypes.func,
    onPrevMonthClick: React.PropTypes.func

  },

  getDefaultProps: function() {
    return { initialMonth: moment(), enableOutsideDays: false };
  },

  getInitialState: function() {
    return { month: this.props.initialMonth.clone() };
  },

  handleDayTouchTap: function(day, modifiers, e) {
    if (this.props.onDayTouchTap) {
      this.props.onDayTouchTap(day, modifiers, e);
    }
  },

  handleDayClick: function(day, modifiers, e) {
    if (this.props.onDayClick) {
      this.props.onDayClick(day, modifiers, e);
    }
  },

  handleDayMouseEnter: function(day, modifiers, e) {
    if (this.props.onDayMouseEnter) {
      this.props.onDayMouseEnter(day, modifiers, e);
    }
  },

  handleDayMouseLeave: function(day, modifiers, e) {
    if (this.props.onDayMouseLeave) {
      this.props.onDayMouseLeave(day, modifiers, e);
    }
  },

  handleNextMonthClick: function(e) {
    e.preventDefault();
    e.stopPropagation();
    const { month } = this.state;
    const nextMonth = month.clone().add(1, 'month');
    this.setState({ month: nextMonth }, () => {
      if (this.props.onNextMonthClick) {
        this.props.onNextMonthClick(this.state.month);
      }
    });
  },

  handlePrevMonthClick: function(e) {
    e.preventDefault();
    e.stopPropagation();
    const { month } = this.state;
    const prevMonth = month.clone().subtract(1, 'month');
    this.setState({ month: prevMonth }, () => {
      if (this.props.onPrevMonthClick) {
        this.props.onPrevMonthClick(this.state.month);
      }
    });
  },

  getModifiersForDay: function(day) {
    const { modifiers } = this.props;
    let dayModifiers = [];
    if (modifiers) {
      for (let modifier in modifiers) {
        let func = modifiers[modifier];
        if (func(day)) {
          dayModifiers.push(modifier);
        }
      }
    }
    return dayModifiers;
  },

  showMonth: function(month) {
    this.setState({month: month});
  },

  render: function() {
    const { month } = this.state;
    return (
      <table className="DayPicker">
        <caption className="DayPicker-caption">
          { this.renderNavButton('left') }
          { month.format('MMMM YYYY') }
          { this.renderNavButton('right') }
        </caption>
        <thead>
          { this.renderWeekHeader() }
        </thead>
        <tbody>
          { this.renderWeeks() }
        </tbody>
      </table>
    );
  },

  renderNavButton: function(position) {
    const className = `DayPicker-nav DayPicker-nav--${position}`;
    const handler = position === 'left'
      ? this.handlePrevMonthClick
      : this.handleNextMonthClick;

    return <span ref={"btn-"+position} className={className}
      style={{float: position}} onClick={handler} />;
  },

  renderWeeks: function() {
    return weeks(this.state.month).map((week, i) =>
      <tr key={i} className="DayPicker-week">
        { this.renderDays(week) }
      </tr>
    );
  },

  renderWeekHeader: function() {
    let header = [];
    for (let i = 0; i < 7; i++) {
      header.push(
        <th key={i} className="DayPicker-weekday">
          { moment().weekday(i).format('dd') }
        </th>
      );
    }
    return header;
  },

  renderDays: function(week) {
    const firstDay = week[0];
    const lastDay = week[week.length-1];

    let days = week.map(day => this.renderDay(day));

    // days belonging to the previous month
    for (let i = 0; i < firstDay.weekday(); i++) {
      const prevDay = firstDay.clone().subtract(i+1, 'day');
      days.unshift(this.renderDay(prevDay, true));
    }

    // days belonging to the next month
    for (let j = lastDay.weekday() + 1, count = 1; j < 7; j++, count++) {
      const nextDay = lastDay.clone().add(count, 'day');
      days.push(this.renderDay(nextDay, true));
    }

    return days;
  },

  renderDay: function(day, outside) {
    const key = `${day.dayOfYear()}`;
    let className = 'DayPicker-day';
    if (outside) {
      className += ' DayPicker-day--outside';
    }
    if (outside && !this.props.enableOutsideDays) {
      return <td className={className} ref={key} key={key} />;
    }
    else {
      const modifiers = this.getModifiersForDay(day);
      className += modifiers.map(mod => ` DayPicker-day--${mod}`).join('');
      return (
        <td ref={key} key={key}
          className={className}
          onMouseEnter={this.handleDayMouseEnter.bind(this, day, modifiers)}
          onMouseLeave={this.handleDayMouseLeave.bind(this, day, modifiers)}
          onTouchTap={this.handleDayTouchTap.bind(this, day, modifiers)}
          onClick={this.handleDayClick.bind(this, day, modifiers)}>
          { day.format('D') }
        </td>
      );
    }
  }

});

var c = React.render(
  <DayPicker />,
  document.getElementById('calendar')
);

**Comment by pjebs** [comment]
In that case, how can I use the precompiled version you have in the dist folder: DayPicker.js and utils.js

I included those files in my html file.

Chrome keeps saying: 

Uncaught ReferenceError: exports is not defined utils.js:5 (anonymous function)
Uncaught ReferenceError: require is not defined DayPicker.js:5 

What other files would I need to include?

**Comment by gpbl** [comment]
Hi @pjebs, you could use browserify or webpack to minify the lib into a single file and expose it as global var.

**Comment by pjebs** [comment]
I attempted to use browserify. I don't think your code works with React 0.13 anymore.

I cd into src directory. then ran sudo browserify DayPicker.js -o pj.js

And it spits out this error:

Error: Parsing file /Users/PJ20/Desktop/react-day-picker-master/src/DayPicker.js: Unexpected token (101:6)
    at Deps.parseDeps (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:418:28)
    at fromSource (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:361:48)
    at /usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:356:17
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/browserify/node_modules/concat-stream/index.js:32:43)
    at ConcatStream.emit (events.js:129:20)
    at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:199:16)

**Comment by gpbl** [comment]
@pjebs the src is written in babeljs, so if you want to compile from the source you need to use babelify. You go better with the dist version:

```
browserify ./dist/DayPicker.js -o pj.js
```

actually you shouldn't need to run it with `sudo`. 

Beware this won't be enough for your goal, because you need to make the module accessibile from the global scope (honestly i have no idea on how to make this with browserify). 

But again I suggest you to adopt the module from npm, and use browserify or webpack for writing your app – instead of messing up with this single module. You need to read some docs before, but it's worth the time spent.
