### ISSUE TITLE
Clicking on selected day again removes the format

### ISSUE THREAD

**Issue by ArunChockalingam** [gpbl/react-day-picker#802]
Code Sandbox: https://codesandbox.io/s/5v1xpq01on

Steps to reproduce:

1. choose a day (format will be MM/DD/YYYY)
2. choose the same day again (format will change to YYYY-MM-DD)

If you choose a different day, then it will go back to MM/DD/YYYY.

Can you please help with this issue or suggest other alternatives. Thanks!

**Comment by Flaeron** [comment]
I have the same trouble :(
