### ISSUE TITLE
Can't set empty value for input ( reproduction )

### ISSUE THREAD

**Issue by wenzoto** [gpbl/react-day-picker#804]
There was a [similar error](https://github.com/gpbl/react-day-picker/issues/666), but could not reproduce it.

https://codesandbox.io/s/7m6q1y8xmj

### reproduction

<a href="https://gyazo.com/5bbb2bc21ffb6a2bede4045e91cf7ed3"><img src="https://i.gyazo.com/5bbb2bc21ffb6a2bede4045e91cf7ed3.gif" alt="Image from Gyazo" width="538"/></a>

**Comment by cjnickel** [comment]
Ran into this issue as well. Looks like PR #816 should fix this assuming it gets merged.

**Comment by Bereware** [comment]
This would be a temporary solution.
This error is the one that shows when you try to modify the state:
 _**Warning: A component is changing a controlled input of type undefined to be uncontrolled**_

I have solved it this way, it is not recommended to use refs but ... xD 
```js
<DayPickerInput
    value={from}
    ref={(el) => (this.from = el)}
.../>
<DayPickerInput
    value={to}
    ref={(el) => (this.to = el)}
.../>
handleResetClick = () => {
        // this fixed the encapsulated input uncontrolled bug
        this.from.setState({ value: '', typedValue: '' });
        this.to.setState({ value: '', typedValue: '' });
    };
```
I hope help you

**Comment by serban-condrea** [comment]
In order to avoid refs, I used another little hack 😅

```
<DayPickerInput
    value={to || ' '}
.../>
```

**Comment by gpbl** [comment]
This has been fixed in the latest releases - please upgrade thanks

**Comment by owen-stellar** [comment]
Though I've upgraded to 7.4.8 I don't see this being resolved. When I clear out the value (in a blur function when the entry is deemed to be invalid) the typedValue remains the same. Is there something more that needs to be done besides simply upgrading to 7.4.8?

**Comment by tanelih** [comment]
The latest release still exhibits this problem when clearing a value that is not a valid Date.

I've played around changing the following line to also set the typed value to the given value & the problem seems to go away.

https://github.com/gpbl/react-day-picker/blob/v7/src/DayPickerInput.js#L198

```
if (isDate(value)) {
  newState.value = formatDate(value, format, dayPickerProps.locale);
} else {
  newState.value = value;
  newState.typedValue = value;
}
```

However I'm not a 100% certain this is the best solution, but it seems to work for my use case, where dates are stored in the form state as plain strings.
