### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by zomars** [gpbl/react-day-picker#808]
When trying to follow the localization example I'm getting the following error:

```
moment.js?5738:3 Uncaught ReferenceError: require is not defined
    at eval (moment.js?5738:3)
    at Object../node_modules/react-day-picker/moment.js (main.js:70846)
    at __webpack_require__ (main.js:765)
    at fn (main.js:128)
```

**Comment by gpbl** [comment]
Hi @zomars please read

https://github.com/gpbl/react-day-picker/blob/master/.github/ISSUE_TEMPLATE.md

and update your issue! I’ll reopen it when we have more info. Thanks.

**Comment by zomars** [comment]
Sorry but the sandbox link is throwing an error: https://codesandbox.io/s/XDAE3x0W8

```
Invariant Violation
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

**Comment by gpbl** [comment]
Working great here. Which browser are you using?

**Comment by zomars** [comment]
On the [sandbox it's working fine](https://codesandbox.io/s/x9pr5o98q4), but in my local install it's displaying this warning, I don't know if it's related:

![image](https://user-images.githubusercontent.com/3504472/46320347-1a800380-c59b-11e8-9284-2bcbd8c89ca2.png)
