### ISSUE TITLE
LocaleUtils should be exported from types/index.d.ts

### ISSUE THREAD

**Issue by UselessPickles** [gpbl/react-day-picker#812]
Previous versions of react-day-picker exported the LocaleUtils interface in the TypeScript type definitions. This was changed at some point, and LocaleUtils is no longer exported.

Without this exported type, it is still possible, but cumbersome, to obtain the type as follows:
```ts
import { DayPickerProps } from "react-day-picker";
type DayPickerLocaleUtils = Exclude<DayPickerProps["localeUtils"], undefined>;
```

It would be much more convenient if LocaleUtils was exported by "react-day-picker".

Similarly, the other interfaces defined in utils.d.ts should probably also be exported for convenience. This would be as simple as adding the following line to index.d.ts:
```ts
export * from './utils';
```

**Comment by ZakTax** [comment]
I am hitting the same issue

**Comment by vertic4l** [comment]
same here

**Comment by UselessPickles** [comment]
There's already a PR for this that have been open since Nov 28, 2018. Can we get this merged? It's a one-liner: https://github.com/gpbl/react-day-picker/pull/834
