### ISSUE TITLE
DayPicker-Weekdays should have a table-row as child

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#82]
As pointed out by @nkbt, [this commit](https://github.com/gpbl/react-day-picker/commit/0164a38f651771c00d3b4949898937d2013c7ddd) broke some styles, so [the proposed solution](https://github.com/gpbl/react-day-picker/pull/81) by @JKillian is to remove `display: table-row` in  the CSS.

However it is preferred to have a `table-row` inside `DayPicker-Weekdays`, which is a `table-header-group`.

So we should revert that commit and restore the surrounding `div`. This `div` was however missing a className, thus the confusion that lead to this problem: I'd assign to this element the `DayPicker-Weekdays-row` class.

**Comment by nkbt** [comment]
Oh, so I actually ran into bug. Thanks!
