### ISSUE TITLE
Make all dates except for certain ones disabled

### ISSUE THREAD

**Issue by amasson99** [gpbl/react-day-picker#835]
Hey there,

I am trying to make it so that in react-day-picker, only the dates that are available are selectable 
(i.e. A user is only available for two days, all those other days are disabled and unselectable). 

I've tried doing this method:
```
<DayPicker
      selectedDays={this.state.selectedDays}
      onDayClick={this.handleDayClick}
      disabledDays={(day => (day !== ServiceRequestEngagementCreateModal.availableDates(service.available_dates)))}
    />
```
But that makes all of the dates unavailable.

Any help would be appreciated, thanks!

Link to where I asked it on SO: https://stackoverflow.com/questions/53576996/make-all-dates-except-for-certain-ones-disabled

**Comment by amasson99** [comment]
@tricinus Hey there, I figured it out. Heres the code we ended up using
`
<DayPicker
              selectedDays={this.state.selectedDays}
              onDayClick={this.handleDayClick}
              disabledDays={(day => (availableDateStrings.indexOf(day.toDateString()) === -1))}
            />`

**Comment by tricinus** [comment]
Thanks @amasson99 !

**Comment by gpbl** [comment]
(Seem solved – closing)
