### ISSUE TITLE
set initial month as first available, if current month whole disabled

### ISSUE THREAD

**Issue by Alexander-64** [gpbl/react-day-picker#836]
So, here is a problem: if all days in the current month are disabled, no matter, react-day-picker shows the current month as initial. Is there another way, except computing a month where are available days for choosing?

**Comment by gpbl** [comment]
@Alexander-64 do you still need help for this? Also, a way to reproduce it would be nice. I’ll reopen it if you write back :)

**Comment by eseite47** [comment]
Was this resolved? I would love to know how to work around this as well. Thanks!
