### ISSUE TITLE
RTL keyboard handling issues

### ISSUE THREAD

**Issue by johnjesse** [gpbl/react-day-picker#837]
Hello,

First, let me say that so far I have found this library to be great!

I have an issue when using the day picker in RTL. the keyboard handling is counter-intuitive. Moving the arrow keys left/right moves the focus of the date in the opposite direction.
See: https://codesandbox.io/s/l9wj0ow469 - use the code-pen to move around the day picker with the arrow keys and you'll see what I mean.

It'd be nice if Day picker used the dir prop and then decided what to do based on that, I think I could submit a PR for that if we agreed that should be the approach. Also, the docs for the dir prop appears to be non-existant - http://react-day-picker.js.org/api/DayPicker#dir

**Comment by gpbl** [comment]
Fixed with #845
