### ISSUE TITLE
Why is onChange handler called onDayChange? 🤔

### ISSUE THREAD

**Issue by developer239** [gpbl/react-day-picker#853]
Why is `onChange` handler called `onDayChange`? 🤔

Please, don't take it the wrong way but imagine someone creating a react button component and instead of `disable` or `isDisabled` prop you would have to write something like `shouldIgnoreClick`.

**Comment by pmarcelll** [comment]
[`onDayChange`](http://react-day-picker.js.org/api/DayPickerInput/#onDayChange) is different from `onChange`, it doesn't receive an event, but three different parameters. If you want to call onChange, it's also available.

**Comment by developer239** [comment]
`DayPicker` does not have any `onChange` prop: https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L113

**Comment by pmarcelll** [comment]
`DayPicker` doesn't seem to have an `onDayChange` prop either.

**Comment by developer239** [comment]
It looks like the project I am working on has quite an old version of your package. I will migrate it maybe it will fix my issue. 🙂
