### ISSUE TITLE
why is months undefined in CaptionElementProps?

### ISSUE THREAD

**Issue by giladgray** [gpbl/react-day-picker#855]
the type for `CaptionElementProps.months` is declared as `undefined`, but I don't think that's true. is this a bug in the types?

https://github.com/gpbl/react-day-picker/blob/master/types/props.d.ts#L13

**Comment by giladgray** [comment]
@gpbl ping here? a quick answer would be appreciated. i'm happy to submit a PR if needed.

**Comment by johnjesse** [comment]
Would #842 cover it?

**Comment by giladgray** [comment]
@johnjesse yes that would do it! 

one concern is that elsewhere in the types, `months` is typed as a 12-element `string` tuple: https://github.com/gpbl/react-day-picker/blob/39ad48ecadb18355e28ee5ef1741ca484949760d/types/props.d.ts#L65-L78

**Comment by johnjesse** [comment]
Yep, I've submitted a PR to also change that to `string[]` (#843 ) as in my experience it is unwieldy, but if that isn't taken I'd happily change #842 to match the 12-element `string` tuple

**Comment by gpbl** [comment]
#843 and #842 are merged – they should fix your problem @giladgray (release coming soon). If not, please reopen.
