### ISSUE TITLE
The default `initialMonth` is determined on import instead of on mount

### ISSUE THREAD

**Issue by batmantis** [gpbl/react-day-picker#861]
The default value of the `initialMonth` prop is determined when the file is imported instead of when the component is mounted.  This is the opposite of what I would expect to happen.  For example, if the component is loaded close to midnight on the last day of the month and the component is mounted the following month, then the month will be wrong.

It's a little tough to demo the behavior, but this should give a general idea: https://codesandbox.io/s/nrxzq0223l

I plan to create a PR to fix this.

**Comment by gpbl** [comment]
Hey this is an interesting bug. Thanks for catching it up and the repro.
