### ISSUE TITLE
Release Plan

### ISSUE THREAD

**Issue by glockjt** [gpbl/react-day-picker#864]
How often do you plan to release changes?  There is a backlog of PRs that are pilling up.  It would be nice to get some of these fixes into master.

**Comment by gpbl** [comment]
Hey @glockjt thanks for asking! 

I enjoy maintaining this project but lately I haven’t had much time. The more I leave this repo alone, the more daunting is to start working on it again 😅 I found the courage to look at the issues/PRs: it is not that bad as I thought. It is rewarding seeing other people care about its progress. 

Updates are coming in the next months as I think I'll have some more free time 🙏 

Open to accept the help of new maintainers and to ideas to maintain better the project.

**Comment by gpbl** [comment]
For example, which bots could help me organizing the issues?

**Comment by gpbl** [comment]
Here some of the stuff I'd like to work on:

- remove the input component, it is really a bad idea
- make sure timezone issues are fixed / UTC mode
- maybe a better website, with versioning support (docusaurus?)
- what are labels that could actually help?
- move to typescript?
- do github’s “project” make sense? Would they help organizing the releases?
- find a better name for the concept of “modifier”
- add functional tests
- use jest snapshots in tests
- move to rollup
- better issues template (copy from famous repos)
- review styling customization

**Comment by davidspiess** [comment]
All the points you make sound reasonable. Especially first class typescript support would be awesome!
I can imagine the daunting task to keep incoming issues low, so don't feel bad for taking some time off, especially if you do something for free! You do a great job :)

**Comment by glockjt** [comment]
@gpbl Sorry for the delayed response.  I would be willing to help out and maintain this repo, maybe we could have a conversation some time to discuss what this would entail if I started helping you maintain.

**Comment by rdsedmundo** [comment]
> remove the input component, it is really a bad idea
I actually find it pretty useful. Why is it a bad idea?

**Comment by davidspiess** [comment]
Since our company relies heavily on your component, i could help out too!

**Comment by gpbl** [comment]
Some updates! Thanks for your patience. Moving this discussion here:

https://github.com/gpbl/react-day-picker/issues/921
