### ISSUE TITLE
Add icon in Component get error 'Attempts to access this ref will fail'

### ISSUE THREAD

**Issue by ekobayu** [gpbl/react-day-picker#869]
Hi,

I get error when passing some props combine with icon. Here is my code.
```
<DayPickerInput 
      value={moment().format('DD MMM YYYY')}
      placeholder={moment().format('DD MMM YYYY')}
      format='DD MMMM YYYY'
      formatDate={formatDate}
      parseDate={parseDate}
      dayPickerProps={{
      selectedDays: [new Date(moment())],
      disabledDays: {
      before: new Date(moment().add(1, 'days'))
       }
      }}
      onDayChange={this.handleImmediateDateChange}
      component={props => <Input icon='calendar alternate outline' {...props} /> }
/>
```

at `component={props => <Input icon='calendar alternate outline' {...props} />` I get error 

> Warning: Function components cannot be given refs. Attempts to access this ref will fail.

I follow suggestion from here but not works. [https://github.com/gpbl/react-day-picker/issues/748#issuecomment-441282377](url)

Current Version:
```
"react": "^16.5.2",
"react-dom": "^16.5.2",
"react-day-picker": "^7.2.4",
```

Please Help.

**Comment by ekobayu** [comment]
Maybe someone have same problem. Finally I got the solution. The problem is in the 'ref' cannot use in component so I set null for the 'ref' at inputProps. Here is for the full code.

```
<DayPickerInput 
      value={moment().format('DD MMM YYYY')}
      placeholder={moment().format('DD MMM YYYY')}
      format='DD MMMM YYYY'
      inputProps={{ ref: null }}
      formatDate={formatDate}
      parseDate={parseDate}
      dayPickerProps={{
      selectedDays: [new Date(moment())],
      disabledDays: {
      before: new Date(moment().add(1, 'days'))
       }
      }}
      onDayChange={this.handleImmediateDateChange}
      component={props => <Input icon='calendar alternate outline' {...props} /> }
/>
```

**Comment by diegodesouza** [comment]
@ekobayu Can you clarify what `<Input/>` component you're importing?

**Comment by ekobayu** [comment]
Hi @diegodesouza for ` <Input/> ` importing from react semantic library. On the head section I'm added this one `import { Input } from 'semantic-ui-react'`

**Comment by diegodesouza** [comment]
gotcha, thank you @ekobayu will try that.

**Comment by diegodesouza** [comment]
@ekobayu no success, I'm not sure what's happening, i asked this on stackoverflow as well https://stackoverflow.com/questions/60529206/how-to-add-icon-in-react-day-picker-daypickerinput
