### ISSUE TITLE
Preset date button

### ISSUE THREAD

**Issue by zek0faws** [gpbl/react-day-picker#876]
Hi,

First of all, thanks for this react day picker, really nice.

But there is one missing feature (or maybe I didn't found it) : multiple preset buttons.

Here's an example : 
![image](https://user-images.githubusercontent.com/5436815/53559135-c37e5a80-3b49-11e9-88a1-bdd800907482.png)
It's from [Airbnb react dates](http://airbnb.io/react-dates/?selectedKind=PresetDateRangePicker&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel). 

In your plugin there is no button for such a choice. I know (and already working on) I can put myself some buttons but it wouldn't have the same UI as your plugin.

Is there any change you could add this feature in a further update ?

Thanks

**Comment by gpbl** [comment]
Nope, sorry: I prefer we focus on the calendar features without making too much assumptions. But, you could publish your work on npm if you are brave enough 💪
