### ISSUE TITLE
Daypickerinput switch year & month

### ISSUE THREAD

**Issue by emjeard** [gpbl/react-day-picker#878]
Hi, can i implement this http://react-day-picker.js.org/examples/elements-year-navigation/ on daypicker input ?

when i try implement, datepicker always show before i click input field.

how to solve this?
thanks before

**Comment by kpereda** [comment]
hey @emjeard  how are you passing the props? I've implemented the example you mentioned by doing this and works well

```
 <DayPickerInput
// your other props here
    dayPickerProps={{
            selectedDays: selectedDate,
            weekdayElement: Weekday,
            month: this.state.month,
            fromMonth: fromMonth,
            toMonth: toMonth,
            captionElement: ({ date, localeUtils }) => (
              <YearMonthForm
                date={date}
                localeUtils={localeUtils}
                onChange={this.handleYearMonthChange}
              />
            )
          }}
/>
```

**Comment by wuqing1450** [comment]
@kpereda can you please paste the complete codes here?

**Comment by kpereda** [comment]
@wuqing1450 let me know if this helps:

`
```jsx
render () {
    const { id, selectedDate, onlyPastDates, rangeOfYears } = this.props
    const dayPickerInputProps = {
      ...this.props,
      onSetTodayClick: this.handleSetTodayClick
    }

    const dayPickerProps = {
      selectedDays: selectedDate,
      weekdayElement: Weekday,
      month: this.state.month,
      rangeOfYears,
      captionElement: ({ date, localeUtils }) => (
        <YearMonthForm
          date={date}
          localeUtils={localeUtils}
          onChange={this.handleYearMonthChange}
          rangeOfYears={rangeOfYears}
        />
      )
    }

    if (onlyPastDates) {
      dayPickerProps.disabledDays = (day) => {
        const renderDay = Moment(day)
        const today = Moment(new Date())

        return renderDay.isSameOrAfter(today, 'day')
      }
    }

    return (
        <DayPickerInput
          id={`date-picker-${id}`}
          className="date-picker-component"
          component={InputForDatePicker}
          inputProps={dayPickerInputProps}
          ref={(el) => (this.datePickerElement = el)}
          onDayPickerHide={this.onDayPickerHide}
          keepFocus={false}
          formatDate={formatDate}
          parseDate={parseDate}
          format="MMMM DD, YYYY"
          value={selectedDate}
          onDayChange={this.handleDayChange}
          dayPickerProps={dayPickerProps}
        />
    )
  }
````

**Comment by SchauweM** [comment]
> @wuqing1450 let me know if this helps:
> 
> `
> 
> ```js-jsx
> render () {
>     const { id, selectedDate, onlyPastDates, rangeOfYears } = this.props
>     const dayPickerInputProps = {
>       ...this.props,
>       onSetTodayClick: this.handleSetTodayClick
>     }
> 
>     const dayPickerProps = {
>       selectedDays: selectedDate,
>       weekdayElement: Weekday,
>       month: this.state.month,
>       rangeOfYears,
>       captionElement: ({ date, localeUtils }) => (
>         <YearMonthForm
>           date={date}
>           localeUtils={localeUtils}
>           onChange={this.handleYearMonthChange}
>           rangeOfYears={rangeOfYears}
>         />
>       )
>     }
> 
>     if (onlyPastDates) {
>       dayPickerProps.disabledDays = (day) => {
>         const renderDay = Moment(day)
>         const today = Moment(new Date())
> 
>         return renderDay.isSameOrAfter(today, 'day')
>       }
>     }
> 
>     return (
>         <DayPickerInput
>           id={`�date-picker-${id}`}
>           className="date-picker-component"
>           component={InputForDatePicker}
>           inputProps={dayPickerInputProps}
>           ref={(el) => (this.datePickerElement = el)}
>           onDayPickerHide={this.onDayPickerHide}
>           keepFocus={false}
>           formatDate={formatDate}
>           parseDate={parseDate}
>           format="MMMM DD, YYYY"
>           value={selectedDate}
>           onDayChange={this.handleDayChange}
>           dayPickerProps={dayPickerProps}
>         />
>     )
>   }
> ```

Using that will result in the form being rendered in the "DayPicker-Months" element instead of the "DayPicker-NavBar" tho.

**Comment by gpbl** [comment]
FYI we are planning to remove the input element in the next major version to have a less opinionated way to bind it with any input. I'm closing the issues related to it because we won't make major changes for now.

**Comment by a2441918** [comment]
> ```js-jsx
> Weekday
> ```

Could you link me to a playground for this please? Thanks.
