### ISSUE TITLE
Switch between years and months on DatePickerInput not working properly on iOS browsers

### ISSUE THREAD

**Issue by iamacatperson** [gpbl/react-day-picker#880]
I saw a similar issue last time #579 and it has been fixed.

However, it seems like the same issue is still happening if you open it on an iOS browser (using iPhone / iPad). So far tested in Safari and Chrome and both showing the same behavior where clicking the months/years dropdown will temporarily show the options but then it'll disappear after a split second.

To test you may open this example which I forked from the issue mentioned above but using the latest `react-day-picker` package:
https://codesandbox.io/s/0y84wrp8mn?fontsize=14

**Comment by gpbl** [comment]
FYI we are planning to remove the input element in the next major version to have a less opinionated way to bind it with any input. I'm closing the issues related to it because we won't make major changes to it.
