### ISSUE TITLE
'DateUtils' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by JonasGaldikas** [gpbl/react-day-picker#887]
Hello guys, 

i thought i can reproduce error on sandbox, but it worked perfectly on it. Error i got is "'DateUtils' only refers to a type, but is being used as a value here." . Maybe someone has confronted similar error? 

I am using --Select days on mouse enter-- 100% coppied from examples.

Maybe have any solutions? Thx in advance :)

**Comment by JonasGaldikas** [comment]
Delete issue pls.

**Comment by FaganSC** [comment]
Jonas, I'm getting the same thing. Is there something you found that you missed at first? It might be the same thing I haven't found. Thanks in advance!

**Comment by coreybruyere** [comment]
@JonasGaldikas what was the issue here?

**Comment by JonasGaldikas** [comment]
well i am not importing DateUtils as in example 
`import DayPicker, { DateUtils } from 'react-day-picker`

i only import 
`import  DayPicker from 'react-day-picker'`

and instead of using 
`from && DateUtils.isDayBefore(day, from);`

i use 
`from && DayPicker.DateUtils.isDayBefore(day, from);`

I hope it helped you guys ;)
