### ISSUE TITLE
Remove focus ring on click

### ISSUE THREAD

**Issue by theochampion** [gpbl/react-day-picker#892]
Hi,

Great work with that module, love it!
I was wondering if there is any way to remove the focus ring that appear on click:

<img width="242" alt="Screen Shot 2019-04-08 at 5 25 07 pm" src="https://user-images.githubusercontent.com/14275989/55706121-c0696a80-5a23-11e9-97f1-09fae089ce94.png">
<img width="267" alt="Screen Shot 2019-04-08 at 5 24 57 pm" src="https://user-images.githubusercontent.com/14275989/55706132-c8c1a580-5a23-11e9-8dab-41d24c5286fc.png">

Any ideas? :)

**Comment by gpbl** [comment]
Yes, learn about the [`:focus` pseudoselector](https://developer.mozilla.org/en/docs/Web/CSS/:focus). I wouldn't remove it for usability reasons though… 

good luck!

**Comment by theochampion** [comment]
What I don't understand is where to modify the CSS to add that ?
