### ISSUE TITLE
Disabled Future date input-daypiker

### ISSUE THREAD

**Issue by wesleydesantana** [gpbl/react-day-picker#897]
I am being applying a disable on future days in react-input-day-piker but did not succeed. Is there any way to do this in the library? Also try to apply a mask, when the user types in the field, also to no avail. Can you help me on that?

**Comment by gpbl** [comment]
Hi, we can help if you help us to help. Please see https://github.com/gpbl/react-day-picker/blob/master/.github/ISSUE_TEMPLATE.md
