### ISSUE TITLE
Babel 6 compatibility 

### ISSUE THREAD

**Issue by megheaiulian** [gpbl/react-day-picker#90]
There is backward-incompatible change from Babel 5.x to 6 as `stage` option is replaced with `presets`.

**Comment by gpbl** [comment]
Yes, the source code is not yet using Babel 6. I wonder is this a problem?

**Comment by gpbl** [comment]
I'm trying to upgrade to babel 6 in #99. @megheaiulian care to explain your experience? Because I also have some problems :)

**Comment by megheaiulian** [comment]
@gpbl 
It seems that if you just setup a correct .babelrc the code is already compatible with Babel 6.
I see you get a lot of errors in your pull request. Try maybe to use only babel-preset-stage-0 ?

**Comment by gpbl** [comment]
I have no idea. It seems everything is right there.
