### ISSUE TITLE
Alternative LocaleUtils with Day.js

### ISSUE THREAD

**Issue by Ktchan825** [gpbl/react-day-picker#900]
Moment.js is a great and popular module, but [its size is really too larger](https://github.com/moment/moment/issues/2373).

I know we can use our own LocaleUtils, but It would be great to have an alternative localeutil from the modules. I would suggest having one using dayjs, as it got similar api to moment.js

**Comment by gpbl** [comment]
Hey thanks for citing dayjs! We will consider it for the next major release.

**Comment by humayunkabir** [comment]
Any update on this?
