### ISSUE TITLE
Question: Is posible month and year only?

### ISSUE THREAD

**Issue by moasl** [gpbl/react-day-picker#902]
Is posible to transform day-picker in a moth-year picker changing the props.
Something like 
https://github.com/nickeljew/react-month-picker#snapshots

Thanks

**Comment by DimitrK** [comment]
Hello, wondering the same as well.

**Comment by glapsable** [comment]
me too

**Comment by gpbl** [comment]
Sorry, but this feature would go out from the goal of this component. You could easily implement a month/year view by yourself!
