### ISSUE TITLE
BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by PlanetIrata** [gpbl/react-day-picker#905]
Hi, I just upgraded react-scripts (Create React App) from 2.1.8 to 3.0.1 and when starting my app, now the compilation fails with this error:

`./node_modules/react-day-picker/lib/style.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-day-picker/lib/style.css)
BrowserslistError: Unknown browser query 'dead'
    at Array.reduce (<anonymous>)`

Everything is ok if I revert to react-scripts@2.1.8

Any idea of the problem ?

Thanks for your help.

**Comment by gpbl** [comment]
Sorry, I can't help you here – see https://github.com/browserslist/browserslist/issues/266, thanks!
