### ISSUE TITLE
Wrong day number displayed with outdated date-fns

### ISSUE THREAD

**Issue by sialbul** [gpbl/react-day-picker#912]
![image](https://user-images.githubusercontent.com/46114540/61585998-e381db00-ab37-11e9-9976-92bda7384a75.png)

Hi, I just wanted to let you know that as you see in the screenshot, it shows the day wrong  in Changing the date format section (7/201/2019) .

**Comment by krnlde** [comment]
Can confirm. Looks like its using date-fns' `DDD` "Day of year" formatting, despite having set `M/D/YYYY` properly.

**Comment by gpbl** [comment]
Thanks! Fixed!
