### ISSUE TITLE
Have a focus prop that will bring the date in focus

### ISSUE THREAD

**Issue by aitchkhan** [gpbl/react-day-picker#913]
This is a feature request.
We have recently been working on making our application more accessible. This feature request has an influence of the work that we are doing to make our application WCAG  2.0 AA compliant atleast.

For our specific use-case we don't show DayPicker by default. When it opens up, we want to have a focus on the selected day. That way, it will be read out by the screen reader and it will be easier for the user to navigate via the keyboard.

Approach:
Add a `focus` prop which takes a date object and steal focus on that one.

I can create a PR for this.

**Comment by thecoorum** [comment]
Hey @aitchkhan, is there any progress about this feature? Or maybe you can share you thoughts on how to achieve this behavior?
