### ISSUE TITLE
Next version status – looking for contributors

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#921]
I will keep track of some insights about the next version here.

## 🚒 react-day-picker is looking for contributors

The package is being downloaded 1M+/months and I need help maintaining such big user base. 

* Need help triaging issues and organizing the project on Github
* Need someone expert in Typescript that can help to maintain the typings
* Need help setting up e2e tests in multiple browsers
* Need help writing documentation website
* Would love one or more code reviewers ❤️

### Major rewrite

By looking at the code, I see the package requires a major rewrite. Next major version may use hooks thus it may be compatible with react 16.8+.

### Removing DayPickerInput

DayPickerInput will be removed. Integration with input fields will be left to the implementer. I plan to add some examples in the website.

### Compatibility with v7

The goal it to maintain the same API Some props will be deprecated.

### New website

I'd like to create a new website with [Docusaurus](https://docusaurus.io) and [Storybook](https://storybook.js.org).

### JS Bundler and dev environment

* i'm evaluating rollupjs instead of webpack
* I'm developing using a storybook – this will likely included in the documentation

### TypeScript

* I won't write this version in TypeScript, as it will delay the release and I have no interest in TS for now
* I can't really do much on PR and issues related to TS. If nobody want to "officially" maintain the typings, I'll remove them from the package, sorry!

### Datetime library dependency

* I'm currently trying date-fns@2 as peer dependency. It is still in beta, but the library is very solid and remove the hassle of working with native dates and i can concentrate better on the component itself. My bet is that for the next mayor release of react-date-picker it will be out of beta!
* I've tried `dayjs` but I don't like the momentjs-like syntax. Also I don't agree much with some [design choices](https://github.com/iamkun/dayjs/issues/655).

### Design and features

I'd like to explore some new layouts to give a more modern UX to the calendar: animation, scrolling, etc, I'd explored [react-window](https://github.com/bvaughn/react-window/) but without much success. I'd like user could implement a layout like this:

![Screen Recording 2019-08-12 at 20 04 15 2019-08-12 20_04_58](https://user-images.githubusercontent.com/120693/62906473-d1f9b080-bd3c-11e9-865b-d67edfdb193f.gif)

(this is actually the pre-alpha i'm working on)

**Comment by ahmedam55** [comment]
Count me in 🙋‍♂️. I'm more than happy to help in such an amazing project!

**Comment by stunaz** [comment]
Instead of using directly date-fns, what about letting the user choose their prefered date library using something like https://github.com/dmtrKovalenko/date-io. This way if I am a fan of dayjs and dont want to include date-fns in my bundle, it could still be ok for me.

**Comment by gpbl** [comment]
@stunaz it doesn't seem date-fns is increasing that much the bundle size and it would be an internal implementation anyway. I will open to PRs implementing a way to allow switching date library anyway. Thanks for the suggestion :)

**Comment by CodeWitchBella** [comment]
:raising_hand_woman: I would like to help. Might be able to help with rollup bundling :slightly_smiling_face:

**Comment by mirshko** [comment]
I'd be happy to help with the Storybook website! 

With their latest version documenting can be done with just Storybook! No need for docusarus! 

I've had good experience building four different design systems in Storybook and documenting examples well! 

Let me know!

**Comment by gpbl** [comment]
Hey thanks everybody for answering! Where do the cool kids meet online for organizing things? :) I'm on reactiflux @gpbl (I'll try to be online there).

Some updates: i've been experimenting with a rewrite and I've found a good architecture. I've been playing with it for a while so it is almost feature complete. I'd love to open a PR and get some reviews. Does it make sense?

I actually need help with github issues, how to approach the opened PRs, and such. I feel sorry for all the fellow developers not having an answer from me.

Is @davidspiess still using this component? It would be nice to know how much a major release would impact current users.

Thanks please send motivation :)

**Comment by gpbl** [comment]
> I'll open the PR including my rolluo untested build, hop 

@CodeWitchBella that would be so welcomed, I'll open the PR including my rolluo untested build, hop 

> 🙋 I would like to help. Might be able to help with rollup bundling 🙂

@CodeWitchBella that would be so welcomed. I'll open a PR with my (untested) rollup bundle and call you for help 🙏🏾

**Comment by gpbl** [comment]
> I'd be happy to help with the Storybook website!
> With their latest version documenting can be done with just Storybook! No need for docusarus

@mirshko I am using Storybook at work and I love it. But for a OSS project I find better Docusaurus, being it between Gatsby and Storybook. 

I am talking about [docusaurus v2](http://v2.docusaurus.io), which is still in alpha, hence my doubt using it. I don't understand how much support is getting the project and I have not time myself to contribute.

**Comment by davidspiess** [comment]
@gpbl yes, we are using react-day-picker since the beginning extensively in our booking / enquiry widgets. ATM we have more than 1500 clients which have it running on their website. Many of them added their own stylings to the calendar, which could break for them, if the div structure / classnames change too much. Until now we had almost no problems upgrading, since every breaking change was well documented and we could analyze the impact carefully.

**Comment by gpbl** [comment]
@davidspiess wow that means 1500 day pickers? :D Which version of React are you using?

**Comment by davidspiess** [comment]
If you are interested, here you can see one in action: [Link](https://www.dasgerstl.com/en/rooms-prices/booking.html)
Right now we are still using 16.8.x, but we will soon upgrade to the latest 16.9.x.

**Comment by gpbl** [comment]
Thanks @davidspiess good you are in one of the latest React :)

**Comment by gpbl** [comment]
Thanks everybody, there's a preview of the next version/website here:
http://rdp-v8.netlify.com/docs/intro 

Closing this in favour of https://github.com/gpbl/react-day-picker/issues/942

If someone is still interested to contribute, there there's a big list of things to do :)

**Comment by gpbl** [comment]
@davidspiess (or anyone interested) I could easily migrate to TypeScript. I'd really love a review:

https://github.com/gpbl/react-day-picker/pull/944 🙏🏾

**Comment by gpbl** [comment]
@mirshko I'd still need help with the website (mostly code examples, text proofing etc.) maybe you are interested anyway? No Storybook,  but all MDX via docusaurus. Website project is neat has some nice tricks in it. It's actually the most time consuming part now.

@CodeWitchBella if you have some time, review #944 for my rollup implementation. I haven't tested it much yet 🔬

**Comment by ryanburr** [comment]
@gpbl I can take a look at your TypeScript implementation. Glad to help any repo make the switch over to TypeScript
