### ISSUE TITLE
Problems with DayPicker Overlay focus and hiding

### ISSUE THREAD

**Issue by zovcharov** [gpbl/react-day-picker#926]
Hi
When I am using day picker with custom input field, there is one problem.
After focusing on DayPickerOverlay, click on any place on the screen calls only onOverlayFocus handler, not onBlur
That`s why after overlay had been focused once I cant close it by click on some other area on the screen.
What can I do for solving this problem?

Thanks

**Comment by gitpash** [comment]
@zovcharov seems like UX issue, can suggest only workaround like this
`dayPickerProps={{
          // other props
          onBlur: () => {
            const activeElement = document.activeElement;
            const overlayContainer = document.getElementsByClassName('DayPickerInput-Overlay');

            if (overlayContainer && !overlayContainer[0].contains(activeElement)) {
              inputRef.current.hideAfterDayClick();
            }
          }
        }}`

**Comment by Kamilius** [comment]
Having same issue.
Downside of this workaround is an error inside console:
![Screen Shot 2020-01-03 at 8 50 54 AM](https://user-images.githubusercontent.com/3115794/71710699-40333280-2e06-11ea-9680-baa4b1fbea0b.png)

**Comment by zovcharov** [comment]
The problem can also be if you have more than one DatePicker on the page. To avoid this issue you can try to create custom ref for each one of the DatePicker instance.

And also you can try something like this.
Create handler for blur event of your DatePickers.
`const handlerOnBlur = function() {
        setTimeout(() => {
            const elClicked = document.activeElement;
            const container = document.getElementsByName(props.name);

            if (container && !container[0].contains(elClicked)) {
                dayPickerInputRef.hideDayPicker();
            }
        }, 1);
};
`
And after that you can use DatePicker in container:
`<div name={props.name}>
            <DayPickerInput
                ref={ref => (dayPickerInputRef = ref)}
                component={InputComp}
                dayPickerProps={{
                    input: InputComp,
                    onBlur: handlerOnBlur,
                }}
                placeholder=""
                format="DD MMMM YYYY"
                formatDate={formatDate}
                parseDate={parseDate}
                value={props.date}
            />
        </div>`

It`s possible to use this way if you have two or more DatePickers on the page.

**Comment by Kamilius** [comment]
@zovcharov already using similar solution, but there is an issue with relying on `onBlur` callback. It is being triggered even when clicking first a `nextMonth` and then - `prevMonth` buttons or vise versa. Which causes this dropdown to close each time you're trying to return to previously shown month... :(

**Comment by Ahmad-Zahid** [comment]
@Kamilius can you please share your custom hook solution in detail?
