### ISSUE TITLE
Propagate Event (e) argument to onDayChange handler

### ISSUE THREAD

**Issue by bmeverett** [gpbl/react-day-picker#933]
Hi! 👋 

I am doing some custom selection when the shift key is selected and would like access to the event handler to detect my key presses instead of listening to the key changes in my component. 

Currently onDayChange is defined as `onDayChange(day, modifiers, dayPicker)`. I want to propose to be able to access the e (event) argument as well: `onDayChange(day, modifiers, dayPicker, e)`

Happy to further discuss or even look into making a PR. 

Thanks!

**Comment by gpbl** [comment]
Hi @bmeverett thanks for you feedback! Next version (v8) will allow you to do that. The problem in the current architecture is that the event handler is dispatched from two different points: when clicking a day, or when typing in the input, so the event wouldn't be the same.

I don't know if you can hack it adding a `onChange` to your input, tho. Try it :)
