### ISSUE TITLE
Replace moment.js with date.js

### ISSUE THREAD

**Issue by noodny** [gpbl/react-day-picker#934]
Hi! First of all thanks for maintaining this module, it is a huge time saver. I've however noticed in the docs that you're using moment.js, which is probably the most versatile date manipulation library out there, but at the same time is pretty heavy for a frontend use (especially bundled in a third party module) and is a mutability fueled ticking bomb. Would you consider using https://github.com/iamkun/dayjs instead in v8? The switch should be pretty straightforward.

**Comment by totaldis** [comment]
see https://github.com/gpbl/react-day-picker/issues/921#issue-479905679, specifically *Datetime library dependency*.

**Comment by noodny** [comment]
👍 all clear, thanks!
