### ISSUE TITLE
Overall filled with issues DateInput needs work

### ISSUE THREAD

**Issue by developdeez** [gpbl/react-day-picker#946]
This seems to be agood project and got me close to y goal but many of the features dont work. Not even in your own demo, the format is off: https://codesandbox.io/s/537qkxy4wn

Also seems to be no way to select a target start date in DateInput.

Is new version going to fix all of this?

**Comment by gpbl** [comment]
Hi thanks for your feedback. Please read the docs to use the component, there are more examples here. http://react-day-picker.js.org/examples/basic/

**Comment by developdeez** [comment]
Read the docs and thats why im here...

**Comment by developdeez** [comment]
How about address the issue of not being about to give an initial date?

**Comment by developdeez** [comment]
Docs dont seem to mention or have an example of that
