### ISSUE TITLE
LocaleUtils in not a value, causing types to be broken

### ISSUE THREAD

**Issue by MhMadHamster** [gpbl/react-day-picker#948]
In this pr: https://github.com/gpbl/react-day-picker/pull/873 `LocaleUtils` was changed from value to type (interface), i'm not sure if it's intended, but in the latest version v.7.4.0 types are broken, cause there are a lot of `typeof LocaleUtils` which expects value, not the type.

P.S. consider adding tests for types

**Comment by PiTomar** [comment]
Can confirm, same issue here.

**Comment by madebyew** [comment]
This is an issue for me, too.

**Comment by gpbl** [comment]
Sorry for the bugged release, people, but I need help maintaining v7 as I'm busy working with the next major version. Please branch off `v7` branch to send a PR, thanks 🙏🏾 
I'll see if I can work on this today.

**Comment by zvertovsek** [comment]
Any updates on the fix?

**Comment by tpetrina** [comment]
Downgrade to 7.3.2 and it should work.

**Comment by n-romaniv** [comment]
Thanks for the great library, guys! @gpbl, any updates?

**Comment by kevinlandsberg** [comment]
Still no updates... :S

**Comment by gpbl** [comment]
This should be fixed in v7.4.7, hope so. If not please open another issue, this one was lost into the list of untriaged stuff :) Thanks @MhMadHamster!
