### ISSUE TITLE
Website: Update example to support date-fns v2

### ISSUE THREAD

**Issue by bj00rn** [gpbl/react-day-picker#949]
The `date-fns` [example](http://react-day-picker.js.org/examples/input-date-fns) is not working with `date-fns>2`

Are the docs here on github?

* Fixed code here: https://codesandbox.io/s/react-day-picker-base-tkcnu
* Instruction to install date-fns@next can be removed now since date-fns v2 is out

**Comment by gpbl** [comment]
Yes @bj00rn is in the `v7` branch – sorry we are undergoing a major review of the repo during these weeks. I'll see if I can remove these instructions, thanks for the heads up!

**Comment by bj00rn** [comment]
@gpbl here's a PR for ya!

**Comment by gpbl** [comment]
you awesome! thanks!
