### ISSUE TITLE
Bug in fromMonth/toMonth and showMonth method

### ISSUE THREAD

**Issue by JKillian** [gpbl/react-day-picker#95]
Say `toMonth` is set to December 2015 and someone tried to call `showMonth(new Date(2015,11))` in order to display December 2015.

`allowMonth` incorrectly returns false as `toMonth` and `d` are the same month. It should return true. I believe this should be a simple fix by changing `Helpers.getMonthsDiff(toMonth, d) >= 0` to `Helpers.getMonthsDiff(toMonth, d) > 0` (and doing the same for `fromMonth`).

**Comment by gpbl** [comment]
Published as v1.1.5 🤖

**Comment by JKillian** [comment]
@gpbl think you forgot to run the build for bower ;)

**Comment by gpbl** [comment]
Grrr yes sure... I have to remember to run the `prerelease` task each time... because that boring `prepublish` thing in npm :( 

Anyway, I would not publish a new npm release for this. I just updated `dist` and tagged 1.1.6 – bower should catch it, right?

**Comment by JKillian** [comment]
Yep, that should work - thanks!
