### ISSUE TITLE
Disabling "Sunday" when firstDayOfWeek is Monday

### ISSUE THREAD

**Issue by alexbusuioc** [gpbl/react-day-picker#952]
This is very simple to reproduce. Just set the DayPicker to start with Monday as firstDayOfWeek,
and try disabling "Sunday" (index 7)

<DayPicker
    firstDayOfWeek={1}
    disabledDays={[ { before: new Date()} , { daysOfWeek: [6,7]} ]}
 />

In the example above, only "Saturday" will be disabled

**Comment by alexbusuioc** [comment]
oh, silly me. Sunday has the index of "0", not "7"

**Comment by CezarCobuz** [comment]
It can happen to anyone from EU working with US code  ^_^
