### ISSUE TITLE
A11y - NVDA not reading dates

### ISSUE THREAD

**Issue by mzlock** [gpbl/react-day-picker#953]
Sorry this is a bit second-hand, but I tried to get as much information as I could before submitting an Issue. This issue was flagged by a client testing with a Windows set-up -- they've confirmed that it's also happening on the sandboxed date-picker.

I'll need to get a VM working in order to test myself and provide more details....

Set-up:
- OS: Windows 7 Professional
- Browser: Firefox (69.0.3)
- Screen Reader: NVDA

NVDA is not reading the full dates in the `aria-label`. You just hear "1", "2", "3", etc -- not "Friday Nov 01 2019", "Saturday Nov 02 2019", etc.

There is also no announcement to the user when you change months.

---

Possible fixes:

Move the `aria-label` text into the gridcell:
```
<div class="DayPicker-Day DayPicker-Day--selected DayPicker-Day--today" tabindex="0" role="gridcell" aria-disabled="false" aria-selected="true">
  <span aria-hidden="true">1</span>
  <span class="sr-only">Fri Nov 01 2019</span>
</div>
```
where `sr-only` just visually hides the text, but it still exists for screen-readers.

Add `aria-live="polite"` to the month heading. It also needs a heading level per #922   This could potentially conflict with other `aria-live` areas... So, another option might be to append a `<p role="status">` instead - but then you need to remove it from the DOM and add it again for a new announcement, unlike a live area.

I hope this helps!

**Comment by gpbl** [comment]
This definitely has to be addressed in v8 https://github.com/gpbl/react-day-picker/issues/1036 too.

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version that is not longer maintained.
