### ISSUE TITLE
aria properties on `<Day />` component don't work when using custom CSS classes

### ISSUE THREAD

**Issue by bengry** [gpbl/react-day-picker#959]
**Describe the bug**
When using custom CSS classes, the `aria-selected` and `aria-disabled` on the `<Day />` component don't work.
This is because of [these lines](https://github.com/gpbl/react-day-picker/blob/d6d0f7702908ca2657fa88d9d639dabcc6ff89db/src/Month.js#L110) - which look for a specific key name, which doesn't exist when using custom CSS classes (e.g. with CSS Modules the class names are generated).

In addition, there's no way to override this behavior from the outside.

**To Reproduce**
Reproduction Sandbox: https://codesandbox.io/s/react-day-picker-base-1rs3g
Notice that the selected day has an `aria-selected="false"`.

**Expected behavior**
the `aria-*` attributes should use the `selectedDays` and `disabledDays` props to set them.

**Screenshots**
![image](https://user-images.githubusercontent.com/260431/69493924-ea41a580-0ebd-11ea-8eab-9a61fed9b39e.png)

**Additional context**
This happens in both `v7.3.2` and `v7.4.0`, probably in earlier version as well.

**Comment by camflan** [comment]
I've pushed a PR for this on v7

https://github.com/gpbl/react-day-picker/pull/1004

**Comment by camflan** [comment]
Merged

**Comment by bengry** [comment]
@gpbl any plans to release v7.4.1 with this fix (and others that got into the v7 branch)?

**Comment by gpbl** [comment]
Fixed in v7.4.1: https://codesandbox.io/s/react-day-picker-base-wnjjp?file=/index.js
