### ISSUE TITLE
Lack of style property in the DayPickerInputProps interface

### ISSUE THREAD

**Issue by Dremuchev** [gpbl/react-day-picker#966]
**Describe the bug**
In the DayPickerInputProps interface, style property has been missed, although it was provided to the component earlier. Typescript throw error. 
Someone tried to add in the pull https://github.com/gpbl/react-day-picker/pull/918 

**To Reproduce**
Clone [this CodeSandbox]
https://codesandbox.io/s/react-typescript-v4kd8?fontsize=14&hidenavigation=1&theme=dark
to reproduce the bug.

**Expected behavior**
Typescript throw error that style is missing in DayPickerInputProps. 

**Screenshots**
![image](https://user-images.githubusercontent.com/34788837/70617569-f51c6a00-1c21-11ea-990e-dfd73ed92be4.png)

**Comment by gpbl** [comment]
I've deployed the fix in v7.4.1 with @anilkabobo change – I still see other types errors here:
https://codesandbox.io/s/react-typescript-ko9hs

It would be nice if someone could give a look :)
