### ISSUE TITLE
Highlighted modifier doesn' t select correct month

### ISSUE THREAD

**Issue by Codefeak** [gpbl/react-day-picker#969]
**Describe the bug**
selecting month is not working properly

**To Reproduce**
check Matching days with modifiers in https://react-day-picker.js.org/docs/matching-days

**Expected behavior**
Month should be 1-12 which is Jan to Dec. It shouldn't show 1 as Feb and 11 as Dec and 15 as March and so on. 

**Screenshots**
![image](https://user-images.githubusercontent.com/31770740/71007553-dae5fe80-20ef-11ea-9640-39c87823915b.png)

**Additional context**
Thank You

**Comment by KyorCode** [comment]
Hi, this isn't really a bug. It is just the way Dates work in javascript.

Months are zero based. 

For more information: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth

**Comment by gpbl** [comment]
Thank @Codefeak and @KyorCode I think I can close this.
