### ISSUE TITLE
Strange behavior when clicking days with outside modifier

### ISSUE THREAD

**Issue by JKillian** [gpbl/react-day-picker#97]
The first bug is that clicking outside days only changes the month if you have an `onDayClick` prop set (which is surprising behavior). This seems to be because [`handleDayClick`](https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L281) is only called if `props.onDayClick` is set. I think this should maybe be opt-in behavior that happens regardless of `onDayClick`'s value?

The second bug is that you can use this month changing functionality to navigate to days outside of the bounds set by `fromMonth` and `toMonth`. It seems that [`showMonthForOutsideDays`](https://github.com/gpbl/react-day-picker/blob/bd22d696f5fae2f6d54c565d3b70461c03392b23/src/DayPicker.js#L150) doesn't check if the month is allowed or not. Perhaps instead of calling `setState` directly it should call `showMonth` instead?

**Comment by gpbl** [comment]
1. yes, this was a design choice
2. this is indeed a bug 💧 i agree it should call `showMonth` and not directly set the state

**Comment by JKillian** [comment]
Thanks for the fix for the second bug! However, I think we might have messed up a little bit - instead of using `showMonth`, I think it should use `showPreviousMonth` and `showNextMonth`. This way, the `onMonthChange` prop will get called as it should be.

**Comment by gpbl** [comment]
@JKillian Our reasoning was right, because the old code is actually displaying a month based on the `numberOfMonths` prop, so not always is the next/prev month. However, this is actually an old behavior which should have already been changed. Going to fix this as well 👍

**Comment by gpbl** [comment]
See #112

**Comment by gpbl** [comment]
@JKillian these issues should be fixed in the new 1.2.0 release. There's event a [new example](http://www.gpbl.org/react-day-picker/examples/#restricted) showing the corrected behaviors.
