### ISSUE TITLE
Previous date being set to aria-selected="true" & class="DayPicker-Day--selected" in Safari

### ISSUE THREAD

**Issue by bjfresh** [gpbl/react-day-picker#972]
**Describe the bug**
In Safari (13.0.03, for me), clicking a date sets aria-selected and class attributes for the preceding day, rather than the date clicked. This happens despite the correct date having appropriate hover + focus styles on click, and the correct date is verifiably selected when attaching console output to the onDayClick event.

I should note that doesn't appear to happen with 100% consistency in Safari, as I was not able to reproduce my team's bug reports on this until today.

This bug is occurring in an instance of DayPicker in a fairly minimal React component.

**Expected behavior**
The date that is clicked gets the correct attributes: aria-selected="true" & class="DayPicker-Day--selected"

**Screenshots**
I've created an animated gif to show the effect:
https://www.dropbox.com/s/qr5x0p6qbpi2znm/animation.gif?dl=0

**Comment by edgarsd** [comment]
I can confirm that this issue is still present today and can be replicated on older laptops using safari.
Does anyone has any idea what could cause this and maybe have some possible workarounds?

**Comment by gpbl** [comment]
Please provide a link to reproduce the issue and we can reopen this. Thanks!
