### ISSUE TITLE
Website: CodeSandbox links not working anymore

### ISSUE THREAD

**Issue by jnachtigall** [gpbl/react-day-picker#985]
Go to http://react-day-picker.js.org/examples/basic/ and try clicking (normal mouse, middle mouse) on the `CodeSandbox` button. (btw, why `button` and not a normal link?!). **Nothing happens**

**Expected behavior**
Opens Code Sandbox example in new tab.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3307404/73542127-539ce200-4434-11ea-9337-581d8a541ef7.png)

**Additional context**
Both Firefox Developer Editon and normal chrome on Windows 10.

PS Thanks for the DayPicker, really well done component!

**Comment by harshilparmar** [comment]
Can I try this issue

**Comment by gpbl** [comment]
Thanks everybody this is fixed ! @harshilparmar appreciate the help, thanks, as you see this issue was stale for long.
