### ISSUE TITLE
Re-render caption when month prop is updated

### ISSUE THREAD

**Issue by velohomme** [gpbl/react-day-picker#987]
After rendering the DayPicker with months prop = ["January", "February" "March".....]. The title above shows the correct text for the current month. However, if I update update the months prop with a new array (a different language) the title continues to use the old text.

The weekdaysShort prop does not behave this way.  The week names change as expected.

If I use the arrows to navigate months the new names DO appear.  

**To Reproduce**
Clone [this CodeSandbox](https://codesandbox.io/s/react-day-picker-base-8vpwz) to reproduce the bug.

**Expected behavior**
Month name at top of picker would change to new text

**Screenshots**
Actual:
![image](https://user-images.githubusercontent.com/1175924/73693875-de2b4e80-468b-11ea-925d-1054a1a9b316.png)
Expected:
![image](https://user-images.githubusercontent.com/1175924/73693926-f307e200-468b-11ea-838a-05a9460e15f9.png)

**Additional context**

**Comment by LettItBrew** [comment]
I'm experiencing the same problem. Is there any progress on this?

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
