### ISSUE TITLE
Incorrect example in "Matching days with modifiers"

### ISSUE THREAD

**Issue by mahnunchik** [gpbl/react-day-picker#989]
**Describe the bug**

Incorrect documentation of Matching days with modifiers http://react-day-picker.js.org/docs/matching-days

**To Reproduce**

```jsx
const highlighted = { 
  from: new Date(2018, 0, 12), 
  to: new Date(2018, 0, 16) 
}
<DayPicker modifiers={ highlighted } />
```

Will produces classes `DayPicker-Day--from` on Date(2018, 0, 12) element and `DayPicker-Day--to` on new Date(2018, 0, 16) element. Not as described in the documentation: `.DayPicker-Day--highlighted` will match the days between the 12th and the 16th of January.

**Expected behavior**

It should be at least `<DayPicker modifiers={ { highlighted } } />` in the doc.

**Additional context**

The same incorrect behavior in other samples.

```jsx
const past = { 
  before: new Date(),
}
<DayPicker modifiers={ past } />
// expected .DayPicker-Day--past
// actual  .DayPicker-Day--before
```

```jsx
<DayPicker modifiers={ [weekends, sunday, firstOfMonth] } />
// expected .DayPicker-Day--weekends, .DayPicker-Day--sunday, .DayPicker-Day--firstOfMonth

// should be
<DayPicker modifiers={ {weekends, sunday, firstOfMonth} } />
```

**Comment by gpbl** [comment]
Hey thanks for spotting it out – definitely a typo!

**Comment by gpbl** [comment]
Closing as [we've released v8](https://github.com/gpbl/react-day-picker/discussions/1412): this issue belongs to a version which is not longer maintained, and it is likely fixed. In case, please open a new issue. Thanks!
