### ISSUE TITLE
How do I add a default value to the input component from the state ? 

### ISSUE THREAD

**Issue by osman144** [gpbl/react-day-picker#993]
<DayPickerInput  inputProps={{ style: { width: 300 } }} onDayChange={this.handleDayChange} /> 

Forgive my ignorance. Searched everywhere for this particular issue and reviewed the docs but can't seem to find anything.

- How do I add a default date or preset a day in the DayPickerInput component ?
- Is it possible to add a date from the state in to the input? How will the formatting work? I'd like to format the date from utc 8601 to whatever format DayPickerInput requires

**Comment by swrobel** [comment]
I believe it's as simple as `<DayPickerInput value={value} />`.

**Comment by gpbl** [comment]
Thanks @swrobel, yes that is the solution:

https://codesandbox.io/s/react-day-picker-base-jtqw1?file=/index.js
