### ISSUE TITLE
TodayButtonElement property to render customized TodayButton

### ISSUE THREAD

**Issue by kevinlandsberg** [gpbl/react-day-picker#999]
**Is your feature request related to a problem? Please describe.**
I cannot add my own button component to be rendered as the ```TodayButton```.

**Describe the solution you'd like**
The solution would be to have a property like ```weekdayElement``` or ```navbarElement```, to be able to customize the rendered ```HTML``` for the ```TodayButton```.

**Describe alternatives you've considered**
There are no alternatives atm.

**Additional context**
Would be nice to have a function property for the ```DayPicker``` called ```TodayButtonElement``` returning a react component for the ```TodayButton```. Important to have typed props for the function.

**Comment by KyorCode** [comment]
You can use the captionElement for this.

https://react-day-picker.js.org/examples/elements-year-navigation

**Comment by kevinlandsberg** [comment]
> You can use the captionElement for this.
> 
> https://react-day-picker.js.org/examples/elements-year-navigation

Lol? Did you understand my request? I am talking about the TodayButton which is rendered below the calendar...
